/*
 * i18n-core.js — shared i18n functions + _initI18nAutoGen
 *
 * Auto-generated by scripts/_phase_e6_a_split_i18n.mjs
 * Source: js/i18n.js
 * Generated: 2026-06-13T13:25:42.876Z
 *
 * DO NOT EDIT BY HAND. To regenerate after editing js/i18n.js, run:
 *   node scripts/_phase_e6_a_split_i18n.mjs
 *
 * Phase E6-a — i18n Per-Language Split.
 * The original js/i18n.js is preserved unchanged for Node-side require()
 * (server.js SSR uses TRANSLATIONS_BY_LANG from the full bundle).
 * Browser delivery now uses i18n-core.js + i18n/{lang}.js (this file).
 */

'use strict';

// Placeholder so per-lang bundles can attach even if they load BEFORE core
// (browser defer order is not strictly guaranteed across <script> tags).
if (typeof window !== 'undefined') {
    window.TRANSLATIONS = window.TRANSLATIONS || {};
}


// Phase E6-a: refactored from the original IIFE _autoGenPatternedAttrs() so
// per-language bundles can call it AFTER they attach their dict to the global
// TRANSLATIONS object. Iterates only the requested lang (or all loaded langs
// if no arg). Safe to call multiple times — adds keys only if missing.
function _initI18nAutoGen(onlyLang) {
    if (!window.TRANSLATIONS) return;
    const langs = onlyLang ? [onlyLang] : Object.keys(window.TRANSLATIONS);
    for (const lang of langs) {
        const dict = window.TRANSLATIONS[lang];
        if (!dict) continue;
        const flagPat = dict['flag.alt_pattern'];
        const tilePat = dict['tile.title_pattern'];
        for (const key of Object.keys(dict)) {
            const mc = key.match(/^country\.(.+)$/);
            if (mc && flagPat) {
                const cc = mc[1];
                const flagKey = 'flag.' + cc;
                if (!(flagKey in dict)) {
                    dict[flagKey] = flagPat.replace('{country}', dict[key]);
                }
            }
            const mt = key.match(/^city\.(.+)$/);
            if (mt && tilePat) {
                const ck = mt[1];
                const tileKey = 'tile.' + ck;
                if (!(tileKey in dict)) {
                    dict[tileKey] = tilePat.replace('{city}', dict[key]);
                }
            }
        }
    }
}
// Expose globally so per-lang bundles can call it.
if (typeof window !== 'undefined') window._initI18nAutoGen = _initI18nAutoGen;


// ── Original helpers from js/i18n.js (post-IIFE section) ──
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { TRANSLATIONS };
}

// اكتشاف اللغة: URL هو المرجع الوحيد
// /en/... → إنجليزي | /fr/... → فرنسي | /tr/... → تركي | /ur/... → أردو | /de/... → ألماني | /id/... → إندونيسي | غير ذلك → عربي
const SUPPORTED_LANGS = ['ar', 'en', 'fr', 'tr', 'ur', 'de', 'id', 'es', 'bn', 'ms'];
const RTL_LANGS = ['ar', 'ur'];
function _detectLang() {
    // حماية SSR: لا نصل إلى window خارج المتصفّح — server.js يستورد هذا الملفّ للترجمات فقط
    if (typeof window === 'undefined') return 'ar';
    const p = window.location.pathname;
    for (const l of ['en', 'fr', 'tr', 'ur', 'de', 'id', 'es', 'bn', 'ms']) {
        if (p === '/' + l || p.startsWith('/' + l + '/')) return l;
    }
    return 'ar';
}
let _lang = _detectLang();

function t(key, params) {
    let v = TRANSLATIONS[_lang]?.[key];
    if (v === undefined) v = TRANSLATIONS['en']?.[key];
    if (v === undefined) v = TRANSLATIONS['ar']?.[key];
    if (v === undefined) v = key;
    // دعم placeholders البسيطة بصيغة {name}
    if (params && typeof v === 'string') {
        for (const p in params) {
            v = v.split('{' + p + '}').join(params[p]);
        }
    }
    return v;
}

function getCurrentLang() { return _lang; }
function isRTL(lang) { return RTL_LANGS.includes(lang || _lang); }

function _stripLangPrefix(path) {
    for (const l of ['en', 'fr', 'tr', 'ur', 'de', 'id', 'es', 'bn', 'ms']) {
        if (path === '/' + l) return '/';
        if (path.startsWith('/' + l + '/')) return path.substring(l.length + 1) || '/';
    }
    return path;
}

function setLanguage(lang) {
    if (!SUPPORTED_LANGS.includes(lang)) return;
    // التنقل بين إصدارات URL عند تغيير اللغة
    const curPath = window.location.pathname;
    const basePath = _stripLangPrefix(curPath).replace(/\.html$/, '');
    if (window.location.protocol !== 'file:') {
        localStorage.setItem('app_lang', lang);
        const prefix = (lang === 'ar') ? '' : ('/' + lang);
        // Phase HC-5 (2026-05-06): the previous formula
        //     prefix + (basePath === '/' ? '/' : basePath)
        // produced '/en/' (with trailing slash) for the homepage in non-AR
        // languages, but the server canonicalizes to '/en' (no trailing
        // slash) via 301. Result: clicking a non-AR lang from / triggered
        // an infinite redirect loop:
        //     setLanguage('en') → window.location.href='/en/'
        //     server 301 → /en
        //     DOMContentLoaded → setLanguage('en') → href='/en/' again
        //     loop forever
        // Fix: when basePath is the root, drop the trailing slash for
        // non-AR (use just the prefix '/en'). For AR (no prefix), keep '/'.
        const newPath = (basePath === '/')
            ? (prefix || '/')
            : (prefix + basePath);
        if (newPath !== curPath) {
            window.location.href = newPath + window.location.search;
            return;
        }
    }
    _lang = lang;
    localStorage.setItem('app_lang', lang);

    // تحديث اتجاه الصفحة
    document.documentElement.lang = lang;
    document.documentElement.dir  = isRTL(lang) ? 'rtl' : 'ltr';

    // تطبيق النصوص الثابتة
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        const val = t(key);
        if (val && val !== key) el.textContent = val;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.dataset.i18nPlaceholder;
        const val = t(key);
        if (val && val !== key) el.placeholder = val;
    });
    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const key = el.dataset.i18nTitle;
        const val = t(key);
        if (val && val !== key) el.title = val;
    });
    // 🆕 Round 8b: aria-label attribute i18n (tooltip accessibility parity across 10 langs)
    document.querySelectorAll('[data-i18n-aria-label]').forEach(el => {
        const key = el.dataset.i18nAriaLabel;
        const val = t(key);
        if (val && val !== key) el.setAttribute('aria-label', val);
    });
    // UAT-3c.2: alt attribute i18n (image accessibility — flag images, etc.)
    document.querySelectorAll('[data-i18n-alt]').forEach(el => {
        const key = el.dataset.i18nAlt;
        const val = t(key);
        if (val && val !== key) el.setAttribute('alt', val);
    });

    // تحديث زر اللغة (الإصدار القديم — للتوافق الخلفي)
    const LANG_BTN_LABELS = { ar: 'عر', en: 'EN', fr: 'FR', tr: 'TR', ur: 'اردو', de: 'DE', id: 'ID', es: 'ES', bn: 'BN', ms: 'MS' };
    document.querySelectorAll('.lang-toggle-btn').forEach(btn => {
        const order = ['ar','en','fr','tr','ur','de','id','es','bn','ms'];
        const next  = order[(order.indexOf(lang) + 1) % order.length];
        btn.textContent = LANG_BTN_LABELS[next] || 'EN';
        btn.setAttribute('data-next-lang', next);
    });
    // تحديث القائمة المنسدلة للغة إن وُجدت
    document.querySelectorAll('.lang-select').forEach(sel => {
        if (sel.value !== lang) sel.value = lang;
    });
    // تحديث مُبدّل اللغة الجديد (الأعلام + القائمة)
    _renderLangSwitcher();

    // تحديث أشهر الهجري والميلادي وأيام الأسبوع في HijriDate
    if (typeof HijriDate !== 'undefined') {
        const hm = Array.from({length:12}, (_,i) => t('hmonth.'+(i+1)));
        const gm = Array.from({length:12}, (_,i) => t('gmonth.'+(i+1)));
        const wd = Array.from({length:7},  (_,i) => t('wday.'+i));
        HijriDate.hijriMonths.splice(0, 12, ...hm);
        HijriDate.gregorianMonths.splice(0, 12, ...gm);
        HijriDate.dayNames.splice(0, 7, ...wd);
    }

    // إعادة رسم المحتوى الديناميكي
    if (typeof onLanguageChange === 'function') onLanguageChange(lang);
}

function toggleLanguage() {
    // دورة: AR → EN → FR → TR → UR → DE → ID → ES → BN → MS → AR (للتوافق الخلفي)
    const order = ['ar', 'en', 'fr', 'tr', 'ur', 'de', 'id', 'es', 'bn', 'ms'];
    const next  = order[(order.indexOf(_lang) + 1) % order.length];
    setLanguage(next);
}

// ===== مُبدّل اللغة الجديد: زر العلم + قائمة منسدلة =====
// iso: رمز الدولة لعرض العلم من flagcdn.com
const LANG_META = {
    ar: { iso: 'sa', code: 'AR', name: 'العربية' },
    en: { iso: 'gb', code: 'EN', name: 'English' },
    fr: { iso: 'fr', code: 'FR', name: 'Français' },
    tr: { iso: 'tr', code: 'TR', name: 'Türkçe' },
    ur: { iso: 'pk', code: 'UR', name: 'اردو' },
    de: { iso: 'de', code: 'DE', name: 'Deutsch' },
    id: { iso: 'id', code: 'ID', name: 'Bahasa Indonesia' },
    es: { iso: 'es', code: 'ES', name: 'Español' },
    bn: { iso: 'bd', code: 'BN', name: 'বাংলা' },
    ms: { iso: 'my', code: 'MS', name: 'Bahasa Melayu' }
};
const _FLAG_BASE = 'https://flagcdn.com/w40/';

function _renderLangSwitcher() {
    document.querySelectorAll('.lang-switcher').forEach(sw => {
        const btn = sw.querySelector('.lang-switcher-btn');
        const menu = sw.querySelector('.lang-menu');
        if (!btn || !menu) return;
        const cur = LANG_META[_lang] || LANG_META.en;
        const flagEl = btn.querySelector('.lang-flag');
        const codeEl = btn.querySelector('.lang-code');
        if (flagEl) {
            // إن كان العلم <img> نُحدّث src، وإلا نُحوّله
            if (flagEl.tagName === 'IMG') {
                flagEl.src = _FLAG_BASE + cur.iso + '.png';
                flagEl.alt = cur.code;
            } else {
                const img = document.createElement('img');
                img.className = 'lang-flag';
                img.src = _FLAG_BASE + cur.iso + '.png';
                img.alt = cur.code;
                img.width = 20; img.height = 15;
                img.loading = 'eager';
                flagEl.replaceWith(img);
            }
        }
        if (codeEl) codeEl.textContent = cur.code;
        // بناء عناصر القائمة: كل اللغات عدا الحالية
        menu.innerHTML = SUPPORTED_LANGS
            .filter(l => l !== _lang)
            .map(l => {
                const m = LANG_META[l];
                return `<button class="lang-menu-item" role="menuitem" type="button" data-lang="${l}">
                            <img class="lang-flag" src="${_FLAG_BASE}${m.iso}.png" alt="${m.code}" width="22" height="16" loading="lazy">
                            <span class="lang-name">${m.name}</span>
                        </button>`;
            }).join('');
        menu.querySelectorAll('.lang-menu-item').forEach(mi => {
            mi.addEventListener('click', (e) => {
                e.stopPropagation();
                sw.classList.remove('open');
                btn.setAttribute('aria-expanded', 'false');
                setLanguage(mi.dataset.lang);
            });
        });
    });
}

function toggleLangMenu(btn) {
    const sw = btn.closest('.lang-switcher');
    if (!sw) return;
    const isOpen = sw.classList.toggle('open');
    btn.setAttribute('aria-expanded', String(isOpen));
    // إغلاق أي قوائم أخرى مفتوحة
    document.querySelectorAll('.lang-switcher.open').forEach(other => {
        if (other !== sw) {
            other.classList.remove('open');
            const b = other.querySelector('.lang-switcher-btn');
            if (b) b.setAttribute('aria-expanded', 'false');
        }
    });
}

// حماية SSR: تجاهل ربط أحداث DOM خارج المتصفّح
if (typeof document !== 'undefined') {
    // إغلاق القائمة عند النقر خارجها أو Escape
    document.addEventListener('click', (e) => {
        document.querySelectorAll('.lang-switcher.open').forEach(sw => {
            if (!sw.contains(e.target)) {
                sw.classList.remove('open');
                const b = sw.querySelector('.lang-switcher-btn');
                if (b) b.setAttribute('aria-expanded', 'false');
            }
        });
    });
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            document.querySelectorAll('.lang-switcher.open').forEach(sw => {
                sw.classList.remove('open');
                const b = sw.querySelector('.lang-switcher-btn');
                if (b) b.setAttribute('aria-expanded', 'false');
            });
        }
    });

    // تطبيق اللغة عند تحميل الصفحة
    document.addEventListener('DOMContentLoaded', () => setLanguage(_lang));
}
