// Hijri New Year translations — 10 languages × ~67 keys

module.exports = {

ar: {
    'hijri_ny.h1': '📅 كم باقي على رأس السنة الهجريّة؟',
    'hijri_ny.intro': 'اكتشف الأيّام المتبقّية حتّى رأس السنة الهجريّة الجديدة مع التاريخ الميلاديّ والهجريّ. يوافق أوّل يوم من شهر محرّم بداية السنة الهجريّة، وقد يختلف الإعلان يومًا بين الدول حسب ثبوت هلال محرّم.',
    'hijri_ny.event_name': 'رأس السنة الهجريّة',
    'hijri_ny.hijri_1': '1 محرّم',
    'hijri_ny.meta_title': '📅 كم باقي على رأس السنة الهجريّة؟ — التاريخ المتوقّع وعدّ تنازليّ',
    'hijri_ny.meta_desc': 'عدّ تنازليّ دقيق لرأس السنة الهجريّة الجديدة (1 محرّم) — بالأيّام والساعات والدقائق — مع التاريخ الميلاديّ والهجريّ والسياق التاريخيّ للهجرة النبويّة.',
    'hijri_ny.cards_title': '📋 معلومات أساسيّة',
    'hijri_ny.card1_title': 'رأس السنة الهجريّة المتوقّع',
    'hijri_ny.card2_title': 'التاريخ الهجريّ',
    'hijri_ny.card3_title': 'الأيّام المتبقّية',
    'hijri_ny.card4_title': 'حالة التحديد',
    'hijri_ny.card4_value': 'حسابيّ · بانتظار الرؤية',
    'hijri_ny.notice_title': '📜 اعتماد التاريخ',
    'hijri_ny.notice_body': 'رأس السنة الهجريّة يبدأ بأوّل يوم من شهر محرّم. التاريخ المعروض محسوب فلكيًّا وفق التقويم الهجريّ الحسابيّ، وقد يختلف الإعلان الرسميّ بيوم واحد حسب رؤية هلال محرّم في كلّ بلد.',
    'hijri_ny.lunar_title': '🌙 الارتباط القمريّ',
    'hijri_ny.lunar_current': 'مرحلة القمر الحاليّة:',
    'hijri_ny.lunar_link_today': '🌙 حالة القمر اليوم →',
    'hijri_ny.lunar_link_new_moon': '🌑 المحاق القادم →',
    'hijri_ny.lunar_link_crescent': '🌒 هلال محرّم القادم →',
    'hijri_ny.years_title': '📅 مواعيد رأس السنة الهجريّة في السنوات القادمة',
    'hijri_ny.years_col_hijri': 'السنة الهجريّة',
    'hijri_ny.years_col_greg': 'السنة الميلاديّة',
    'hijri_ny.years_col_start': '1 محرّم (تقديريّ)',
    'hijri_ny.years_col_note': 'ملاحظة',
    'hijri_ny.years_note': '* جميع التواريخ تقديريّة حسابيًّا وقد تختلف بيوم واحد حسب الرؤية.',
    'hijri_ny.years_note_cell': 'تقديريّ · يعتمد على الرؤية',
    'hijri_ny.cities_title': '🌍 رأس السنة الهجريّة حول العالم',
    'hijri_ny.city_sa': 'رأس السنة الهجريّة في السعودية',
    'hijri_ny.city_eg': 'رأس السنة الهجريّة في مصر',
    'hijri_ny.city_ae': 'رأس السنة الهجريّة في الإمارات',
    'hijri_ny.city_uk': 'رأس السنة الهجريّة في لندن',
    'hijri_ny.city_tr': 'رأس السنة الهجريّة في إسطنبول',
    'hijri_ny.city_id': 'رأس السنة الهجريّة في جاكرتا',
    'hijri_ny.faq_title': '❓ أسئلة شائعة عن رأس السنة الهجريّة',
    'hijri_ny.faq_q1': 'كم باقي على رأس السنة الهجريّة؟',
    'hijri_ny.faq_a1': 'يتبقّى {n} يومًا على رأس السنة الهجريّة المتوقّع.',
    'hijri_ny.faq_q2': 'متى تبدأ السنة الهجريّة الجديدة هذا العام؟',
    'hijri_ny.faq_a2': 'تبدأ السنة الهجريّة {hyear} هـ بتاريخ {date} تقديريًّا.',
    'hijri_ny.faq_q3': 'ما التاريخ الهجريّ لرأس السنة؟',
    'hijri_ny.faq_a3': 'يوافق اليوم الأوّل من شهر محرّم سنة {hyear} هـ.',
    'hijri_ny.faq_q4': 'هل قد يختلف موعد رأس السنة الهجريّة بين الدول؟',
    'hijri_ny.faq_a4': 'نعم، قد يختلف يومًا واحدًا بين الدول حسب الرؤية المحلّيّة لهلال شهر محرّم.',
    'hijri_ny.faq_q5': 'ما مناسبة رأس السنة الهجريّة؟',
    'hijri_ny.faq_a5': 'يبدأ التاريخ الهجريّ من هجرة النبيّ ﷺ من مكّة إلى المدينة المنوّرة، وقد اعتمد هذا التأريخ الخليفة عمر بن الخطّاب رضي الله عنه.',
    'hijri_ny.faq_q6': 'ما هو شهر محرّم؟',
    'hijri_ny.faq_a6': 'محرّم هو الشهر الأوّل من السنة الهجريّة، وأحد الأشهر الحرم الأربعة، ويُستحبّ فيه الصيام لا سيّما يوم عاشوراء.',
    'hijri_ny.faq_q7': 'ما هو يوم عاشوراء؟',
    'hijri_ny.faq_a7': 'عاشوراء هو اليوم العاشر من شهر محرّم، وصيامه سنّة مؤكّدة لأنّ فيه نجّى الله موسى عليه السلام ومن معه من فرعون.',
    'hijri_ny.faq_q8': 'هل يحتفل المسلمون برأس السنة الهجريّة؟',
    'hijri_ny.faq_a8': 'رأس السنة الهجريّة ذكرى تأمّل ومحاسبة للنفس، وليس عيدًا من الأعياد الشرعيّة، لكنّ كثيرًا من المسلمين يتخذونه مناسبة للتذكير بسيرة الهجرة.',
    'hijri_ny.faq_q9': 'كم عدد أيّام السنة الهجريّة؟',
    'hijri_ny.faq_a9': 'السنة الهجريّة القمريّة حوالي 354 يومًا، أي أقصر من السنة الميلاديّة بـ 10 أو 11 يومًا.',
    'hijri_ny.faq_q10': 'لماذا تتحرّك المناسبات الإسلاميّة على التقويم الميلاديّ؟',
    'hijri_ny.faq_a10': 'لأنّ السنة الهجريّة قمريّة وأقصر من السنة الميلاديّة الشمسيّة، فتتقدّم المناسبات الإسلاميّة 10-11 يومًا كلّ سنة ميلاديّة.',
    'hijri_ny.info_title': '📖 معلومات عن رأس السنة الهجريّة',
    'hijri_ny.info_h1': 'بداية التقويم الإسلاميّ',
    'hijri_ny.info_h1_body': 'التقويم الهجريّ تقويم قمريّ اعتمده المسلمون رسميًّا في عهد الخليفة عمر بن الخطّاب رضي الله عنه، وجُعلت بدايته من السنة التي هاجر فيها النبيّ ﷺ من مكّة إلى المدينة المنوّرة، ويتكوّن من 12 شهرًا قمريًّا.',
    'hijri_ny.info_h2': 'شهر محرّم والأشهر الحرم',
    'hijri_ny.info_h2_body': 'محرّم أحد الأشهر الحرم الأربعة (ذو القعدة، ذو الحجّة، محرّم، رجب)، وقد عظّمه الإسلام كما عظّمته العرب من قبل، ويتأكّد فيه اجتناب الظلم والمحرّمات.',
    'hijri_ny.info_h3': 'يوم عاشوراء',
    'hijri_ny.info_h3_body': 'اليوم العاشر من محرّم يوم فضيل؛ صامه النبيّ ﷺ شكرًا لله لما نجّى موسى عليه السلام، ويُستحبّ صيامه مع اليوم التاسع (تاسوعاء) مخالفةً لأهل الكتاب.',
    'hijri_ny.links_title': '🔗 روابط مفيدة',
    'hijri_ny.link_ramadan': '🌙 كم باقي على رمضان',
    'hijri_ny.link_fitr': '🎉 كم باقي على عيد الفطر',
    'hijri_ny.link_adha': '🐑 كم باقي على عيد الأضحى',
    'hijri_ny.link_moon': '🌙 حالة القمر اليوم',
    'hijri_ny.link_hijri_today': '📅 التاريخ الهجريّ اليوم',
},

en: {
    'hijri_ny.h1': '📅 How Long Until Hijri New Year?',
    'hijri_ny.intro': 'Discover the days remaining until the new Hijri (Islamic lunar) year with the expected Gregorian and Hijri dates. The new year begins on 1 Muharram, and the announcement may differ by a day between countries based on the Muharram crescent sighting.',
    'hijri_ny.event_name': 'Hijri New Year',
    'hijri_ny.hijri_1': '1 Muharram',
    'hijri_ny.meta_title': '📅 Hijri New Year Countdown — Expected Date & Live Timer',
    'hijri_ny.meta_desc': 'Accurate countdown to the new Hijri year (1 Muharram) — in days, hours, and minutes — with Gregorian and Hijri dates and historical context of the Prophetic migration (Hijrah).',
    'hijri_ny.cards_title': '📋 Key Information',
    'hijri_ny.card1_title': 'Expected Hijri New Year',
    'hijri_ny.card2_title': 'Hijri Date',
    'hijri_ny.card3_title': 'Days Remaining',
    'hijri_ny.card4_title': 'Status',
    'hijri_ny.card4_value': 'Calculated \u00B7 Pending sighting',
    'hijri_ny.notice_title': '\ud83d\udcdc Date Verification',
    'hijri_ny.notice_body': 'The Hijri New Year begins with the first day of Muharram. The date shown is astronomically calculated according to the tabular Hijri calendar; the official announcement may differ by one day depending on the local sighting of the Muharram crescent in each country.',
    'hijri_ny.lunar_title': '\ud83c\udf19 Lunar Connection',
    'hijri_ny.lunar_current': 'Current moon phase:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 Moon status today \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 Next new moon \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 Next Muharram crescent \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 Hijri New Year Dates in Upcoming Years',
    'hijri_ny.years_col_hijri': 'Hijri Year',
    'hijri_ny.years_col_greg': 'Gregorian Year',
    'hijri_ny.years_col_start': '1 Muharram (estimated)',
    'hijri_ny.years_col_note': 'Note',
    'hijri_ny.years_note': '* All dates are calculated estimates and may differ by one day based on sighting.',
    'hijri_ny.years_note_cell': 'Estimated \u00B7 Depends on sighting',
    'hijri_ny.cities_title': '\ud83c\udf0d Hijri New Year Around the World',
    'hijri_ny.city_sa': 'Hijri New Year in Saudi Arabia',
    'hijri_ny.city_eg': 'Hijri New Year in Egypt',
    'hijri_ny.city_ae': 'Hijri New Year in the UAE',
    'hijri_ny.city_uk': 'Hijri New Year in London',
    'hijri_ny.city_tr': 'Hijri New Year in Istanbul',
    'hijri_ny.city_id': 'Hijri New Year in Jakarta',
    'hijri_ny.faq_title': '\u2753 Frequently Asked Questions about Hijri New Year',
    'hijri_ny.faq_q1': 'How many days until the Hijri New Year?',
    'hijri_ny.faq_a1': '{n} days remain until the expected Hijri New Year.',
    'hijri_ny.faq_q2': 'When does the new Hijri year begin this year?',
    'hijri_ny.faq_q3': 'What is the Hijri date of the new year?',
    'hijri_ny.faq_a2': 'The Hijri year {hyear} AH begins on {date} (estimated).',
    'hijri_ny.faq_a3': 'It corresponds to the 1st day of Muharram in the year {hyear} AH.',
    'hijri_ny.faq_q4': 'Can the date of the Hijri New Year differ between countries?',
    'hijri_ny.faq_a4': 'Yes, it may differ by one day between countries depending on local sighting of the Muharram crescent.',
    'hijri_ny.faq_q5': 'What is the occasion of the Hijri New Year?',
    'hijri_ny.faq_a5': 'The Hijri calendar begins from the migration (Hijrah) of the Prophet Muhammad \uFEFA from Mecca to Medina. This dating was adopted by Caliph Umar ibn al-Khattab (may Allah be pleased with him).',
    'hijri_ny.faq_q6': 'What is the month of Muharram?',
    'hijri_ny.faq_a6': 'Muharram is the first month of the Hijri year and one of the four sacred months. Fasting is recommended during it, especially on the Day of Ashura.',
    'hijri_ny.faq_q7': 'What is the Day of Ashura?',
    'hijri_ny.faq_a7': 'Ashura is the tenth day of Muharram. Fasting on it is a confirmed Sunnah because on this day Allah saved Moses (peace be upon him) and his people from Pharaoh.',
    'hijri_ny.faq_q8': 'Do Muslims celebrate the Hijri New Year?',
    'hijri_ny.faq_a8': 'The Hijri New Year is an occasion for reflection and self-review rather than a religious festival, though many Muslims use it to remember the Prophetic migration.',
    'hijri_ny.faq_q9': 'How many days are there in a Hijri year?',
    'hijri_ny.faq_a9': 'The lunar Hijri year is about 354 days, which is 10 or 11 days shorter than the Gregorian solar year.',
    'hijri_ny.faq_q10': 'Why do Islamic occasions shift each Gregorian year?',
    'hijri_ny.faq_a10': 'Because the Hijri year is lunar and shorter than the solar Gregorian year, Islamic occasions advance by 10\u201311 days every Gregorian year.',
    'hijri_ny.info_title': '\ud83d\udcd6 About the Hijri New Year',
    'hijri_ny.info_h1': 'Start of the Islamic Calendar',
    'hijri_ny.info_h1_body': 'The Hijri calendar is a lunar calendar officially adopted by Muslims during the reign of Caliph Umar ibn al-Khattab. Its starting point is the year of the Prophet Muhammad\u2019s migration from Mecca to Medina, and it consists of 12 lunar months.',
    'hijri_ny.info_h2': 'Muharram and the Sacred Months',
    'hijri_ny.info_h2_body': 'Muharram is one of the four sacred months (Dhul-Qi\u2018dah, Dhul-Hijjah, Muharram, and Rajab). Islam honored it as the Arabs had before, and avoiding injustice and forbidden acts during it is especially emphasized.',
    'hijri_ny.info_h3': 'The Day of Ashura',
    'hijri_ny.info_h3_body': 'The tenth of Muharram is a virtuous day; the Prophet \uFEFA fasted it in gratitude to Allah for saving Moses (peace be upon him). Fasting it together with the ninth (Tasu\u2018a) is recommended to differ from the People of the Book.',
    'hijri_ny.links_title': '\ud83d\udd17 Useful Links',
    'hijri_ny.link_ramadan': '\ud83c\udf19 How Long Until Ramadan',
    'hijri_ny.link_fitr': '\ud83c\udf89 How Long Until Eid al-Fitr',
    'hijri_ny.link_adha': '\ud83d\udc11 How Long Until Eid al-Adha',
    'hijri_ny.link_moon': '\ud83c\udf19 Moon Status Today',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 Hijri Date Today',
},

fr: {
    'hijri_ny.h1': '\ud83d\udcc5 Combien de jours avant le Nouvel An hégirien\u00a0?',
    'hijri_ny.intro': 'Découvrez les jours restants avant le nouvel an hégirien (calendrier lunaire islamique) avec les dates grégorienne et hégirienne prévues. La nouvelle année commence le 1er Mouharram, et l\u2019annonce peut varier d\u2019un jour selon l\u2019observation du croissant de Mouharram dans chaque pays.',
    'hijri_ny.event_name': 'Nouvel An hégirien',
    'hijri_ny.hijri_1': '1 Mouharram',
    'hijri_ny.meta_title': '\ud83d\udcc5 Combien de jours avant le Nouvel An hégirien\u00a0? \u2014 Date prévue et compte à rebours',
    'hijri_ny.meta_desc': 'Compte à rebours précis jusqu\u2019au nouvel an hégirien (1 Mouharram) \u2014 en jours, heures et minutes \u2014 avec les dates grégorienne et hégirienne et le contexte historique de l\u2019Hégire prophétique.',
    'hijri_ny.cards_title': '\ud83d\udccb Informations clés',
    'hijri_ny.card1_title': 'Nouvel An hégirien prévu',
    'hijri_ny.card2_title': 'Date hégirienne',
    'hijri_ny.card3_title': 'Jours restants',
    'hijri_ny.card4_title': 'Statut',
    'hijri_ny.card4_value': 'Calculé \u00B7 En attente d\u2019observation',
    'hijri_ny.notice_title': '\ud83d\udcdc Vérification de la date',
    'hijri_ny.notice_body': 'Le Nouvel An hégirien commence le premier jour de Mouharram. La date affichée est calculée astronomiquement selon le calendrier hégirien tabulaire\u00a0; l\u2019annonce officielle peut varier d\u2019un jour selon l\u2019observation locale du croissant de Mouharram dans chaque pays.',
    'hijri_ny.lunar_title': '\ud83c\udf19 Lien lunaire',
    'hijri_ny.lunar_current': 'Phase actuelle de la lune\u00a0:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 État de la lune aujourd\u2019hui \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 Prochaine nouvelle lune \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 Prochain croissant de Mouharram \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 Dates du Nouvel An hégirien pour les prochaines années',
    'hijri_ny.years_col_hijri': 'Année hégirienne',
    'hijri_ny.years_col_greg': 'Année grégorienne',
    'hijri_ny.years_col_start': '1 Mouharram (estimation)',
    'hijri_ny.years_col_note': 'Remarque',
    'hijri_ny.years_note': '* Toutes les dates sont des estimations calculées et peuvent varier d\u2019un jour selon l\u2019observation.',
    'hijri_ny.years_note_cell': 'Estimation \u00B7 Dépend de l\u2019observation',
    'hijri_ny.cities_title': '\ud83c\udf0d Le Nouvel An hégirien à travers le monde',
    'hijri_ny.city_sa': 'Nouvel An hégirien en Arabie saoudite',
    'hijri_ny.city_eg': 'Nouvel An hégirien en Égypte',
    'hijri_ny.city_ae': 'Nouvel An hégirien aux Émirats arabes unis',
    'hijri_ny.city_uk': 'Nouvel An hégirien à Londres',
    'hijri_ny.city_tr': 'Nouvel An hégirien à Istanbul',
    'hijri_ny.city_id': 'Nouvel An hégirien à Jakarta',
    'hijri_ny.faq_title': '\u2753 Questions fréquentes sur le Nouvel An hégirien',
    'hijri_ny.faq_q1': 'Combien de jours avant le Nouvel An hégirien\u00a0?',
    'hijri_ny.faq_a1': 'Il reste {n} jours avant le Nouvel An hégirien prévu.',
    'hijri_ny.faq_q2': 'Quand commence la nouvelle année hégirienne cette année\u00a0?',
    'hijri_ny.faq_a2': 'L\u2019année hégirienne {hyear} AH commence le {date} (estimé).',
    'hijri_ny.faq_q3': 'Quelle est la date hégirienne du nouvel an\u00a0?',
    'hijri_ny.faq_a3': 'Elle correspond au 1er jour de Mouharram de l\u2019an {hyear} AH.',
    'hijri_ny.faq_q4': 'La date du Nouvel An hégirien peut-elle différer entre les pays\u00a0?',
    'hijri_ny.faq_a4': 'Oui, elle peut varier d\u2019un jour selon l\u2019observation locale du croissant de Mouharram.',
    'hijri_ny.faq_q5': 'Quelle est l\u2019origine du Nouvel An hégirien\u00a0?',
    'hijri_ny.faq_a5': 'Le calendrier hégirien commence à partir de l\u2019Hégire (migration) du Prophète Mahomet \uFEFA de La Mecque à Médine. Cette datation fut adoptée par le calife Omar ibn al-Khattab.',
    'hijri_ny.faq_q6': 'Qu\u2019est-ce que le mois de Mouharram\u00a0?',
    'hijri_ny.faq_a6': 'Mouharram est le premier mois de l\u2019année hégirienne et l\u2019un des quatre mois sacrés. Le jeûne y est recommandé, en particulier le jour d\u2019Achoura.',
    'hijri_ny.faq_q7': 'Qu\u2019est-ce que le jour d\u2019Achoura\u00a0?',
    'hijri_ny.faq_a7': 'Achoura est le dixième jour de Mouharram. Son jeûne est une Sunna confirmée, car en ce jour Allah a sauvé Moïse (paix sur lui) et son peuple de Pharaon.',
    'hijri_ny.faq_q8': 'Les musulmans célèbrent-ils le Nouvel An hégirien\u00a0?',
    'hijri_ny.faq_a8': 'Le Nouvel An hégirien est une occasion de réflexion et d\u2019examen de soi plutôt qu\u2019une fête religieuse, mais beaucoup de musulmans s\u2019en servent pour se rappeler l\u2019Hégire.',
    'hijri_ny.faq_q9': 'Combien de jours y a-t-il dans une année hégirienne\u00a0?',
    'hijri_ny.faq_a9': 'L\u2019année lunaire hégirienne compte environ 354 jours, soit 10 à 11 jours de moins que l\u2019année grégorienne.',
    'hijri_ny.faq_q10': 'Pourquoi les fêtes islamiques se décalent-elles chaque année grégorienne\u00a0?',
    'hijri_ny.faq_a10': 'Parce que l\u2019année hégirienne est lunaire et plus courte que l\u2019année grégorienne solaire, les occasions islamiques avancent de 10 à 11 jours chaque année grégorienne.',
    'hijri_ny.info_title': '\ud83d\udcd6 À propos du Nouvel An hégirien',
    'hijri_ny.info_h1': 'Début du calendrier islamique',
    'hijri_ny.info_h1_body': 'Le calendrier hégirien est un calendrier lunaire officiellement adopté par les musulmans sous le califat d\u2019Omar ibn al-Khattab. Son point de départ est l\u2019année de la migration du Prophète Mahomet de La Mecque à Médine, et il comprend 12 mois lunaires.',
    'hijri_ny.info_h2': 'Mouharram et les mois sacrés',
    'hijri_ny.info_h2_body': 'Mouharram est l\u2019un des quatre mois sacrés (Dhou al-Qi\u2018da, Dhou al-Hijja, Mouharram et Rajab). L\u2019islam l\u2019a honoré comme les Arabes avant lui, et il y est particulièrement important d\u2019éviter l\u2019injustice et les actes interdits.',
    'hijri_ny.info_h3': 'Le jour d\u2019Achoura',
    'hijri_ny.info_h3_body': 'Le dixième de Mouharram est un jour vertueux\u00a0; le Prophète \uFEFA l\u2019a jeûné en gratitude envers Allah pour avoir sauvé Moïse (paix sur lui). Il est recommandé de le jeûner avec le neuvième (Tasou\u2018a) pour se distinguer des Gens du Livre.',
    'hijri_ny.links_title': '\ud83d\udd17 Liens utiles',
    'hijri_ny.link_ramadan': '\ud83c\udf19 Combien de jours avant le Ramadan',
    'hijri_ny.link_fitr': '\ud83c\udf89 Combien de jours avant l\u2019Aïd el-Fitr',
    'hijri_ny.link_adha': '\ud83d\udc11 Combien de jours avant l\u2019Aïd el-Adha',
    'hijri_ny.link_moon': '\ud83c\udf19 État de la lune aujourd\u2019hui',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 Date hégirienne aujourd\u2019hui',
},

tr: {
    'hijri_ny.h1': '\ud83d\udcc5 Hicri Yılbaşına Ne Kadar Kaldı?',
    'hijri_ny.intro': 'Yeni hicri (İslami ay) yılına kalan günleri miladi ve hicri tarihlerle birlikte keşfedin. Yeni yıl 1 Muharrem\u2019de başlar; resmî ilan, her ülkedeki Muharrem hilalinin görülmesine göre bir gün farklılık gösterebilir.',
    'hijri_ny.event_name': 'Hicri Yılbaşı',
    'hijri_ny.hijri_1': '1 Muharrem',
    'hijri_ny.meta_title': '\ud83d\udcc5 Hicri Yılbaşı Geri Sayım — Beklenen Tarih ve Canlı Sayaç',
    'hijri_ny.meta_desc': 'Yeni hicri yıla (1 Muharrem) gün, saat ve dakika cinsinden hassas geri sayım — miladi ve hicri tarihler ile peygamber efendimizin hicretinin tarihsel bağlamıyla birlikte.',
    'hijri_ny.cards_title': '\ud83d\udccb Temel Bilgiler',
    'hijri_ny.card1_title': 'Beklenen Hicri Yılbaşı',
    'hijri_ny.card2_title': 'Hicri Tarih',
    'hijri_ny.card3_title': 'Kalan Gün',
    'hijri_ny.card4_title': 'Durum',
    'hijri_ny.card4_value': 'Hesaplanmış \u00B7 Rüyet bekleniyor',
    'hijri_ny.notice_title': '\ud83d\udcdc Tarih Doğrulaması',
    'hijri_ny.notice_body': 'Hicri Yılbaşı, Muharrem ayının ilk günü başlar. Gösterilen tarih tablo esaslı hicri takvime göre astronomik olarak hesaplanır; resmi ilan, her ülkedeki Muharrem hilalinin yerel olarak görülmesine bağlı olarak bir gün değişebilir.',
    'hijri_ny.lunar_title': '\ud83c\udf19 Ay Bağlantısı',
    'hijri_ny.lunar_current': 'Şu anki ay evresi:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 Bugün ayın durumu \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 Sonraki yeni ay \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 Sonraki Muharrem hilali \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 Önümüzdeki Yıllarda Hicri Yılbaşı Tarihleri',
    'hijri_ny.years_col_hijri': 'Hicri Yıl',
    'hijri_ny.years_col_greg': 'Miladi Yıl',
    'hijri_ny.years_col_start': '1 Muharrem (tahmini)',
    'hijri_ny.years_col_note': 'Not',
    'hijri_ny.years_note': '* Tüm tarihler hesaplanmış tahminlerdir ve rüyete göre bir gün değişebilir.',
    'hijri_ny.years_note_cell': 'Tahmini \u00B7 Rüyete bağlı',
    'hijri_ny.cities_title': '\ud83c\udf0d Dünyada Hicri Yılbaşı',
    'hijri_ny.city_sa': 'Suudi Arabistan\u2019da Hicri Yılbaşı',
    'hijri_ny.city_eg': 'Mısır\u2019da Hicri Yılbaşı',
    'hijri_ny.city_ae': 'BAE\u2019de Hicri Yılbaşı',
    'hijri_ny.city_uk': 'Londra\u2019da Hicri Yılbaşı',
    'hijri_ny.city_tr': 'İstanbul\u2019da Hicri Yılbaşı',
    'hijri_ny.city_id': 'Jakarta\u2019da Hicri Yılbaşı',
    'hijri_ny.faq_title': '\u2753 Hicri Yılbaşı Hakkında Sık Sorulan Sorular',
    'hijri_ny.faq_q1': 'Hicri Yılbaşına kaç gün kaldı?',
    'hijri_ny.faq_a1': 'Beklenen Hicri Yılbaşına {n} gün kaldı.',
    'hijri_ny.faq_q2': 'Yeni hicri yıl bu yıl ne zaman başlıyor?',
    'hijri_ny.faq_a2': '{hyear} hicri yılı tahminî olarak {date} tarihinde başlar.',
    'hijri_ny.faq_q3': 'Yeni yılın hicri tarihi nedir?',
    'hijri_ny.faq_a3': '{hyear} hicri yılının Muharrem ayının 1. gününe denk gelir.',
    'hijri_ny.faq_q4': 'Hicri Yılbaşının tarihi ülkeler arasında değişebilir mi?',
    'hijri_ny.faq_a4': 'Evet, Muharrem hilalinin yerel olarak görülmesine göre ülkeler arasında bir gün fark olabilir.',
    'hijri_ny.faq_q5': 'Hicri Yılbaşı hangi olaya dayanır?',
    'hijri_ny.faq_a5': 'Hicri takvim, Peygamber Efendimiz\u2019in \uFEFA Mekke\u2019den Medine\u2019ye hicretiyle başlar. Bu tarihlendirme Halife Ömer bin Hattab (r.a.) tarafından kabul edilmiştir.',
    'hijri_ny.faq_q6': 'Muharrem ayı nedir?',
    'hijri_ny.faq_a6': 'Muharrem, hicri yılın ilk ayı ve dört haram aydan biridir. Bu ayda oruç tutmak, özellikle Aşure gününde, müstehaptır.',
    'hijri_ny.faq_q7': 'Aşure günü nedir?',
    'hijri_ny.faq_a7': 'Aşure, Muharrem ayının onuncu günüdür. Bu gün Allah\u2019ın Musa\u2019yı (a.s.) ve kavmini Firavun\u2019dan kurtardığı gün olduğu için oruç tutmak müekked sünnettir.',
    'hijri_ny.faq_q8': 'Müslümanlar Hicri Yılbaşını kutlar mı?',
    'hijri_ny.faq_a8': 'Hicri Yılbaşı dinî bir bayramdan çok, tefekkür ve muhasebe günüdür; ancak birçok Müslüman onu hicreti hatırlamak için bir vesile olarak değerlendirir.',
    'hijri_ny.faq_q9': 'Bir hicri yılda kaç gün vardır?',
    'hijri_ny.faq_a9': 'Kameri hicri yıl yaklaşık 354 gündür, yani güneş esaslı miladi yıldan 10-11 gün daha kısadır.',
    'hijri_ny.faq_q10': 'İslami mübarek günler her miladi yılda neden kayar?',
    'hijri_ny.faq_a10': 'Hicri yıl kameri olduğu ve güneş esaslı miladi yıldan daha kısa olduğu için İslami mübarek günler her miladi yılda 10-11 gün öne kayar.',
    'hijri_ny.info_title': '\ud83d\udcd6 Hicri Yılbaşı Hakkında',
    'hijri_ny.info_h1': 'İslami Takvimin Başlangıcı',
    'hijri_ny.info_h1_body': 'Hicri takvim, Halife Ömer bin Hattab döneminde Müslümanlar tarafından resmen kabul edilen kameri bir takvimdir. Başlangıç noktası, Peygamber Efendimiz\u2019in Mekke\u2019den Medine\u2019ye hicret ettiği yıldır ve 12 kameri aydan oluşur.',
    'hijri_ny.info_h2': 'Muharrem ve Haram Aylar',
    'hijri_ny.info_h2_body': 'Muharrem, dört haram aydan biridir (Zilkade, Zilhicce, Muharrem ve Recep). İslam, Arapların ondan önce de saygı gösterdiği gibi bu ayı yüceltmiştir; bu ayda zulümden ve haramlardan kaçınmak özellikle önemlidir.',
    'hijri_ny.info_h3': 'Aşure Günü',
    'hijri_ny.info_h3_body': 'Muharrem\u2019in onu faziletli bir gündür; Peygamber Efendimiz \uFEFA Musa\u2019yı (a.s.) kurtardığı için Allah\u2019a şükür olarak bu günde oruç tutmuştur. Ehl-i kitaba muhalefet olsun diye dokuzuncu (Tasua) günü de ekleyerek oruç tutmak müstehaptır.',
    'hijri_ny.links_title': '\ud83d\udd17 Faydalı Bağlantılar',
    'hijri_ny.link_ramadan': '\ud83c\udf19 Ramazan\u2019a Ne Kadar Kaldı',
    'hijri_ny.link_fitr': '\ud83c\udf89 Ramazan Bayramına Ne Kadar Kaldı',
    'hijri_ny.link_adha': '\ud83d\udc11 Kurban Bayramına Ne Kadar Kaldı',
    'hijri_ny.link_moon': '\ud83c\udf19 Bugün Ayın Durumu',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 Bugünün Hicri Tarihi',
},

ur: {
    'hijri_ny.h1': '\ud83d\udcc5 ہجری نئے سال میں کتنا وقت باقی ہے؟',
    'hijri_ny.intro': 'نئے ہجری (اسلامی قمری) سال تک باقی ایّام کو میلادی اور ہجری تاریخ کے ساتھ دیکھیے۔ نیا سال 1 محرّم کو شروع ہوتا ہے، اور ہر ملک میں محرّم کے چاند کی رویت کے مطابق اعلان میں ایک دن کا فرق ہو سکتا ہے۔',
    'hijri_ny.event_name': 'ہجری نیا سال',
    'hijri_ny.hijri_1': '1 محرّم',
    'hijri_ny.meta_title': '\ud83d\udcc5 ہجری نیا سال کاؤنٹ ڈاؤن — متوقع تاریخ اور براہِ راست ٹائمر',
    'hijri_ny.meta_desc': 'نئے ہجری سال (1 محرّم) کے لیے درست کاؤنٹ ڈاؤن — ایّام، گھنٹے اور منٹ — میلادی و ہجری تاریخوں اور ہجرتِ نبویؐ کے تاریخی پس منظر کے ساتھ۔',
    'hijri_ny.cards_title': '\ud83d\udccb بنیادی معلومات',
    'hijri_ny.card1_title': 'متوقع ہجری نیا سال',
    'hijri_ny.card2_title': 'ہجری تاریخ',
    'hijri_ny.card3_title': 'باقی ایّام',
    'hijri_ny.card4_title': 'حالت',
    'hijri_ny.card4_value': 'حسابی \u00B7 رؤیت کا منتظر',
    'hijri_ny.notice_title': '\ud83d\udcdc تاریخ کی تصدیق',
    'hijri_ny.notice_body': 'ہجری نیا سال محرّم کے پہلے دن شروع ہوتا ہے۔ دکھائی گئی تاریخ فلکی حساب (ٹیبلر ہجری تقویم) کے مطابق ہے؛ ہر ملک میں محرّم کے ہلال کی رؤیت کے لحاظ سے سرکاری اعلان میں ایک دن کا فرق ممکن ہے۔',
    'hijri_ny.lunar_title': '\ud83c\udf19 قمری تعلق',
    'hijri_ny.lunar_current': 'چاند کا موجودہ مرحلہ:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 آج چاند کی صورت حال \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 اگلا محاق \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 محرّم کا آنے والا ہلال \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 آنے والے سالوں میں ہجری نئے سال کی تاریخیں',
    'hijri_ny.years_col_hijri': 'ہجری سال',
    'hijri_ny.years_col_greg': 'میلادی سال',
    'hijri_ny.years_col_start': '1 محرّم (تخمینی)',
    'hijri_ny.years_col_note': 'نوٹ',
    'hijri_ny.years_note': '* تمام تاریخیں حسابی تخمینی ہیں اور رؤیت کے لحاظ سے ایک دن مختلف ہو سکتی ہیں۔',
    'hijri_ny.years_note_cell': 'تخمینی \u00B7 رؤیت پر منحصر',
    'hijri_ny.cities_title': '\ud83c\udf0d دنیا بھر میں ہجری نیا سال',
    'hijri_ny.city_sa': 'سعودی عرب میں ہجری نیا سال',
    'hijri_ny.city_eg': 'مصر میں ہجری نیا سال',
    'hijri_ny.city_ae': 'امارات میں ہجری نیا سال',
    'hijri_ny.city_uk': 'لندن میں ہجری نیا سال',
    'hijri_ny.city_tr': 'استنبول میں ہجری نیا سال',
    'hijri_ny.city_id': 'جکارتہ میں ہجری نیا سال',
    'hijri_ny.faq_title': '\u2753 ہجری نئے سال کے بارے میں عام سوالات',
    'hijri_ny.faq_q1': 'ہجری نئے سال میں کتنے دن باقی ہیں؟',
    'hijri_ny.faq_a1': 'متوقع ہجری نئے سال میں {n} دن باقی ہیں۔',
    'hijri_ny.faq_q2': 'اس سال نیا ہجری سال کب شروع ہو رہا ہے؟',
    'hijri_ny.faq_a2': 'ہجری سال {hyear} ھ تخمیناً {date} کو شروع ہوتا ہے۔',
    'hijri_ny.faq_q3': 'نئے سال کی ہجری تاریخ کیا ہے؟',
    'hijri_ny.faq_a3': 'یہ {hyear} ھ کے محرّم کی پہلی تاریخ سے ملتا ہے۔',
    'hijri_ny.faq_q4': 'کیا ہجری نئے سال کی تاریخ ملکوں میں مختلف ہو سکتی ہے؟',
    'hijri_ny.faq_a4': 'جی ہاں، محرّم کے چاند کی مقامی رؤیت کی بنا پر ملکوں میں ایک دن کا فرق ہو سکتا ہے۔',
    'hijri_ny.faq_q5': 'ہجری نئے سال کی مناسبت کیا ہے؟',
    'hijri_ny.faq_a5': 'ہجری کیلنڈر حضورؐ کی مکّہ سے مدینہ کی ہجرت سے شروع ہوتا ہے۔ یہ تاریخ سازی حضرت عمر بن الخطاب رضی اللہ عنہ نے اپنائی تھی۔',
    'hijri_ny.faq_q6': 'محرّم کا مہینہ کیا ہے؟',
    'hijri_ny.faq_a6': 'محرّم ہجری سال کا پہلا مہینہ اور چار حرمت والے مہینوں میں سے ایک ہے۔ اس میں روزہ خاص طور پر یومِ عاشورا کو مستحب ہے۔',
    'hijri_ny.faq_q7': 'یومِ عاشورا کیا ہے؟',
    'hijri_ny.faq_a7': 'عاشورا محرّم کی دسویں تاریخ ہے۔ اس دن اللہ نے موسیٰ علیہ السلام اور ان کی قوم کو فرعون سے نجات دی تھی، اس لیے اس کا روزہ سنّتِ مؤکّدہ ہے۔',
    'hijri_ny.faq_q8': 'کیا مسلمان ہجری نیا سال مناتے ہیں؟',
    'hijri_ny.faq_a8': 'ہجری نیا سال کوئی دینی عید نہیں بلکہ غور و محاسبہ کا موقع ہے، تاہم بہت سے مسلمان اسے ہجرت نبویؐ کی یاد کے لیے ایک مناسبت سمجھتے ہیں۔',
    'hijri_ny.faq_q9': 'ایک ہجری سال میں کتنے دن ہوتے ہیں؟',
    'hijri_ny.faq_a9': 'قمری ہجری سال تقریباً 354 دن کا ہوتا ہے، یعنی شمسی میلادی سال سے 10-11 دن کم۔',
    'hijri_ny.faq_q10': 'اسلامی تقاریب ہر میلادی سال میں آگے کیوں منتقل ہوتی ہیں؟',
    'hijri_ny.faq_a10': 'کیونکہ ہجری سال قمری اور میلادی شمسی سال سے چھوٹا ہے، اس لیے اسلامی تقاریب ہر میلادی سال میں 10-11 دن آگے منتقل ہوتی ہیں۔',
    'hijri_ny.info_title': '\ud83d\udcd6 ہجری نئے سال کے بارے میں',
    'hijri_ny.info_h1': 'اسلامی کیلنڈر کا آغاز',
    'hijri_ny.info_h1_body': 'ہجری کیلنڈر ایک قمری کیلنڈر ہے جو خلیفہ عمر بن الخطاب کے دور میں مسلمانوں نے باضابطہ اختیار کیا۔ اس کا آغاز اس سال سے ہے جس میں حضورؐ نے مکّہ سے مدینہ ہجرت فرمائی، اور یہ 12 قمری مہینوں پر مشتمل ہے۔',
    'hijri_ny.info_h2': 'محرّم اور حرمت والے مہینے',
    'hijri_ny.info_h2_body': 'محرّم چار حرمت والے مہینوں (ذیقعدہ، ذی الحجہ، محرّم، رجب) میں سے ایک ہے۔ اسلام نے اس کی تعظیم کی جس طرح عربوں نے پہلے سے کی تھی؛ اس میں ظلم اور حرام کاموں سے بچنا خاص طور پر مؤکد ہے۔',
    'hijri_ny.info_h3': 'یومِ عاشورا',
    'hijri_ny.info_h3_body': 'محرّم کا دسواں دن فضیلت والا دن ہے؛ حضورؐ نے موسیٰ علیہ السلام کی نجات پر اللہ کا شکرانہ ادا کرنے کے لیے اس دن روزہ رکھا۔ اہلِ کتاب کی مخالفت میں نویں (تاسوعاء) کے ساتھ رکھنا مستحب ہے۔',
    'hijri_ny.links_title': '\ud83d\udd17 مفید روابط',
    'hijri_ny.link_ramadan': '\ud83c\udf19 رمضان میں کتنا وقت باقی',
    'hijri_ny.link_fitr': '\ud83c\udf89 عید الفطر میں کتنا وقت باقی',
    'hijri_ny.link_adha': '\ud83d\udc11 عید الاضحیٰ میں کتنا وقت باقی',
    'hijri_ny.link_moon': '\ud83c\udf19 آج چاند کی صورتحال',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 آج کی ہجری تاریخ',
},

de: {
    'hijri_ny.h1': '\ud83d\udcc5 Wie lange bis zum hidschrischen Neujahr?',
    'hijri_ny.intro': 'Entdecken Sie die verbleibenden Tage bis zum neuen hidschrischen (islamischen Mond-) Jahr mit den erwarteten gregorianischen und hidschrischen Daten. Das neue Jahr beginnt am 1. Muharram, und die offizielle Ankündigung kann je nach Sichtung der Muharram-Mondsichel von Land zu Land um einen Tag abweichen.',
    'hijri_ny.event_name': 'Hidschrisches Neujahr',
    'hijri_ny.hijri_1': '1. Muharram',
    'hijri_ny.meta_title': '\ud83d\udcc5 Hidschrisches Neujahr Countdown \u2014 Erwartetes Datum und Live-Timer',
    'hijri_ny.meta_desc': 'Genauer Countdown bis zum neuen hidschrischen Jahr (1. Muharram) \u2014 in Tagen, Stunden und Minuten \u2014 mit gregorianischen und hidschrischen Daten und dem historischen Kontext der prophetischen Auswanderung (Hidschra).',
    'hijri_ny.cards_title': '\ud83d\udccb Wichtige Informationen',
    'hijri_ny.card1_title': 'Erwartetes hidschrisches Neujahr',
    'hijri_ny.card2_title': 'Hidschrisches Datum',
    'hijri_ny.card3_title': 'Verbleibende Tage',
    'hijri_ny.card4_title': 'Status',
    'hijri_ny.card4_value': 'Berechnet \u00B7 Sichtung ausstehend',
    'hijri_ny.notice_title': '\ud83d\udcdc Datumsüberprüfung',
    'hijri_ny.notice_body': 'Das hidschrische Neujahr beginnt mit dem ersten Tag des Muharram. Das angezeigte Datum wird astronomisch nach dem tabellarischen hidschrischen Kalender berechnet; die offizielle Ankündigung kann je nach lokaler Sichtung der Muharram-Mondsichel in jedem Land um einen Tag abweichen.',
    'hijri_ny.lunar_title': '\ud83c\udf19 Mondverbindung',
    'hijri_ny.lunar_current': 'Aktuelle Mondphase:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 Mondstatus heute \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 Nächster Neumond \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 Nächste Muharram-Mondsichel \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 Hidschrische Neujahrsdaten der kommenden Jahre',
    'hijri_ny.years_col_hijri': 'Hidschrisches Jahr',
    'hijri_ny.years_col_greg': 'Gregorianisches Jahr',
    'hijri_ny.years_col_start': '1. Muharram (geschätzt)',
    'hijri_ny.years_col_note': 'Hinweis',
    'hijri_ny.years_note': '* Alle Daten sind berechnete Schätzungen und können je nach Sichtung um einen Tag abweichen.',
    'hijri_ny.years_note_cell': 'Geschätzt \u00B7 Abhängig von Sichtung',
    'hijri_ny.cities_title': '\ud83c\udf0d Hidschrisches Neujahr weltweit',
    'hijri_ny.city_sa': 'Hidschrisches Neujahr in Saudi-Arabien',
    'hijri_ny.city_eg': 'Hidschrisches Neujahr in Ägypten',
    'hijri_ny.city_ae': 'Hidschrisches Neujahr in den VAE',
    'hijri_ny.city_uk': 'Hidschrisches Neujahr in London',
    'hijri_ny.city_tr': 'Hidschrisches Neujahr in Istanbul',
    'hijri_ny.city_id': 'Hidschrisches Neujahr in Jakarta',
    'hijri_ny.faq_title': '\u2753 Häufig gestellte Fragen zum hidschrischen Neujahr',
    'hijri_ny.faq_q1': 'Wie viele Tage bis zum hidschrischen Neujahr?',
    'hijri_ny.faq_a1': 'Es verbleiben {n} Tage bis zum erwarteten hidschrischen Neujahr.',
    'hijri_ny.faq_q2': 'Wann beginnt das neue hidschrische Jahr dieses Jahr?',
    'hijri_ny.faq_a2': 'Das hidschrische Jahr {hyear} AH beginnt voraussichtlich am {date}.',
    'hijri_ny.faq_q3': 'Welches hidschrische Datum hat das Neujahr?',
    'hijri_ny.faq_a3': 'Es entspricht dem 1. Tag des Muharram im Jahr {hyear} AH.',
    'hijri_ny.faq_q4': 'Kann das Datum des hidschrischen Neujahrs zwischen Ländern abweichen?',
    'hijri_ny.faq_a4': 'Ja, je nach lokaler Sichtung der Muharram-Mondsichel kann es einen Tag Unterschied zwischen Ländern geben.',
    'hijri_ny.faq_q5': 'Was ist der Anlass des hidschrischen Neujahrs?',
    'hijri_ny.faq_a5': 'Der hidschrische Kalender beginnt mit der Auswanderung (Hidschra) des Propheten Muhammad \uFEFA von Mekka nach Medina. Diese Datierung wurde vom Kalifen Umar ibn al-Khattab eingeführt.',
    'hijri_ny.faq_q6': 'Was ist der Monat Muharram?',
    'hijri_ny.faq_a6': 'Muharram ist der erste Monat des hidschrischen Jahres und einer der vier heiligen Monate. Das Fasten ist in ihm empfohlen, besonders am Aschura-Tag.',
    'hijri_ny.faq_q7': 'Was ist der Aschura-Tag?',
    'hijri_ny.faq_a7': 'Aschura ist der zehnte Tag des Muharram. Das Fasten an diesem Tag ist eine bestätigte Sunna, denn an diesem Tag rettete Allah Moses (Friede sei mit ihm) und sein Volk vor dem Pharao.',
    'hijri_ny.faq_q8': 'Feiern Muslime das hidschrische Neujahr?',
    'hijri_ny.faq_a8': 'Das hidschrische Neujahr ist eher ein Anlass zur Reflexion und Selbstprüfung als ein religiöses Fest, doch viele Muslime nutzen es, um an die prophetische Auswanderung zu erinnern.',
    'hijri_ny.faq_q9': 'Wie viele Tage hat ein hidschrisches Jahr?',
    'hijri_ny.faq_a9': 'Das hidschrische Mondjahr hat etwa 354 Tage und ist damit 10 bis 11 Tage kürzer als das gregorianische Sonnenjahr.',
    'hijri_ny.faq_q10': 'Warum verschieben sich islamische Anlässe jedes gregorianische Jahr?',
    'hijri_ny.faq_a10': 'Weil das hidschrische Jahr ein Mondjahr und kürzer als das gregorianische Sonnenjahr ist, rücken islamische Anlässe pro gregorianischem Jahr um 10\u201311 Tage nach vorne.',
    'hijri_ny.info_title': '\ud83d\udcd6 Über das hidschrische Neujahr',
    'hijri_ny.info_h1': 'Beginn des islamischen Kalenders',
    'hijri_ny.info_h1_body': 'Der hidschrische Kalender ist ein Mondkalender, der offiziell von den Muslimen unter der Herrschaft von Kalif Umar ibn al-Khattab angenommen wurde. Sein Ausgangspunkt ist das Jahr der Auswanderung des Propheten Muhammad von Mekka nach Medina, und er besteht aus 12 Mondmonaten.',
    'hijri_ny.info_h2': 'Muharram und die heiligen Monate',
    'hijri_ny.info_h2_body': 'Muharram ist einer der vier heiligen Monate (Dhu al-Qa\u2018da, Dhu al-Hidscha, Muharram und Radschab). Der Islam ehrte ihn, wie es die Araber zuvor taten; das Vermeiden von Ungerechtigkeit und verbotenen Handlungen ist in ihm besonders hervorgehoben.',
    'hijri_ny.info_h3': 'Der Aschura-Tag',
    'hijri_ny.info_h3_body': 'Der zehnte des Muharram ist ein verdienstvoller Tag; der Prophet \uFEFA fastete ihn aus Dankbarkeit gegenüber Allah für die Rettung von Moses (Friede sei mit ihm). Das Fasten zusammen mit dem neunten (Tasu\u2018a) wird empfohlen, um sich von den Leuten des Buches zu unterscheiden.',
    'hijri_ny.links_title': '\ud83d\udd17 Nützliche Links',
    'hijri_ny.link_ramadan': '\ud83c\udf19 Wie lange bis Ramadan',
    'hijri_ny.link_fitr': '\ud83c\udf89 Wie lange bis zum Eid al-Fitr',
    'hijri_ny.link_adha': '\ud83d\udc11 Wie lange bis zum Eid al-Adha',
    'hijri_ny.link_moon': '\ud83c\udf19 Mondstatus heute',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 Hidschrisches Datum heute',
},

id: {
    'hijri_ny.h1': '\ud83d\udcc5 Berapa Lama Lagi Tahun Baru Hijriah?',
    'hijri_ny.intro': 'Temukan sisa hari menuju Tahun Baru Hijriah (kalender qamariah Islam) dengan tanggal Masehi dan Hijriah yang diperkirakan. Tahun baru dimulai pada 1 Muharram, dan pengumuman bisa berbeda satu hari antarnegara tergantung rukyat hilal Muharram.',
    'hijri_ny.event_name': 'Tahun Baru Hijriah',
    'hijri_ny.hijri_1': '1 Muharram',
    'hijri_ny.meta_title': '\ud83d\udcc5 Hitung Mundur Tahun Baru Hijriah \u2014 Tanggal Diperkirakan & Pengatur Waktu Langsung',
    'hijri_ny.meta_desc': 'Hitung mundur akurat menuju tahun baru Hijriah (1 Muharram) \u2014 dalam hari, jam, dan menit \u2014 dengan tanggal Masehi dan Hijriah serta konteks sejarah hijrah Nabi.',
    'hijri_ny.cards_title': '\ud83d\udccb Informasi Utama',
    'hijri_ny.card1_title': 'Tahun Baru Hijriah Diperkirakan',
    'hijri_ny.card2_title': 'Tanggal Hijriah',
    'hijri_ny.card3_title': 'Sisa Hari',
    'hijri_ny.card4_title': 'Status',
    'hijri_ny.card4_value': 'Dihitung \u00B7 Menunggu rukyat',
    'hijri_ny.notice_title': '\ud83d\udcdc Verifikasi Tanggal',
    'hijri_ny.notice_body': 'Tahun Baru Hijriah dimulai pada hari pertama bulan Muharram. Tanggal yang ditampilkan dihitung secara astronomis mengikuti kalender Hijriah tabular; pengumuman resmi dapat berbeda satu hari tergantung rukyat hilal Muharram di setiap negara.',
    'hijri_ny.lunar_title': '\ud83c\udf19 Kaitan Bulan',
    'hijri_ny.lunar_current': 'Fase bulan saat ini:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 Kondisi bulan hari ini \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 Bulan baru berikutnya \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 Hilal Muharram berikutnya \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 Tanggal Tahun Baru Hijriah Mendatang',
    'hijri_ny.years_col_hijri': 'Tahun Hijriah',
    'hijri_ny.years_col_greg': 'Tahun Masehi',
    'hijri_ny.years_col_start': '1 Muharram (perkiraan)',
    'hijri_ny.years_col_note': 'Catatan',
    'hijri_ny.years_note': '* Semua tanggal adalah perkiraan hasil perhitungan dan dapat berbeda satu hari tergantung rukyat.',
    'hijri_ny.years_note_cell': 'Perkiraan \u00B7 Tergantung rukyat',
    'hijri_ny.cities_title': '\ud83c\udf0d Tahun Baru Hijriah di Seluruh Dunia',
    'hijri_ny.city_sa': 'Tahun Baru Hijriah di Arab Saudi',
    'hijri_ny.city_eg': 'Tahun Baru Hijriah di Mesir',
    'hijri_ny.city_ae': 'Tahun Baru Hijriah di UEA',
    'hijri_ny.city_uk': 'Tahun Baru Hijriah di London',
    'hijri_ny.city_tr': 'Tahun Baru Hijriah di Istanbul',
    'hijri_ny.city_id': 'Tahun Baru Hijriah di Jakarta',
    'hijri_ny.faq_title': '\u2753 Pertanyaan Umum tentang Tahun Baru Hijriah',
    'hijri_ny.faq_q1': 'Berapa hari lagi menuju Tahun Baru Hijriah?',
    'hijri_ny.faq_a1': 'Tersisa {n} hari menuju Tahun Baru Hijriah yang diperkirakan.',
    'hijri_ny.faq_q2': 'Kapan tahun baru Hijriah dimulai tahun ini?',
    'hijri_ny.faq_a2': 'Tahun Hijriah {hyear} H diperkirakan dimulai pada {date}.',
    'hijri_ny.faq_q3': 'Apa tanggal Hijriah tahun baru?',
    'hijri_ny.faq_a3': 'Bertepatan dengan 1 Muharram tahun {hyear} H.',
    'hijri_ny.faq_q4': 'Apakah tanggal Tahun Baru Hijriah dapat berbeda antarnegara?',
    'hijri_ny.faq_a4': 'Ya, dapat berbeda satu hari antarnegara tergantung rukyat lokal hilal Muharram.',
    'hijri_ny.faq_q5': 'Apa makna Tahun Baru Hijriah?',
    'hijri_ny.faq_a5': 'Kalender Hijriah dimulai dari hijrah Nabi Muhammad \uFEFA dari Mekah ke Madinah. Penanggalan ini ditetapkan oleh Khalifah Umar bin Khattab radhiyallahu \u2018anhu.',
    'hijri_ny.faq_q6': 'Apa itu bulan Muharram?',
    'hijri_ny.faq_a6': 'Muharram adalah bulan pertama tahun Hijriah dan salah satu dari empat bulan haram. Puasa dianjurkan di dalamnya, terutama pada hari Asyura.',
    'hijri_ny.faq_q7': 'Apa itu hari Asyura?',
    'hijri_ny.faq_a7': 'Asyura adalah hari kesepuluh bulan Muharram. Berpuasa padanya adalah sunnah muakkadah karena pada hari itu Allah menyelamatkan Musa (\u2018alaihis salam) dan kaumnya dari Fir\u2018aun.',
    'hijri_ny.faq_q8': 'Apakah umat Islam merayakan Tahun Baru Hijriah?',
    'hijri_ny.faq_a8': 'Tahun Baru Hijriah lebih merupakan momen renungan dan muhasabah daripada hari raya, namun banyak Muslim menjadikannya kesempatan mengenang hijrah Nabi.',
    'hijri_ny.faq_q9': 'Berapa hari dalam satu tahun Hijriah?',
    'hijri_ny.faq_a9': 'Tahun Hijriah qamariah berkisar 354 hari, yaitu 10 atau 11 hari lebih pendek dari tahun Masehi syamsiah.',
    'hijri_ny.faq_q10': 'Mengapa peringatan Islam bergeser setiap tahun Masehi?',
    'hijri_ny.faq_a10': 'Karena tahun Hijriah bersifat qamariah dan lebih pendek dari tahun Masehi syamsiah, maka peringatan Islam maju 10\u201311 hari tiap tahun Masehi.',
    'hijri_ny.info_title': '\ud83d\udcd6 Tentang Tahun Baru Hijriah',
    'hijri_ny.info_h1': 'Awal Kalender Islam',
    'hijri_ny.info_h1_body': 'Kalender Hijriah adalah kalender qamariah yang secara resmi diadopsi umat Islam pada masa Khalifah Umar bin Khattab. Titik awalnya adalah tahun hijrah Nabi Muhammad dari Mekah ke Madinah, dan terdiri dari 12 bulan qamariah.',
    'hijri_ny.info_h2': 'Muharram dan Bulan-Bulan Haram',
    'hijri_ny.info_h2_body': 'Muharram adalah salah satu dari empat bulan haram (Dzulqa\u2018dah, Dzulhijjah, Muharram, dan Rajab). Islam memuliakannya sebagaimana orang Arab sebelumnya; menghindari kezaliman dan perbuatan haram sangat ditekankan padanya.',
    'hijri_ny.info_h3': 'Hari Asyura',
    'hijri_ny.info_h3_body': 'Hari kesepuluh Muharram adalah hari yang utama; Nabi \uFEFA berpuasa padanya sebagai syukur kepada Allah atas keselamatan Musa (\u2018alaihis salam). Disunahkan berpuasa dengan tanggal kesembilan (Tasu\u2018a) untuk berbeda dengan ahli kitab.',
    'hijri_ny.links_title': '\ud83d\udd17 Tautan Berguna',
    'hijri_ny.link_ramadan': '\ud83c\udf19 Berapa Lama Lagi Ramadan',
    'hijri_ny.link_fitr': '\ud83c\udf89 Berapa Lama Lagi Idulfitri',
    'hijri_ny.link_adha': '\ud83d\udc11 Berapa Lama Lagi Iduladha',
    'hijri_ny.link_moon': '\ud83c\udf19 Kondisi Bulan Hari Ini',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 Tanggal Hijriah Hari Ini',
},

es: {
    'hijri_ny.h1': '\ud83d\udcc5 ¿Cuánto falta para el Año Nuevo hégira?',
    'hijri_ny.intro': 'Descubre los días restantes hasta el nuevo año hégira (calendario lunar islámico) con las fechas gregoriana e hégira previstas. El nuevo año comienza el 1 de Muharram y el anuncio puede diferir en un día entre países según el avistamiento del creciente de Muharram.',
    'hijri_ny.event_name': 'Año Nuevo hégira',
    'hijri_ny.hijri_1': '1 de Muharram',
    'hijri_ny.meta_title': '\ud83d\udcc5 Cuenta regresiva al Año Nuevo hégira \u2014 Fecha prevista y temporizador en vivo',
    'hijri_ny.meta_desc': 'Cuenta regresiva precisa al nuevo año hégira (1 de Muharram) \u2014 en días, horas y minutos \u2014 con fechas gregoriana e hégira y el contexto histórico de la Hégira del Profeta.',
    'hijri_ny.cards_title': '\ud83d\udccb Información clave',
    'hijri_ny.card1_title': 'Año Nuevo hégira previsto',
    'hijri_ny.card2_title': 'Fecha hégira',
    'hijri_ny.card3_title': 'Días restantes',
    'hijri_ny.card4_title': 'Estado',
    'hijri_ny.card4_value': 'Calculado \u00B7 Pendiente de avistamiento',
    'hijri_ny.notice_title': '\ud83d\udcdc Verificación de la fecha',
    'hijri_ny.notice_body': 'El Año Nuevo hégira comienza con el primer día de Muharram. La fecha mostrada se calcula astronómicamente según el calendario hégira tabular; el anuncio oficial puede diferir en un día según el avistamiento local del creciente de Muharram en cada país.',
    'hijri_ny.lunar_title': '\ud83c\udf19 Conexión lunar',
    'hijri_ny.lunar_current': 'Fase lunar actual:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 Estado de la luna hoy \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 Próxima luna nueva \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 Próximo creciente de Muharram \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 Fechas del Año Nuevo hégira en los próximos años',
    'hijri_ny.years_col_hijri': 'Año hégira',
    'hijri_ny.years_col_greg': 'Año gregoriano',
    'hijri_ny.years_col_start': '1 de Muharram (estimado)',
    'hijri_ny.years_col_note': 'Nota',
    'hijri_ny.years_note': '* Todas las fechas son estimaciones calculadas y pueden diferir en un día según el avistamiento.',
    'hijri_ny.years_note_cell': 'Estimado \u00B7 Depende del avistamiento',
    'hijri_ny.cities_title': '\ud83c\udf0d El Año Nuevo hégira en el mundo',
    'hijri_ny.city_sa': 'Año Nuevo hégira en Arabia Saudita',
    'hijri_ny.city_eg': 'Año Nuevo hégira en Egipto',
    'hijri_ny.city_ae': 'Año Nuevo hégira en EAU',
    'hijri_ny.city_uk': 'Año Nuevo hégira en Londres',
    'hijri_ny.city_tr': 'Año Nuevo hégira en Estambul',
    'hijri_ny.city_id': 'Año Nuevo hégira en Yakarta',
    'hijri_ny.faq_title': '\u2753 Preguntas frecuentes sobre el Año Nuevo hégira',
    'hijri_ny.faq_q1': '¿Cuántos días faltan para el Año Nuevo hégira?',
    'hijri_ny.faq_a1': 'Faltan {n} días para el Año Nuevo hégira previsto.',
    'hijri_ny.faq_q2': '¿Cuándo comienza el nuevo año hégira este año?',
    'hijri_ny.faq_a2': 'El año hégira {hyear} AH comienza el {date} (estimado).',
    'hijri_ny.faq_q3': '¿Cuál es la fecha hégira del año nuevo?',
    'hijri_ny.faq_a3': 'Corresponde al primer día de Muharram del año {hyear} AH.',
    'hijri_ny.faq_q4': '¿La fecha del Año Nuevo hégira puede diferir entre países?',
    'hijri_ny.faq_a4': 'Sí, puede diferir en un día entre países según el avistamiento local del creciente de Muharram.',
    'hijri_ny.faq_q5': '¿Qué conmemora el Año Nuevo hégira?',
    'hijri_ny.faq_a5': 'El calendario hégira comienza con la Hégira (migración) del Profeta Muhammad \uFEFA de La Meca a Medina. Este cómputo fue adoptado por el califa Umar ibn al-Jattab.',
    'hijri_ny.faq_q6': '¿Qué es el mes de Muharram?',
    'hijri_ny.faq_a6': 'Muharram es el primer mes del año hégira y uno de los cuatro meses sagrados. El ayuno en él es recomendable, especialmente en el Día de Ashura.',
    'hijri_ny.faq_q7': '¿Qué es el Día de Ashura?',
    'hijri_ny.faq_a7': 'Ashura es el décimo día de Muharram. Ayunarlo es una Sunna confirmada, pues en ese día Alá salvó a Moisés (la paz sea con él) y a su pueblo del Faraón.',
    'hijri_ny.faq_q8': '¿Los musulmanes celebran el Año Nuevo hégira?',
    'hijri_ny.faq_a8': 'El Año Nuevo hégira es más una ocasión de reflexión y autoexamen que una fiesta religiosa, pero muchos musulmanes lo aprovechan para recordar la Hégira del Profeta.',
    'hijri_ny.faq_q9': '¿Cuántos días tiene un año hégira?',
    'hijri_ny.faq_a9': 'El año hégira lunar tiene unos 354 días, es decir, 10 u 11 días menos que el año gregoriano solar.',
    'hijri_ny.faq_q10': '¿Por qué las celebraciones islámicas se adelantan cada año gregoriano?',
    'hijri_ny.faq_a10': 'Porque el año hégira es lunar y más corto que el año gregoriano solar, las ocasiones islámicas avanzan 10\u201311 días cada año gregoriano.',
    'hijri_ny.info_title': '\ud83d\udcd6 Acerca del Año Nuevo hégira',
    'hijri_ny.info_h1': 'Inicio del calendario islámico',
    'hijri_ny.info_h1_body': 'El calendario hégira es un calendario lunar adoptado oficialmente por los musulmanes durante el califato de Umar ibn al-Jattab. Su punto de partida es el año de la migración del Profeta Muhammad de La Meca a Medina, y consta de 12 meses lunares.',
    'hijri_ny.info_h2': 'Muharram y los meses sagrados',
    'hijri_ny.info_h2_body': 'Muharram es uno de los cuatro meses sagrados (Dhu al-Qa\u2018da, Dhu al-Hiyya, Muharram y Rayab). El islam lo honró como lo hicieron los árabes antes; evitar la injusticia y las acciones prohibidas es especialmente importante en él.',
    'hijri_ny.info_h3': 'El Día de Ashura',
    'hijri_ny.info_h3_body': 'El décimo de Muharram es un día virtuoso; el Profeta \uFEFA lo ayunó en gratitud a Alá por salvar a Moisés (la paz sea con él). Se recomienda ayunar también el noveno (Tasu\u2018a) para diferenciarse de la Gente del Libro.',
    'hijri_ny.links_title': '\ud83d\udd17 Enlaces útiles',
    'hijri_ny.link_ramadan': '\ud83c\udf19 Cuánto falta para el Ramadán',
    'hijri_ny.link_fitr': '\ud83c\udf89 Cuánto falta para el Eid al-Fitr',
    'hijri_ny.link_adha': '\ud83d\udc11 Cuánto falta para el Eid al-Adha',
    'hijri_ny.link_moon': '\ud83c\udf19 Estado de la luna hoy',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 Fecha hégira hoy',
},

bn: {
    'hijri_ny.h1': '\ud83d\udcc5 হিজরি নববর্ষের আর কত দিন?',
    'hijri_ny.intro': 'মিলাদি ও হিজরি প্রত্যাশিত তারিখসহ নতুন হিজরি (ইসলামী চান্দ্র) বর্ষ পর্যন্ত অবশিষ্ট দিনগুলো জানুন। নতুন বছর 1 মহররমে শুরু হয়, এবং প্রতি দেশে মহররমের চাঁদ দেখার ওপর নির্ভর করে ঘোষণায় এক দিনের পার্থক্য থাকতে পারে।',
    'hijri_ny.event_name': 'হিজরি নববর্ষ',
    'hijri_ny.hijri_1': '1 মহররম',
    'hijri_ny.meta_title': '\ud83d\udcc5 হিজরি নববর্ষ কাউন্টডাউন \u2014 প্রত্যাশিত তারিখ ও লাইভ টাইমার',
    'hijri_ny.meta_desc': 'নতুন হিজরি বছর (1 মহররম)-এর জন্য নির্ভুল কাউন্টডাউন \u2014 দিন, ঘণ্টা ও মিনিটে \u2014 মিলাদি ও হিজরি তারিখ এবং নবীজির হিজরতের ঐতিহাসিক প্রেক্ষাপটসহ।',
    'hijri_ny.cards_title': '\ud83d\udccb প্রধান তথ্য',
    'hijri_ny.card1_title': 'প্রত্যাশিত হিজরি নববর্ষ',
    'hijri_ny.card2_title': 'হিজরি তারিখ',
    'hijri_ny.card3_title': 'বাকি দিন',
    'hijri_ny.card4_title': 'অবস্থা',
    'hijri_ny.card4_value': 'হিসাবকৃত \u00B7 চাঁদ দেখার অপেক্ষা',
    'hijri_ny.notice_title': '\ud83d\udcdc তারিখ যাচাই',
    'hijri_ny.notice_body': 'হিজরি নববর্ষ মহররম মাসের প্রথম দিন থেকে শুরু হয়। প্রদর্শিত তারিখ ট্যাবুলার হিজরি ক্যালেন্ডার অনুসারে জ্যোতির্বৈজ্ঞানিকভাবে হিসাব করা; প্রতি দেশে মহররমের চাঁদ দেখার স্থানীয় ফলাফল অনুযায়ী আনুষ্ঠানিক ঘোষণায় এক দিনের পার্থক্য হতে পারে।',
    'hijri_ny.lunar_title': '\ud83c\udf19 চান্দ্র সংযোগ',
    'hijri_ny.lunar_current': 'বর্তমান চাঁদের দশা:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 আজকের চাঁদের অবস্থা \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 পরবর্তী অমাবস্যা \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 পরবর্তী মহররমের চাঁদ \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 আসন্ন বছরগুলোতে হিজরি নববর্ষের তারিখ',
    'hijri_ny.years_col_hijri': 'হিজরি বছর',
    'hijri_ny.years_col_greg': 'মিলাদি বছর',
    'hijri_ny.years_col_start': '1 মহররম (আনুমানিক)',
    'hijri_ny.years_col_note': 'নোট',
    'hijri_ny.years_note': '* সব তারিখ হিসাবকৃত আনুমানিক এবং চাঁদ দেখার ওপর নির্ভর করে এক দিনের পার্থক্য হতে পারে।',
    'hijri_ny.years_note_cell': 'আনুমানিক \u00B7 চাঁদ দেখার ওপর নির্ভরশীল',
    'hijri_ny.cities_title': '\ud83c\udf0d বিশ্বজুড়ে হিজরি নববর্ষ',
    'hijri_ny.city_sa': 'সৌদি আরবে হিজরি নববর্ষ',
    'hijri_ny.city_eg': 'মিশরে হিজরি নববর্ষ',
    'hijri_ny.city_ae': 'আমিরাতে হিজরি নববর্ষ',
    'hijri_ny.city_uk': 'লন্ডনে হিজরি নববর্ষ',
    'hijri_ny.city_tr': 'ইস্তাম্বুলে হিজরি নববর্ষ',
    'hijri_ny.city_id': 'জাকার্তায় হিজরি নববর্ষ',
    'hijri_ny.faq_title': '\u2753 হিজরি নববর্ষ সম্পর্কে সাধারণ প্রশ্ন',
    'hijri_ny.faq_q1': 'হিজরি নববর্ষের আর কত দিন বাকি?',
    'hijri_ny.faq_a1': 'প্রত্যাশিত হিজরি নববর্ষের আর {n} দিন বাকি।',
    'hijri_ny.faq_q2': 'এই বছরে নতুন হিজরি বছর কবে শুরু হয়?',
    'hijri_ny.faq_a2': 'হিজরি {hyear} হিজরি বছর আনুমানিক {date}-এ শুরু হয়।',
    'hijri_ny.faq_q3': 'নববর্ষের হিজরি তারিখ কী?',
    'hijri_ny.faq_a3': 'এটি {hyear} হিজরি বছরের মহররম মাসের প্রথম দিনের সমতুল্য।',
    'hijri_ny.faq_q4': 'হিজরি নববর্ষের তারিখ কি দেশভেদে ভিন্ন হতে পারে?',
    'hijri_ny.faq_a4': 'হ্যাঁ, মহররমের চাঁদ দেখার স্থানীয় ফলাফল অনুযায়ী দেশভেদে এক দিনের পার্থক্য হতে পারে।',
    'hijri_ny.faq_q5': 'হিজরি নববর্ষের তাৎপর্য কী?',
    'hijri_ny.faq_a5': 'হিজরি ক্যালেন্ডার মহানবী \uFEFA-এর মক্কা থেকে মদীনায় হিজরতের বছর থেকে শুরু হয়। এই সন পদ্ধতি গ্রহণ করেছিলেন খলিফা উমর ইবনুল খাত্তাব রাদিয়াল্লাহু আনহু।',
    'hijri_ny.faq_q6': 'মহররম মাস কী?',
    'hijri_ny.faq_a6': 'মহররম হিজরি বছরের প্রথম মাস এবং চারটি পবিত্র (হারাম) মাসের একটি। এতে রোজা রাখা মুস্তাহাব, বিশেষ করে আশুরার দিনে।',
    'hijri_ny.faq_q7': 'আশুরার দিন কী?',
    'hijri_ny.faq_a7': 'আশুরা হলো মহররমের দশম দিন। এই দিন আল্লাহ মুসা (আ.) ও তাঁর অনুসারীদের ফিরআউন থেকে নাজাত দিয়েছিলেন, তাই এর রোজা মুয়াক্কাদা সুন্নত।',
    'hijri_ny.faq_q8': 'মুসলিমরা কি হিজরি নববর্ষ উদযাপন করেন?',
    'hijri_ny.faq_a8': 'হিজরি নববর্ষ কোনো ধর্মীয় উৎসব নয় বরং আত্ম-মূল্যায়ন ও ইবরতের উপলক্ষ; তবে অনেক মুসলিম একে হিজরতের স্মরণের সুযোগ হিসেবে নেন।',
    'hijri_ny.faq_q9': 'এক হিজরি বছরে কত দিন?',
    'hijri_ny.faq_a9': 'চান্দ্র হিজরি বছর প্রায় 354 দিন, অর্থাৎ সৌর মিলাদি বছরের চেয়ে 10 বা 11 দিন কম।',
    'hijri_ny.faq_q10': 'ইসলামী উপলক্ষগুলো প্রতি মিলাদি বছরে কেন সামনে সরে যায়?',
    'hijri_ny.faq_a10': 'কারণ হিজরি বছর চান্দ্র এবং সৌর মিলাদি বছরের চেয়ে ছোট, তাই ইসলামী উপলক্ষ প্রতি মিলাদি বছরে 10\u201311 দিন এগিয়ে যায়।',
    'hijri_ny.info_title': '\ud83d\udcd6 হিজরি নববর্ষ সম্পর্কে',
    'hijri_ny.info_h1': 'ইসলামী ক্যালেন্ডারের সূচনা',
    'hijri_ny.info_h1_body': 'হিজরি ক্যালেন্ডার একটি চান্দ্র ক্যালেন্ডার যা খলিফা উমর ইবনুল খাত্তাবের আমলে মুসলিমদের দ্বারা আনুষ্ঠানিকভাবে গ্রহণ করা হয়। এর সূচনা নবী \uFEFA-এর মক্কা থেকে মদীনায় হিজরতের বছর থেকে, এবং এতে 12টি চান্দ্র মাস থাকে।',
    'hijri_ny.info_h2': 'মহররম এবং পবিত্র মাসসমূহ',
    'hijri_ny.info_h2_body': 'মহররম চার পবিত্র মাসের একটি (জিলকদ, জিলহজ, মহররম ও রজব)। ইসলাম একে সম্মান দিয়েছে যেমন আরবরা পূর্বে দিত; এতে জুলুম ও হারাম কাজ থেকে বিরত থাকা বিশেষভাবে গুরুত্বপূর্ণ।',
    'hijri_ny.info_h3': 'আশুরার দিন',
    'hijri_ny.info_h3_body': 'মহররমের দশম দিন একটি ফজিলতপূর্ণ দিন; নবী \uFEFA মুসা (আ.)-কে নাজাত দেওয়ার জন্য আল্লাহর শুকরিয়া হিসেবে এ দিন রোজা রেখেছিলেন। আহলে কিতাবের বিরোধিতায় নবম দিন (তাসু\u2018আ)-এর সাথে রোজা রাখা মুস্তাহাব।',
    'hijri_ny.links_title': '\ud83d\udd17 উপকারী লিঙ্ক',
    'hijri_ny.link_ramadan': '\ud83c\udf19 রমজানের আর কত দিন',
    'hijri_ny.link_fitr': '\ud83c\udf89 ঈদুল ফিতরের আর কত দিন',
    'hijri_ny.link_adha': '\ud83d\udc11 ঈদুল আযহার আর কত দিন',
    'hijri_ny.link_moon': '\ud83c\udf19 আজকের চাঁদের অবস্থা',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 আজকের হিজরি তারিখ',
},

ms: {
    'hijri_ny.h1': '\ud83d\udcc5 Berapa Lama Lagi Tahun Baru Hijrah?',
    'hijri_ny.intro': 'Ketahui bilangan hari yang tinggal sebelum Tahun Baru Hijrah (kalendar qamari Islam) dengan tarikh Masihi dan Hijrah yang dijangkakan. Tahun baru bermula pada 1 Muharam, dan pengumuman mungkin berbeza satu hari antara negara bergantung pada rukyah anak bulan Muharam.',
    'hijri_ny.event_name': 'Tahun Baru Hijrah',
    'hijri_ny.hijri_1': '1 Muharam',
    'hijri_ny.meta_title': '\ud83d\udcc5 Kiraan Detik Tahun Baru Hijrah \u2014 Tarikh Dijangka & Pemasa Langsung',
    'hijri_ny.meta_desc': 'Kiraan detik tepat ke tahun baru Hijrah (1 Muharam) \u2014 dalam hari, jam dan minit \u2014 dengan tarikh Masihi dan Hijrah serta konteks sejarah hijrah Nabi.',
    'hijri_ny.cards_title': '\ud83d\udccb Maklumat Utama',
    'hijri_ny.card1_title': 'Tahun Baru Hijrah Dijangka',
    'hijri_ny.card2_title': 'Tarikh Hijrah',
    'hijri_ny.card3_title': 'Hari Berbaki',
    'hijri_ny.card4_title': 'Status',
    'hijri_ny.card4_value': 'Dikira \u00B7 Menunggu rukyah',
    'hijri_ny.notice_title': '\ud83d\udcdc Pengesahan Tarikh',
    'hijri_ny.notice_body': 'Tahun Baru Hijrah bermula pada hari pertama bulan Muharam. Tarikh yang dipaparkan dikira secara astronomi mengikut kalendar Hijrah berjadual; pengumuman rasmi mungkin berbeza satu hari bergantung pada rukyah tempatan anak bulan Muharam di setiap negara.',
    'hijri_ny.lunar_title': '\ud83c\udf19 Kaitan Bulan',
    'hijri_ny.lunar_current': 'Fasa bulan semasa:',
    'hijri_ny.lunar_link_today': '\ud83c\udf19 Keadaan bulan hari ini \u2192',
    'hijri_ny.lunar_link_new_moon': '\ud83c\udf11 Bulan baru seterusnya \u2192',
    'hijri_ny.lunar_link_crescent': '\ud83c\udf12 Anak bulan Muharam seterusnya \u2192',
    'hijri_ny.years_title': '\ud83d\udcc5 Tarikh Tahun Baru Hijrah pada Tahun-Tahun Akan Datang',
    'hijri_ny.years_col_hijri': 'Tahun Hijrah',
    'hijri_ny.years_col_greg': 'Tahun Masihi',
    'hijri_ny.years_col_start': '1 Muharam (anggaran)',
    'hijri_ny.years_col_note': 'Nota',
    'hijri_ny.years_note': '* Semua tarikh adalah anggaran kiraan dan mungkin berbeza satu hari berdasarkan rukyah.',
    'hijri_ny.years_note_cell': 'Anggaran \u00B7 Bergantung pada rukyah',
    'hijri_ny.cities_title': '\ud83c\udf0d Tahun Baru Hijrah di Seluruh Dunia',
    'hijri_ny.city_sa': 'Tahun Baru Hijrah di Arab Saudi',
    'hijri_ny.city_eg': 'Tahun Baru Hijrah di Mesir',
    'hijri_ny.city_ae': 'Tahun Baru Hijrah di UAE',
    'hijri_ny.city_uk': 'Tahun Baru Hijrah di London',
    'hijri_ny.city_tr': 'Tahun Baru Hijrah di Istanbul',
    'hijri_ny.city_id': 'Tahun Baru Hijrah di Jakarta',
    'hijri_ny.faq_title': '\u2753 Soalan Lazim tentang Tahun Baru Hijrah',
    'hijri_ny.faq_q1': 'Berapa hari lagi sebelum Tahun Baru Hijrah?',
    'hijri_ny.faq_a1': 'Tinggal {n} hari sebelum Tahun Baru Hijrah dijangkakan.',
    'hijri_ny.faq_q2': 'Bilakah tahun baru Hijrah bermula tahun ini?',
    'hijri_ny.faq_a2': 'Tahun Hijrah {hyear} H dijangka bermula pada {date}.',
    'hijri_ny.faq_q3': 'Apakah tarikh Hijrah tahun baru?',
    'hijri_ny.faq_a3': 'Ia bersamaan dengan 1 Muharam tahun {hyear} H.',
    'hijri_ny.faq_q4': 'Bolehkah tarikh Tahun Baru Hijrah berbeza antara negara?',
    'hijri_ny.faq_a4': 'Ya, ia boleh berbeza satu hari antara negara bergantung pada rukyah tempatan anak bulan Muharam.',
    'hijri_ny.faq_q5': 'Apakah kepentingan Tahun Baru Hijrah?',
    'hijri_ny.faq_a5': 'Kalendar Hijrah bermula dari hijrah Nabi Muhammad \uFEFA dari Makkah ke Madinah. Pengiraan ini diterima pakai oleh Khalifah Umar bin al-Khattab radhiallahu anhu.',
    'hijri_ny.faq_q6': 'Apakah bulan Muharam?',
    'hijri_ny.faq_a6': 'Muharam adalah bulan pertama tahun Hijrah dan salah satu daripada empat bulan haram. Berpuasa padanya digalakkan, terutama pada hari Asyura.',
    'hijri_ny.faq_q7': 'Apakah hari Asyura?',
    'hijri_ny.faq_a7': 'Asyura ialah hari kesepuluh Muharam. Berpuasa padanya adalah sunat muakkad kerana pada hari itu Allah menyelamatkan Nabi Musa a.s. dan kaumnya daripada Firaun.',
    'hijri_ny.faq_q8': 'Adakah umat Islam menyambut Tahun Baru Hijrah?',
    'hijri_ny.faq_a8': 'Tahun Baru Hijrah lebih kepada kesempatan muhasabah dan renungan berbanding perayaan agama; namun ramai umat Islam menjadikannya peluang mengingati hijrah Nabi.',
    'hijri_ny.faq_q9': 'Berapakah hari dalam setahun Hijrah?',
    'hijri_ny.faq_a9': 'Tahun Hijrah qamari lebih kurang 354 hari, iaitu 10 atau 11 hari lebih pendek daripada tahun Masihi syamsi.',
    'hijri_ny.faq_q10': 'Mengapakah peristiwa Islam bergerak setiap tahun Masihi?',
    'hijri_ny.faq_a10': 'Kerana tahun Hijrah bersifat qamari dan lebih pendek daripada tahun Masihi syamsi, peristiwa Islam maju 10\u201311 hari setiap tahun Masihi.',
    'hijri_ny.info_title': '\ud83d\udcd6 Tentang Tahun Baru Hijrah',
    'hijri_ny.info_h1': 'Permulaan Kalendar Islam',
    'hijri_ny.info_h1_body': 'Kalendar Hijrah ialah kalendar qamari yang diterima pakai secara rasmi oleh umat Islam pada zaman Khalifah Umar bin al-Khattab. Titik permulaannya ialah tahun hijrah Nabi Muhammad dari Makkah ke Madinah, dan ia mengandungi 12 bulan qamari.',
    'hijri_ny.info_h2': 'Muharam dan Bulan-bulan Haram',
    'hijri_ny.info_h2_body': 'Muharam adalah salah satu daripada empat bulan haram (Zulkaedah, Zulhijah, Muharam dan Rejab). Islam memuliakannya sebagaimana bangsa Arab sebelumnya; menjauhi kezaliman dan perbuatan haram amat ditekankan di dalamnya.',
    'hijri_ny.info_h3': 'Hari Asyura',
    'hijri_ny.info_h3_body': 'Hari kesepuluh Muharam adalah hari yang mulia; Nabi \uFEFA berpuasa padanya sebagai tanda syukur kepada Allah atas penyelamatan Nabi Musa a.s. Digalakkan berpuasa bersama hari kesembilan (Tasu\u2018a) untuk berbeza dengan Ahli Kitab.',
    'hijri_ny.links_title': '\ud83d\udd17 Pautan Berguna',
    'hijri_ny.link_ramadan': '\ud83c\udf19 Berapa Lama Lagi Ramadan',
    'hijri_ny.link_fitr': '\ud83c\udf89 Berapa Lama Lagi Aidilfitri',
    'hijri_ny.link_adha': '\ud83d\udc11 Berapa Lama Lagi Aidiladha',
    'hijri_ny.link_moon': '\ud83c\udf19 Keadaan Bulan Hari Ini',
    'hijri_ny.link_hijri_today': '\ud83d\udcc5 Tarikh Hijrah Hari Ini',
},

};
