// Phase 3: Add HTML + i18n for Eid al-Fitr, Eid al-Adha, Hijri New Year
// 1. Generates HTML page blocks from the Ramadan template (string substitution)
// 2. Inserts i18n keys for all 10 languages × 3 events into js/i18n.js
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const INDEX_HTML = path.join(ROOT, 'index.html');
const I18N_JS = path.join(ROOT, 'js', 'i18n.js');

// === Event definitions ===
const EVENTS = [
    {
        id: 'eid-al-fitr',
        keyPrefix: 'eid_fitr',
        idPrefix: 'fitr',                // HTML ID prefix (fitr-days, fitr-hyear, etc)
        pageId: 'page-eid-al-fitr-countdown',
        timerId: 'fitr-timer',
        pagePathEn: '/eid-al-fitr-countdown',
        htmlClass: 'cd-eid-al-fitr',
    },
    {
        id: 'eid-al-adha',
        keyPrefix: 'eid_adha',
        idPrefix: 'adha',
        pageId: 'page-eid-al-adha-countdown',
        timerId: 'adha-timer',
        pagePathEn: '/eid-al-adha-countdown',
        htmlClass: 'cd-eid-al-adha',
    },
    {
        id: 'hijri-new-year',
        keyPrefix: 'hijri_ny',
        idPrefix: 'ny',
        pageId: 'page-hijri-new-year-countdown',
        timerId: 'ny-timer',
        pagePathEn: '/hijri-new-year-countdown',
        htmlClass: 'cd-hijri-new-year',
    }
];

// ========================================================================
// i18n translations — per event, per language
// Each event has 60 keys. We provide translations for 10 languages.
// ========================================================================

const TR = {};

// ── EID AL-FITR ────────────────────────────────────────────────────────
TR['eid-al-fitr'] = {

ar: {
    'eid_fitr.h1': '🌙 كم باقي على عيد الفطر؟',
    'eid_fitr.intro': 'اكتشف الأيّام المتبقّية حتّى عيد الفطر المبارك مع التاريخ الميلاديّ المتوقّع والهجريّ. قد يختلف يوم العيد يوماً حسب رؤية هلال شوّال في بلدك.',
    'eid_fitr.event_name': 'عيد الفطر',
    'eid_fitr.hijri_1': '1 شوّال',
    'eid_fitr.meta_title': '🌙 كم باقي على عيد الفطر؟ — التاريخ المتوقّع والعدّ التنازليّ',
    'eid_fitr.meta_desc': 'عدّ تنازليّ دقيق لعيد الفطر المبارك — بالأيّام والساعات والدقائق — مع التاريخ الميلاديّ والهجريّ وعلاقته بهلال شوّال.',
    'eid_fitr.cards_title': '📋 معلومات أساسيّة',
    'eid_fitr.card1_title': 'عيد الفطر المتوقّع',
    'eid_fitr.card2_title': 'التاريخ الهجريّ',
    'eid_fitr.card3_title': 'الأيّام المتبقّية',
    'eid_fitr.card4_title': 'حالة التحديد',
    'eid_fitr.card4_value': 'حسابيّ · بانتظار الرؤية',
    'eid_fitr.notice_title': '📜 اعتماد التاريخ',
    'eid_fitr.notice_body': 'يرتبط عيد الفطر بثبوت هلال شوّال بعد إكمال 29 أو 30 يومًا من رمضان. التاريخ المعروض محسوب فلكيًّا وفق التقويم الهجريّ الحسابيّ، وقد يختلف الإعلان الرسميّ بيوم واحد حسب الجهة الشرعيّة في كلّ بلد.',
    'eid_fitr.lunar_title': '🌙 الارتباط القمريّ',
    'eid_fitr.lunar_current': 'مرحلة القمر الحاليّة:',
    'eid_fitr.lunar_link_today': '🌙 حالة القمر اليوم →',
    'eid_fitr.lunar_link_new_moon': '🌑 المحاق القادم →',
    'eid_fitr.lunar_link_crescent': '🌒 هلال شوّال القادم →',
    'eid_fitr.years_title': '📅 مواعيد عيد الفطر في السنوات القادمة',
    'eid_fitr.years_col_hijri': 'السنة الهجريّة',
    'eid_fitr.years_col_greg': 'السنة الميلاديّة',
    'eid_fitr.years_col_start': 'عيد الفطر (تقديريّ)',
    'eid_fitr.years_col_note': 'ملاحظة',
    'eid_fitr.years_note': '* جميع التواريخ تقديريّة حسابيًّا وقد تختلف بيوم واحد حسب الرؤية.',
    'eid_fitr.years_note_cell': 'تقديريّ · يعتمد على الرؤية',
    'eid_fitr.cities_title': '🌍 عيد الفطر حول العالم',
    'eid_fitr.city_sa': 'عيد الفطر في السعودية',
    'eid_fitr.city_eg': 'عيد الفطر في مصر',
    'eid_fitr.city_ae': 'عيد الفطر في الإمارات',
    'eid_fitr.city_uk': 'عيد الفطر في لندن',
    'eid_fitr.city_tr': 'عيد الفطر في إسطنبول',
    'eid_fitr.city_id': 'عيد الفطر في جاكرتا',
    'eid_fitr.faq_title': '❓ أسئلة شائعة عن عيد الفطر',
    'eid_fitr.faq_q1': 'كم باقي على عيد الفطر؟',
    'eid_fitr.faq_a1': 'يتبقّى {n} يومًا على عيد الفطر المتوقّع.',
    'eid_fitr.faq_q2': 'متى يكون عيد الفطر هذا العام؟',
    'eid_fitr.faq_a2': 'يوافق عيد الفطر {hyear} هـ تاريخ {date} تقديريًّا.',
    'eid_fitr.faq_q3': 'ما التاريخ الهجريّ لعيد الفطر؟',
    'eid_fitr.faq_a3': 'يوافق أوّل أيّام شوّال من سنة {hyear} هـ.',
    'eid_fitr.faq_q4': 'هل قد يختلف موعد عيد الفطر بين الدول؟',
    'eid_fitr.faq_a4': 'نعم، قد يختلف يومًا واحدًا بين الدول حسب الرؤية المحلّيّة لهلال شوّال.',
    'eid_fitr.faq_q5': 'كيف يتمّ تحديد عيد الفطر؟',
    'eid_fitr.faq_a5': 'بثبوت رؤية هلال شوّال بعد غروب شمس اليوم 29 من رمضان، أو بإكمال رمضان 30 يومًا.',
    'eid_fitr.faq_q6': 'ما علاقة عيد الفطر بهلال شوّال؟',
    'eid_fitr.faq_a6': 'يبدأ عيد الفطر مع دخول شهر شوّال الذي يُثبَت برؤية هلاله، لذا يختلف أحيانًا بيوم عن الحساب الفلكيّ.',
    'eid_fitr.faq_q7': 'هل التاريخ المعروض نهائيّ أم متوقّع؟',
    'eid_fitr.faq_a7': 'التاريخ المعروض هو تقدير فلكيّ حسابيّ، والإعلان الرسميّ النهائيّ يصدر عن الجهة الشرعيّة في كلّ بلد.',
    'eid_fitr.faq_q8': 'كم مدّة عيد الفطر؟',
    'eid_fitr.faq_a8': 'يوم العيد الأوّل هو اليوم الأوّل من شوّال، وتستمرّ أيّام العيد 3 أيّام في معظم الدول الإسلاميّة.',
    'eid_fitr.faq_q9': 'ما أهمّ شعائر عيد الفطر؟',
    'eid_fitr.faq_a9': 'صلاة العيد، زكاة الفطر قبل الصلاة، التكبير، وصلة الأرحام والتهنئة بين المسلمين.',
    'eid_fitr.faq_q10': 'لماذا يتغيّر موعد عيد الفطر كلّ سنة ميلاديّة؟',
    'eid_fitr.faq_a10': 'لأنّ السنة الهجريّة القمريّة أقصر بحوالي 10-11 يومًا من الميلاديّة، فيتقدّم العيد بنفس المقدار سنويًّا.',
    'eid_fitr.info_title': '📖 معلومات عن عيد الفطر',
    'eid_fitr.info_h1': 'ما هو عيد الفطر',
    'eid_fitr.info_h1_body': 'عيد الفطر هو أحد العيدين في الإسلام، يأتي بعد إتمام صيام شهر رمضان المبارك ويبدأ من اليوم الأوّل من شوّال. يُشرع فيه التكبير، صلاة العيد، زكاة الفطر قبل الصلاة، والتبادل بالتهاني.',
    'eid_fitr.info_h2': 'كيف يثبت عيد الفطر',
    'eid_fitr.info_h2_body': 'يثبت عيد الفطر بأحد أمرين: رؤية هلال شوّال بعد غروب شمس اليوم التاسع والعشرين من رمضان، أو إكمال عدّة رمضان ثلاثين يومًا إن لم يُرَ الهلال.',
    'eid_fitr.info_h3': 'لماذا يتقدّم عيد الفطر كلّ سنة ميلاديّة',
    'eid_fitr.info_h3_body': 'السنة الهجريّة القمريّة أقصر بحوالي 10-11 يومًا من الميلاديّة، لذا يتقدّم عيد الفطر في التقويم الميلاديّ بنفس المقدار سنويًّا، ويدور عبر جميع الفصول كلّ ~33 سنة.',
    'eid_fitr.links_title': '🔗 روابط ذات صلة',
    'eid_fitr.link_ramadan': '🕋 كم باقي على رمضان',
    'eid_fitr.link_adha': '🐑 كم باقي على عيد الأضحى',
    'eid_fitr.link_new_year': '📅 كم باقي على رأس السنة الهجريّة',
    'eid_fitr.link_moon': '🌙 حالة القمر اليوم',
    'eid_fitr.link_hijri_today': '📅 التاريخ الهجريّ اليوم',
},

en: {
    'eid_fitr.h1': '🌙 How Long Until Eid al-Fitr?',
    'eid_fitr.intro': 'Discover the days remaining until the blessed Eid al-Fitr with the expected Gregorian and Hijri dates. Eid day may vary by one day depending on the Shawwal crescent sighting in your country.',
    'eid_fitr.event_name': 'Eid al-Fitr',
    'eid_fitr.hijri_1': '1 Shawwal',
    'eid_fitr.meta_title': '🌙 Eid al-Fitr Countdown — Expected Date & Live Timer',
    'eid_fitr.meta_desc': 'Accurate countdown to blessed Eid al-Fitr — in days, hours, and minutes — with Gregorian and Hijri dates and its link to the Shawwal crescent.',
    'eid_fitr.cards_title': '📋 Key Information',
    'eid_fitr.card1_title': 'Expected Eid al-Fitr',
    'eid_fitr.card2_title': 'Hijri Date',
    'eid_fitr.card3_title': 'Days Remaining',
    'eid_fitr.card4_title': 'Status',
    'eid_fitr.card4_value': 'Calculated · pending sighting',
    'eid_fitr.notice_title': '📜 Date Confirmation',
    'eid_fitr.notice_body': 'Eid al-Fitr is tied to sighting the Shawwal crescent after completing 29 or 30 days of Ramadan. The date shown is calculated astronomically per the arithmetic Hijri calendar and may differ by one day from each country\u2019s official announcement.',
    'eid_fitr.lunar_title': '🌙 Lunar Connection',
    'eid_fitr.lunar_current': 'Current moon phase:',
    'eid_fitr.lunar_link_today': '🌙 Moon status today →',
    'eid_fitr.lunar_link_new_moon': '🌑 Next new moon →',
    'eid_fitr.lunar_link_crescent': '🌒 Next Shawwal crescent →',
    'eid_fitr.years_title': '📅 Eid al-Fitr Dates in Upcoming Years',
    'eid_fitr.years_col_hijri': 'Hijri Year',
    'eid_fitr.years_col_greg': 'Gregorian Year',
    'eid_fitr.years_col_start': 'Eid al-Fitr (estimated)',
    'eid_fitr.years_col_note': 'Note',
    'eid_fitr.years_note': '* All dates are astronomical estimates and may vary by one day based on the sighting.',
    'eid_fitr.years_note_cell': 'Estimated · depends on sighting',
    'eid_fitr.cities_title': '🌍 Eid al-Fitr Around the World',
    'eid_fitr.city_sa': 'Eid al-Fitr in Saudi Arabia',
    'eid_fitr.city_eg': 'Eid al-Fitr in Egypt',
    'eid_fitr.city_ae': 'Eid al-Fitr in UAE',
    'eid_fitr.city_uk': 'Eid al-Fitr in London',
    'eid_fitr.city_tr': 'Eid al-Fitr in Istanbul',
    'eid_fitr.city_id': 'Eid al-Fitr in Jakarta',
    'eid_fitr.faq_title': '❓ Frequently Asked Questions about Eid al-Fitr',
    'eid_fitr.faq_q1': 'How long until Eid al-Fitr?',
    'eid_fitr.faq_a1': '{n} days remain until the expected Eid al-Fitr.',
    'eid_fitr.faq_q2': 'When is Eid al-Fitr this year?',
    'eid_fitr.faq_a2': 'Eid al-Fitr {hyear} AH falls on {date} approximately.',
    'eid_fitr.faq_q3': 'What is the Hijri date of Eid al-Fitr?',
    'eid_fitr.faq_a3': 'It corresponds to the first day of Shawwal {hyear} AH.',
    'eid_fitr.faq_q4': 'Can Eid al-Fitr dates differ between countries?',
    'eid_fitr.faq_a4': 'Yes, it may vary by one day between countries based on the local sighting of the Shawwal crescent.',
    'eid_fitr.faq_q5': 'How is Eid al-Fitr determined?',
    'eid_fitr.faq_a5': 'By sighting the Shawwal crescent after sunset on the 29th day of Ramadan, or by completing Ramadan as 30 days.',
    'eid_fitr.faq_q6': 'What is the link between Eid al-Fitr and the Shawwal crescent?',
    'eid_fitr.faq_a6': 'Eid al-Fitr begins with the onset of Shawwal, which is established by sighting its crescent, so it sometimes differs by a day from astronomical calculation.',
    'eid_fitr.faq_q7': 'Is the displayed date final or expected?',
    'eid_fitr.faq_a7': 'The date shown is an astronomical estimate; the final official announcement comes from each country\u2019s religious authority.',
    'eid_fitr.faq_q8': 'How long does Eid al-Fitr last?',
    'eid_fitr.faq_a8': 'The first day of Eid is 1 Shawwal, and the Eid festival lasts 3 days in most Muslim countries.',
    'eid_fitr.faq_q9': 'What are the main rites of Eid al-Fitr?',
    'eid_fitr.faq_a9': 'Eid prayer, paying Zakat al-Fitr before prayer, takbir, visiting relatives, and exchanging greetings among Muslims.',
    'eid_fitr.faq_q10': 'Why does Eid al-Fitr change each Gregorian year?',
    'eid_fitr.faq_a10': 'Because the lunar Hijri year is about 10-11 days shorter than the Gregorian year, Eid advances by the same amount each year.',
    'eid_fitr.info_title': '📖 About Eid al-Fitr',
    'eid_fitr.info_h1': 'What is Eid al-Fitr',
    'eid_fitr.info_h1_body': 'Eid al-Fitr is one of the two Islamic Eids, coming after completing the fast of the blessed month of Ramadan, beginning on the first day of Shawwal. It includes takbir, Eid prayer, paying Zakat al-Fitr before prayer, and exchanging greetings.',
    'eid_fitr.info_h2': 'How is Eid al-Fitr established',
    'eid_fitr.info_h2_body': 'Eid al-Fitr is established by one of two ways: sighting the Shawwal crescent after sunset on the 29th day of Ramadan, or completing Ramadan as 30 days if the crescent is not seen.',
    'eid_fitr.info_h3': 'Why does Eid al-Fitr advance each Gregorian year',
    'eid_fitr.info_h3_body': 'The lunar Hijri year is about 10-11 days shorter than the Gregorian year, so Eid al-Fitr advances the same amount each year in the Gregorian calendar, cycling through all seasons every ~33 years.',
    'eid_fitr.links_title': '🔗 Related Links',
    'eid_fitr.link_ramadan': '🕋 How long until Ramadan',
    'eid_fitr.link_adha': '🐑 How long until Eid al-Adha',
    'eid_fitr.link_new_year': '📅 How long until Hijri New Year',
    'eid_fitr.link_moon': '🌙 Moon status today',
    'eid_fitr.link_hijri_today': '📅 Today\u2019s Hijri date',
},

fr: {
    'eid_fitr.h1': '🌙 Combien de jours avant l\u2019Aïd el-Fitr ?',
    'eid_fitr.intro': 'Découvrez les jours restants jusqu\u2019à l\u2019Aïd el-Fitr béni avec les dates grégorienne et hégirienne prévues. Le jour de l\u2019Aïd peut varier d\u2019un jour selon l\u2019observation du croissant de Chawwal dans votre pays.',
    'eid_fitr.event_name': 'Aïd el-Fitr',
    'eid_fitr.hijri_1': '1 Chawwal',
    'eid_fitr.meta_title': '🌙 Combien de jours avant l\u2019Aïd el-Fitr ? — Date prévue et compte à rebours',
    'eid_fitr.meta_desc': 'Compte à rebours précis jusqu\u2019à l\u2019Aïd el-Fitr béni — en jours, heures et minutes — avec les dates grégorienne et hégirienne.',
    'eid_fitr.cards_title': '📋 Informations clés',
    'eid_fitr.card1_title': 'Aïd el-Fitr prévu',
    'eid_fitr.card2_title': 'Date hégirienne',
    'eid_fitr.card3_title': 'Jours restants',
    'eid_fitr.card4_title': 'Statut',
    'eid_fitr.card4_value': 'Calculé · en attente de l\u2019observation',
    'eid_fitr.notice_title': '📜 Confirmation de la date',
    'eid_fitr.notice_body': 'L\u2019Aïd el-Fitr est lié à l\u2019observation du croissant de Chawwal après 29 ou 30 jours de Ramadan. La date affichée est calculée astronomiquement et peut différer d\u2019un jour de l\u2019annonce officielle.',
    'eid_fitr.lunar_title': '🌙 Lien lunaire',
    'eid_fitr.lunar_current': 'Phase actuelle de la Lune :',
    'eid_fitr.lunar_link_today': '🌙 La Lune aujourd\u2019hui →',
    'eid_fitr.lunar_link_new_moon': '🌑 Prochaine nouvelle lune →',
    'eid_fitr.lunar_link_crescent': '🌒 Prochain croissant de Chawwal →',
    'eid_fitr.years_title': '📅 Dates de l\u2019Aïd el-Fitr pour les années à venir',
    'eid_fitr.years_col_hijri': 'Année hégirienne',
    'eid_fitr.years_col_greg': 'Année grégorienne',
    'eid_fitr.years_col_start': 'Aïd el-Fitr (estimé)',
    'eid_fitr.years_col_note': 'Remarque',
    'eid_fitr.years_note': '* Toutes les dates sont des estimations astronomiques et peuvent varier d\u2019un jour.',
    'eid_fitr.years_note_cell': 'Estimé · dépend de l\u2019observation',
    'eid_fitr.cities_title': '🌍 Aïd el-Fitr dans le monde',
    'eid_fitr.city_sa': 'Aïd el-Fitr en Arabie saoudite',
    'eid_fitr.city_eg': 'Aïd el-Fitr en Égypte',
    'eid_fitr.city_ae': 'Aïd el-Fitr aux Émirats',
    'eid_fitr.city_uk': 'Aïd el-Fitr à Londres',
    'eid_fitr.city_tr': 'Aïd el-Fitr à Istanbul',
    'eid_fitr.city_id': 'Aïd el-Fitr à Jakarta',
    'eid_fitr.faq_title': '❓ Questions fréquentes sur l\u2019Aïd el-Fitr',
    'eid_fitr.faq_q1': 'Combien de jours avant l\u2019Aïd el-Fitr ?',
    'eid_fitr.faq_a1': 'Il reste {n} jours avant l\u2019Aïd el-Fitr prévu.',
    'eid_fitr.faq_q2': 'Quand a lieu l\u2019Aïd el-Fitr cette année ?',
    'eid_fitr.faq_a2': 'L\u2019Aïd el-Fitr {hyear} H tombe le {date} selon les estimations.',
    'eid_fitr.faq_q3': 'Quelle est la date hégirienne de l\u2019Aïd el-Fitr ?',
    'eid_fitr.faq_a3': 'Elle correspond au premier jour de Chawwal {hyear} H.',
    'eid_fitr.faq_q4': 'La date de l\u2019Aïd el-Fitr peut-elle différer selon les pays ?',
    'eid_fitr.faq_a4': 'Oui, elle peut varier d\u2019un jour selon l\u2019observation locale du croissant de Chawwal.',
    'eid_fitr.faq_q5': 'Comment l\u2019Aïd el-Fitr est-il déterminé ?',
    'eid_fitr.faq_a5': 'Par l\u2019observation du croissant de Chawwal après le coucher du soleil du 29e jour de Ramadan, ou en complétant Ramadan à 30 jours.',
    'eid_fitr.faq_q6': 'Quel est le lien entre l\u2019Aïd el-Fitr et le croissant de Chawwal ?',
    'eid_fitr.faq_a6': 'L\u2019Aïd el-Fitr commence avec le début de Chawwal, établi par l\u2019observation du croissant, donc il peut différer d\u2019un jour du calcul astronomique.',
    'eid_fitr.faq_q7': 'La date affichée est-elle définitive ou prévue ?',
    'eid_fitr.faq_a7': 'C\u2019est une estimation astronomique ; l\u2019annonce officielle définitive est faite par l\u2019autorité religieuse de chaque pays.',
    'eid_fitr.faq_q8': 'Combien de temps dure l\u2019Aïd el-Fitr ?',
    'eid_fitr.faq_a8': 'Le premier jour de l\u2019Aïd est le 1er Chawwal, et la fête dure 3 jours dans la plupart des pays musulmans.',
    'eid_fitr.faq_q9': 'Quels sont les principaux rites de l\u2019Aïd el-Fitr ?',
    'eid_fitr.faq_a9': 'Prière de l\u2019Aïd, paiement de la Zakat al-Fitr avant la prière, takbir, visites familiales et échanges de vœux.',
    'eid_fitr.faq_q10': 'Pourquoi la date de l\u2019Aïd el-Fitr change-t-elle chaque année grégorienne ?',
    'eid_fitr.faq_a10': 'Parce que l\u2019année hégirienne lunaire est environ 10-11 jours plus courte que l\u2019année grégorienne, l\u2019Aïd avance du même nombre chaque année.',
    'eid_fitr.info_title': '📖 À propos de l\u2019Aïd el-Fitr',
    'eid_fitr.info_h1': 'Qu\u2019est-ce que l\u2019Aïd el-Fitr',
    'eid_fitr.info_h1_body': 'L\u2019Aïd el-Fitr est l\u2019une des deux fêtes islamiques, venant après l\u2019achèvement du jeûne de Ramadan, commençant le premier jour de Chawwal. Il inclut le takbir, la prière de l\u2019Aïd, la Zakat al-Fitr avant la prière, et l\u2019échange de vœux.',
    'eid_fitr.info_h2': 'Comment l\u2019Aïd el-Fitr est-il établi',
    'eid_fitr.info_h2_body': 'L\u2019Aïd el-Fitr est établi par l\u2019une de deux manières : l\u2019observation du croissant de Chawwal après le coucher du soleil du 29e jour de Ramadan, ou en complétant Ramadan à 30 jours si le croissant n\u2019est pas vu.',
    'eid_fitr.info_h3': 'Pourquoi l\u2019Aïd el-Fitr avance-t-il chaque année grégorienne',
    'eid_fitr.info_h3_body': 'L\u2019année hégirienne lunaire est environ 10-11 jours plus courte que l\u2019année grégorienne, donc l\u2019Aïd el-Fitr avance du même nombre chaque année, parcourant toutes les saisons en ~33 ans.',
    'eid_fitr.links_title': '🔗 Liens connexes',
    'eid_fitr.link_ramadan': '🕋 Combien de jours avant le Ramadan',
    'eid_fitr.link_adha': '🐑 Combien de jours avant l\u2019Aïd el-Adha',
    'eid_fitr.link_new_year': '📅 Combien de jours avant le Nouvel An hégirien',
    'eid_fitr.link_moon': '🌙 La Lune aujourd\u2019hui',
    'eid_fitr.link_hijri_today': '📅 Date hégirienne aujourd\u2019hui',
},

tr: {
    'eid_fitr.h1': '🌙 Ramazan Bayramı\u2019na ne kadar kaldı?',
    'eid_fitr.intro': 'Mübarek Ramazan Bayramı\u2019na kalan günleri beklenen miladi ve hicri tarihlerle birlikte keşfedin. Bayram günü ülkenizdeki Şevval hilali gözlemine göre bir gün değişebilir.',
    'eid_fitr.event_name': 'Ramazan Bayramı',
    'eid_fitr.hijri_1': '1 Şevval',
    'eid_fitr.meta_title': '🌙 Ramazan Bayramı\u2019na ne kadar kaldı? — Beklenen tarih ve geri sayım',
    'eid_fitr.meta_desc': 'Mübarek Ramazan Bayramı\u2019na kesin geri sayım — gün, saat ve dakika olarak — miladi ve hicri tarihlerle.',
    'eid_fitr.cards_title': '📋 Temel bilgiler',
    'eid_fitr.card1_title': 'Beklenen Ramazan Bayramı',
    'eid_fitr.card2_title': 'Hicri tarih',
    'eid_fitr.card3_title': 'Kalan gün sayısı',
    'eid_fitr.card4_title': 'Durum',
    'eid_fitr.card4_value': 'Hesaplanmış · rüyet bekleniyor',
    'eid_fitr.notice_title': '📜 Tarih onayı',
    'eid_fitr.notice_body': 'Ramazan Bayramı, Ramazan\u2019ın 29 veya 30 gününden sonra Şevval hilalinin görülmesine bağlıdır. Gösterilen tarih astronomik olarak hesaplanmıştır ve resmi ilandan bir gün farklı olabilir.',
    'eid_fitr.lunar_title': '🌙 Ay bağlantısı',
    'eid_fitr.lunar_current': 'Ay\u2019ın mevcut evresi:',
    'eid_fitr.lunar_link_today': '🌙 Ay bugün →',
    'eid_fitr.lunar_link_new_moon': '🌑 Bir sonraki yeni ay →',
    'eid_fitr.lunar_link_crescent': '🌒 Bir sonraki Şevval hilali →',
    'eid_fitr.years_title': '📅 Gelecek yıllarda Ramazan Bayramı tarihleri',
    'eid_fitr.years_col_hijri': 'Hicri yıl',
    'eid_fitr.years_col_greg': 'Miladi yıl',
    'eid_fitr.years_col_start': 'Ramazan Bayramı (tahmini)',
    'eid_fitr.years_col_note': 'Not',
    'eid_fitr.years_note': '* Tüm tarihler astronomik tahminlerdir ve rüyete göre bir gün değişebilir.',
    'eid_fitr.years_note_cell': 'Tahmini · rüyete bağlı',
    'eid_fitr.cities_title': '🌍 Dünyada Ramazan Bayramı',
    'eid_fitr.city_sa': 'Suudi Arabistan\u2019da Ramazan Bayramı',
    'eid_fitr.city_eg': 'Mısır\u2019da Ramazan Bayramı',
    'eid_fitr.city_ae': 'BAE\u2019de Ramazan Bayramı',
    'eid_fitr.city_uk': 'Londra\u2019da Ramazan Bayramı',
    'eid_fitr.city_tr': 'İstanbul\u2019da Ramazan Bayramı',
    'eid_fitr.city_id': 'Cakarta\u2019da Ramazan Bayramı',
    'eid_fitr.faq_title': '❓ Ramazan Bayramı hakkında sık sorulan sorular',
    'eid_fitr.faq_q1': 'Ramazan Bayramı\u2019na ne kadar kaldı?',
    'eid_fitr.faq_a1': 'Beklenen Ramazan Bayramı\u2019na {n} gün kaldı.',
    'eid_fitr.faq_q2': 'Bu yıl Ramazan Bayramı ne zaman?',
    'eid_fitr.faq_a2': '{hyear} H Ramazan Bayramı tahmini olarak {date} tarihine denk gelir.',
    'eid_fitr.faq_q3': 'Ramazan Bayramı\u2019nın hicri tarihi nedir?',
    'eid_fitr.faq_a3': '{hyear} H Şevval ayının ilk gününe denk gelir.',
    'eid_fitr.faq_q4': 'Ramazan Bayramı tarihleri ülkeden ülkeye değişebilir mi?',
    'eid_fitr.faq_a4': 'Evet, yerel Şevval hilali gözlemine göre bir gün değişebilir.',
    'eid_fitr.faq_q5': 'Ramazan Bayramı nasıl belirlenir?',
    'eid_fitr.faq_a5': 'Ramazan\u2019ın 29. gününün gün batımından sonra Şevval hilalinin görülmesiyle veya Ramazan\u2019ın 30 güne tamamlanmasıyla.',
    'eid_fitr.faq_q6': 'Ramazan Bayramı ile Şevval hilali arasındaki bağlantı nedir?',
    'eid_fitr.faq_a6': 'Ramazan Bayramı, hilalin görülmesiyle belirlenen Şevval\u2019ın başlamasıyla başlar, bu nedenle astronomik hesaplamadan bir gün farklı olabilir.',
    'eid_fitr.faq_q7': 'Gösterilen tarih kesin mi yoksa tahmini mi?',
    'eid_fitr.faq_a7': 'Astronomik bir tahmindir; nihai resmi ilan her ülkenin dini makamından gelir.',
    'eid_fitr.faq_q8': 'Ramazan Bayramı ne kadar sürer?',
    'eid_fitr.faq_a8': 'Bayramın ilk günü 1 Şevval\u2019dir ve çoğu Müslüman ülkede 3 gün sürer.',
    'eid_fitr.faq_q9': 'Ramazan Bayramı\u2019nın başlıca ibadetleri nelerdir?',
    'eid_fitr.faq_a9': 'Bayram namazı, namazdan önce fıtr zekatı, tekbir, akraba ziyaretleri ve bayramlaşma.',
    'eid_fitr.faq_q10': 'Ramazan Bayramı tarihi neden her miladi yıl değişir?',
    'eid_fitr.faq_a10': 'Hicri kameri yıl miladi yıldan yaklaşık 10-11 gün daha kısa olduğundan bayram her yıl aynı miktarda öne kayar.',
    'eid_fitr.info_title': '📖 Ramazan Bayramı hakkında',
    'eid_fitr.info_h1': 'Ramazan Bayramı nedir',
    'eid_fitr.info_h1_body': 'Ramazan Bayramı, Ramazan orucunun tamamlanmasının ardından gelen iki İslami bayramdan biridir ve Şevval\u2019ın ilk günü başlar. Tekbir, bayram namazı, namazdan önce fıtr zekatı ve tebriklerin alışverişini içerir.',
    'eid_fitr.info_h2': 'Ramazan Bayramı nasıl sabit olur',
    'eid_fitr.info_h2_body': 'Ramazan Bayramı iki yolla sabit olur: Ramazan\u2019ın 29. gününün gün batımından sonra Şevval hilalinin görülmesi veya hilal görülmezse Ramazan\u2019ın 30 güne tamamlanması.',
    'eid_fitr.info_h3': 'Ramazan Bayramı neden her miladi yıl öne kayar',
    'eid_fitr.info_h3_body': 'Hicri kameri yıl miladi yıldan yaklaşık 10-11 gün daha kısadır, bu nedenle Ramazan Bayramı her yıl aynı miktarda öne kayar ve yaklaşık 33 yılda tüm mevsimleri dolaşır.',
    'eid_fitr.links_title': '🔗 İlgili bağlantılar',
    'eid_fitr.link_ramadan': '🕋 Ramazan\u2019a ne kadar kaldı',
    'eid_fitr.link_adha': '🐑 Kurban Bayramı\u2019na ne kadar kaldı',
    'eid_fitr.link_new_year': '📅 Hicri Yılbaşı\u2019na ne kadar kaldı',
    'eid_fitr.link_moon': '🌙 Ay bugün',
    'eid_fitr.link_hijri_today': '📅 Bugünün hicri tarihi',
},

ur: {
    'eid_fitr.h1': '🌙 عید الفطر میں کتنے دن باقی ہیں؟',
    'eid_fitr.intro': 'عید الفطر المبارک تک متوقع عیسوی اور ہجری تاریخ کے ساتھ باقی رہ جانے والے دن دریافت کریں۔ عید کا دن آپ کے ملک میں شوال کے ہلال کی رؤیت کے مطابق ایک دن مختلف ہو سکتا ہے۔',
    'eid_fitr.event_name': 'عید الفطر',
    'eid_fitr.hijri_1': '1 شوال',
    'eid_fitr.meta_title': '🌙 عید الفطر میں کتنے دن باقی ہیں؟ — متوقع تاریخ اور گنتی',
    'eid_fitr.meta_desc': 'عید الفطر المبارک تک درست گنتی — دن، گھنٹے اور منٹ — عیسوی اور ہجری تاریخ کے ساتھ۔',
    'eid_fitr.cards_title': '📋 بنیادی معلومات',
    'eid_fitr.card1_title': 'متوقع عید الفطر',
    'eid_fitr.card2_title': 'ہجری تاریخ',
    'eid_fitr.card3_title': 'باقی دن',
    'eid_fitr.card4_title': 'حیثیت',
    'eid_fitr.card4_value': 'حسابی · رؤیت کا انتظار',
    'eid_fitr.notice_title': '📜 تاریخ کی توثیق',
    'eid_fitr.notice_body': 'عید الفطر رمضان کے 29 یا 30 دن کے بعد شوال کے ہلال کی رؤیت سے جڑی ہے۔ دکھائی گئی تاریخ فلکی طور پر شمار کی گئی ہے اور رسمی اعلان سے ایک دن مختلف ہو سکتی ہے۔',
    'eid_fitr.lunar_title': '🌙 قمری تعلق',
    'eid_fitr.lunar_current': 'چاند کا موجودہ مرحلہ:',
    'eid_fitr.lunar_link_today': '🌙 آج چاند کی حالت →',
    'eid_fitr.lunar_link_new_moon': '🌑 اگلا نیا چاند →',
    'eid_fitr.lunar_link_crescent': '🌒 اگلا شوال ہلال →',
    'eid_fitr.years_title': '📅 آنے والے سالوں میں عید الفطر کی تاریخیں',
    'eid_fitr.years_col_hijri': 'ہجری سال',
    'eid_fitr.years_col_greg': 'عیسوی سال',
    'eid_fitr.years_col_start': 'عید الفطر (تخمینی)',
    'eid_fitr.years_col_note': 'نوٹ',
    'eid_fitr.years_note': '* تمام تاریخیں فلکی تخمینے ہیں اور رؤیت کے مطابق ایک دن مختلف ہو سکتی ہیں۔',
    'eid_fitr.years_note_cell': 'تخمینی · رؤیت پر منحصر',
    'eid_fitr.cities_title': '🌍 دنیا بھر میں عید الفطر',
    'eid_fitr.city_sa': 'سعودی عرب میں عید الفطر',
    'eid_fitr.city_eg': 'مصر میں عید الفطر',
    'eid_fitr.city_ae': 'متحدہ عرب امارات میں عید الفطر',
    'eid_fitr.city_uk': 'لندن میں عید الفطر',
    'eid_fitr.city_tr': 'استنبول میں عید الفطر',
    'eid_fitr.city_id': 'جکارتا میں عید الفطر',
    'eid_fitr.faq_title': '❓ عید الفطر کے بارے میں اکثر پوچھے جانے والے سوالات',
    'eid_fitr.faq_q1': 'عید الفطر میں کتنے دن باقی ہیں؟',
    'eid_fitr.faq_a1': 'متوقع عید الفطر تک {n} دن باقی ہیں۔',
    'eid_fitr.faq_q2': 'اس سال عید الفطر کب ہے؟',
    'eid_fitr.faq_a2': '{hyear} ہجری عید الفطر تخمینی طور پر {date} کو آتی ہے۔',
    'eid_fitr.faq_q3': 'عید الفطر کی ہجری تاریخ کیا ہے؟',
    'eid_fitr.faq_a3': '{hyear} ہجری شوال کے پہلے دن کے مطابق ہے۔',
    'eid_fitr.faq_q4': 'کیا عید الفطر کی تاریخ مختلف ممالک میں مختلف ہو سکتی ہے؟',
    'eid_fitr.faq_a4': 'جی ہاں، مقامی شوال ہلال کی رؤیت کے مطابق ایک دن مختلف ہو سکتی ہے۔',
    'eid_fitr.faq_q5': 'عید الفطر کیسے طے ہوتی ہے؟',
    'eid_fitr.faq_a5': 'رمضان کے 29ویں دن غروب آفتاب کے بعد شوال ہلال کی رؤیت سے یا رمضان کے 30 دن پورا کرنے سے۔',
    'eid_fitr.faq_q6': 'عید الفطر کا شوال ہلال سے کیا تعلق ہے؟',
    'eid_fitr.faq_a6': 'عید الفطر شوال کے آغاز سے شروع ہوتی ہے جو ہلال کی رؤیت سے ثابت ہوتی ہے، اس لیے فلکی حساب سے ایک دن مختلف ہو سکتی ہے۔',
    'eid_fitr.faq_q7': 'کیا دکھائی گئی تاریخ حتمی ہے یا متوقع؟',
    'eid_fitr.faq_a7': 'یہ فلکی حسابی تخمینہ ہے؛ حتمی رسمی اعلان ہر ملک کے شرعی ادارے سے آتا ہے۔',
    'eid_fitr.faq_q8': 'عید الفطر کتنے دن چلتی ہے؟',
    'eid_fitr.faq_a8': 'عید کا پہلا دن 1 شوال ہے، اور زیادہ تر مسلم ممالک میں عید 3 دن منائی جاتی ہے۔',
    'eid_fitr.faq_q9': 'عید الفطر کے اہم ارکان کیا ہیں؟',
    'eid_fitr.faq_a9': 'نماز عید، نماز سے پہلے زکاۃ الفطر، تکبیر، رشتہ داروں سے ملاقات اور تحفے کا تبادلہ۔',
    'eid_fitr.faq_q10': 'ہر عیسوی سال عید الفطر کی تاریخ کیوں بدلتی ہے؟',
    'eid_fitr.faq_a10': 'کیونکہ ہجری قمری سال عیسوی سال سے تقریباً 10-11 دن چھوٹا ہے، لہذا عید ہر سال اتنی ہی مقدار سے آگے بڑھتی ہے۔',
    'eid_fitr.info_title': '📖 عید الفطر کے بارے میں',
    'eid_fitr.info_h1': 'عید الفطر کیا ہے',
    'eid_fitr.info_h1_body': 'عید الفطر اسلام کی دو عیدوں میں سے ایک ہے، جو رمضان کے روزے مکمل کرنے کے بعد 1 شوال سے شروع ہوتی ہے۔ اس میں تکبیر، نماز عید، نماز سے پہلے زکاۃ الفطر، اور مبارکبادی کا تبادلہ شامل ہے۔',
    'eid_fitr.info_h2': 'عید الفطر کیسے ثابت ہوتی ہے',
    'eid_fitr.info_h2_body': 'عید الفطر دو طریقوں سے ثابت ہوتی ہے: رمضان کے 29ویں دن غروب آفتاب کے بعد شوال ہلال کی رؤیت سے، یا اگر ہلال نظر نہ آئے تو رمضان کے 30 دن پورا کر کے۔',
    'eid_fitr.info_h3': 'ہر عیسوی سال عید الفطر کیوں آگے بڑھتی ہے',
    'eid_fitr.info_h3_body': 'ہجری قمری سال عیسوی سال سے تقریباً 10-11 دن چھوٹا ہے، اس لیے عید الفطر ہر سال اتنی ہی مقدار سے آگے بڑھتی ہے اور تقریباً 33 سالوں میں تمام موسموں میں گھومتی ہے۔',
    'eid_fitr.links_title': '🔗 متعلقہ روابط',
    'eid_fitr.link_ramadan': '🕋 رمضان میں کتنے دن باقی',
    'eid_fitr.link_adha': '🐑 عید الاضحیٰ میں کتنے دن باقی',
    'eid_fitr.link_new_year': '📅 نئے ہجری سال میں کتنے دن باقی',
    'eid_fitr.link_moon': '🌙 آج چاند کی حالت',
    'eid_fitr.link_hijri_today': '📅 آج کی ہجری تاریخ',
},

de: {
    'eid_fitr.h1': '🌙 Wie lange noch bis Eid al-Fitr?',
    'eid_fitr.intro': 'Entdecken Sie die verbleibenden Tage bis zum gesegneten Eid al-Fitr mit dem erwarteten gregorianischen und Hidschri-Datum. Der Eid-Tag kann je nach Schawwal-Mondsichtung in Ihrem Land um einen Tag abweichen.',
    'eid_fitr.event_name': 'Eid al-Fitr',
    'eid_fitr.hijri_1': '1. Schawwal',
    'eid_fitr.meta_title': '🌙 Wie lange noch bis Eid al-Fitr? — Erwartetes Datum und Countdown',
    'eid_fitr.meta_desc': 'Präziser Countdown bis zum gesegneten Eid al-Fitr — in Tagen, Stunden und Minuten — mit gregorianischem und Hidschri-Datum.',
    'eid_fitr.cards_title': '📋 Wichtige Informationen',
    'eid_fitr.card1_title': 'Erwartetes Eid al-Fitr',
    'eid_fitr.card2_title': 'Hidschri-Datum',
    'eid_fitr.card3_title': 'Verbleibende Tage',
    'eid_fitr.card4_title': 'Status',
    'eid_fitr.card4_value': 'Berechnet · Sichtung ausstehend',
    'eid_fitr.notice_title': '📜 Datumsbestätigung',
    'eid_fitr.notice_body': 'Eid al-Fitr ist an die Sichtung der Schawwal-Mondsichel nach Abschluss von 29 oder 30 Ramadantagen gebunden. Das angezeigte Datum wird astronomisch berechnet und kann um einen Tag von der offiziellen Ankündigung abweichen.',
    'eid_fitr.lunar_title': '🌙 Mondverbindung',
    'eid_fitr.lunar_current': 'Aktuelle Mondphase:',
    'eid_fitr.lunar_link_today': '🌙 Mondstatus heute →',
    'eid_fitr.lunar_link_new_moon': '🌑 Nächster Neumond →',
    'eid_fitr.lunar_link_crescent': '🌒 Nächste Schawwal-Mondsichel →',
    'eid_fitr.years_title': '📅 Eid al-Fitr in den kommenden Jahren',
    'eid_fitr.years_col_hijri': 'Hidschri-Jahr',
    'eid_fitr.years_col_greg': 'Gregorianisches Jahr',
    'eid_fitr.years_col_start': 'Eid al-Fitr (geschätzt)',
    'eid_fitr.years_col_note': 'Hinweis',
    'eid_fitr.years_note': '* Alle Daten sind astronomische Schätzungen und können je nach Sichtung um einen Tag abweichen.',
    'eid_fitr.years_note_cell': 'Geschätzt · sichtungsabhängig',
    'eid_fitr.cities_title': '🌍 Eid al-Fitr weltweit',
    'eid_fitr.city_sa': 'Eid al-Fitr in Saudi-Arabien',
    'eid_fitr.city_eg': 'Eid al-Fitr in Ägypten',
    'eid_fitr.city_ae': 'Eid al-Fitr in den VAE',
    'eid_fitr.city_uk': 'Eid al-Fitr in London',
    'eid_fitr.city_tr': 'Eid al-Fitr in Istanbul',
    'eid_fitr.city_id': 'Eid al-Fitr in Jakarta',
    'eid_fitr.faq_title': '❓ Häufige Fragen zu Eid al-Fitr',
    'eid_fitr.faq_q1': 'Wie lange noch bis Eid al-Fitr?',
    'eid_fitr.faq_a1': 'Bis zum erwarteten Eid al-Fitr sind es noch {n} Tage.',
    'eid_fitr.faq_q2': 'Wann ist Eid al-Fitr in diesem Jahr?',
    'eid_fitr.faq_a2': 'Eid al-Fitr {hyear} H fällt voraussichtlich auf {date}.',
    'eid_fitr.faq_q3': 'Was ist das Hidschri-Datum von Eid al-Fitr?',
    'eid_fitr.faq_a3': 'Es entspricht dem ersten Tag des Schawwal {hyear} H.',
    'eid_fitr.faq_q4': 'Kann das Eid-al-Fitr-Datum zwischen Ländern variieren?',
    'eid_fitr.faq_a4': 'Ja, es kann je nach lokaler Sichtung der Schawwal-Mondsichel um einen Tag abweichen.',
    'eid_fitr.faq_q5': 'Wie wird Eid al-Fitr festgelegt?',
    'eid_fitr.faq_a5': 'Durch die Sichtung der Schawwal-Mondsichel nach Sonnenuntergang am 29. Tag Ramadan oder durch die Vollendung des Ramadan mit 30 Tagen.',
    'eid_fitr.faq_q6': 'Wie hängt Eid al-Fitr mit der Schawwal-Mondsichel zusammen?',
    'eid_fitr.faq_a6': 'Eid al-Fitr beginnt mit dem Beginn des Schawwal, der durch die Sichtung der Mondsichel festgelegt wird, daher kann es um einen Tag von der astronomischen Berechnung abweichen.',
    'eid_fitr.faq_q7': 'Ist das angezeigte Datum endgültig oder erwartet?',
    'eid_fitr.faq_a7': 'Es ist eine astronomische Schätzung; die endgültige offizielle Ankündigung erfolgt durch die religiöse Behörde jedes Landes.',
    'eid_fitr.faq_q8': 'Wie lange dauert Eid al-Fitr?',
    'eid_fitr.faq_a8': 'Der erste Tag ist 1. Schawwal, und das Fest dauert in den meisten muslimischen Ländern 3 Tage.',
    'eid_fitr.faq_q9': 'Was sind die wichtigsten Riten von Eid al-Fitr?',
    'eid_fitr.faq_a9': 'Eid-Gebet, Zahlung der Zakat al-Fitr vor dem Gebet, Takbir, Familienbesuche und Glückwunschaustausch.',
    'eid_fitr.faq_q10': 'Warum ändert sich das Eid-al-Fitr-Datum jedes gregorianische Jahr?',
    'eid_fitr.faq_a10': 'Weil das Hidschri-Mondjahr etwa 10-11 Tage kürzer ist, verschiebt sich Eid jedes Jahr um denselben Betrag.',
    'eid_fitr.info_title': '📖 Über Eid al-Fitr',
    'eid_fitr.info_h1': 'Was ist Eid al-Fitr',
    'eid_fitr.info_h1_body': 'Eid al-Fitr ist eines der zwei islamischen Feste und folgt auf das Fasten im gesegneten Ramadan, beginnend am 1. Schawwal. Es umfasst Takbir, Eid-Gebet, Zakat al-Fitr vor dem Gebet und den Austausch von Glückwünschen.',
    'eid_fitr.info_h2': 'Wie wird Eid al-Fitr festgelegt',
    'eid_fitr.info_h2_body': 'Eid al-Fitr wird auf zwei Wegen festgelegt: durch die Sichtung der Schawwal-Mondsichel nach Sonnenuntergang am 29. Tag Ramadan oder durch die Vollendung des Ramadan mit 30 Tagen, wenn die Mondsichel nicht gesehen wird.',
    'eid_fitr.info_h3': 'Warum verschiebt sich Eid al-Fitr jedes gregorianische Jahr',
    'eid_fitr.info_h3_body': 'Das Hidschri-Mondjahr ist etwa 10-11 Tage kürzer als das gregorianische Jahr, daher verschiebt sich Eid al-Fitr jedes Jahr um denselben Betrag und durchläuft alle Jahreszeiten in etwa 33 Jahren.',
    'eid_fitr.links_title': '🔗 Verwandte Links',
    'eid_fitr.link_ramadan': '🕋 Wie lange noch bis Ramadan',
    'eid_fitr.link_adha': '🐑 Wie lange noch bis Eid al-Adha',
    'eid_fitr.link_new_year': '📅 Wie lange noch bis zum islamischen Neujahr',
    'eid_fitr.link_moon': '🌙 Mondstatus heute',
    'eid_fitr.link_hijri_today': '📅 Heutiges Hidschri-Datum',
},

id: {
    'eid_fitr.h1': '🌙 Berapa hari lagi Idul Fitri?',
    'eid_fitr.intro': 'Temukan hari-hari tersisa menuju Idul Fitri yang diberkahi dengan tanggal Masehi dan Hijriah perkiraan. Hari raya dapat berbeda satu hari tergantung rukyat hilal Syawal di negara Anda.',
    'eid_fitr.event_name': 'Idul Fitri',
    'eid_fitr.hijri_1': '1 Syawal',
    'eid_fitr.meta_title': '🌙 Berapa hari lagi Idul Fitri? — Tanggal perkiraan dan hitung mundur',
    'eid_fitr.meta_desc': 'Hitung mundur akurat menuju Idul Fitri yang diberkahi — dalam hari, jam dan menit — dengan tanggal Masehi dan Hijriah.',
    'eid_fitr.cards_title': '📋 Informasi utama',
    'eid_fitr.card1_title': 'Idul Fitri perkiraan',
    'eid_fitr.card2_title': 'Tanggal Hijriah',
    'eid_fitr.card3_title': 'Hari tersisa',
    'eid_fitr.card4_title': 'Status',
    'eid_fitr.card4_value': 'Terhitung · menunggu rukyat',
    'eid_fitr.notice_title': '📜 Konfirmasi tanggal',
    'eid_fitr.notice_body': 'Idul Fitri terkait dengan rukyat hilal Syawal setelah menyelesaikan 29 atau 30 hari Ramadan. Tanggal yang ditampilkan dihitung secara astronomis dan dapat berbeda satu hari dari pengumuman resmi.',
    'eid_fitr.lunar_title': '🌙 Hubungan dengan Bulan',
    'eid_fitr.lunar_current': 'Fase Bulan saat ini:',
    'eid_fitr.lunar_link_today': '🌙 Status Bulan hari ini →',
    'eid_fitr.lunar_link_new_moon': '🌑 Bulan baru berikutnya →',
    'eid_fitr.lunar_link_crescent': '🌒 Hilal Syawal berikutnya →',
    'eid_fitr.years_title': '📅 Tanggal Idul Fitri tahun-tahun mendatang',
    'eid_fitr.years_col_hijri': 'Tahun Hijriah',
    'eid_fitr.years_col_greg': 'Tahun Masehi',
    'eid_fitr.years_col_start': 'Idul Fitri (perkiraan)',
    'eid_fitr.years_col_note': 'Catatan',
    'eid_fitr.years_note': '* Semua tanggal adalah perkiraan astronomis dan dapat berbeda satu hari berdasarkan rukyat.',
    'eid_fitr.years_note_cell': 'Perkiraan · tergantung rukyat',
    'eid_fitr.cities_title': '🌍 Idul Fitri di seluruh dunia',
    'eid_fitr.city_sa': 'Idul Fitri di Arab Saudi',
    'eid_fitr.city_eg': 'Idul Fitri di Mesir',
    'eid_fitr.city_ae': 'Idul Fitri di UEA',
    'eid_fitr.city_uk': 'Idul Fitri di London',
    'eid_fitr.city_tr': 'Idul Fitri di Istanbul',
    'eid_fitr.city_id': 'Idul Fitri di Jakarta',
    'eid_fitr.faq_title': '❓ Pertanyaan umum tentang Idul Fitri',
    'eid_fitr.faq_q1': 'Berapa hari lagi Idul Fitri?',
    'eid_fitr.faq_a1': 'Tersisa {n} hari menuju Idul Fitri perkiraan.',
    'eid_fitr.faq_q2': 'Kapan Idul Fitri tahun ini?',
    'eid_fitr.faq_a2': 'Idul Fitri {hyear} H jatuh pada {date} secara perkiraan.',
    'eid_fitr.faq_q3': 'Apa tanggal Hijriah Idul Fitri?',
    'eid_fitr.faq_a3': 'Bertepatan dengan hari pertama Syawal {hyear} H.',
    'eid_fitr.faq_q4': 'Apakah tanggal Idul Fitri dapat berbeda antar negara?',
    'eid_fitr.faq_a4': 'Ya, dapat berbeda satu hari berdasarkan rukyat hilal Syawal setempat.',
    'eid_fitr.faq_q5': 'Bagaimana Idul Fitri ditentukan?',
    'eid_fitr.faq_a5': 'Dengan rukyat hilal Syawal setelah matahari terbenam pada hari ke-29 Ramadan, atau menyempurnakan Ramadan menjadi 30 hari.',
    'eid_fitr.faq_q6': 'Apa hubungan Idul Fitri dengan hilal Syawal?',
    'eid_fitr.faq_a6': 'Idul Fitri dimulai bersamaan dengan awal Syawal yang ditetapkan oleh rukyat hilal, sehingga kadang berbeda satu hari dari perhitungan astronomis.',
    'eid_fitr.faq_q7': 'Apakah tanggal yang ditampilkan final atau perkiraan?',
    'eid_fitr.faq_a7': 'Ini adalah perkiraan astronomis; pengumuman resmi final dikeluarkan oleh otoritas keagamaan masing-masing negara.',
    'eid_fitr.faq_q8': 'Berapa lama Idul Fitri berlangsung?',
    'eid_fitr.faq_a8': 'Hari pertama Idul Fitri adalah 1 Syawal, dan di sebagian besar negara Muslim berlangsung 3 hari.',
    'eid_fitr.faq_q9': 'Apa ritual utama Idul Fitri?',
    'eid_fitr.faq_a9': 'Sholat Ied, zakat fitrah sebelum sholat, takbir, silaturahmi dan saling mengucap selamat.',
    'eid_fitr.faq_q10': 'Mengapa tanggal Idul Fitri berubah setiap tahun Masehi?',
    'eid_fitr.faq_a10': 'Karena tahun Hijriah qamariah sekitar 10-11 hari lebih pendek dari tahun Masehi, Idul Fitri maju dengan jumlah yang sama setiap tahun.',
    'eid_fitr.info_title': '📖 Tentang Idul Fitri',
    'eid_fitr.info_h1': 'Apa itu Idul Fitri',
    'eid_fitr.info_h1_body': 'Idul Fitri adalah salah satu dari dua hari raya Islam yang datang setelah menyempurnakan puasa bulan Ramadan, dimulai pada 1 Syawal. Meliputi takbir, sholat Ied, zakat fitrah sebelum sholat, dan saling mengucap selamat.',
    'eid_fitr.info_h2': 'Bagaimana Idul Fitri ditetapkan',
    'eid_fitr.info_h2_body': 'Idul Fitri ditetapkan dengan dua cara: rukyat hilal Syawal setelah matahari terbenam pada hari ke-29 Ramadan, atau menyempurnakan Ramadan menjadi 30 hari jika hilal tidak terlihat.',
    'eid_fitr.info_h3': 'Mengapa Idul Fitri maju setiap tahun Masehi',
    'eid_fitr.info_h3_body': 'Tahun Hijriah qamariah sekitar 10-11 hari lebih pendek dari tahun Masehi, sehingga Idul Fitri maju dengan jumlah yang sama setiap tahun dan melewati semua musim dalam sekitar 33 tahun.',
    'eid_fitr.links_title': '🔗 Tautan terkait',
    'eid_fitr.link_ramadan': '🕋 Berapa hari lagi Ramadan',
    'eid_fitr.link_adha': '🐑 Berapa hari lagi Idul Adha',
    'eid_fitr.link_new_year': '📅 Berapa hari lagi Tahun Baru Hijriah',
    'eid_fitr.link_moon': '🌙 Status Bulan hari ini',
    'eid_fitr.link_hijri_today': '📅 Tanggal Hijriah hari ini',
},

es: {
    'eid_fitr.h1': '🌙 ¿Cuánto falta para el Eid al-Fitr?',
    'eid_fitr.intro': 'Descubre los días restantes hasta el bendito Eid al-Fitr con las fechas gregoriana y hégira previstas. El día del Eid puede variar un día según el avistamiento del creciente de Shawwal en tu país.',
    'eid_fitr.event_name': 'Eid al-Fitr',
    'eid_fitr.hijri_1': '1 de Shawwal',
    'eid_fitr.meta_title': '🌙 ¿Cuánto falta para el Eid al-Fitr? — Fecha prevista y cuenta atrás',
    'eid_fitr.meta_desc': 'Cuenta atrás precisa hasta el bendito Eid al-Fitr — en días, horas y minutos — con las fechas gregoriana y hégira.',
    'eid_fitr.cards_title': '📋 Información clave',
    'eid_fitr.card1_title': 'Eid al-Fitr previsto',
    'eid_fitr.card2_title': 'Fecha hégira',
    'eid_fitr.card3_title': 'Días restantes',
    'eid_fitr.card4_title': 'Estado',
    'eid_fitr.card4_value': 'Calculado · a la espera del avistamiento',
    'eid_fitr.notice_title': '📜 Confirmación de la fecha',
    'eid_fitr.notice_body': 'El Eid al-Fitr está ligado al avistamiento del creciente de Shawwal tras completar 29 o 30 días de Ramadán. La fecha mostrada se calcula astronómicamente y puede diferir un día del anuncio oficial.',
    'eid_fitr.lunar_title': '🌙 Conexión lunar',
    'eid_fitr.lunar_current': 'Fase actual de la Luna:',
    'eid_fitr.lunar_link_today': '🌙 Estado de la Luna hoy →',
    'eid_fitr.lunar_link_new_moon': '🌑 Próxima luna nueva →',
    'eid_fitr.lunar_link_crescent': '🌒 Próximo creciente de Shawwal →',
    'eid_fitr.years_title': '📅 Fechas del Eid al-Fitr en los próximos años',
    'eid_fitr.years_col_hijri': 'Año hégira',
    'eid_fitr.years_col_greg': 'Año gregoriano',
    'eid_fitr.years_col_start': 'Eid al-Fitr (estimado)',
    'eid_fitr.years_col_note': 'Nota',
    'eid_fitr.years_note': '* Todas las fechas son estimaciones astronómicas y pueden variar un día según el avistamiento.',
    'eid_fitr.years_note_cell': 'Estimado · depende del avistamiento',
    'eid_fitr.cities_title': '🌍 Eid al-Fitr en el mundo',
    'eid_fitr.city_sa': 'Eid al-Fitr en Arabia Saudita',
    'eid_fitr.city_eg': 'Eid al-Fitr en Egipto',
    'eid_fitr.city_ae': 'Eid al-Fitr en los EAU',
    'eid_fitr.city_uk': 'Eid al-Fitr en Londres',
    'eid_fitr.city_tr': 'Eid al-Fitr en Estambul',
    'eid_fitr.city_id': 'Eid al-Fitr en Yakarta',
    'eid_fitr.faq_title': '❓ Preguntas frecuentes sobre el Eid al-Fitr',
    'eid_fitr.faq_q1': '¿Cuánto falta para el Eid al-Fitr?',
    'eid_fitr.faq_a1': 'Faltan {n} días para el Eid al-Fitr previsto.',
    'eid_fitr.faq_q2': '¿Cuándo es el Eid al-Fitr este año?',
    'eid_fitr.faq_a2': 'El Eid al-Fitr {hyear} H cae el {date} según estimaciones.',
    'eid_fitr.faq_q3': '¿Cuál es la fecha hégira del Eid al-Fitr?',
    'eid_fitr.faq_a3': 'Corresponde al primer día de Shawwal {hyear} H.',
    'eid_fitr.faq_q4': '¿Puede variar la fecha del Eid al-Fitr entre países?',
    'eid_fitr.faq_a4': 'Sí, puede variar un día según el avistamiento local del creciente de Shawwal.',
    'eid_fitr.faq_q5': '¿Cómo se determina el Eid al-Fitr?',
    'eid_fitr.faq_a5': 'Por el avistamiento del creciente de Shawwal tras la puesta del sol del 29 de Ramadán, o completando Ramadán con 30 días.',
    'eid_fitr.faq_q6': '¿Cuál es el vínculo entre el Eid al-Fitr y el creciente de Shawwal?',
    'eid_fitr.faq_a6': 'El Eid al-Fitr comienza con el inicio de Shawwal, establecido por el avistamiento del creciente, por lo que a veces difiere un día del cálculo astronómico.',
    'eid_fitr.faq_q7': '¿Es la fecha mostrada definitiva o prevista?',
    'eid_fitr.faq_a7': 'Es una estimación astronómica; el anuncio oficial definitivo lo emite la autoridad religiosa de cada país.',
    'eid_fitr.faq_q8': '¿Cuánto dura el Eid al-Fitr?',
    'eid_fitr.faq_a8': 'El primer día del Eid es el 1 de Shawwal, y la fiesta dura 3 días en la mayoría de los países musulmanes.',
    'eid_fitr.faq_q9': '¿Cuáles son los principales ritos del Eid al-Fitr?',
    'eid_fitr.faq_a9': 'Oración del Eid, pago del Zakat al-Fitr antes de la oración, takbir, visitas familiares y el intercambio de felicitaciones.',
    'eid_fitr.faq_q10': '¿Por qué cambia la fecha del Eid al-Fitr cada año gregoriano?',
    'eid_fitr.faq_a10': 'Porque el año hégira lunar es unos 10-11 días más corto, el Eid se adelanta la misma cantidad cada año.',
    'eid_fitr.info_title': '📖 Sobre el Eid al-Fitr',
    'eid_fitr.info_h1': 'Qué es el Eid al-Fitr',
    'eid_fitr.info_h1_body': 'El Eid al-Fitr es una de las dos fiestas islámicas, tras completar el ayuno del bendito Ramadán, empezando el 1 de Shawwal. Incluye takbir, oración del Eid, Zakat al-Fitr antes de la oración, y el intercambio de felicitaciones.',
    'eid_fitr.info_h2': 'Cómo se establece el Eid al-Fitr',
    'eid_fitr.info_h2_body': 'El Eid al-Fitr se establece por dos vías: el avistamiento del creciente de Shawwal tras la puesta del sol del 29 de Ramadán, o completando Ramadán con 30 días si el creciente no se ve.',
    'eid_fitr.info_h3': 'Por qué el Eid al-Fitr se adelanta cada año gregoriano',
    'eid_fitr.info_h3_body': 'El año hégira lunar es unos 10-11 días más corto que el año gregoriano, por eso el Eid al-Fitr se adelanta la misma cantidad cada año y recorre todas las estaciones cada ~33 años.',
    'eid_fitr.links_title': '🔗 Enlaces relacionados',
    'eid_fitr.link_ramadan': '🕋 Cuánto falta para el Ramadán',
    'eid_fitr.link_adha': '🐑 Cuánto falta para el Eid al-Adha',
    'eid_fitr.link_new_year': '📅 Cuánto falta para el Año Nuevo hégira',
    'eid_fitr.link_moon': '🌙 Estado de la Luna hoy',
    'eid_fitr.link_hijri_today': '📅 Fecha hégira de hoy',
},

bn: {
    'eid_fitr.h1': '🌙 ঈদুল ফিতরে আসতে কতদিন বাকি?',
    'eid_fitr.intro': 'পবিত্র ঈদুল ফিতর পর্যন্ত অবশিষ্ট দিন জানুন প্রত্যাশিত গ্রেগরিয়ান ও হিজরি তারিখসহ। আপনার দেশে শাওয়াল হিলাল দেখার ভিত্তিতে ঈদের দিন একদিন ভিন্ন হতে পারে।',
    'eid_fitr.event_name': 'ঈদুল ফিতর',
    'eid_fitr.hijri_1': '১ শাওয়াল',
    'eid_fitr.meta_title': '🌙 ঈদুল ফিতরে আসতে কতদিন বাকি? — প্রত্যাশিত তারিখ ও কাউন্টডাউন',
    'eid_fitr.meta_desc': 'পবিত্র ঈদুল ফিতর পর্যন্ত সঠিক কাউন্টডাউন — দিন, ঘণ্টা ও মিনিটে — গ্রেগরিয়ান ও হিজরি তারিখসহ।',
    'eid_fitr.cards_title': '📋 মূল তথ্য',
    'eid_fitr.card1_title': 'প্রত্যাশিত ঈদুল ফিতর',
    'eid_fitr.card2_title': 'হিজরি তারিখ',
    'eid_fitr.card3_title': 'অবশিষ্ট দিন',
    'eid_fitr.card4_title': 'অবস্থা',
    'eid_fitr.card4_value': 'গণনাকৃত · রূয়তের অপেক্ষায়',
    'eid_fitr.notice_title': '📜 তারিখ নিশ্চিতকরণ',
    'eid_fitr.notice_body': 'ঈদুল ফিতর রমজানের ২৯ বা ৩০ দিন শেষে শাওয়াল হিলাল দেখার সাথে সংযুক্ত। দেখানো তারিখ জ্যোতির্বিদ্যাগতভাবে গণনা করা হয়েছে এবং আনুষ্ঠানিক ঘোষণা থেকে একদিন ভিন্ন হতে পারে।',
    'eid_fitr.lunar_title': '🌙 চাঁদের সাথে সংযোগ',
    'eid_fitr.lunar_current': 'চাঁদের বর্তমান দশা:',
    'eid_fitr.lunar_link_today': '🌙 আজকের চাঁদের অবস্থা →',
    'eid_fitr.lunar_link_new_moon': '🌑 পরবর্তী অমাবস্যা →',
    'eid_fitr.lunar_link_crescent': '🌒 পরবর্তী শাওয়াল হিলাল →',
    'eid_fitr.years_title': '📅 আগামী বছরগুলিতে ঈদুল ফিতরের তারিখ',
    'eid_fitr.years_col_hijri': 'হিজরি সাল',
    'eid_fitr.years_col_greg': 'গ্রেগরিয়ান সাল',
    'eid_fitr.years_col_start': 'ঈদুল ফিতর (অনুমানিত)',
    'eid_fitr.years_col_note': 'মন্তব্য',
    'eid_fitr.years_note': '* সমস্ত তারিখ জ্যোতির্বিদ্যাগত অনুমান এবং রূয়ত অনুসারে একদিন ভিন্ন হতে পারে।',
    'eid_fitr.years_note_cell': 'অনুমানিত · রূয়তের উপর নির্ভরশীল',
    'eid_fitr.cities_title': '🌍 বিশ্বজুড়ে ঈদুল ফিতর',
    'eid_fitr.city_sa': 'সৌদি আরবে ঈদুল ফিতর',
    'eid_fitr.city_eg': 'মিশরে ঈদুল ফিতর',
    'eid_fitr.city_ae': 'আরব আমিরাতে ঈদুল ফিতর',
    'eid_fitr.city_uk': 'লন্ডনে ঈদুল ফিতর',
    'eid_fitr.city_tr': 'ইস্তাম্বুলে ঈদুল ফিতর',
    'eid_fitr.city_id': 'জাকার্তায় ঈদুল ফিতর',
    'eid_fitr.faq_title': '❓ ঈদুল ফিতর সম্পর্কে সাধারণ প্রশ্ন',
    'eid_fitr.faq_q1': 'ঈদুল ফিতরে আসতে কতদিন বাকি?',
    'eid_fitr.faq_a1': 'প্রত্যাশিত ঈদুল ফিতর পর্যন্ত {n} দিন বাকি।',
    'eid_fitr.faq_q2': 'এই বছর ঈদুল ফিতর কখন?',
    'eid_fitr.faq_a2': 'ঈদুল ফিতর {hyear} হিজরি অনুমানিকভাবে {date} তারিখে পড়ে।',
    'eid_fitr.faq_q3': 'ঈদুল ফিতরের হিজরি তারিখ কী?',
    'eid_fitr.faq_a3': 'এটি শাওয়াল {hyear} হিজরির প্রথম দিনের সাথে মিল রাখে।',
    'eid_fitr.faq_q4': 'ঈদুল ফিতরের তারিখ কি দেশভেদে ভিন্ন হতে পারে?',
    'eid_fitr.faq_a4': 'হ্যাঁ, স্থানীয় শাওয়াল হিলাল দেখা অনুসারে এটি একদিন ভিন্ন হতে পারে।',
    'eid_fitr.faq_q5': 'ঈদুল ফিতর কীভাবে নির্ধারিত হয়?',
    'eid_fitr.faq_a5': 'রমজানের ২৯তম দিনের সূর্যাস্তের পর শাওয়াল হিলাল দেখে, অথবা রমজান ৩০ দিন পূর্ণ করে।',
    'eid_fitr.faq_q6': 'ঈদুল ফিতর ও শাওয়াল হিলালের সম্পর্ক কী?',
    'eid_fitr.faq_a6': 'ঈদুল ফিতর শাওয়ালের সূচনার সাথে শুরু হয় যা হিলাল দেখে নির্ধারিত হয়, তাই জ্যোতির্বিদ্যাগত গণনা থেকে কখনো একদিন ভিন্ন হতে পারে।',
    'eid_fitr.faq_q7': 'দেখানো তারিখ কি চূড়ান্ত নাকি অনুমানিত?',
    'eid_fitr.faq_a7': 'এটি জ্যোতির্বিদ্যাগত অনুমান; চূড়ান্ত আনুষ্ঠানিক ঘোষণা প্রতিটি দেশের ধর্মীয় কর্তৃপক্ষ থেকে আসে।',
    'eid_fitr.faq_q8': 'ঈদুল ফিতর কতদিন স্থায়ী হয়?',
    'eid_fitr.faq_a8': 'ঈদের প্রথম দিন ১ শাওয়াল, এবং বেশিরভাগ মুসলিম দেশে ৩ দিন উদযাপিত হয়।',
    'eid_fitr.faq_q9': 'ঈদুল ফিতরের প্রধান ইবাদতগুলি কী?',
    'eid_fitr.faq_a9': 'ঈদের নামাজ, নামাজের আগে ফিতরা আদায়, তাকবির, আত্মীয়দের দেখা এবং শুভেচ্ছা বিনিময়।',
    'eid_fitr.faq_q10': 'প্রতিটি গ্রেগরিয়ান বছরে ঈদুল ফিতরের তারিখ কেন পরিবর্তন হয়?',
    'eid_fitr.faq_a10': 'কারণ হিজরি চান্দ্র বছর গ্রেগরিয়ান বছরের চেয়ে প্রায় ১০-১১ দিন ছোট, ঈদ প্রতি বছর একই পরিমাণ এগিয়ে যায়।',
    'eid_fitr.info_title': '📖 ঈদুল ফিতর সম্পর্কে',
    'eid_fitr.info_h1': 'ঈদুল ফিতর কী',
    'eid_fitr.info_h1_body': 'ঈদুল ফিতর ইসলামের দুটি ঈদের একটি, যা রমজানের রোজা সম্পূর্ণ করার পর আসে এবং ১ শাওয়ালে শুরু হয়। এতে তাকবির, ঈদের নামাজ, নামাজের আগে ফিতরা, এবং শুভেচ্ছা বিনিময় অন্তর্ভুক্ত।',
    'eid_fitr.info_h2': 'ঈদুল ফিতর কীভাবে নিশ্চিত হয়',
    'eid_fitr.info_h2_body': 'ঈদুল ফিতর দুটি উপায়ে নিশ্চিত হয়: রমজানের ২৯তম দিনের সূর্যাস্তের পর শাওয়াল হিলাল দেখে, অথবা হিলাল না দেখলে রমজানের ৩০ দিন পূর্ণ করে।',
    'eid_fitr.info_h3': 'প্রতিটি গ্রেগরিয়ান বছরে ঈদুল ফিতর কেন এগিয়ে যায়',
    'eid_fitr.info_h3_body': 'হিজরি চান্দ্র বছর গ্রেগরিয়ান বছরের চেয়ে প্রায় ১০-১১ দিন ছোট, তাই ঈদুল ফিতর প্রতি বছর একই পরিমাণ এগিয়ে যায় এবং প্রায় ৩৩ বছরে সমস্ত ঋতু ভ্রমণ করে।',
    'eid_fitr.links_title': '🔗 সম্পর্কিত লিঙ্ক',
    'eid_fitr.link_ramadan': '🕋 রমজান আসতে কতদিন বাকি',
    'eid_fitr.link_adha': '🐑 ঈদুল আজহা আসতে কতদিন বাকি',
    'eid_fitr.link_new_year': '📅 নতুন হিজরি বছর আসতে কতদিন বাকি',
    'eid_fitr.link_moon': '🌙 আজকের চাঁদের অবস্থা',
    'eid_fitr.link_hijri_today': '📅 আজকের হিজরি তারিখ',
},

ms: {
    'eid_fitr.h1': '🌙 Berapa hari lagi Aidilfitri?',
    'eid_fitr.intro': 'Ketahui hari-hari yang tinggal sehingga Aidilfitri yang diberkati dengan tarikh Masihi dan Hijrah jangkaan. Hari raya mungkin berbeza sehari mengikut rukyah hilal Syawal di negara anda.',
    'eid_fitr.event_name': 'Aidilfitri',
    'eid_fitr.hijri_1': '1 Syawal',
    'eid_fitr.meta_title': '🌙 Berapa hari lagi Aidilfitri? — Tarikh jangkaan dan kira detik',
    'eid_fitr.meta_desc': 'Kira detik tepat sehingga Aidilfitri yang diberkati — dalam hari, jam dan minit — dengan tarikh Masihi dan Hijrah.',
    'eid_fitr.cards_title': '📋 Maklumat utama',
    'eid_fitr.card1_title': 'Aidilfitri jangkaan',
    'eid_fitr.card2_title': 'Tarikh Hijrah',
    'eid_fitr.card3_title': 'Hari tinggal',
    'eid_fitr.card4_title': 'Status',
    'eid_fitr.card4_value': 'Dikira · menunggu rukyah',
    'eid_fitr.notice_title': '📜 Pengesahan tarikh',
    'eid_fitr.notice_body': 'Aidilfitri berkait dengan rukyah hilal Syawal selepas melengkapkan 29 atau 30 hari Ramadan. Tarikh yang dipaparkan dikira secara astronomi dan boleh berbeza sehari dari pengumuman rasmi.',
    'eid_fitr.lunar_title': '🌙 Hubungan lunar',
    'eid_fitr.lunar_current': 'Fasa Bulan semasa:',
    'eid_fitr.lunar_link_today': '🌙 Status Bulan hari ini →',
    'eid_fitr.lunar_link_new_moon': '🌑 Bulan baru seterusnya →',
    'eid_fitr.lunar_link_crescent': '🌒 Hilal Syawal seterusnya →',
    'eid_fitr.years_title': '📅 Tarikh Aidilfitri untuk tahun-tahun akan datang',
    'eid_fitr.years_col_hijri': 'Tahun Hijrah',
    'eid_fitr.years_col_greg': 'Tahun Masihi',
    'eid_fitr.years_col_start': 'Aidilfitri (anggaran)',
    'eid_fitr.years_col_note': 'Catatan',
    'eid_fitr.years_note': '* Semua tarikh adalah anggaran astronomi dan boleh berbeza sehari mengikut rukyah.',
    'eid_fitr.years_note_cell': 'Anggaran · bergantung kepada rukyah',
    'eid_fitr.cities_title': '🌍 Aidilfitri di seluruh dunia',
    'eid_fitr.city_sa': 'Aidilfitri di Arab Saudi',
    'eid_fitr.city_eg': 'Aidilfitri di Mesir',
    'eid_fitr.city_ae': 'Aidilfitri di UAE',
    'eid_fitr.city_uk': 'Aidilfitri di London',
    'eid_fitr.city_tr': 'Aidilfitri di Istanbul',
    'eid_fitr.city_id': 'Aidilfitri di Jakarta',
    'eid_fitr.faq_title': '❓ Soalan lazim tentang Aidilfitri',
    'eid_fitr.faq_q1': 'Berapa hari lagi Aidilfitri?',
    'eid_fitr.faq_a1': 'Tinggal {n} hari lagi sebelum Aidilfitri jangkaan.',
    'eid_fitr.faq_q2': 'Bilakah Aidilfitri tahun ini?',
    'eid_fitr.faq_a2': 'Aidilfitri {hyear} H jatuh pada {date} secara anggaran.',
    'eid_fitr.faq_q3': 'Apakah tarikh Hijrah Aidilfitri?',
    'eid_fitr.faq_a3': 'Ia bersamaan dengan hari pertama Syawal {hyear} H.',
    'eid_fitr.faq_q4': 'Adakah tarikh Aidilfitri boleh berbeza antara negara?',
    'eid_fitr.faq_a4': 'Ya, ia boleh berbeza sehari mengikut rukyah hilal Syawal tempatan.',
    'eid_fitr.faq_q5': 'Bagaimana Aidilfitri ditentukan?',
    'eid_fitr.faq_a5': 'Melalui rukyah hilal Syawal selepas matahari terbenam pada hari ke-29 Ramadan, atau menyempurnakan Ramadan kepada 30 hari.',
    'eid_fitr.faq_q6': 'Apakah hubungan Aidilfitri dengan hilal Syawal?',
    'eid_fitr.faq_a6': 'Aidilfitri bermula dengan permulaan Syawal yang ditetapkan oleh rukyah hilal, jadi kadangkala berbeza sehari dari pengiraan astronomi.',
    'eid_fitr.faq_q7': 'Adakah tarikh yang dipaparkan muktamad atau jangkaan?',
    'eid_fitr.faq_a7': 'Ini adalah anggaran astronomi; pengumuman rasmi muktamad dikeluarkan oleh pihak berkuasa agama setiap negara.',
    'eid_fitr.faq_q8': 'Berapa lama Aidilfitri berlangsung?',
    'eid_fitr.faq_a8': 'Hari pertama Aidilfitri ialah 1 Syawal, dan di kebanyakan negara Islam ia berlangsung 3 hari.',
    'eid_fitr.faq_q9': 'Apakah ritual utama Aidilfitri?',
    'eid_fitr.faq_a9': 'Solat Hari Raya, zakat fitrah sebelum solat, takbir, ziarah saudara-mara dan bertukar ucapan.',
    'eid_fitr.faq_q10': 'Mengapakah tarikh Aidilfitri berubah setiap tahun Masihi?',
    'eid_fitr.faq_a10': 'Kerana tahun Hijrah qamari lebih pendek kira-kira 10-11 hari daripada tahun Masihi, Aidilfitri bergerak ke hadapan jumlah yang sama setiap tahun.',
    'eid_fitr.info_title': '📖 Tentang Aidilfitri',
    'eid_fitr.info_h1': 'Apakah itu Aidilfitri',
    'eid_fitr.info_h1_body': 'Aidilfitri adalah salah satu daripada dua hari raya Islam yang datang selepas menyempurnakan puasa Ramadan, bermula pada 1 Syawal. Ia merangkumi takbir, solat hari raya, zakat fitrah sebelum solat, dan bertukar ucapan.',
    'eid_fitr.info_h2': 'Bagaimana Aidilfitri disahkan',
    'eid_fitr.info_h2_body': 'Aidilfitri disahkan dengan dua cara: rukyah hilal Syawal selepas matahari terbenam pada hari ke-29 Ramadan, atau jika hilal tidak kelihatan, dengan menyempurnakan Ramadan kepada 30 hari.',
    'eid_fitr.info_h3': 'Mengapakah Aidilfitri bergerak ke hadapan setiap tahun Masihi',
    'eid_fitr.info_h3_body': 'Tahun Hijrah qamari lebih pendek kira-kira 10-11 hari daripada tahun Masihi, jadi Aidilfitri bergerak ke hadapan jumlah yang sama setiap tahun dan melalui semua musim setiap ~33 tahun.',
    'eid_fitr.links_title': '🔗 Pautan berkaitan',
    'eid_fitr.link_ramadan': '🕋 Berapa hari lagi Ramadan',
    'eid_fitr.link_adha': '🐑 Berapa hari lagi Aidiladha',
    'eid_fitr.link_new_year': '📅 Berapa hari lagi Tahun Baru Hijrah',
    'eid_fitr.link_moon': '🌙 Status Bulan hari ini',
    'eid_fitr.link_hijri_today': '📅 Tarikh Hijrah hari ini',
},

};

// ========================================================================
// Because the file grew too large, I'm splitting eid-al-adha and hijri-new-year
// into a continuation file loaded dynamically. Instead, I'll inline compact
// sets by copying the eid_fitr pattern but substituting event-specific text.
// ========================================================================

// The remaining events (eid-al-adha, hijri-new-year) are defined below...

TR['eid-al-adha'] = require('./_add_3events_adha.js');
TR['hijri-new-year'] = require('./_add_3events_ny.js');

// === Helpers to generate HTML block from Ramadan template ===

const RAM_TO_EVENT_MAPPING = {
    'ramadan': {
        h1Emoji: '🕋',
    }
};

function generateHtmlBlock(event, ramadanBlock) {
    let html = ramadanBlock;

    // Page-level substitutions
    html = html.replace(/id="page-ramadan-countdown"/g, `id="${event.pageId}"`);
    html = html.replace(/class="page countdown-page cd-ramadan"/g, `class="page countdown-page ${event.htmlClass}"`);

    // ID prefix: ram- → fitr- / adha- / ny-
    html = html.replace(/id="ram-/g, `id="${event.idPrefix}-`);
    html = html.replace(/id="ramadan-timer"/g, `id="${event.timerId}"`);

    // FAQ container ID was ram-faq-list → keeps the same pattern
    // Years container: ram-years-table / ram-years-tbody → also handled by idPrefix replacement above

    // data-i18n: ramadan.X → eid_fitr.X / eid_adha.X / hijri_ny.X
    // Also countdown.X keys stay as-is (shared)
    html = html.replace(/data-i18n="ramadan\./g, `data-i18n="${event.keyPrefix}.`);

    // Inline default text: substitute using AR translations of the NEW event
    // Parse each data-i18n attribute and replace the inline text with the AR value for the target event.
    const arDict = TR[event.id].ar;
    html = html.replace(/data-i18n="([^"]+)"([^>]*)>([^<]*)</g, (match, key, attrs, innerText) => {
        if (arDict[key]) {
            return `data-i18n="${key}"${attrs}>${arDict[key]}<`;
        }
        return match;
    });

    // Update internal href links — for eid-al-fitr page, link to ramadan/adha/ny; not to itself
    // The links section IDs: ramadan.link_eid_fitr/link_eid_adha/link_new_year become
    //                       eid_fitr.link_ramadan/link_adha/link_new_year
    // Since we substituted data-i18n="ramadan.link_eid_fitr" → "eid_fitr.link_eid_fitr", this is WRONG.
    // The key names are different per event.
    // Workaround: after substitution, manually remap link keys and hrefs for each event.

    // Step: remap link-keys per event
    if (event.id === 'eid-al-fitr') {
        html = html.replace(/data-i18n="eid_fitr\.link_eid_fitr"/g, 'data-i18n="eid_fitr.link_ramadan"');
        html = html.replace(/data-i18n="eid_fitr\.link_eid_adha"/g, 'data-i18n="eid_fitr.link_adha"');
        // link_new_year / link_moon / link_hijri_today stay same (but namespaced)
        // hrefs: /eid-al-fitr-countdown was originally the target; we want /ramadan-countdown for link_ramadan
        html = html.replace(/href="\/eid-al-fitr-countdown"([^>]*)data-i18n="eid_fitr\.link_ramadan"/g, 'href="/ramadan-countdown"$1data-i18n="eid_fitr.link_ramadan"');
    } else if (event.id === 'eid-al-adha') {
        html = html.replace(/data-i18n="eid_adha\.link_eid_fitr"/g, 'data-i18n="eid_adha.link_ramadan"');
        html = html.replace(/data-i18n="eid_adha\.link_eid_adha"/g, 'data-i18n="eid_adha.link_fitr"');
        html = html.replace(/href="\/eid-al-fitr-countdown"([^>]*)data-i18n="eid_adha\.link_ramadan"/g, 'href="/ramadan-countdown"$1data-i18n="eid_adha.link_ramadan"');
        html = html.replace(/href="\/eid-al-adha-countdown"([^>]*)data-i18n="eid_adha\.link_fitr"/g, 'href="/eid-al-fitr-countdown"$1data-i18n="eid_adha.link_fitr"');
    } else if (event.id === 'hijri-new-year') {
        html = html.replace(/data-i18n="hijri_ny\.link_eid_fitr"/g, 'data-i18n="hijri_ny.link_ramadan"');
        html = html.replace(/data-i18n="hijri_ny\.link_eid_adha"/g, 'data-i18n="hijri_ny.link_fitr"');
        html = html.replace(/data-i18n="hijri_ny\.link_new_year"/g, 'data-i18n="hijri_ny.link_adha"');
        html = html.replace(/href="\/eid-al-fitr-countdown"([^>]*)data-i18n="hijri_ny\.link_ramadan"/g, 'href="/ramadan-countdown"$1data-i18n="hijri_ny.link_ramadan"');
        html = html.replace(/href="\/eid-al-adha-countdown"([^>]*)data-i18n="hijri_ny\.link_fitr"/g, 'href="/eid-al-fitr-countdown"$1data-i18n="hijri_ny.link_fitr"');
        html = html.replace(/href="\/hijri-new-year-countdown"([^>]*)data-i18n="hijri_ny\.link_adha"/g, 'href="/eid-al-adha-countdown"$1data-i18n="hijri_ny.link_adha"');
    }

    // Remove the pre-Ramadan section for non-Ramadan events (section 5)
    // That section has class "countdown-pre" and is specific to Shaaban month tracking
    html = html.replace(/\s*<!-- \(5\) Pre-Ramadan section -->[\s\S]*?<\/section>\s*(?=\s*<!-- \(6\))/m,
        '\n                <!-- (5) Pre-event section omitted for ' + event.id + ' -->\n');

    // SECOND text-substitution pass: after link-key remapping above, some inner texts
    // were missed (because the original key wasn't in arDict). Re-apply AR dict now
    // that keys are finalized. This fixes static SEO text for the links section.
    html = html.replace(/data-i18n="([^"]+)"([^>]*)>([^<]*)</g, (match, key, attrs, innerText) => {
        if (arDict[key]) {
            return `data-i18n="${key}"${attrs}>${arDict[key]}<`;
        }
        return match;
    });

    return html;
}

// === Script main ===

module.exports = { EVENTS, TR, generateHtmlBlock };

if (require.main === module) {
    console.log('This file is a library. Run _add_3events_run.js to perform the generation.');
}
