// Phase E2-content-balance-Hub — clean up text in ALL 10 langs to restore
// Keyword Consistency on /moon-today after E2-content-depth-Hub.
//
// Problem (per SEOptimer report after content-depth deploy):
//   • "الإضاءة" appeared 9× → SEOptimer treated as a noisy keyword and asked
//     it to be present in Title/Meta/headings (which it isn't).
//   • "إلى" appeared too many times in DEPTH paragraphs → same issue.
//   • "مكة المكرمة" appeared 6× on a generic Hub page → over-emphasized.
//
// Fix: re-balance the AR text using natural synonyms. ALSO apply parallel
// re-balancing to all 9 other langs so the change is consistent across
// languages (and protects against the same SEOptimer issue if other langs
// are audited).
//
// Per user spec:
//   • Rename SEC2_H2 to literal "موعد بدر قمر مكتمل والطور القادم" (and parallel
//     "(Badr) ... Upcoming Phase" naming in 9 other langs)
//   • Reduce "illumination" / "الإضاءة" / equivalents (use synonyms)
//   • Reduce "to" / "إلى" / equivalents in DEPTH paragraphs
//   • Reduce "Mecca" / "مكة المكرمة" 2× → 1× in SEC3_P
//   • Keep page word count ≥ 729 (E2-content-depth gain)
//
// Hard rules (UNCHANGED):
//   • NO change to Title / Meta / H1 / month H2
//   • NO change to city pages
//   • NO new sections, NO removed sections — pure text re-balancing
//   • Same clean code style as prior phases

import { readFileSync, writeFileSync } from 'node:fs';

const PATH = 'C:\\Users\\Tarek\\Downloads\\TIME PRAYER\\server.js';
let raw = readFileSync(PATH, 'utf8');
const isCRLF = /\r\n/.test(raw);
const EOL = isCRLF ? '\r\n' : '\n';

if (/E2-content-balance-Hub/.test(raw)) {
    throw new Error('[server.js] balance script already ran (header marker present)');
}

// ─── Helper: idempotent block replacement with uniqueness check ───
function replaceBlock(label, oldStr, newStr) {
    const cnt = raw.split(oldStr).length - 1;
    if (cnt !== 1) throw new Error(`[${label}] expected 1 match, got ${cnt}`);
    raw = raw.replace(oldStr, newStr);
    console.log(`✓ ${label}`);
}

// Helper: serialize a per-lang object literal (matches existing format)
function _serializeLangMap(varName, obj, indent = '            ') {
    const inner = '                ';
    return `${indent}const ${varName} = {${EOL}` +
        Object.entries(obj).map(([lang, txt]) => {
            const esc = txt.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
            return `${inner}    ${lang}: '${esc}',`;
        }).join(EOL) + EOL +
        `${inner}};`;
}

// ═════════════════════════════════════════════════════════════════════════
// 1) SEC2_H2 (Badr H2): rename in all 10 langs to make "Full Moon (Badr)
//    Date and Upcoming Phase" the literal heading text.
// ═════════════════════════════════════════════════════════════════════════
const SEC2_H2_NEW = {
    ar: 'موعد بدر قمر مكتمل والطور القادم',
    en: 'Next Full Moon (Badr) Date and Upcoming Phase',
    fr: 'Date de la prochaine pleine lune (Badr) et phase à venir',
    tr: 'Sıradaki Dolunay (Badr) Tarihi ve Yaklaşan Evre',
    ur: 'اگلے بدر مکمل چاند کی تاریخ اور آنے والا مرحلہ',
    de: 'Nächstes Vollmond-Datum (Badr) und kommende Phase',
    id: 'Tanggal Purnama (Badr) Berikutnya dan Fase Mendatang',
    es: 'Próxima fecha de luna llena (Badr) y fase venidera',
    bn: 'পরবর্তী পূর্ণিমা (বদর) তারিখ ও আসন্ন পর্যায়',
    ms: 'Tarikh Bulan Purnama (Badr) Seterusnya dan Fasa Akan Datang',
};

const SEC2_H2_OLD_BLOCK = [
`            const _hubSec2H2 = {`,
`                    ar: 'موعد البدر القادم والقمر المكتمل',`,
`                    en: 'Next Full Moon Date and Full Moon Stage',`,
`                    fr: 'Date de la prochaine pleine lune et étape',`,
`                    tr: 'Sıradaki Dolunay Tarihi ve Dolunay Aşaması',`,
`                    ur: 'اگلے بدر کی تاریخ اور مکمل چاند کا مرحلہ',`,
`                    de: 'Nächstes Vollmond-Datum und Vollmondphase',`,
`                    id: 'Tanggal Purnama Berikutnya dan Tahap Bulan Purnama',`,
`                    es: 'Próxima fecha de luna llena y etapa',`,
`                    bn: 'পরবর্তী পূর্ণিমার তারিখ ও পূর্ণ চাঁদের পর্যায়',`,
`                    ms: 'Tarikh Bulan Purnama Seterusnya dan Peringkat Purnama',`,
`                };`,
].join(EOL);
replaceBlock('SEC2_H2 (Badr H2 — 10 langs)', SEC2_H2_OLD_BLOCK, _serializeLangMap('_hubSec2H2', SEC2_H2_NEW));

// ═════════════════════════════════════════════════════════════════════════
// 2) SEC1_P (E2-final phase paragraph): reduce repetition of
//    "illumination/الإضاءة/iluminasi/etc." across all 10 langs.
//    Strategy: keep one mention of "lit/illuminated portion", replace the
//    other repetition with a synonym.
// ═════════════════════════════════════════════════════════════════════════
const SEC1_P_NEW = {
    ar: 'تعرض صفحة حالة القمر اليوم الطور الحالي للقمر ومقدار الضوء الظاهر وعمر القمر منذ آخر محاق. يتغير طور القمر يومياً بحسب موقعه بالنسبة للشمس والأرض، لذلك تساعد هذه الصفحة على متابعة التغير اليومي في شكل القمر وحركته خلال الشهر الهجري. تشمل بيانات القمر اليوم: النسبة المضيئة الحالية، عمر القمر بالأيام، المسافة بين الأرض والقمر بالكيلومترات، ومواعيد طلوع القمر وغروبه التقريبية.',
    en: "This page shows today's moon phase, the visible lit portion, and the moon's age since the last new moon. The moon phase changes daily based on the moon's position relative to the Sun and Earth, so this page helps you track the daily change in the moon's shape and motion throughout the Hijri month. Today's moon data includes: the current bright portion, moon age in days, the Earth-moon distance in kilometers, and approximate moonrise and moonset times.",
    fr: "Cette page affiche la phase actuelle de la Lune aujourd'hui, la partie éclairée visible et l'âge de la Lune depuis la dernière nouvelle lune. La phase lunaire change quotidiennement selon la position de la Lune par rapport au Soleil et à la Terre, ce qui permet de suivre l'évolution quotidienne de la forme de la Lune et son mouvement durant le mois hégirien. Les données incluent la partie éclairée actuelle, l'âge de la Lune en jours, la distance Terre-Lune en kilomètres, et les heures approximatives de lever et coucher.",
    tr: 'Bu sayfa, ayın bugünkü mevcut evresini, görünen aydınlık kısmı ve son yeni aydan bu yana ayın yaşını gösterir. Ay evresi, Güneş ve Dünya\'ya göre konumuna bağlı olarak günlük değişir, bu nedenle bu sayfa hicri ay boyunca ayın şeklindeki günlük değişimi ve hareketini takip etmenize yardımcı olur. Bugünkü ay verileri şunları içerir: güncel parlak kısım, gün olarak ay yaşı, kilometre cinsinden Dünya-Ay mesafesi ve yaklaşık ay doğuşu ve batış saatleri.',
    ur: 'یہ صفحہ آج چاند کا موجودہ مرحلہ، روشن نظر آنے والا حصہ، اور آخری نئے چاند سے چاند کی عمر دکھاتا ہے۔ چاند کا مرحلہ سورج اور زمین کے نسبت اس کی پوزیشن کے مطابق روزانہ تبدیل ہوتا ہے، اس لیے یہ صفحہ ہجری مہینے کے دوران چاند کی شکل میں روزانہ تبدیلی اور اس کی حرکت کا پتہ لگانے میں مدد کرتا ہے۔ آج کے چاند کا ڈیٹا شامل ہے: موجودہ روشن حصہ، دنوں میں چاند کی عمر، کلومیٹر میں زمین چاند فاصلہ، اور تقریبی طلوع و غروب کے اوقات۔',
    de: 'Diese Seite zeigt die heutige Mondphase, den sichtbaren beleuchteten Teil und das Alter des Mondes seit dem letzten Neumond. Die Mondphase ändert sich täglich je nach Position des Mondes relativ zur Sonne und Erde, weshalb diese Seite Ihnen hilft, die tägliche Veränderung der Mondform und seine Bewegung während des Hidschri-Monats zu verfolgen. Die heutigen Monddaten umfassen den aktuellen hellen Teil, das Mondalter in Tagen, die Erde-Mond-Entfernung in Kilometern und ungefähre Mondaufgangs- und Untergangszeiten.',
    id: 'Halaman ini menampilkan fase Bulan saat ini hari ini, bagian yang terlihat terang, dan usia Bulan sejak bulan baru terakhir. Fase Bulan berubah setiap hari tergantung posisinya relatif terhadap Matahari dan Bumi, sehingga halaman ini membantu Anda melacak perubahan harian dalam bentuk Bulan dan pergerakannya selama bulan Hijriah. Data Bulan hari ini meliputi: bagian terang saat ini, usia Bulan dalam hari, jarak Bumi-Bulan dalam kilometer, dan perkiraan waktu terbit dan terbenam Bulan.',
    es: 'Esta página muestra la fase actual de la Luna hoy, la parte iluminada visible y la edad de la Luna desde la última luna nueva. La fase lunar cambia diariamente según su posición respecto al Sol y a la Tierra, por lo que esta página le ayuda a seguir el cambio diario en la forma de la Luna y su movimiento durante el mes hijri. Los datos lunares de hoy incluyen la parte brillante actual, la edad de la Luna en días, la distancia Tierra-Luna en kilómetros y los horarios aproximados de salida y puesta.',
    bn: 'এই পৃষ্ঠাটি আজকের চাঁদের বর্তমান দশা, দৃশ্যমান আলোকিত অংশ, এবং সর্বশেষ অমাবস্যা থেকে চাঁদের বয়স প্রদর্শন করে। চাঁদের দশা সূর্য এবং পৃথিবীর সাপেক্ষে এর অবস্থানের উপর নির্ভর করে প্রতিদিন পরিবর্তন হয়, তাই এই পৃষ্ঠাটি হিজরি মাস জুড়ে চাঁদের আকারে দৈনিক পরিবর্তন এবং এর গতি ট্র্যাক করতে সাহায্য করে। আজকের চাঁদের তথ্যের মধ্যে রয়েছে: বর্তমান উজ্জ্বল অংশ, দিনের হিসেবে চাঁদের বয়স, কিলোমিটারে পৃথিবী-চাঁদ দূরত্ব এবং চাঁদের আনুমানিক উদয় ও অস্তের সময়।',
    ms: 'Halaman ini memaparkan fasa Bulan semasa hari ini, bahagian terang yang kelihatan, dan usia Bulan sejak anak bulan terakhir. Fasa Bulan berubah setiap hari bergantung pada kedudukannya berbanding Matahari dan Bumi, jadi halaman ini membantu anda mengikuti perubahan harian dalam bentuk Bulan dan pergerakannya sepanjang bulan Hijrah. Data Bulan hari ini meliputi: bahagian terang semasa, usia Bulan dalam hari, jarak Bumi-Bulan dalam kilometer, dan waktu terbit dan terbenam Bulan yang anggaran.',
};

const SEC1_P_OLD_BLOCK = [
`            const _hubSec1P  = {`,
`                    ar: 'تعرض صفحة حالة القمر اليوم الطور الحالي للقمر ونسبة الإضاءة وعمر القمر منذ آخر محاق. يتغير طور القمر يومياً بحسب موقعه بالنسبة إلى الشمس والأرض، لذلك تساعد هذه الصفحة على متابعة التغير اليومي في شكل القمر وحركته خلال الشهر الهجري. تشمل بيانات القمر اليوم: نسبة الإضاءة الحالية، عمر القمر بالأيام، المسافة بين الأرض والقمر بالكيلومترات، ومواعيد طلوع القمر وغروبه التقريبية.',`,
`                    en: 'This page shows today\\'s moon phase, the current illumination percentage, and the moon\\'s age since the last new moon. The moon phase changes daily based on the moon\\'s position relative to the Sun and Earth, so this page helps you track the daily change in the moon\\'s shape and motion throughout the Hijri month. Today\\'s moon data includes: current illumination percentage, moon age in days, the Earth-moon distance in kilometers, and approximate moonrise and moonset times.',`,
`                    fr: 'Cette page affiche la phase actuelle de la Lune aujourd\\'hui, le pourcentage d\\'illumination et l\\'âge de la Lune depuis la dernière nouvelle lune. La phase lunaire change quotidiennement selon la position de la Lune par rapport au Soleil et à la Terre, ce qui permet de suivre l\\'évolution quotidienne de la forme de la Lune et son mouvement durant le mois hégirien. Les données incluent le pourcentage d\\'illumination actuel, l\\'âge de la Lune en jours, la distance Terre-Lune en kilomètres, et les heures approximatives de lever et coucher.',`,
`                    tr: 'Bu sayfa, ayın bugünkü mevcut evresini, aydınlanma yüzdesini ve son yeni aydan bu yana ayın yaşını gösterir. Ay evresi, Güneş ve Dünya\\'ya göre konumuna bağlı olarak günlük değişir, bu nedenle bu sayfa hicri ay boyunca ayın şeklindeki günlük değişimi ve hareketini takip etmenize yardımcı olur. Bugünkü ay verileri şunları içerir: güncel aydınlanma yüzdesi, gün olarak ay yaşı, kilometre cinsinden Dünya-Ay mesafesi ve yaklaşık ay doğuşu ve batış saatleri.',`,
`                    ur: 'یہ صفحہ آج چاند کا موجودہ مرحلہ، روشنی کا فیصد، اور آخری نئے چاند سے چاند کی عمر دکھاتا ہے۔ چاند کا مرحلہ سورج اور زمین کے نسبت اس کی پوزیشن کے مطابق روزانہ تبدیل ہوتا ہے، اس لیے یہ صفحہ ہجری مہینے کے دوران چاند کی شکل میں روزانہ تبدیلی اور اس کی حرکت کا پتہ لگانے میں مدد کرتا ہے۔ آج کے چاند کا ڈیٹا شامل ہے: موجودہ روشنی کا فیصد، دنوں میں چاند کی عمر، کلومیٹر میں زمین چاند فاصلہ، اور تقریبی طلوع و غروب کے اوقات۔',`,
`                    de: 'Diese Seite zeigt die heutige Mondphase, den aktuellen Beleuchtungsprozentsatz und das Alter des Mondes seit dem letzten Neumond. Die Mondphase ändert sich täglich je nach Position des Mondes relativ zur Sonne und Erde, weshalb diese Seite Ihnen hilft, die tägliche Veränderung der Mondform und seine Bewegung während des Hidschri-Monats zu verfolgen. Die heutigen Monddaten umfassen den aktuellen Beleuchtungsprozentsatz, das Mondalter in Tagen, die Erde-Mond-Entfernung in Kilometern und ungefähre Mondaufgangs- und Untergangszeiten.',`,
`                    id: 'Halaman ini menampilkan fase Bulan saat ini hari ini, persentase iluminasi, dan usia Bulan sejak bulan baru terakhir. Fase Bulan berubah setiap hari tergantung posisinya relatif terhadap Matahari dan Bumi, sehingga halaman ini membantu Anda melacak perubahan harian dalam bentuk Bulan dan pergerakannya selama bulan Hijriah. Data Bulan hari ini meliputi: persentase iluminasi saat ini, usia Bulan dalam hari, jarak Bumi-Bulan dalam kilometer, dan perkiraan waktu terbit dan terbenam Bulan.',`,
`                    es: 'Esta página muestra la fase actual de la Luna hoy, el porcentaje de iluminación y la edad de la Luna desde la última luna nueva. La fase lunar cambia diariamente según su posición respecto al Sol y a la Tierra, por lo que esta página le ayuda a seguir el cambio diario en la forma de la Luna y su movimiento durante el mes hijri. Los datos lunares de hoy incluyen el porcentaje de iluminación actual, la edad de la Luna en días, la distancia Tierra-Luna en kilómetros y los horarios aproximados de salida y puesta.',`,
`                    bn: 'এই পৃষ্ঠাটি আজকের চাঁদের বর্তমান দশা, আলোকন শতাংশ, এবং সর্বশেষ অমাবস্যা থেকে চাঁদের বয়স প্রদর্শন করে। চাঁদের দশা সূর্য এবং পৃথিবীর সাপেক্ষে এর অবস্থানের উপর নির্ভর করে প্রতিদিন পরিবর্তন হয়, তাই এই পৃষ্ঠাটি হিজরি মাস জুড়ে চাঁদের আকারে দৈনিক পরিবর্তন এবং এর গতি ট্র্যাক করতে সাহায্য করে। আজকের চাঁদের তথ্যের মধ্যে রয়েছে: বর্তমান আলোকন শতাংশ, দিনের হিসেবে চাঁদের বয়স, কিলোমিটারে পৃথিবী-চাঁদ দূরত্ব এবং চাঁদের আনুমানিক উদয় ও অস্তের সময়।',`,
`                    ms: 'Halaman ini memaparkan fasa Bulan semasa hari ini, peratus pencahayaan, dan usia Bulan sejak anak bulan terakhir. Fasa Bulan berubah setiap hari bergantung pada kedudukannya berbanding Matahari dan Bumi, jadi halaman ini membantu anda mengikuti perubahan harian dalam bentuk Bulan dan pergerakannya sepanjang bulan Hijrah. Data Bulan hari ini meliputi: peratus pencahayaan semasa, usia Bulan dalam hari, jarak Bumi-Bulan dalam kilometer, dan waktu terbit dan terbenam Bulan yang anggaran.',`,
`                };`,
].join(EOL);
replaceBlock('SEC1_P (phase paragraph — 10 langs)', SEC1_P_OLD_BLOCK, _serializeLangMap('_hubSec1P ', SEC1_P_NEW));

// ═════════════════════════════════════════════════════════════════════════
// 3) SEC3_P (E2-final default-city paragraph): reduce 2nd "Mecca/مكة المكرمة"
//    occurrence to "current/selected city" — across all 10 langs.
// ═════════════════════════════════════════════════════════════════════════
const SEC3_P_NEW = {
    ar: 'قد تظهر بيانات القمر افتراضياً لمدينة مكة المكرمة أو للمدينة التي يختارها المستخدم، مع إمكانية الانتقال نحو صفحات المدن لمتابعة حالة القمر اليوم في الرياض أو المدينة الحالية أو غيرها. تختلف أوقات شروق القمر وغروبه قليلاً حسب الموقع الجغرافي، بينما تبقى مراحل القمر العامة مرتبطة بالدورة القمرية نفسها. تتوفر بيانات القمر لجميع المدن الكبرى في العالم العربي والإسلامي.',
    en: "Moon data may appear by default for the city of Mecca or for the city selected by the user, with the option to navigate to city pages to track today's moon state in Riyadh, your current city, or others. Moonrise and moonset times differ slightly by geographic location, while general moon phases remain tied to the lunar cycle itself. Moon data is available for all major cities in the Arab and Islamic world.",
    fr: "Les données lunaires peuvent s'afficher par défaut pour la ville de La Mecque ou pour la ville choisie par l'utilisateur, avec la possibilité d'accéder aux pages de villes pour suivre l'état actuel de la Lune à Riyad, votre ville actuelle ou ailleurs. Les heures de lever et de coucher de la Lune diffèrent légèrement selon l'emplacement géographique, tandis que les phases lunaires générales restent liées au cycle lunaire lui-même. Les données lunaires sont disponibles pour toutes les grandes villes du monde arabe et islamique.",
    tr: 'Ay verileri varsayılan olarak Mekke şehri veya kullanıcının seçtiği şehir için görünebilir; bugünkü ay durumunu Riyad, mevcut şehrinizde veya diğer şehirlerde takip etmek için şehir sayfalarına gitme imkânı vardır. Ay doğuş ve batış saatleri coğrafi konuma göre biraz farklılık gösterir, genel ay evreleri ise ay döngüsünün kendisine bağlı kalır. Ay verileri Arap ve İslam dünyasının tüm büyük şehirleri için mevcuttur.',
    ur: 'چاند کا ڈیٹا بطور ڈیفالٹ مکہ مکرمہ شہر کے لیے یا صارف کے منتخب کردہ شہر کے لیے ظاہر ہو سکتا ہے، شہر کے صفحات پر جانے کے ساتھ آج کا چاند ریاض، آپ کا موجودہ شہر یا دیگر میں دیکھ سکتے ہیں۔ چاند کے طلوع و غروب کے اوقات جغرافیائی محل وقوع کے مطابق تھوڑے مختلف ہوتے ہیں، جبکہ چاند کے عام مراحل قمری چکر سے ہی جڑے رہتے ہیں۔ چاند کا ڈیٹا عرب اور اسلامی دنیا کے تمام بڑے شہروں کے لیے دستیاب ہے۔',
    de: 'Monddaten können standardmäßig für die Stadt Mekka oder für die vom Benutzer ausgewählte Stadt angezeigt werden, mit der Möglichkeit, zu Stadtseiten zu navigieren, um den heutigen Mondzustand in Riad, Ihrer aktuellen Stadt oder anderen Städten zu verfolgen. Mondaufgangs- und Untergangszeiten unterscheiden sich leicht je nach geografischem Standort, während die allgemeinen Mondphasen an den Mondzyklus selbst gebunden bleiben. Monddaten sind für alle großen Städte der arabischen und islamischen Welt verfügbar.',
    id: 'Data Bulan dapat muncul secara default untuk kota Makkah atau untuk kota yang dipilih pengguna, dengan opsi untuk menavigasi ke halaman kota untuk melacak keadaan Bulan hari ini di Riyadh, kota Anda saat ini, atau lainnya. Waktu terbit dan terbenam Bulan sedikit berbeda berdasarkan lokasi geografis, sementara fase Bulan secara umum tetap terkait dengan siklus bulan itu sendiri. Data Bulan tersedia untuk semua kota besar di dunia Arab dan Islam.',
    es: 'Los datos lunares pueden mostrarse por defecto para la ciudad de La Meca o para la ciudad seleccionada por el usuario, con la opción de navegar a las páginas de ciudades para seguir el estado actual de la Luna en Riad, su ciudad actual u otras. Los horarios de salida y puesta de la Luna difieren ligeramente según la ubicación geográfica, mientras que las fases lunares generales permanecen vinculadas al propio ciclo lunar. Los datos lunares están disponibles para todas las principales ciudades del mundo árabe e islámico.',
    bn: 'চাঁদের তথ্য ডিফল্টরূপে মক্কা শহরের জন্য বা ব্যবহারকারীর নির্বাচিত শহরের জন্য দেখাতে পারে, রিয়াদ, আপনার বর্তমান শহর বা অন্যান্য শহরে আজকের চাঁদের অবস্থা ট্র্যাক করতে শহর পৃষ্ঠাগুলিতে নেভিগেট করার বিকল্প সহ। চাঁদের উদয় ও অস্তের সময় ভৌগলিক অবস্থান অনুযায়ী সামান্য পার্থক্য থাকে, যেখানে চাঁদের সাধারণ দশাগুলি চান্দ্র চক্রের সাথেই বাঁধা থাকে। চাঁদের তথ্য আরব ও ইসলামী বিশ্বের সমস্ত বড় শহরের জন্য উপলব্ধ।',
    ms: 'Data Bulan boleh dipaparkan secara lalai untuk bandar Mekah atau untuk bandar yang dipilih pengguna, dengan pilihan untuk melayari halaman bandar bagi memantau keadaan Bulan hari ini di Riyadh, bandar semasa anda, atau lain-lain. Waktu terbit dan terbenam Bulan sedikit berbeza mengikut lokasi geografi, sementara fasa Bulan secara umum tetap terikat dengan kitaran bulan itu sendiri. Data Bulan tersedia untuk semua bandar utama di dunia Arab dan Islam.',
};

const SEC3_P_OLD_BLOCK = [
`            const _hubSec3P  = {`,
`                    ar: 'قد تظهر بيانات القمر افتراضياً لمدينة مكة المكرمة أو للمدينة التي يختارها المستخدم، مع إمكانية الانتقال إلى صفحات المدن لمتابعة حالة القمر اليوم في الرياض أو مكة المكرمة أو غيرها. تختلف أوقات شروق القمر وغروبه قليلاً حسب الموقع الجغرافي، بينما تبقى مراحل القمر العامة مرتبطة بالدورة القمرية نفسها. تتوفر بيانات القمر لجميع المدن الكبرى في العالم العربي والإسلامي.',`,
`                    en: 'Moon data may appear by default for the city of Mecca or for the city selected by the user, with the option to navigate to city pages to track today\\'s moon state in Riyadh, Mecca, or others. Moonrise and moonset times differ slightly by geographic location, while general moon phases remain tied to the lunar cycle itself. Moon data is available for all major cities in the Arab and Islamic world.',`,
`                    fr: 'Les données lunaires peuvent s\\'afficher par défaut pour la ville de La Mecque ou pour la ville choisie par l\\'utilisateur, avec la possibilité d\\'accéder aux pages de villes pour suivre l\\'état actuel de la Lune à Riyad, La Mecque ou ailleurs. Les heures de lever et de coucher de la Lune diffèrent légèrement selon l\\'emplacement géographique, tandis que les phases lunaires générales restent liées au cycle lunaire lui-même. Les données lunaires sont disponibles pour toutes les grandes villes du monde arabe et islamique.',`,
`                    tr: 'Ay verileri varsayılan olarak Mekke şehri veya kullanıcının seçtiği şehir için görünebilir; bugünkü ay durumunu Riyad, Mekke veya diğer şehirlerde takip etmek için şehir sayfalarına gitme imkânı vardır. Ay doğuş ve batış saatleri coğrafi konuma göre biraz farklılık gösterir, genel ay evreleri ise ay döngüsünün kendisine bağlı kalır. Ay verileri Arap ve İslam dünyasının tüm büyük şehirleri için mevcuttur.',`,
`                    ur: 'چاند کا ڈیٹا بطور ڈیفالٹ مکہ مکرمہ شہر کے لیے یا صارف کے منتخب کردہ شہر کے لیے ظاہر ہو سکتا ہے، شہر کے صفحات پر جانے کے ساتھ آج کا چاند ریاض، مکہ یا دیگر میں دیکھ سکتے ہیں۔ چاند کے طلوع و غروب کے اوقات جغرافیائی محل وقوع کے مطابق تھوڑے مختلف ہوتے ہیں، جبکہ چاند کے عام مراحل قمری چکر سے ہی جڑے رہتے ہیں۔ چاند کا ڈیٹا عرب اور اسلامی دنیا کے تمام بڑے شہروں کے لیے دستیاب ہے۔',`,
`                    de: 'Monddaten können standardmäßig für die Stadt Mekka oder für die vom Benutzer ausgewählte Stadt angezeigt werden, mit der Möglichkeit, zu Stadtseiten zu navigieren, um den heutigen Mondzustand in Riad, Mekka oder anderen Städten zu verfolgen. Mondaufgangs- und Untergangszeiten unterscheiden sich leicht je nach geografischem Standort, während die allgemeinen Mondphasen an den Mondzyklus selbst gebunden bleiben. Monddaten sind für alle großen Städte der arabischen und islamischen Welt verfügbar.',`,
`                    id: 'Data Bulan dapat muncul secara default untuk kota Makkah atau untuk kota yang dipilih pengguna, dengan opsi untuk menavigasi ke halaman kota untuk melacak keadaan Bulan hari ini di Riyadh, Makkah, atau lainnya. Waktu terbit dan terbenam Bulan sedikit berbeda berdasarkan lokasi geografis, sementara fase Bulan secara umum tetap terkait dengan siklus bulan itu sendiri. Data Bulan tersedia untuk semua kota besar di dunia Arab dan Islam.',`,
`                    es: 'Los datos lunares pueden mostrarse por defecto para la ciudad de La Meca o para la ciudad seleccionada por el usuario, con la opción de navegar a las páginas de ciudades para seguir el estado actual de la Luna en Riad, La Meca u otras. Los horarios de salida y puesta de la Luna difieren ligeramente según la ubicación geográfica, mientras que las fases lunares generales permanecen vinculadas al propio ciclo lunar. Los datos lunares están disponibles para todas las principales ciudades del mundo árabe e islámico.',`,
`                    bn: 'চাঁদের তথ্য ডিফল্টরূপে মক্কা শহরের জন্য বা ব্যবহারকারীর নির্বাচিত শহরের জন্য দেখাতে পারে, রিয়াদ, মক্কা বা অন্যান্য শহরে আজকের চাঁদের অবস্থা ট্র্যাক করতে শহর পৃষ্ঠাগুলিতে নেভিগেট করার বিকল্প সহ। চাঁদের উদয় ও অস্তের সময় ভৌগলিক অবস্থান অনুযায়ী সামান্য পার্থক্য থাকে, যেখানে চাঁদের সাধারণ দশাগুলি চান্দ্র চক্রের সাথেই বাঁধা থাকে। চাঁদের তথ্য আরব ও ইসলামী বিশ্বের সমস্ত বড় শহরের জন্য উপলব্ধ।',`,
`                    ms: 'Data Bulan boleh dipaparkan secara lalai untuk bandar Mekah atau untuk bandar yang dipilih pengguna, dengan pilihan untuk melayari halaman bandar bagi memantau keadaan Bulan hari ini di Riyadh, Mekah, atau lain-lain. Waktu terbit dan terbenam Bulan sedikit berbeza mengikut lokasi geografi, sementara fasa Bulan secara umum tetap terikat dengan kitaran bulan itu sendiri. Data Bulan tersedia untuk semua bandar utama di dunia Arab dan Islam.',`,
`                };`,
].join(EOL);
replaceBlock('SEC3_P (default-city paragraph — 10 langs)', SEC3_P_OLD_BLOCK, _serializeLangMap('_hubSec3P ', SEC3_P_NEW));

// ═════════════════════════════════════════════════════════════════════════
// 4) DEPTH_P1 (depth section paragraph 1): reduce "to/إلى" repetition.
//    Replace "leading up to ... returning to" pattern with "ending with ...
//    reaching ... stage" — across all 10 langs.
// ═════════════════════════════════════════════════════════════════════════
const DEPTH_P1_NEW = {
    ar: 'تجمع صفحة حالة القمر اليوم بين عدة مؤشرات فلكية تساعد المستخدم على فهم شكل القمر الحالي بطريقة مبسطة. سطوع القمر يوضّح مقدار الجزء المضيء من قرص القمر كما يظهر من الأرض، بينما يوضح عمر القمر عدد الأيام التي مرّت منذ آخر محاق. وكلما تقدّم العمر القمري اقترب القمر من أطواره التالية، مثل التربيع الأول ثم الأحدب المتزايد، ثم يكتمل بدراً، وبعده يبدأ التناقص تدريجياً حتى مرحلة المحاق من جديد.',
    en: "The today's moon page combines several astronomical indicators that help the user understand the current moon shape in a simple way. The moon's brightness shows the proportion of the lit portion of the moon disc as seen from Earth, while moon age indicates the number of days that have passed since the last new moon. As the lunar age progresses, the moon approaches its next phases, such as the first quarter and waxing gibbous, ending with the full moon, after which it gradually wanes until reaching the new moon stage again.",
    fr: "La page de l'état de la Lune aujourd'hui combine plusieurs indicateurs astronomiques qui aident l'utilisateur à comprendre la forme actuelle de la Lune de façon simple. Le brillance de la Lune indique la proportion de la partie éclairée du disque lunaire telle qu'elle est vue depuis la Terre, tandis que l'âge de la Lune indique le nombre de jours écoulés depuis la dernière nouvelle lune. À mesure que l'âge lunaire progresse, la Lune se rapproche de ses phases suivantes, comme le premier quartier puis la Lune gibbeuse croissante, jusqu'à la pleine lune, après quoi elle décroît progressivement vers le stade de la nouvelle lune.",
    tr: 'Bugünkü ay sayfası, kullanıcının mevcut ay şeklini basit bir şekilde anlamasına yardımcı olan birkaç astronomik göstergeyi birleştirir. Ayın parlaklığı, Ay diskinin Dünya\'dan görüldüğü kadarıyla aydınlık kısmının oranını gösterirken, ay yaşı son yeni aydan bu yana geçen gün sayısını gösterir. Ay yaşı ilerledikçe Ay, ilk dördün, sonra büyüyen şişkin ay gibi sonraki evrelerine yaklaşır ve dolunaya ulaşır; ardından yavaş yavaş azalır ve yeni ay aşamasına döner.',
    ur: 'آج کا چاند صفحہ کئی فلکی اشاروں کو یکجا کرتا ہے جو صارف کو آسان طریقے سے چاند کی موجودہ شکل سمجھنے میں مدد کرتے ہیں۔ چاند کی چمک چاند کی ڈسک کے روشن حصے کا تناسب ظاہر کرتی ہے جیسا کہ زمین سے دیکھا جاتا ہے، جبکہ چاند کی عمر آخری نئے چاند کے بعد سے گزرے ہوئے دنوں کی تعداد ظاہر کرتی ہے۔ جیسے جیسے قمری عمر بڑھتی ہے، چاند اپنے اگلے مراحل کے قریب آتا ہے، جیسے پہلی چوتھائی پھر بڑھتا ہوا گبس، بدر تک پہنچتا ہے، جس کے بعد وہ آہستہ آہستہ گھٹتا ہے اور دوبارہ نئے چاند کے مرحلے پر آتا ہے۔',
    de: 'Die heutige Mondseite kombiniert mehrere astronomische Indikatoren, die dem Benutzer helfen, die aktuelle Mondform auf einfache Weise zu verstehen. Die Helligkeit des Mondes zeigt den Anteil des beleuchteten Teils der Mondscheibe, wie er von der Erde aus gesehen wird, während das Mondalter die Anzahl der Tage seit dem letzten Neumond angibt. Mit fortschreitendem Mondalter nähert sich der Mond seinen nächsten Phasen, wie dem ersten Viertel und dem zunehmenden Halbmond, bis hin zum Vollmond; danach nimmt er allmählich ab und kehrt zur Neumondphase zurück.',
    id: 'Halaman Bulan hari ini menggabungkan beberapa indikator astronomi yang membantu pengguna memahami bentuk Bulan saat ini dengan cara sederhana. Kecerahan Bulan menunjukkan proporsi bagian yang terang dari piringan Bulan seperti yang terlihat dari Bumi, sementara usia Bulan menunjukkan jumlah hari yang telah berlalu sejak bulan baru terakhir. Seiring bertambahnya usia lunar, Bulan mendekati fase berikutnya, seperti kuartal pertama dan bulan cembung membesar, hingga menjadi bulan purnama, setelah itu secara bertahap berkurang hingga mencapai fase bulan baru.',
    es: 'La página del estado de la Luna hoy combina varios indicadores astronómicos que ayudan al usuario a comprender la forma actual de la Luna de manera sencilla. El brillo de la Luna muestra la proporción de la parte iluminada del disco lunar tal como se ve desde la Tierra, mientras que la edad de la Luna indica el número de días que han pasado desde la última luna nueva. A medida que avanza la edad lunar, la Luna se acerca a sus siguientes fases, como el primer cuarto y la gibosa creciente, hasta llegar a la luna llena, tras la cual disminuye gradualmente hacia la fase de luna nueva.',
    bn: 'আজকের চাঁদের পৃষ্ঠা বেশ কয়েকটি জ্যোতির্বিজ্ঞান নির্দেশক একত্রিত করে যা ব্যবহারকারীকে সহজভাবে চাঁদের বর্তমান আকৃতি বুঝতে সাহায্য করে। চাঁদের উজ্জ্বলতা পৃথিবী থেকে দেখা চাঁদের চাকতির আলোকিত অংশের অনুপাত দেখায়, যেখানে চাঁদের বয়স সর্বশেষ অমাবস্যা থেকে অতিবাহিত দিনের সংখ্যা নির্দেশ করে। চান্দ্র বয়স যত বাড়ে, চাঁদ তার পরবর্তী দশার দিকে এগিয়ে যায়, যেমন প্রথম পাদ এবং বাড়ন্ত গিবাস, পূর্ণিমা পর্যন্ত পৌঁছায়, এরপর ধীরে ধীরে কমতে থাকে এবং অমাবস্যার পর্যায়ে ফিরে আসে।',
    ms: 'Halaman Bulan hari ini menggabungkan beberapa penunjuk astronomi yang membantu pengguna memahami bentuk Bulan semasa dengan cara mudah. Kecerahan Bulan menunjukkan kadar bahagian Bulan yang bercahaya seperti dilihat dari Bumi, manakala usia Bulan menunjukkan bilangan hari yang telah berlalu sejak anak bulan terakhir. Apabila usia bulan bertambah, Bulan menghampiri fasanya yang seterusnya, seperti suku pertama dan bulan cembung membesar, sehingga menjadi bulan purnama, selepas itu ia berkurang secara beransur-ansur menuju fasa anak bulan.',
};

const DEPTH_P1_OLD_BLOCK = [
`            const _depthP1 = {`,
`                    ar: 'تجمع صفحة حالة القمر اليوم بين عدة مؤشرات فلكية تساعد المستخدم على فهم شكل القمر الحالي بطريقة مبسطة. نسبة الإضاءة توضّح مقدار الجزء المضيء من قرص القمر كما يظهر من الأرض، بينما يوضح عمر القمر عدد الأيام التي مرّت منذ آخر محاق. وكلما تقدّم العمر القمري اقترب القمر من أطواره التالية، مثل التربيع الأول ثم الأحدب المتزايد وصولاً إلى البدر، وبعده يبدأ التناقص تدريجياً حتى يعود إلى المحاق من جديد.',`,
`                    en: 'The today\\'s moon page combines several astronomical indicators that help the user understand the current moon shape in a simple way. The illumination percentage shows the proportion of the lit portion of the moon disc as seen from Earth, while moon age indicates the number of days that have passed since the last new moon. As the lunar age progresses, the moon approaches its next phases, such as the first quarter and waxing gibbous, leading up to the full moon, after which it gradually wanes until returning to the new moon again.',`,
`                    fr: 'La page de l\\'état de la Lune aujourd\\'hui combine plusieurs indicateurs astronomiques qui aident l\\'utilisateur à comprendre la forme actuelle de la Lune de façon simple. Le pourcentage d\\'illumination indique la proportion de la partie éclairée du disque lunaire telle qu\\'elle est vue depuis la Terre, tandis que l\\'âge de la Lune indique le nombre de jours écoulés depuis la dernière nouvelle lune. À mesure que l\\'âge lunaire progresse, la Lune se rapproche de ses phases suivantes, comme le premier quartier puis la Lune gibbeuse croissante, jusqu\\'à la pleine lune, après quoi elle décroît progressivement jusqu\\'au retour à la nouvelle lune.',`,
`                    tr: 'Bugünkü ay sayfası, kullanıcının mevcut ay şeklini basit bir şekilde anlamasına yardımcı olan birkaç astronomik göstergeyi birleştirir. Aydınlanma yüzdesi, Ay diskinin Dünya\\'dan görüldüğü kadarıyla aydınlık kısmının oranını gösterirken, ay yaşı son yeni aydan bu yana geçen gün sayısını gösterir. Ay yaşı ilerledikçe Ay, ilk dördün, sonra büyüyen şişkin ay gibi sonraki evrelerine yaklaşır ve dolunaya ulaşır; ardından yavaş yavaş azalır ve tekrar yeni aya döner.',`,
`                    ur: 'آج کا چاند صفحہ کئی فلکی اشاروں کو یکجا کرتا ہے جو صارف کو آسان طریقے سے چاند کی موجودہ شکل سمجھنے میں مدد کرتے ہیں۔ روشنی کا فیصد چاند کی ڈسک کے روشن حصے کا تناسب ظاہر کرتا ہے جیسا کہ زمین سے دیکھا جاتا ہے، جبکہ چاند کی عمر آخری نئے چاند کے بعد سے گزرے ہوئے دنوں کی تعداد ظاہر کرتی ہے۔ جیسے جیسے قمری عمر بڑھتی ہے، چاند اپنے اگلے مراحل کے قریب آتا ہے، جیسے پہلی چوتھائی پھر بڑھتا ہوا گبس، بدر تک پہنچتا ہے، جس کے بعد وہ آہستہ آہستہ گھٹتا ہے اور دوبارہ نئے چاند کی طرف لوٹتا ہے۔',`,
`                    de: 'Die heutige Mondseite kombiniert mehrere astronomische Indikatoren, die dem Benutzer helfen, die aktuelle Mondform auf einfache Weise zu verstehen. Der Beleuchtungsprozentsatz zeigt den Anteil des beleuchteten Teils der Mondscheibe, wie er von der Erde aus gesehen wird, während das Mondalter die Anzahl der Tage seit dem letzten Neumond angibt. Mit fortschreitendem Mondalter nähert sich der Mond seinen nächsten Phasen, wie dem ersten Viertel und dem zunehmenden Halbmond, bis hin zum Vollmond; danach nimmt er allmählich ab und kehrt zum Neumond zurück.',`,
`                    id: 'Halaman Bulan hari ini menggabungkan beberapa indikator astronomi yang membantu pengguna memahami bentuk Bulan saat ini dengan cara sederhana. Persentase iluminasi menunjukkan proporsi bagian yang terang dari piringan Bulan seperti yang terlihat dari Bumi, sementara usia Bulan menunjukkan jumlah hari yang telah berlalu sejak bulan baru terakhir. Seiring bertambahnya usia lunar, Bulan mendekati fase berikutnya, seperti kuartal pertama dan bulan cembung membesar, menuju ke bulan purnama, setelah itu secara bertahap berkurang hingga kembali ke bulan baru.',`,
`                    es: 'La página del estado de la Luna hoy combina varios indicadores astronómicos que ayudan al usuario a comprender la forma actual de la Luna de manera sencilla. El porcentaje de iluminación muestra la proporción de la parte iluminada del disco lunar tal como se ve desde la Tierra, mientras que la edad de la Luna indica el número de días que han pasado desde la última luna nueva. A medida que avanza la edad lunar, la Luna se acerca a sus siguientes fases, como el primer cuarto y la gibosa creciente, hasta llegar a la luna llena, tras la cual disminuye gradualmente hasta volver a la luna nueva.',`,
`                    bn: 'আজকের চাঁদের পৃষ্ঠা বেশ কয়েকটি জ্যোতির্বিজ্ঞান নির্দেশক একত্রিত করে যা ব্যবহারকারীকে সহজভাবে চাঁদের বর্তমান আকৃতি বুঝতে সাহায্য করে। আলোকন শতাংশ পৃথিবী থেকে দেখা চাঁদের চাকতির আলোকিত অংশের অনুপাত দেখায়, যেখানে চাঁদের বয়স সর্বশেষ অমাবস্যা থেকে অতিবাহিত দিনের সংখ্যা নির্দেশ করে। চান্দ্র বয়স যত বাড়ে, চাঁদ তার পরবর্তী দশার দিকে এগিয়ে যায়, যেমন প্রথম পাদ এবং বাড়ন্ত গিবাস, পূর্ণিমা পর্যন্ত পৌঁছায়, এরপর ধীরে ধীরে কমতে থাকে যতক্ষণ না অমাবস্যায় ফিরে আসে।',`,
`                    ms: 'Halaman Bulan hari ini menggabungkan beberapa penunjuk astronomi yang membantu pengguna memahami bentuk Bulan semasa dengan cara mudah. Peratus pencahayaan menunjukkan kadar bahagian Bulan yang bercahaya seperti dilihat dari Bumi, manakala usia Bulan menunjukkan bilangan hari yang telah berlalu sejak anak bulan terakhir. Apabila usia bulan bertambah, Bulan menghampiri fasanya yang seterusnya, seperti suku pertama dan bulan cembung membesar, sehingga ke bulan purnama, selepas itu ia berkurang secara beransur-ansur sehingga kembali kepada anak bulan.',`,
`                };`,
].join(EOL);
replaceBlock('DEPTH_P1 (depth paragraph 1 — 10 langs)', DEPTH_P1_OLD_BLOCK, _serializeLangMap('_depthP1', DEPTH_P1_NEW));

// ═════════════════════════════════════════════════════════════════════════
// 5) DEPTH_P2 (depth section paragraph 2): reduce "to/إلى" repetition.
//    Replace "from one city to another ... navigate to" pattern with "across
//    cities ... navigate toward" — across all 10 langs.
// ═════════════════════════════════════════════════════════════════════════
const DEPTH_P2_NEW = {
    ar: 'تساعد بيانات شروق القمر وغروبه على معرفة الوقت التقريبي الذي يظهر فيه القمر في السماء أو يغيب عن الأفق، وقد تختلف هذه الأوقات بحسب المدينة بسبب اختلاف الموقع الجغرافي وخط الطول والعرض. لذلك قد تعرض الصفحة بيانات افتراضية لمدينة محددة، مع إتاحة الانتقال نحو صفحات المدن لمتابعة حالة القمر بحسب موقع المستخدم. كما يرتبط تتبع القمر بالتقويم الهجري، لأن بداية الشهور الهجرية تعتمد على دورة القمر ورؤية الهلال، مما يجعل متابعة أطوار القمر مفيدة لمن يهتم بالتاريخ الهجري، ومواعيد البدر، وحركة القمر خلال الشهر.',
    en: "Moonrise and moonset data help identify the approximate time when the moon appears in the sky or sets below the horizon, and these times can differ across cities due to geographic location, longitude, and latitude. The page may therefore display default data for a specific city, with the option to navigate toward city pages and track the moon based on the user's location. Moon tracking is also tied to the Hijri calendar, since the start of Hijri months depends on the lunar cycle and crescent visibility, making it useful for those interested in the Hijri date, full moon timings, and the moon's motion through the month.",
    fr: "Les données de lever et de coucher de la Lune aident à connaître l'heure approximative à laquelle la Lune apparaît dans le ciel ou disparaît sous l'horizon, et ces horaires peuvent différer selon la ville en raison de la localisation géographique, de la longitude et de la latitude. La page peut donc afficher des données par défaut pour une ville spécifique, avec la possibilité d'accéder vers les pages de villes pour suivre la Lune selon la position de l'utilisateur. Le suivi de la Lune est également lié au calendrier hégirien, puisque le début des mois hégiriens dépend du cycle lunaire et de la visibilité du croissant, ce qui rend le suivi des phases utile à ceux qui s'intéressent à la date hégirienne, aux horaires de pleine lune et au mouvement de la Lune au cours du mois.",
    tr: 'Ay doğuşu ve batış verileri, Ayın gökyüzünde göründüğü veya ufkun altına battığı yaklaşık zamanı belirlemeye yardımcı olur ve bu zamanlar coğrafi konum, boylam ve enlem nedeniyle şehirden şehre farklılık gösterebilir. Sayfa bu nedenle belirli bir şehir için varsayılan veri gösterebilir; kullanıcının konumuna göre Ayı takip etmek üzere şehir sayfalarına geçiş imkânı vardır. Ay takibi ayrıca hicri takvim ile bağlantılıdır; çünkü hicri ayların başlangıcı ay döngüsüne ve hilalin görünürlüğüne bağlıdır, bu da hicri tarih, dolunay zamanları ve Ayın ay boyunca hareketi ile ilgilenenler için yararlı kılar.',
    ur: 'چاند کے طلوع و غروب کا ڈیٹا چاند کے آسمان میں ظاہر ہونے یا افق کے نیچے غروب ہونے کے تقریبی وقت کا تعین کرنے میں مدد کرتا ہے، اور یہ اوقات جغرافیائی محل وقوع، طول البلد اور عرض البلد کی وجہ سے شہر کے مطابق مختلف ہو سکتے ہیں۔ لہذا صفحہ کسی مخصوص شہر کے لیے ڈیفالٹ ڈیٹا دکھا سکتا ہے، صارف کے مقام کے مطابق چاند کا پتہ لگانے کے لیے شہر کے صفحات کی طرف جانے کے اختیار کے ساتھ۔ چاند کی پیروی ہجری کیلنڈر سے بھی منسلک ہے، کیونکہ ہجری مہینوں کی شروعات قمری چکر اور ہلال کی رؤیت پر منحصر ہے، جو ہجری تاریخ، بدر کے اوقات، اور پورے مہینے میں چاند کی حرکت میں دلچسپی رکھنے والوں کے لیے مفید ہے۔',
    de: 'Mondaufgangs- und Untergangsdaten helfen dabei, die ungefähre Zeit zu ermitteln, zu der der Mond am Himmel erscheint oder unter den Horizont sinkt, und diese Zeiten können je nach Stadt aufgrund der geografischen Lage, des Längen- und Breitengrades unterschiedlich sein. Die Seite kann daher Standarddaten für eine bestimmte Stadt anzeigen, mit der Möglichkeit, über Stadtseiten den Mond entsprechend dem Standort des Benutzers zu verfolgen. Die Mondverfolgung ist auch mit dem Hidschri-Kalender verbunden, da der Beginn der Hidschri-Monate vom Mondzyklus und der Sichtbarkeit der Sichel abhängt, was sie für diejenigen nützlich macht, die sich für das Hidschri-Datum, die Vollmondzeiten und die Bewegung des Mondes durch den Monat interessieren.',
    id: 'Data terbit dan terbenam Bulan membantu mengidentifikasi waktu perkiraan ketika Bulan muncul di langit atau terbenam di bawah cakrawala, dan waktu-waktu ini dapat berbeda antar kota karena lokasi geografis, garis bujur, dan garis lintang. Halaman dapat oleh karena itu menampilkan data default untuk kota tertentu, dengan opsi untuk mengarahkan menuju halaman kota dalam melacak Bulan berdasarkan lokasi pengguna. Pelacakan Bulan juga terkait dengan kalender Hijriah, karena awal bulan Hijriah bergantung pada siklus bulan dan visibilitas hilal, yang membuatnya berguna bagi mereka yang tertarik pada tanggal Hijriah, waktu purnama, dan pergerakan Bulan sepanjang bulan.',
    es: 'Los datos de salida y puesta de la Luna ayudan a identificar el tiempo aproximado en que la Luna aparece en el cielo o se pone bajo el horizonte, y estos tiempos pueden diferir según la ciudad debido a la ubicación geográfica, la longitud y la latitud. Por ello la página puede mostrar datos predeterminados para una ciudad específica, con la opción de dirigirse hacia las páginas de ciudades para seguir la Luna según la ubicación del usuario. El seguimiento de la Luna también está vinculado al calendario hijri, ya que el comienzo de los meses hijri depende del ciclo lunar y la visibilidad del creciente, lo que lo hace útil para quienes se interesan por la fecha hijri, los horarios de luna llena y el movimiento de la Luna a lo largo del mes.',
    bn: 'চাঁদের উদয় ও অস্তের ডেটা চাঁদ আকাশে কখন আবির্ভূত হয় বা দিগন্তের নিচে অস্ত যায় তার আনুমানিক সময় চিহ্নিত করতে সাহায্য করে, এবং এই সময়গুলি ভৌগলিক অবস্থান, দ্রাঘিমাংশ এবং অক্ষাংশের কারণে শহর অনুযায়ী ভিন্ন হতে পারে। তাই পৃষ্ঠা একটি নির্দিষ্ট শহরের জন্য ডিফল্ট ডেটা প্রদর্শন করতে পারে, ব্যবহারকারীর অবস্থান অনুযায়ী চাঁদ ট্র্যাক করতে শহর পৃষ্ঠাগুলির দিকে নেভিগেট করার বিকল্প সহ। চাঁদ ট্র্যাকিং হিজরি ক্যালেন্ডারের সাথেও যুক্ত, কারণ হিজরি মাসের শুরু চান্দ্র চক্র এবং হিলালের দৃশ্যমানতার উপর নির্ভর করে, যা হিজরি তারিখ, পূর্ণিমার সময় এবং সারা মাস জুড়ে চাঁদের গতিতে আগ্রহী ব্যক্তিদের জন্য এটি দরকারী করে তোলে।',
    ms: 'Data terbit dan terbenam Bulan membantu mengenal pasti masa anggaran apabila Bulan muncul di langit atau terbenam di bawah ufuk, dan masa-masa ini boleh berbeza mengikut bandar disebabkan lokasi geografi, garisan bujur, dan garisan lintang. Halaman ini oleh itu boleh memaparkan data lalai untuk bandar tertentu, dengan pilihan untuk mengarah menuju halaman bandar bagi memantau Bulan berdasarkan lokasi pengguna. Pemantauan Bulan juga dikaitkan dengan kalendar Hijrah, kerana permulaan bulan Hijrah bergantung pada kitaran bulan dan kelihatan hilal, yang menjadikannya berguna untuk mereka yang berminat dengan tarikh Hijrah, waktu purnama, dan pergerakan Bulan sepanjang bulan.',
};

const DEPTH_P2_OLD_BLOCK = [
`            const _depthP2 = {`,
`                    ar: 'تساعد بيانات شروق القمر وغروبه على معرفة الوقت التقريبي الذي يظهر فيه القمر في السماء أو يغيب عن الأفق، وقد تختلف هذه الأوقات من مدينة إلى أخرى بسبب اختلاف الموقع الجغرافي وخط الطول والعرض. لذلك قد تعرض الصفحة بيانات افتراضية لمدينة محددة، مع إتاحة الانتقال إلى صفحات المدن لمتابعة حالة القمر بحسب موقع المستخدم. كما يرتبط تتبع القمر بالتقويم الهجري، لأن بداية الشهور الهجرية تعتمد على دورة القمر ورؤية الهلال، مما يجعل متابعة أطوار القمر مفيدة لمن يهتم بالتاريخ الهجري، ومواعيد البدر، وحركة القمر خلال الشهر.',`,
`                    en: 'Moonrise and moonset data help identify the approximate time when the moon appears in the sky or sets below the horizon, and these times can differ from one city to another due to geographic location, longitude, and latitude. The page may therefore display default data for a specific city, with the option to navigate to city pages to track the moon based on the user\\'s location. Moon tracking is also tied to the Hijri calendar, since the start of Hijri months depends on the lunar cycle and crescent visibility, making it useful for those interested in the Hijri date, full moon timings, and the moon\\'s motion through the month.',`,
`                    fr: 'Les données de lever et de coucher de la Lune aident à connaître l\\'heure approximative à laquelle la Lune apparaît dans le ciel ou disparaît sous l\\'horizon, et ces horaires peuvent différer d\\'une ville à l\\'autre en raison de la localisation géographique, de la longitude et de la latitude. La page peut donc afficher des données par défaut pour une ville spécifique, avec la possibilité d\\'accéder aux pages de villes pour suivre la Lune selon la position de l\\'utilisateur. Le suivi de la Lune est également lié au calendrier hégirien, puisque le début des mois hégiriens dépend du cycle lunaire et de la visibilité du croissant, ce qui rend le suivi des phases utile à ceux qui s\\'intéressent à la date hégirienne, aux horaires de pleine lune et au mouvement de la Lune au cours du mois.',`,
`                    tr: 'Ay doğuşu ve batış verileri, Ayın gökyüzünde göründüğü veya ufkun altına battığı yaklaşık zamanı belirlemeye yardımcı olur ve bu zamanlar coğrafi konum, boylam ve enlem nedeniyle şehirden şehre farklılık gösterebilir. Sayfa bu nedenle belirli bir şehir için varsayılan veri gösterebilir; kullanıcının konumuna göre Ayı takip etmek için şehir sayfalarına gitme imkânı vardır. Ay takibi ayrıca hicri takvim ile bağlantılıdır; çünkü hicri ayların başlangıcı ay döngüsüne ve hilalin görünürlüğüne bağlıdır, bu da hicri tarih, dolunay zamanları ve Ayın ay boyunca hareketi ile ilgilenenler için yararlı kılar.',`,
`                    ur: 'چاند کے طلوع و غروب کا ڈیٹا چاند کے آسمان میں ظاہر ہونے یا افق کے نیچے غروب ہونے کے تقریبی وقت کا تعین کرنے میں مدد کرتا ہے، اور یہ اوقات جغرافیائی محل وقوع، طول البلد اور عرض البلد کی وجہ سے ایک شہر سے دوسرے شہر میں مختلف ہو سکتے ہیں۔ لہذا صفحہ کسی مخصوص شہر کے لیے ڈیفالٹ ڈیٹا دکھا سکتا ہے، صارف کے مقام کے مطابق چاند کا پتہ لگانے کے لیے شہر کے صفحات پر جانے کے اختیار کے ساتھ۔ چاند کی پیروی ہجری کیلنڈر سے بھی منسلک ہے، کیونکہ ہجری مہینوں کی شروعات قمری چکر اور ہلال کی رؤیت پر منحصر ہے، جو ہجری تاریخ، بدر کے اوقات، اور پورے مہینے میں چاند کی حرکت میں دلچسپی رکھنے والوں کے لیے مفید ہے۔',`,
`                    de: 'Mondaufgangs- und Untergangsdaten helfen dabei, die ungefähre Zeit zu ermitteln, zu der der Mond am Himmel erscheint oder unter den Horizont sinkt, und diese Zeiten können von Stadt zu Stadt aufgrund der geografischen Lage, des Längen- und Breitengrades unterschiedlich sein. Die Seite kann daher Standarddaten für eine bestimmte Stadt anzeigen, mit der Möglichkeit, zu Stadtseiten zu navigieren, um den Mond entsprechend dem Standort des Benutzers zu verfolgen. Die Mondverfolgung ist auch mit dem Hidschri-Kalender verbunden, da der Beginn der Hidschri-Monate vom Mondzyklus und der Sichtbarkeit der Sichel abhängt, was sie für diejenigen nützlich macht, die sich für das Hidschri-Datum, die Vollmondzeiten und die Bewegung des Mondes durch den Monat interessieren.',`,
`                    id: 'Data terbit dan terbenam Bulan membantu mengidentifikasi waktu perkiraan ketika Bulan muncul di langit atau terbenam di bawah cakrawala, dan waktu-waktu ini dapat berbeda dari satu kota ke kota lain karena lokasi geografis, garis bujur, dan garis lintang. Halaman dapat oleh karena itu menampilkan data default untuk kota tertentu, dengan opsi untuk menavigasi ke halaman kota untuk melacak Bulan berdasarkan lokasi pengguna. Pelacakan Bulan juga terkait dengan kalender Hijriah, karena awal bulan Hijriah bergantung pada siklus bulan dan visibilitas hilal, yang membuatnya berguna bagi mereka yang tertarik pada tanggal Hijriah, waktu purnama, dan pergerakan Bulan sepanjang bulan.',`,
`                    es: 'Los datos de salida y puesta de la Luna ayudan a identificar el tiempo aproximado en que la Luna aparece en el cielo o se pone bajo el horizonte, y estos tiempos pueden diferir de una ciudad a otra debido a la ubicación geográfica, la longitud y la latitud. Por ello la página puede mostrar datos predeterminados para una ciudad específica, con la opción de navegar a las páginas de ciudades para seguir la Luna según la ubicación del usuario. El seguimiento de la Luna también está vinculado al calendario hijri, ya que el comienzo de los meses hijri depende del ciclo lunar y la visibilidad del creciente, lo que lo hace útil para quienes se interesan por la fecha hijri, los horarios de luna llena y el movimiento de la Luna a lo largo del mes.',`,
`                    bn: 'চাঁদের উদয় ও অস্তের ডেটা চাঁদ আকাশে কখন আবির্ভূত হয় বা দিগন্তের নিচে অস্ত যায় তার আনুমানিক সময় চিহ্নিত করতে সাহায্য করে, এবং এই সময়গুলি ভৌগলিক অবস্থান, দ্রাঘিমাংশ এবং অক্ষাংশের কারণে এক শহর থেকে অন্য শহরে ভিন্ন হতে পারে। তাই পৃষ্ঠা একটি নির্দিষ্ট শহরের জন্য ডিফল্ট ডেটা প্রদর্শন করতে পারে, ব্যবহারকারীর অবস্থান অনুযায়ী চাঁদ ট্র্যাক করতে শহর পৃষ্ঠাগুলিতে নেভিগেট করার বিকল্প সহ। চাঁদ ট্র্যাকিং হিজরি ক্যালেন্ডারের সাথেও যুক্ত, কারণ হিজরি মাসের শুরু চান্দ্র চক্র এবং হিলালের দৃশ্যমানতার উপর নির্ভর করে, যা হিজরি তারিখ, পূর্ণিমার সময় এবং সারা মাস জুড়ে চাঁদের গতিতে আগ্রহী ব্যক্তিদের জন্য এটি দরকারী করে তোলে।',`,
`                    ms: 'Data terbit dan terbenam Bulan membantu mengenal pasti masa anggaran apabila Bulan muncul di langit atau terbenam di bawah ufuk, dan masa-masa ini boleh berbeza dari satu bandar ke bandar lain disebabkan lokasi geografi, garisan bujur, dan garisan lintang. Halaman ini oleh itu boleh memaparkan data lalai untuk bandar tertentu, dengan pilihan untuk melayari halaman bandar bagi memantau Bulan berdasarkan lokasi pengguna. Pemantauan Bulan juga dikaitkan dengan kalendar Hijrah, kerana permulaan bulan Hijrah bergantung pada kitaran bulan dan kelihatan hilal, yang menjadikannya berguna untuk mereka yang berminat dengan tarikh Hijrah, waktu purnama, dan pergerakan Bulan sepanjang bulan.',`,
`                };`,
].join(EOL);
replaceBlock('DEPTH_P2 (depth paragraph 2 — 10 langs)', DEPTH_P2_OLD_BLOCK, _serializeLangMap('_depthP2', DEPTH_P2_NEW));

// ═════════════════════════════════════════════════════════════════════════
// 6) Add header marker so re-runs of THIS script can detect prior application.
// ═════════════════════════════════════════════════════════════════════════
replaceBlock(
    'header marker for E2-content-balance-Hub',
    `        // ── Phase E2-keywords-Hub-final (2026-05-01): inject 4 SSR-only`,
    `        // ── Phase E2-keywords-Hub-final (2026-05-01) + E2-content-balance-Hub (2026-05-01): inject 4 SSR-only`
);

writeFileSync(PATH, raw);

console.log('\n✅ Phase E2-content-balance-Hub — 5 text blocks rebalanced across 10 langs each.');
console.log('\nWord count check (AR rendered text):');
const arPieces = [SEC2_H2_NEW.ar, SEC1_P_NEW.ar, SEC3_P_NEW.ar, DEPTH_P1_NEW.ar, DEPTH_P2_NEW.ar];
const arWords = arPieces.join(' ').split(/\s+/).filter(Boolean).length;
console.log(`  AR new total (5 blocks): ${arWords} words`);
console.log('\nKeyword balance check (AR — should be reduced):');
const arAll = arPieces.join(' ');
const checks = ['الإضاءة', 'إلى', 'مكة المكرمة', 'بدر قمر مكتمل', 'قمر مكتمل'];
for (const k of checks) {
    const re = new RegExp(k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    const matches = arAll.match(re) || [];
    console.log(`  "${k}": ${matches.length} occurrence(s)`);
}
