// One-shot seeder for CURATED-ARAB-COMPLETE-1 — appends ~61 missing
// Arab cities to curated-places.json so the Arabic-speaking core
// audience never falls back to Nominatim for important MENA cities.
//
// Scope: Syria (16 — all major governorates), Yemen (5), Libya (5),
// Palestine (5), Sudan (4), Iraq (6), Lebanon (3), Jordan (3),
// Morocco (4), Algeria (4), Tunisia (4), Mauritania (2).
//
// Each entry follows the same schema as prior phases:
//   slug, type='city', countryCode, lat, lng, timezone (IANA),
//   names in 10 langs (ar/en/fr/de/tr/ur/id/es/bn/ms),
//   aliases (Arabic variants users actually type),
//   admin.countryAr / admin.countryEn,
//   priority (70-90),
//   source='curated', verified=true.
//
// Idempotent (skips entries that already exist by slug).
import fs from 'node:fs';

const PATH = './db/places/curated-places.json';
const places = JSON.parse(fs.readFileSync(PATH, 'utf8'));
const seen = new Set(places.map(p => p.slug));

const newCities = [
    // ══════════ Syria (16) ══════════
    { slug: 'hama', cc: 'sy', lat: 35.1318, lng: 36.7578, tz: 'Asia/Damascus',
        names: {ar:'حماة',en:'Hama',fr:'Hama',de:'Hama',tr:'Hama',ur:'حماہ',id:'Hama',es:'Hama',bn:'হামা',ms:'Hama'},
        aliases: {ar:['حماة','حماه']},
        countryAr:'سوريا', countryEn:'Syria', priority: 85 },
    { slug: 'homs', cc: 'sy', lat: 34.7324, lng: 36.7137, tz: 'Asia/Damascus',
        names: {ar:'حمص',en:'Homs',fr:'Homs',de:'Homs',tr:'Humus',ur:'حمص',id:'Homs',es:'Homs',bn:'হোমস',ms:'Homs'},
        aliases: {ar:['حمص']},
        countryAr:'سوريا', countryEn:'Syria', priority: 85 },
    { slug: 'latakia', cc: 'sy', lat: 35.5168, lng: 35.7811, tz: 'Asia/Damascus',
        names: {ar:'اللاذقية',en:'Latakia',fr:'Lattaquié',de:'Latakia',tr:'Lazkiye',ur:'لاذقیہ',id:'Latakia',es:'Latakia',bn:'লাতাকিয়া',ms:'Latakia'},
        aliases: {ar:['اللاذقية','لاذقية']},
        countryAr:'سوريا', countryEn:'Syria', priority: 82 },
    { slug: 'tartus', cc: 'sy', lat: 34.8959, lng: 35.8867, tz: 'Asia/Damascus',
        names: {ar:'طرطوس',en:'Tartus',fr:'Tartous',de:'Tartus',tr:'Tartus',ur:'طرطوس',id:'Tartus',es:'Tartus',bn:'তারতুস',ms:'Tartus'},
        aliases: {ar:['طرطوس']},
        countryAr:'سوريا', countryEn:'Syria', priority: 80 },
    { slug: 'deir-ez-zor', cc: 'sy', lat: 35.3357, lng: 40.1408, tz: 'Asia/Damascus',
        names: {ar:'دير الزور',en:'Deir ez-Zor',fr:'Deir ez-Zor',de:'Dair az-Zaur',tr:'Deyrizor',ur:'دیر الزور',id:'Deir ez-Zor',es:'Deir ez-Zor',bn:'দেইর এজ-জোর',ms:'Deir ez-Zor'},
        aliases: {ar:['دير الزور','ديرالزور']},
        countryAr:'سوريا', countryEn:'Syria', priority: 78 },
    { slug: 'raqqa', cc: 'sy', lat: 35.9528, lng: 39.0078, tz: 'Asia/Damascus',
        names: {ar:'الرقة',en:'Raqqa',fr:'Raqqa',de:'Raqqa',tr:'Rakka',ur:'رقہ',id:'Raqqa',es:'Raqa',bn:'রাক্কা',ms:'Raqqa'},
        aliases: {ar:['الرقة','رقة']},
        countryAr:'سوريا', countryEn:'Syria', priority: 78 },
    { slug: 'idlib', cc: 'sy', lat: 35.9333, lng: 36.6333, tz: 'Asia/Damascus',
        names: {ar:'إدلب',en:'Idlib',fr:'Idleb',de:'Idlib',tr:'İdlib',ur:'ادلب',id:'Idlib',es:'Idlib',bn:'ইদলিব',ms:'Idlib'},
        aliases: {ar:['إدلب','ادلب']},
        countryAr:'سوريا', countryEn:'Syria', priority: 78 },
    { slug: 'daraa', cc: 'sy', lat: 32.6189, lng: 36.1058, tz: 'Asia/Damascus',
        names: {ar:'درعا',en:'Daraa',fr:'Deraa',de:'Daraa',tr:'Deraa',ur:'درعا',id:'Daraa',es:'Deraa',bn:'দারা',ms:'Daraa'},
        aliases: {ar:['درعا']},
        countryAr:'سوريا', countryEn:'Syria', priority: 76 },
    { slug: 'as-suwayda', cc: 'sy', lat: 32.7095, lng: 36.5666, tz: 'Asia/Damascus',
        names: {ar:'السويداء',en:'As-Suwayda',fr:'Soueïda',de:'as-Suwaida',tr:'Süveyda',ur:'السويداء',id:'As-Suwayda',es:'Sweida',bn:'সুওয়েদা',ms:'As-Suwayda'},
        aliases: {ar:['السويداء','سويداء']},
        countryAr:'سوريا', countryEn:'Syria', priority: 74 },
    { slug: 'qamishli', cc: 'sy', lat: 37.0526, lng: 41.2310, tz: 'Asia/Damascus',
        names: {ar:'القامشلي',en:'Qamishli',fr:'Qamichli',de:'al-Qamishli',tr:'Kamışlı',ur:'قامشلی',id:'Qamishli',es:'Qamishli',bn:'কামিশলি',ms:'Qamishli'},
        aliases: {ar:['القامشلي','قامشلي']},
        countryAr:'سوريا', countryEn:'Syria', priority: 76 },
    { slug: 'al-hasakah', cc: 'sy', lat: 36.5117, lng: 40.7464, tz: 'Asia/Damascus',
        names: {ar:'الحسكة',en:'Al-Hasakah',fr:'Hassaké',de:'al-Hasaka',tr:'Haseke',ur:'الحسکہ',id:'Al-Hasakah',es:'Hassaka',bn:'আল-হাসাকা',ms:'Al-Hasakah'},
        aliases: {ar:['الحسكة','حسكة']},
        countryAr:'سوريا', countryEn:'Syria', priority: 74 },
    { slug: 'manbij', cc: 'sy', lat: 36.5283, lng: 37.9554, tz: 'Asia/Damascus',
        names: {ar:'منبج',en:'Manbij',fr:'Manbij',de:'Manbidsch',tr:'Münbiç',ur:'منبج',id:'Manbij',es:'Manbij',bn:'মানবিজ',ms:'Manbij'},
        aliases: {ar:['منبج']},
        countryAr:'سوريا', countryEn:'Syria', priority: 72 },
    { slug: 'al-bab', cc: 'sy', lat: 36.3700, lng: 37.5167, tz: 'Asia/Damascus',
        names: {ar:'الباب',en:'Al-Bab',fr:'Al-Bab',de:'al-Bab',tr:'El-Bab',ur:'الباب',id:'Al-Bab',es:'Al-Bab',bn:'আল-বাব',ms:'Al-Bab'},
        aliases: {ar:['الباب']},
        countryAr:'سوريا', countryEn:'Syria', priority: 70 },
    { slug: 'azaz', cc: 'sy', lat: 36.5870, lng: 37.0470, tz: 'Asia/Damascus',
        names: {ar:'أعزاز',en:'Azaz',fr:'Azaz',de:"A'zaz",tr:'Azez',ur:'اعزاز',id:'Azaz',es:'Azaz',bn:'আজাজ',ms:'Azaz'},
        aliases: {ar:['أعزاز','اعزاز']},
        countryAr:'سوريا', countryEn:'Syria', priority: 70 },
    { slug: 'saraqib', cc: 'sy', lat: 35.8629, lng: 36.8082, tz: 'Asia/Damascus',
        names: {ar:'سراقب',en:'Saraqib',fr:'Saraqeb',de:'Saraqib',tr:'Sarakıb',ur:'سراقب',id:'Saraqib',es:'Saraqib',bn:'সারাকিব',ms:'Saraqib'},
        aliases: {ar:['سراقب']},
        countryAr:'سوريا', countryEn:'Syria', priority: 70 },
    { slug: 'maarat-al-numan', cc: 'sy', lat: 35.6431, lng: 36.6699, tz: 'Asia/Damascus',
        names: {ar:'معرة النعمان',en:'Maarat al-Numan',fr:'Maarat an-Numan',de:"Ma'arrat an-Nu'man",tr:'Maarat al-Numan',ur:'معرة النعمان',id:'Maarat al-Numan',es:'Maarat al-Numan',bn:"মা'আরাত আল-নুমান",ms:'Maarat al-Numan'},
        aliases: {ar:['معرة النعمان','معرة نعمان']},
        countryAr:'سوريا', countryEn:'Syria', priority: 70 },

    // ══════════ Yemen (5) ══════════
    { slug: 'taiz', cc: 'ye', lat: 13.5795, lng: 44.0209, tz: 'Asia/Aden',
        names: {ar:'تعز',en:'Taiz',fr:'Taëz',de:'Taizz',tr:'Taiz',ur:'تعز',id:'Taiz',es:'Taiz',bn:'তায়েজ',ms:'Taiz'},
        aliases: {ar:['تعز','تعزّ']},
        countryAr:'اليمن', countryEn:'Yemen', priority: 82 },
    { slug: 'hodeidah', cc: 'ye', lat: 14.7978, lng: 42.9545, tz: 'Asia/Aden',
        names: {ar:'الحديدة',en:'Hodeidah',fr:'Hodeïda',de:'al-Hudaida',tr:'Hudeyde',ur:'الحدیدہ',id:'Hodeidah',es:'Al Hudayda',bn:'হুদায়দাহ',ms:'Hodeidah'},
        aliases: {ar:['الحديدة','حديدة']},
        countryAr:'اليمن', countryEn:'Yemen', priority: 80 },
    { slug: 'ibb', cc: 'ye', lat: 13.9667, lng: 44.1833, tz: 'Asia/Aden',
        names: {ar:'إب',en:'Ibb',fr:'Ibb',de:'Ibb',tr:'İbb',ur:'اب',id:'Ibb',es:'Ibb',bn:'ইব',ms:'Ibb'},
        aliases: {ar:['إب','اب']},
        countryAr:'اليمن', countryEn:'Yemen', priority: 76 },
    { slug: 'mukalla', cc: 'ye', lat: 14.5424, lng: 49.1242, tz: 'Asia/Aden',
        names: {ar:'المكلا',en:'Mukalla',fr:'Moukalla',de:'Mukalla',tr:'Mukalla',ur:'مکلا',id:'Mukalla',es:'Al-Mukalla',bn:'মুকাল্লা',ms:'Mukalla'},
        aliases: {ar:['المكلا','مكلا']},
        countryAr:'اليمن', countryEn:'Yemen', priority: 76 },
    { slug: 'saada', cc: 'ye', lat: 16.9402, lng: 43.7635, tz: 'Asia/Aden',
        names: {ar:'صعدة',en:'Saada',fr:'Saada',de:'Saada',tr:'Sada',ur:'صعدہ',id:'Saada',es:'Saada',bn:'সাদা',ms:'Saada'},
        aliases: {ar:['صعدة']},
        countryAr:'اليمن', countryEn:'Yemen', priority: 72 },

    // ══════════ Libya (5) ══════════
    { slug: 'misrata', cc: 'ly', lat: 32.3754, lng: 15.0925, tz: 'Africa/Tripoli',
        names: {ar:'مصراتة',en:'Misrata',fr:'Misrata',de:'Misrata',tr:'Misrata',ur:'مصراتہ',id:'Misrata',es:'Misrata',bn:'মিসরাতা',ms:'Misrata'},
        aliases: {ar:['مصراتة','مصراته']},
        countryAr:'ليبيا', countryEn:'Libya', priority: 82 },
    { slug: 'sirte', cc: 'ly', lat: 31.2089, lng: 16.5887, tz: 'Africa/Tripoli',
        names: {ar:'سرت',en:'Sirte',fr:'Syrte',de:'Sirte',tr:'Sirte',ur:'سرت',id:'Sirte',es:'Sirte',bn:'সিরতে',ms:'Sirte'},
        aliases: {ar:['سرت']},
        countryAr:'ليبيا', countryEn:'Libya', priority: 78 },
    { slug: 'zawiya', cc: 'ly', lat: 32.7522, lng: 12.7280, tz: 'Africa/Tripoli',
        names: {ar:'الزاوية',en:'Zawiya',fr:'Zaouïa',de:'az-Zawiya',tr:'Zaviye',ur:'زاویہ',id:'Zawiya',es:'Zauía',bn:'জাউয়িয়া',ms:'Zawiya'},
        aliases: {ar:['الزاوية','زاوية']},
        countryAr:'ليبيا', countryEn:'Libya', priority: 76 },
    { slug: 'sabha', cc: 'ly', lat: 27.0377, lng: 14.4283, tz: 'Africa/Tripoli',
        names: {ar:'سبها',en:'Sabha',fr:'Sebha',de:'Sabha',tr:'Sebha',ur:'سبھا',id:'Sabha',es:'Sabha',bn:'সাবহা',ms:'Sabha'},
        aliases: {ar:['سبها']},
        countryAr:'ليبيا', countryEn:'Libya', priority: 74 },
    { slug: 'tobruk', cc: 'ly', lat: 32.0763, lng: 23.9763, tz: 'Africa/Tripoli',
        names: {ar:'طبرق',en:'Tobruk',fr:'Tobrouk',de:'Tobruk',tr:'Tobruk',ur:'طبرق',id:'Tobruk',es:'Tobruk',bn:'তোব্রুক',ms:'Tobruk'},
        aliases: {ar:['طبرق']},
        countryAr:'ليبيا', countryEn:'Libya', priority: 76 },

    // ══════════ Palestine (5) ══════════
    { slug: 'nablus', cc: 'ps', lat: 32.2227, lng: 35.2621, tz: 'Asia/Hebron',
        names: {ar:'نابلس',en:'Nablus',fr:'Naplouse',de:'Nablus',tr:'Nablus',ur:'نابلس',id:'Nablus',es:'Nablus',bn:'নাবলুস',ms:'Nablus'},
        aliases: {ar:['نابلس']},
        countryAr:'فلسطين', countryEn:'Palestine', priority: 82 },
    { slug: 'hebron', cc: 'ps', lat: 31.5325, lng: 35.0998, tz: 'Asia/Hebron',
        names: {ar:'الخليل',en:'Hebron',fr:'Hébron',de:'Hebron',tr:'El-Halil',ur:'الخلیل',id:'Hebron',es:'Hebrón',bn:'হেব্রন',ms:'Hebron'},
        aliases: {ar:['الخليل','خليل']},
        countryAr:'فلسطين', countryEn:'Palestine', priority: 84 },
    { slug: 'bethlehem', cc: 'ps', lat: 31.7054, lng: 35.2024, tz: 'Asia/Hebron',
        names: {ar:'بيت لحم',en:'Bethlehem',fr:'Bethléem',de:'Bethlehem',tr:'Beytüllahim',ur:'بیت لحم',id:'Betlehem',es:'Belén',bn:'বেথলেহেম',ms:'Bethlehem'},
        aliases: {ar:['بيت لحم']},
        countryAr:'فلسطين', countryEn:'Palestine', priority: 80 },
    { slug: 'jenin', cc: 'ps', lat: 32.4571, lng: 35.2944, tz: 'Asia/Hebron',
        names: {ar:'جنين',en:'Jenin',fr:'Jénine',de:'Dschenin',tr:'Cenin',ur:'جنین',id:'Jenin',es:'Yenín',bn:'জেনিন',ms:'Jenin'},
        aliases: {ar:['جنين']},
        countryAr:'فلسطين', countryEn:'Palestine', priority: 76 },
    { slug: 'tulkarem', cc: 'ps', lat: 32.3104, lng: 35.0286, tz: 'Asia/Hebron',
        names: {ar:'طولكرم',en:'Tulkarem',fr:'Tulkarem',de:'Tulkarem',tr:'Tulkarem',ur:'طولکرم',id:'Tulkarem',es:'Tulkarm',bn:'তুলকারেম',ms:'Tulkarem'},
        aliases: {ar:['طولكرم']},
        countryAr:'فلسطين', countryEn:'Palestine', priority: 74 },

    // ══════════ Sudan (4) ══════════
    { slug: 'omdurman', cc: 'sd', lat: 15.6440, lng: 32.4779, tz: 'Africa/Khartoum',
        names: {ar:'أم درمان',en:'Omdurman',fr:'Omdourman',de:'Omdurman',tr:'Omdurman',ur:'ام درمان',id:'Omdurman',es:'Omdurmán',bn:'ওমদুরমান',ms:'Omdurman'},
        aliases: {ar:['أم درمان','ام درمان']},
        countryAr:'السودان', countryEn:'Sudan', priority: 88 },
    { slug: 'port-sudan', cc: 'sd', lat: 19.6158, lng: 37.2164, tz: 'Africa/Khartoum',
        names: {ar:'بورتسودان',en:'Port Sudan',fr:'Port-Soudan',de:'Port Sudan',tr:'Port Sudan',ur:'پورٹ سوڈان',id:'Port Sudan',es:'Puerto Sudán',bn:'পোর্ট সুদান',ms:'Port Sudan'},
        aliases: {ar:['بورتسودان','بور سودان']},
        countryAr:'السودان', countryEn:'Sudan', priority: 80 },
    { slug: 'kassala', cc: 'sd', lat: 15.4503, lng: 36.4000, tz: 'Africa/Khartoum',
        names: {ar:'كسلا',en:'Kassala',fr:'Kassala',de:'Kassala',tr:'Kassala',ur:'کسلا',id:'Kassala',es:'Kassala',bn:'কাসাল্লা',ms:'Kassala'},
        aliases: {ar:['كسلا']},
        countryAr:'السودان', countryEn:'Sudan', priority: 74 },
    { slug: 'nyala', cc: 'sd', lat: 12.0500, lng: 24.8833, tz: 'Africa/Khartoum',
        names: {ar:'نيالا',en:'Nyala',fr:'Nyala',de:'Nyala',tr:'Nyala',ur:'نیالا',id:'Nyala',es:'Nyala',bn:'নিয়ালা',ms:'Nyala'},
        aliases: {ar:['نيالا']},
        countryAr:'السودان', countryEn:'Sudan', priority: 76 },

    // ══════════ Iraq (6) ══════════
    { slug: 'karbala', cc: 'iq', lat: 32.6160, lng: 44.0249, tz: 'Asia/Baghdad',
        names: {ar:'كربلاء',en:'Karbala',fr:'Kerbala',de:'Kerbela',tr:'Kerbela',ur:'کربلا',id:'Karbala',es:'Kerbala',bn:'কারবালা',ms:'Karbala'},
        aliases: {ar:['كربلاء','كربلا']},
        countryAr:'العراق', countryEn:'Iraq', priority: 88 },
    { slug: 'tikrit', cc: 'iq', lat: 34.5959, lng: 43.6788, tz: 'Asia/Baghdad',
        names: {ar:'تكريت',en:'Tikrit',fr:'Tikrit',de:'Tikrit',tr:'Tikrit',ur:'تکریت',id:'Tikrit',es:'Tikrit',bn:'তিকরিত',ms:'Tikrit'},
        aliases: {ar:['تكريت']},
        countryAr:'العراق', countryEn:'Iraq', priority: 76 },
    { slug: 'ramadi', cc: 'iq', lat: 33.4258, lng: 43.3088, tz: 'Asia/Baghdad',
        names: {ar:'الرمادي',en:'Ramadi',fr:'Ramadi',de:'Ramadi',tr:'Remadi',ur:'الرمادی',id:'Ramadi',es:'Ramadi',bn:'রামাদি',ms:'Ramadi'},
        aliases: {ar:['الرمادي','رمادي']},
        countryAr:'العراق', countryEn:'Iraq', priority: 76 },
    { slug: 'fallujah', cc: 'iq', lat: 33.3489, lng: 43.7811, tz: 'Asia/Baghdad',
        names: {ar:'الفلوجة',en:'Fallujah',fr:'Fallouja',de:'Falludscha',tr:'Felluce',ur:'فلوجہ',id:'Fallujah',es:'Faluya',bn:'ফাল্লুজা',ms:'Fallujah'},
        aliases: {ar:['الفلوجة','فلوجة']},
        countryAr:'العراق', countryEn:'Iraq', priority: 76 },
    { slug: 'kirkuk', cc: 'iq', lat: 35.4681, lng: 44.3923, tz: 'Asia/Baghdad',
        names: {ar:'كركوك',en:'Kirkuk',fr:'Kirkouk',de:'Kirkuk',tr:'Kerkük',ur:'کرکوک',id:'Kirkuk',es:'Kirkuk',bn:'কিরকুক',ms:'Kirkuk'},
        aliases: {ar:['كركوك']},
        countryAr:'العراق', countryEn:'Iraq', priority: 82 },
    { slug: 'sulaymaniyah', cc: 'iq', lat: 35.5650, lng: 45.4329, tz: 'Asia/Baghdad',
        names: {ar:'السليمانية',en:'Sulaymaniyah',fr:'Souleimaniye',de:'Sulaimaniyya',tr:'Süleymaniye',ur:'سلیمانیہ',id:'Sulaymaniyah',es:'Solimania',bn:'সুলায়মানিয়াহ',ms:'Sulaymaniyah'},
        aliases: {ar:['السليمانية','سليمانية'], ku:['سلێمانی']},
        countryAr:'العراق', countryEn:'Iraq', priority: 80 },

    // ══════════ Lebanon (3) ══════════
    { slug: 'saida', cc: 'lb', lat: 33.5571, lng: 35.3729, tz: 'Asia/Beirut',
        names: {ar:'صيدا',en:'Sidon',fr:'Saïda',de:'Sidon',tr:'Sayda',ur:'صیدا',id:'Sidon',es:'Sidón',bn:'সিডোন',ms:'Sidon'},
        aliases: {ar:['صيدا'], en:['Saida']},
        countryAr:'لبنان', countryEn:'Lebanon', priority: 80 },
    { slug: 'tyre-lb', cc: 'lb', lat: 33.2733, lng: 35.1939, tz: 'Asia/Beirut',
        names: {ar:'صور',en:'Tyre',fr:'Tyr',de:'Tyros',tr:'Sur',ur:'صور',id:'Tyre',es:'Tiro',bn:'টায়ার',ms:'Tyre'},
        aliases: {ar:['صور'], en:['Sur']},
        countryAr:'لبنان', countryEn:'Lebanon', priority: 78 },
    { slug: 'zahle', cc: 'lb', lat: 33.8467, lng: 35.9019, tz: 'Asia/Beirut',
        names: {ar:'زحلة',en:'Zahle',fr:'Zahlé',de:'Zahla',tr:'Zahle',ur:'زحلہ',id:'Zahle',es:'Zahlé',bn:'জাহলে',ms:'Zahle'},
        aliases: {ar:['زحلة','زحله']},
        countryAr:'لبنان', countryEn:'Lebanon', priority: 76 },

    // ══════════ Jordan (3) ══════════
    { slug: 'zarqa', cc: 'jo', lat: 32.0728, lng: 36.0876, tz: 'Asia/Amman',
        names: {ar:'الزرقاء',en:'Zarqa',fr:'Zarka',de:'az-Zarqa',tr:'Zerka',ur:'زرقا',id:'Zarqa',es:'Zarqa',bn:'জারকা',ms:'Zarqa'},
        aliases: {ar:['الزرقاء','زرقاء']},
        countryAr:'الأردن', countryEn:'Jordan', priority: 80 },
    { slug: 'irbid', cc: 'jo', lat: 32.5556, lng: 35.8500, tz: 'Asia/Amman',
        names: {ar:'إربد',en:'Irbid',fr:'Irbid',de:'Irbid',tr:'Erbid',ur:'اربد',id:'Irbid',es:'Irbid',bn:'ইরবিদ',ms:'Irbid'},
        aliases: {ar:['إربد','اربد']},
        countryAr:'الأردن', countryEn:'Jordan', priority: 78 },
    { slug: 'aqaba', cc: 'jo', lat: 29.5267, lng: 35.0067, tz: 'Asia/Amman',
        names: {ar:'العقبة',en:'Aqaba',fr:'Aqaba',de:'Akaba',tr:'Akabe',ur:'العقبہ',id:'Aqaba',es:'Áqaba',bn:'আকাবা',ms:'Aqaba'},
        aliases: {ar:['العقبة','عقبة']},
        countryAr:'الأردن', countryEn:'Jordan', priority: 78 },

    // ══════════ Morocco (4) ══════════
    { slug: 'tangier', cc: 'ma', lat: 35.7595, lng: -5.8340, tz: 'Africa/Casablanca',
        names: {ar:'طنجة',en:'Tangier',fr:'Tanger',de:'Tanger',tr:'Tanca',ur:'طنجہ',id:'Tangier',es:'Tánger',bn:'ট্যাঞ্জিয়ার',ms:'Tangier'},
        aliases: {ar:['طنجة']},
        countryAr:'المغرب', countryEn:'Morocco', priority: 84 },
    { slug: 'agadir', cc: 'ma', lat: 30.4278, lng: -9.5981, tz: 'Africa/Casablanca',
        names: {ar:'أكادير',en:'Agadir',fr:'Agadir',de:'Agadir',tr:'Agadir',ur:'اگادیر',id:'Agadir',es:'Agadir',bn:'আগাদির',ms:'Agadir'},
        aliases: {ar:['أكادير','اكادير']},
        countryAr:'المغرب', countryEn:'Morocco', priority: 80 },
    { slug: 'meknes', cc: 'ma', lat: 33.8935, lng: -5.5473, tz: 'Africa/Casablanca',
        names: {ar:'مكناس',en:'Meknes',fr:'Meknès',de:'Meknès',tr:'Meknes',ur:'مکناس',id:'Meknes',es:'Mequinez',bn:'মেকনেস',ms:'Meknes'},
        aliases: {ar:['مكناس']},
        countryAr:'المغرب', countryEn:'Morocco', priority: 78 },
    { slug: 'tetouan', cc: 'ma', lat: 35.5785, lng: -5.3683, tz: 'Africa/Casablanca',
        names: {ar:'تطوان',en:'Tetouan',fr:'Tétouan',de:'Tétouan',tr:'Tetuan',ur:'تطوان',id:'Tetouan',es:'Tetuán',bn:'তেতুয়ান',ms:'Tetouan'},
        aliases: {ar:['تطوان']},
        countryAr:'المغرب', countryEn:'Morocco', priority: 76 },

    // ══════════ Algeria (4) ══════════
    { slug: 'annaba', cc: 'dz', lat: 36.9000, lng: 7.7667, tz: 'Africa/Algiers',
        names: {ar:'عنابة',en:'Annaba',fr:'Annaba',de:'Annaba',tr:'Annaba',ur:'عنابہ',id:'Annaba',es:'Annaba',bn:'আন্নাবা',ms:'Annaba'},
        aliases: {ar:['عنابة']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 80 },
    { slug: 'tlemcen', cc: 'dz', lat: 34.8826, lng: -1.3158, tz: 'Africa/Algiers',
        names: {ar:'تلمسان',en:'Tlemcen',fr:'Tlemcen',de:'Tlemcen',tr:'Tilimsan',ur:'تلمسان',id:'Tlemcen',es:'Tremecén',bn:'তেলেমসেন',ms:'Tlemcen'},
        aliases: {ar:['تلمسان']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 76 },
    { slug: 'setif', cc: 'dz', lat: 36.1900, lng: 5.4136, tz: 'Africa/Algiers',
        names: {ar:'سطيف',en:'Setif',fr:'Sétif',de:'Sétif',tr:'Setif',ur:'سطیف',id:'Setif',es:'Sétif',bn:'সেতিফ',ms:'Setif'},
        aliases: {ar:['سطيف']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 76 },
    { slug: 'batna', cc: 'dz', lat: 35.5559, lng: 6.1741, tz: 'Africa/Algiers',
        names: {ar:'باتنة',en:'Batna',fr:'Batna',de:'Batna',tr:'Batna',ur:'باتنہ',id:'Batna',es:'Batna',bn:'বাতনা',ms:'Batna'},
        aliases: {ar:['باتنة']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 74 },

    // ══════════ Tunisia (4) ══════════
    { slug: 'sousse', cc: 'tn', lat: 35.8254, lng: 10.6360, tz: 'Africa/Tunis',
        names: {ar:'سوسة',en:'Sousse',fr:'Sousse',de:'Sousse',tr:'Susa',ur:'سوسہ',id:'Sousse',es:'Susa',bn:'সুস',ms:'Sousse'},
        aliases: {ar:['سوسة']},
        countryAr:'تونس', countryEn:'Tunisia', priority: 82 },
    { slug: 'kairouan', cc: 'tn', lat: 35.6713, lng: 10.1009, tz: 'Africa/Tunis',
        names: {ar:'القيروان',en:'Kairouan',fr:'Kairouan',de:'Kairouan',tr:'Kayrevan',ur:'القیروان',id:'Kairouan',es:'Qayrawán',bn:'কায়রুয়ান',ms:'Kairouan'},
        aliases: {ar:['القيروان','قيروان']},
        countryAr:'تونس', countryEn:'Tunisia', priority: 80 },
    { slug: 'bizerte', cc: 'tn', lat: 37.2746, lng: 9.8739, tz: 'Africa/Tunis',
        names: {ar:'بنزرت',en:'Bizerte',fr:'Bizerte',de:'Biserta',tr:'Bizerte',ur:'بنزرت',id:'Bizerte',es:'Bizerta',bn:'বিজার্তে',ms:'Bizerte'},
        aliases: {ar:['بنزرت']},
        countryAr:'تونس', countryEn:'Tunisia', priority: 76 },
    { slug: 'gabes', cc: 'tn', lat: 33.8814, lng: 10.0982, tz: 'Africa/Tunis',
        names: {ar:'قابس',en:'Gabes',fr:'Gabès',de:'Gabès',tr:'Kabis',ur:'قابس',id:'Gabes',es:'Gabes',bn:'গাবেস',ms:'Gabes'},
        aliases: {ar:['قابس']},
        countryAr:'تونس', countryEn:'Tunisia', priority: 76 },

    // ══════════ Mauritania (2) ══════════
    { slug: 'nouadhibou', cc: 'mr', lat: 20.9303, lng: -17.0347, tz: 'Africa/Nouakchott',
        names: {ar:'نواذيبو',en:'Nouadhibou',fr:'Nouadhibou',de:'Nouadhibou',tr:'Nuvadibu',ur:'نواذیبو',id:'Nouadhibou',es:'Nuadibú',bn:'নুয়াধিবু',ms:'Nouadhibou'},
        aliases: {ar:['نواذيبو']},
        countryAr:'موريتانيا', countryEn:'Mauritania', priority: 76 },
    { slug: 'atar', cc: 'mr', lat: 20.5167, lng: -13.0500, tz: 'Africa/Nouakchott',
        names: {ar:'أطار',en:'Atar',fr:'Atar',de:'Atar',tr:'Atar',ur:'اطار',id:'Atar',es:'Atar',bn:'আতার',ms:'Atar'},
        aliases: {ar:['أطار','اطار']},
        countryAr:'موريتانيا', countryEn:'Mauritania', priority: 70 }
];

let added = 0;
for (const c of newCities) {
    if (seen.has(c.slug)) { console.log('  SKIP (exists)', c.slug); continue; }
    places.push({
        slug: c.slug, type: 'city', countryCode: c.cc,
        lat: c.lat, lng: c.lng, timezone: c.tz,
        names: c.names, aliases: c.aliases,
        admin: { countryAr: c.countryAr, countryEn: c.countryEn },
        priority: c.priority, source: 'curated', verified: true
    });
    seen.add(c.slug);
    added++;
}

fs.writeFileSync(PATH, JSON.stringify(places, null, 2) + '\n');
console.log('Added', added, 'cities. Total entries:', places.length);
const counts = places.reduce((a,p) => { a[p.countryCode]=(a[p.countryCode]||0)+1; return a; }, {});
console.log('Per-country counts:', counts);
