// One-shot seeder for GLOBAL-PLACE-SEARCH-CURATED-WORLD-EXP-WAVE-1
// Appends 110 cities to curated-places.json, focused on the regions
// most relevant to a prayer-times website: Arab/Islamic expansion +
// South Asia + Southeast Asia + Islamic Africa.
//
// Coverage (per user spec):
//   Saudi (12), Gulf (8), Iraq (2), Egypt (10), Sudan/Libya/Yemen (5),
//   Maghreb (7), Turkey (7), Iran (6), Central Asia (3),
//   South Asia (10), Southeast Asia (23), Islamic Africa (17)
//
// Priority scale (per user decision):
//   95 = capital / holy / globally important
//   90 = world-class or major Islamic city
//   85 = major city in its country
//   75 = regionally important
//   65 = complementary
//
// Slug convention: `city` for unique names, `city-cc` for collisions
// (e.g. hyderabad-pk because hyderabad-in already exists).
//
// Idempotent (skips entries that already exist by slug).
import fs from 'node:fs';

const PATH = './db/places/curated-places.json';
const places = JSON.parse(fs.readFileSync(PATH, 'utf8'));
const seen = new Set(places.map(p => p.slug));

const newCities = [
    // ══════════ Saudi Arabia (12) ══════════
    { slug: 'dammam', cc: 'sa', lat: 26.4207, lng: 50.0888, tz: 'Asia/Riyadh',
        names: {ar:'الدمام',en:'Dammam',fr:'Dammam',de:'Dammam',tr:'Dammam',ur:'دمام',id:'Dammam',es:'Dammam',bn:'দাম্মাম',ms:'Dammam'},
        aliases: {ar:['الدمام','دمام']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 90 },
    { slug: 'khobar', cc: 'sa', lat: 26.2172, lng: 50.1971, tz: 'Asia/Riyadh',
        names: {ar:'الخبر',en:'Khobar',fr:'Khobar',de:'al-Chubar',tr:'Khobar',ur:'خبر',id:'Khobar',es:'Khobar',bn:'খোবার',ms:'Khobar'},
        aliases: {ar:['الخبر','خبر'], en:['Al Khobar','Al-Khobar']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 85 },
    { slug: 'dhahran', cc: 'sa', lat: 26.2884, lng: 50.1136, tz: 'Asia/Riyadh',
        names: {ar:'الظهران',en:'Dhahran',fr:'Dhahran',de:'Dhahran',tr:'Zahran',ur:'ظہران',id:'Dhahran',es:'Dahrán',bn:'ধাহরান',ms:'Dhahran'},
        aliases: {ar:['الظهران','ظهران']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 82 },
    { slug: 'qatif', cc: 'sa', lat: 26.5654, lng: 49.9966, tz: 'Asia/Riyadh',
        names: {ar:'القطيف',en:'Qatif',fr:'Qatif',de:'al-Qatif',tr:'Katif',ur:'القطیف',id:'Qatif',es:'Qatif',bn:'কাতিফ',ms:'Qatif'},
        aliases: {ar:['القطيف','قطيف']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 80 },
    { slug: 'najran', cc: 'sa', lat: 17.4933, lng: 44.1277, tz: 'Asia/Riyadh',
        names: {ar:'نجران',en:'Najran',fr:'Nadjran',de:'Nadschran',tr:'Necran',ur:'نجران',id:'Najran',es:'Najran',bn:'নাজরান',ms:'Najran'},
        aliases: {ar:['نجران']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 78 },
    { slug: 'jazan', cc: 'sa', lat: 16.8896, lng: 42.5511, tz: 'Asia/Riyadh',
        names: {ar:'جازان',en:'Jazan',fr:'Djazan',de:'Dschazan',tr:'Cazan',ur:'جازان',id:'Jazan',es:'Yazán',bn:'জাজান',ms:'Jazan'},
        aliases: {ar:['جازان','جيزان']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 78 },
    { slug: 'unaizah', cc: 'sa', lat: 26.0843, lng: 43.9938, tz: 'Asia/Riyadh',
        names: {ar:'عنيزة',en:'Unaizah',fr:'Onaiza',de:'Unaiza',tr:'Uneyze',ur:'عنیزہ',id:'Unaizah',es:'Unaiza',bn:'উনাইজা',ms:'Unaizah'},
        aliases: {ar:['عنيزة'], en:['Onaiza']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 75 },
    { slug: 'hofuf', cc: 'sa', lat: 25.3833, lng: 49.5833, tz: 'Asia/Riyadh',
        names: {ar:'الهفوف',en:'Hofuf',fr:'Hofuf',de:'al-Hufuf',tr:'Hufuf',ur:'الہفوف',id:'Hofuf',es:'Hofuf',bn:'হোফুফ',ms:'Hofuf'},
        aliases: {ar:['الهفوف','هفوف','الأحساء','الاحساء'], en:['Al-Ahsa','Al Hasa']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 82 },
    { slug: 'al-kharj', cc: 'sa', lat: 24.1556, lng: 47.3119, tz: 'Asia/Riyadh',
        names: {ar:'الخرج',en:'Al Kharj',fr:'Al Kharj',de:'al-Charj',tr:'el-Harc',ur:'الخرج',id:'Al Kharj',es:'Al Kharj',bn:'আল-খারজ',ms:'Al Kharj'},
        aliases: {ar:['الخرج']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 75 },
    { slug: 'arar', cc: 'sa', lat: 30.9753, lng: 41.0381, tz: 'Asia/Riyadh',
        names: {ar:'عرعر',en:'Arar',fr:'Arar',de:'Arar',tr:'Arar',ur:'عرعر',id:'Arar',es:'Arar',bn:'আরার',ms:'Arar'},
        aliases: {ar:['عرعر']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 72 },
    { slug: 'sakaka', cc: 'sa', lat: 29.9697, lng: 40.2064, tz: 'Asia/Riyadh',
        names: {ar:'سكاكا',en:'Sakaka',fr:'Sakaka',de:'Sakaka',tr:'Sakaka',ur:'سکاکا',id:'Sakaka',es:'Sakaka',bn:'সাকাকা',ms:'Sakaka'},
        aliases: {ar:['سكاكا']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 72 },
    { slug: 'al-bahah', cc: 'sa', lat: 20.0129, lng: 41.4677, tz: 'Asia/Riyadh',
        names: {ar:'الباحة',en:'Al Bahah',fr:'Al Baha',de:'al-Baha',tr:'el-Baha',ur:'الباحہ',id:'Al Bahah',es:'Al Baha',bn:'আল-বাহাহ',ms:'Al Bahah'},
        aliases: {ar:['الباحة','الباحه'], en:['Al Baha']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 75 },

    // ══════════ Gulf (8) ══════════
    { slug: 'al-rayyan', cc: 'qa', lat: 25.2911, lng: 51.4234, tz: 'Asia/Qatar',
        names: {ar:'الريان',en:'Al Rayyan',fr:'Al Rayyan',de:'ar-Rayyan',tr:'Reyyan',ur:'الریان',id:'Al Rayyan',es:'Al Rayán',bn:'আল-রাইয়ান',ms:'Al Rayyan'},
        aliases: {ar:['الريان','ريان']},
        countryAr:'قطر', countryEn:'Qatar', priority: 85 },
    { slug: 'hawalli', cc: 'kw', lat: 29.3326, lng: 48.0285, tz: 'Asia/Kuwait',
        names: {ar:'حولي',en:'Hawalli',fr:'Hawalli',de:'Hawalli',tr:'Havalli',ur:'حولی',id:'Hawalli',es:'Hawali',bn:'হাওয়ালি',ms:'Hawalli'},
        aliases: {ar:['حولي']},
        countryAr:'الكويت', countryEn:'Kuwait', priority: 80 },
    { slug: 'salmiya', cc: 'kw', lat: 29.3399, lng: 48.0844, tz: 'Asia/Kuwait',
        names: {ar:'السالمية',en:'Salmiya',fr:'Salmiya',de:'Salmiya',tr:'Salmiye',ur:'سالمیہ',id:'Salmiya',es:'Salmiya',bn:'সালমিয়া',ms:'Salmiya'},
        aliases: {ar:['السالمية','سالمية']},
        countryAr:'الكويت', countryEn:'Kuwait', priority: 78 },
    { slug: 'muharraq', cc: 'bh', lat: 26.2572, lng: 50.6111, tz: 'Asia/Bahrain',
        names: {ar:'المحرق',en:'Muharraq',fr:'Mouharraq',de:'al-Muharraq',tr:'Muharrak',ur:'محرق',id:'Muharraq',es:'Muharraq',bn:'মুহাররাক',ms:'Muharraq'},
        aliases: {ar:['المحرق','محرق']},
        countryAr:'البحرين', countryEn:'Bahrain', priority: 80 },
    { slug: 'sohar', cc: 'om', lat: 24.3479, lng: 56.7297, tz: 'Asia/Muscat',
        names: {ar:'صحار',en:'Sohar',fr:'Sohar',de:'Sohar',tr:'Sohar',ur:'صحار',id:'Sohar',es:'Sohar',bn:'সোহার',ms:'Sohar'},
        aliases: {ar:['صحار']},
        countryAr:'سلطنة عمان', countryEn:'Oman', priority: 78 },
    { slug: 'nizwa', cc: 'om', lat: 22.9333, lng: 57.5333, tz: 'Asia/Muscat',
        names: {ar:'نزوى',en:'Nizwa',fr:'Nizwa',de:'Nizwa',tr:'Nizva',ur:'نزوی',id:'Nizwa',es:'Nizwa',bn:'নিজওয়া',ms:'Nizwa'},
        aliases: {ar:['نزوى']},
        countryAr:'سلطنة عمان', countryEn:'Oman', priority: 76 },
    { slug: 'ajman', cc: 'ae', lat: 25.4111, lng: 55.4350, tz: 'Asia/Dubai',
        names: {ar:'عجمان',en:'Ajman',fr:'Ajman',de:'Adschman',tr:'Ecman',ur:'عجمان',id:'Ajman',es:'Ajmán',bn:'আজমান',ms:'Ajman'},
        aliases: {ar:['عجمان']},
        countryAr:'الإمارات العربية المتحدة', countryEn:'United Arab Emirates', priority: 82 },
    { slug: 'fujairah', cc: 'ae', lat: 25.1288, lng: 56.3265, tz: 'Asia/Dubai',
        names: {ar:'الفجيرة',en:'Fujairah',fr:'Fujaïrah',de:'Fudschaira',tr:'Fucayra',ur:'فجیرہ',id:'Fujairah',es:'Fuyaira',bn:'ফুজাইরাহ',ms:'Fujairah'},
        aliases: {ar:['الفجيرة','فجيرة']},
        countryAr:'الإمارات العربية المتحدة', countryEn:'United Arab Emirates', priority: 80 },

    // ══════════ Iraq (2) ══════════
    { slug: 'duhok', cc: 'iq', lat: 36.8669, lng: 42.9886, tz: 'Asia/Baghdad',
        names: {ar:'دهوك',en:'Duhok',fr:'Dahuk',de:'Dohuk',tr:'Dohuk',ur:'دہوک',id:'Duhok',es:'Dahuk',bn:'দোহুক',ms:'Duhok'},
        aliases: {ar:['دهوك','دهوک'], ku:['دهۆک']},
        countryAr:'العراق', countryEn:'Iraq', priority: 76 },
    { slug: 'nasiriyah', cc: 'iq', lat: 31.0560, lng: 46.2575, tz: 'Asia/Baghdad',
        names: {ar:'الناصرية',en:'Nasiriyah',fr:'Nassiriya',de:'Nasiriya',tr:'Nasiriye',ur:'ناصریہ',id:'Nasiriyah',es:'Nasiriya',bn:'নাসিরিয়াহ',ms:'Nasiriyah'},
        aliases: {ar:['الناصرية','ناصرية']},
        countryAr:'العراق', countryEn:'Iraq', priority: 76 },

    // ══════════ Egypt (10) ══════════
    { slug: 'mansoura', cc: 'eg', lat: 31.0364, lng: 31.3807, tz: 'Africa/Cairo',
        names: {ar:'المنصورة',en:'Mansoura',fr:'Mansoura',de:'al-Mansura',tr:'Mansura',ur:'منصورہ',id:'Mansoura',es:'Mansura',bn:'মানসৌরা',ms:'Mansoura'},
        aliases: {ar:['المنصورة','منصورة','منصوره'], en:['El Mansoura','Al Mansurah']},
        countryAr:'مصر', countryEn:'Egypt', priority: 85 },
    { slug: 'tanta', cc: 'eg', lat: 30.7865, lng: 31.0004, tz: 'Africa/Cairo',
        names: {ar:'طنطا',en:'Tanta',fr:'Tanta',de:'Tanta',tr:'Tanta',ur:'طنطا',id:'Tanta',es:'Tanta',bn:'তান্তা',ms:'Tanta'},
        aliases: {ar:['طنطا']},
        countryAr:'مصر', countryEn:'Egypt', priority: 82 },
    { slug: 'zagazig', cc: 'eg', lat: 30.5878, lng: 31.5022, tz: 'Africa/Cairo',
        names: {ar:'الزقازيق',en:'Zagazig',fr:'Zagazig',de:'Zaqaziq',tr:'Zekazik',ur:'زقازیق',id:'Zagazig',es:'Zagazig',bn:'জাকাজিক',ms:'Zagazig'},
        aliases: {ar:['الزقازيق','زقازيق']},
        countryAr:'مصر', countryEn:'Egypt', priority: 78 },
    { slug: 'ismailia', cc: 'eg', lat: 30.5965, lng: 32.2715, tz: 'Africa/Cairo',
        names: {ar:'الإسماعيلية',en:'Ismailia',fr:'Ismaïlia',de:'Ismailia',tr:'İsmailiye',ur:'اسماعیلیہ',id:'Ismailia',es:'Ismailia',bn:'ইসমাইলিয়া',ms:'Ismailia'},
        aliases: {ar:['الإسماعيلية','اسماعيلية','الاسماعيلية']},
        countryAr:'مصر', countryEn:'Egypt', priority: 80 },
    { slug: 'asyut', cc: 'eg', lat: 27.1809, lng: 31.1837, tz: 'Africa/Cairo',
        names: {ar:'أسيوط',en:'Asyut',fr:'Assiout',de:'Asyut',tr:'Asyut',ur:'اسیوط',id:'Asyut',es:'Asiut',bn:'আসইউত',ms:'Asyut'},
        aliases: {ar:['أسيوط','اسيوط']},
        countryAr:'مصر', countryEn:'Egypt', priority: 80 },
    { slug: 'luxor', cc: 'eg', lat: 25.6872, lng: 32.6396, tz: 'Africa/Cairo',
        names: {ar:'الأقصر',en:'Luxor',fr:'Louxor',de:'Luxor',tr:'Luksor',ur:'الاقصر',id:'Luxor',es:'Luxor',bn:'লুক্সর',ms:'Luxor'},
        aliases: {ar:['الأقصر','الاقصر']},
        countryAr:'مصر', countryEn:'Egypt', priority: 85 },
    { slug: 'aswan', cc: 'eg', lat: 24.0889, lng: 32.8998, tz: 'Africa/Cairo',
        names: {ar:'أسوان',en:'Aswan',fr:'Assouan',de:'Assuan',tr:'Asvan',ur:'اسوان',id:'Aswan',es:'Asuán',bn:'আসওয়ান',ms:'Aswan'},
        aliases: {ar:['أسوان','اسوان']},
        countryAr:'مصر', countryEn:'Egypt', priority: 82 },
    { slug: 'fayoum', cc: 'eg', lat: 29.3084, lng: 30.8428, tz: 'Africa/Cairo',
        names: {ar:'الفيوم',en:'Fayoum',fr:'Fayoum',de:'Faijum',tr:'Feyyum',ur:'الفیوم',id:'Fayoum',es:'Fayum',bn:'ফাইউম',ms:'Fayoum'},
        aliases: {ar:['الفيوم','فيوم']},
        countryAr:'مصر', countryEn:'Egypt', priority: 78 },
    { slug: 'minya', cc: 'eg', lat: 28.0871, lng: 30.7618, tz: 'Africa/Cairo',
        names: {ar:'المنيا',en:'Minya',fr:'Minya',de:'al-Minya',tr:'Minya',ur:'منیا',id:'Minya',es:'Minya',bn:'মিনিয়া',ms:'Minya'},
        aliases: {ar:['المنيا','منيا']},
        countryAr:'مصر', countryEn:'Egypt', priority: 76 },
    { slug: 'sohag', cc: 'eg', lat: 26.5569, lng: 31.6948, tz: 'Africa/Cairo',
        names: {ar:'سوهاج',en:'Sohag',fr:'Sohag',de:'Sauhadsch',tr:'Suhac',ur:'سوہاج',id:'Sohag',es:'Sohag',bn:'সোহাগ',ms:'Sohag'},
        aliases: {ar:['سوهاج']},
        countryAr:'مصر', countryEn:'Egypt', priority: 76 },

    // ══════════ Sudan / Libya / Yemen (5) ══════════
    { slug: 'wad-madani', cc: 'sd', lat: 14.4015, lng: 33.5199, tz: 'Africa/Khartoum',
        names: {ar:'ود مدني',en:'Wad Madani',fr:'Wad Madani',de:'Wad Madani',tr:'Vad Medeni',ur:'وادی مدنی',id:'Wad Madani',es:'Wad Madani',bn:'ওয়াদ মাদানি',ms:'Wad Madani'},
        aliases: {ar:['ود مدني','ودمدني','مدني']},
        countryAr:'السودان', countryEn:'Sudan', priority: 78 },
    { slug: 'el-obeid', cc: 'sd', lat: 13.1828, lng: 30.2176, tz: 'Africa/Khartoum',
        names: {ar:'الأبيض',en:'El Obeid',fr:'El Obeid',de:'al-Ubayyid',tr:'el-Ubeyyid',ur:'العبید',id:'El Obeid',es:'El Obeid',bn:'এল-ওবেইদ',ms:'El Obeid'},
        aliases: {ar:['الأبيض','الابيض','الأُبيِّض'], en:['Al-Ubayyid']},
        countryAr:'السودان', countryEn:'Sudan', priority: 75 },
    { slug: 'derna', cc: 'ly', lat: 32.7569, lng: 22.6444, tz: 'Africa/Tripoli',
        names: {ar:'درنة',en:'Derna',fr:'Derna',de:'Darna',tr:'Derne',ur:'درنہ',id:'Derna',es:'Derna',bn:'দারনা',ms:'Derna'},
        aliases: {ar:['درنة']},
        countryAr:'ليبيا', countryEn:'Libya', priority: 75 },
    { slug: 'marib', cc: 'ye', lat: 15.4675, lng: 45.3220, tz: 'Asia/Aden',
        names: {ar:'مأرب',en:'Marib',fr:'Marib',de:'Marib',tr:'Marib',ur:'مأرب',id:'Marib',es:'Marib',bn:'মারিব',ms:'Marib'},
        aliases: {ar:['مأرب','ماأرب','مارب']},
        countryAr:'اليمن', countryEn:'Yemen', priority: 75 },
    { slug: 'dhamar', cc: 'ye', lat: 14.5500, lng: 44.4017, tz: 'Asia/Aden',
        names: {ar:'ذمار',en:'Dhamar',fr:'Dhamar',de:'Dhamar',tr:'Damar',ur:'ذمار',id:'Dhamar',es:'Dhamar',bn:'ধামার',ms:'Dhamar'},
        aliases: {ar:['ذمار']},
        countryAr:'اليمن', countryEn:'Yemen', priority: 72 },

    // ══════════ Maghreb (7) ══════════
    { slug: 'oujda', cc: 'ma', lat: 34.6814, lng: -1.9086, tz: 'Africa/Casablanca',
        names: {ar:'وجدة',en:'Oujda',fr:'Oujda',de:'Oujda',tr:'Vejde',ur:'وجدہ',id:'Oujda',es:'Uchda',bn:'ওজদা',ms:'Oujda'},
        aliases: {ar:['وجدة']},
        countryAr:'المغرب', countryEn:'Morocco', priority: 80 },
    { slug: 'kenitra', cc: 'ma', lat: 34.2610, lng: -6.5802, tz: 'Africa/Casablanca',
        names: {ar:'القنيطرة',en:'Kenitra',fr:'Kénitra',de:'Kenitra',tr:'Kenitra',ur:'قنیطرہ',id:'Kenitra',es:'Kenitra',bn:'কেনিত্রা',ms:'Kenitra'},
        aliases: {ar:['القنيطرة','قنيطرة']},
        countryAr:'المغرب', countryEn:'Morocco', priority: 78 },
    { slug: 'blida', cc: 'dz', lat: 36.4700, lng: 2.8277, tz: 'Africa/Algiers',
        names: {ar:'البليدة',en:'Blida',fr:'Blida',de:'Blida',tr:'Blida',ur:'بلیدہ',id:'Blida',es:'Blida',bn:'ব্লিদা',ms:'Blida'},
        aliases: {ar:['البليدة','بليدة']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 78 },
    { slug: 'bejaia', cc: 'dz', lat: 36.7525, lng: 5.0843, tz: 'Africa/Algiers',
        names: {ar:'بجاية',en:'Bejaia',fr:'Béjaïa',de:'Bejaia',tr:'Bicaya',ur:'بجایہ',id:'Bejaia',es:'Bujía',bn:'বেজাইয়া',ms:'Bejaia'},
        aliases: {ar:['بجاية']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 75 },
    { slug: 'ghardaia', cc: 'dz', lat: 32.4843, lng: 3.6731, tz: 'Africa/Algiers',
        names: {ar:'غرداية',en:'Ghardaia',fr:'Ghardaïa',de:'Ghardaia',tr:'Gardaya',ur:'غردایہ',id:'Ghardaia',es:'Gardaia',bn:'গারদাইয়া',ms:'Ghardaia'},
        aliases: {ar:['غرداية']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 75 },
    { slug: 'monastir', cc: 'tn', lat: 35.7780, lng: 10.8262, tz: 'Africa/Tunis',
        names: {ar:'المنستير',en:'Monastir',fr:'Monastir',de:'Monastir',tr:'Munestir',ur:'منستیر',id:'Monastir',es:'Monastir',bn:'মোনাস্তির',ms:'Monastir'},
        aliases: {ar:['المنستير','منستير']},
        countryAr:'تونس', countryEn:'Tunisia', priority: 75 },
    { slug: 'djerba', cc: 'tn', lat: 33.8076, lng: 10.8451, tz: 'Africa/Tunis',
        names: {ar:'جربة',en:'Djerba',fr:'Djerba',de:'Djerba',tr:'Cerbe',ur:'جربہ',id:'Djerba',es:'Yerba',bn:'জারবা',ms:'Djerba'},
        aliases: {ar:['جربة']},
        countryAr:'تونس', countryEn:'Tunisia', priority: 76 },

    // ══════════ Turkey (7) ══════════
    { slug: 'gaziantep', cc: 'tr', lat: 37.0662, lng: 37.3833, tz: 'Europe/Istanbul',
        names: {ar:'غازي عنتاب',en:'Gaziantep',fr:'Gaziantep',de:'Gaziantep',tr:'Gaziantep',ur:'غازی انتیپ',id:'Gaziantep',es:'Gaziantep',bn:'গাজিয়ান্তেপ',ms:'Gaziantep'},
        aliases: {ar:['غازي عنتاب','عنتاب','عينتاب'], tr:['Antep']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 85 },
    { slug: 'kayseri', cc: 'tr', lat: 38.7312, lng: 35.4787, tz: 'Europe/Istanbul',
        names: {ar:'قيصري',en:'Kayseri',fr:'Kayseri',de:'Kayseri',tr:'Kayseri',ur:'قیصری',id:'Kayseri',es:'Kayseri',bn:'কায়সারি',ms:'Kayseri'},
        aliases: {ar:['قيصري']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 78 },
    { slug: 'mersin', cc: 'tr', lat: 36.8121, lng: 34.6415, tz: 'Europe/Istanbul',
        names: {ar:'مرسين',en:'Mersin',fr:'Mersin',de:'Mersin',tr:'Mersin',ur:'مرسین',id:'Mersin',es:'Mersin',bn:'মেরসিন',ms:'Mersin'},
        aliases: {ar:['مرسين','مرسة']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 78 },
    { slug: 'diyarbakir', cc: 'tr', lat: 37.9144, lng: 40.2306, tz: 'Europe/Istanbul',
        names: {ar:'ديار بكر',en:'Diyarbakir',fr:'Diyarbakır',de:'Diyarbakır',tr:'Diyarbakır',ur:'دیار بکر',id:'Diyarbakir',es:'Diyarbakır',bn:'দিয়ারবাকির',ms:'Diyarbakir'},
        aliases: {ar:['ديار بكر','ديار بكير']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 80 },
    { slug: 'sanliurfa', cc: 'tr', lat: 37.1591, lng: 38.7969, tz: 'Europe/Istanbul',
        names: {ar:'شانلي أورفا',en:'Sanliurfa',fr:'Şanlıurfa',de:'Şanlıurfa',tr:'Şanlıurfa',ur:'شانلی اورفہ',id:'Sanliurfa',es:'Sanliurfa',bn:'শানলিউরফা',ms:'Sanliurfa'},
        aliases: {ar:['شانلي أورفا','الرها','أورفا','اورفا'], tr:['Urfa']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 78 },
    { slug: 'trabzon', cc: 'tr', lat: 41.0027, lng: 39.7178, tz: 'Europe/Istanbul',
        names: {ar:'طرابزون',en:'Trabzon',fr:'Trébizonde',de:'Trabzon',tr:'Trabzon',ur:'طرابزون',id:'Trabzon',es:'Trebisonda',bn:'ট্রাবজোন',ms:'Trabzon'},
        aliases: {ar:['طرابزون']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 78 },
    { slug: 'erzurum', cc: 'tr', lat: 39.9000, lng: 41.2700, tz: 'Europe/Istanbul',
        names: {ar:'أرضروم',en:'Erzurum',fr:'Erzurum',de:'Erzurum',tr:'Erzurum',ur:'ارضروم',id:'Erzurum',es:'Erzurum',bn:'এরজুরুম',ms:'Erzurum'},
        aliases: {ar:['أرضروم','ارضروم']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 76 },

    // ══════════ Iran (6) ══════════
    { slug: 'ahvaz', cc: 'ir', lat: 31.3203, lng: 48.6692, tz: 'Asia/Tehran',
        names: {ar:'الأهواز',en:'Ahvaz',fr:'Ahvaz',de:'Ahvaz',tr:'Ahvaz',ur:'اہواز',id:'Ahvaz',es:'Ahvaz',bn:'আহভাজ',ms:'Ahvaz'},
        aliases: {ar:['الأهواز','اهواز','الاهواز'], fa:['اهواز']},
        countryAr:'إيران', countryEn:'Iran', priority: 82 },
    { slug: 'kermanshah', cc: 'ir', lat: 34.3142, lng: 47.0650, tz: 'Asia/Tehran',
        names: {ar:'كرمانشاه',en:'Kermanshah',fr:'Kermanchah',de:'Kermanschah',tr:'Kirmanşah',ur:'کرمانشاہ',id:'Kermanshah',es:'Kermanshah',bn:'কেরমানশাহ',ms:'Kermanshah'},
        aliases: {ar:['كرمانشاه'], fa:['کرمانشاه']},
        countryAr:'إيران', countryEn:'Iran', priority: 78 },
    { slug: 'rasht', cc: 'ir', lat: 37.2809, lng: 49.5832, tz: 'Asia/Tehran',
        names: {ar:'رشت',en:'Rasht',fr:'Recht',de:'Rascht',tr:'Reşt',ur:'رشت',id:'Rasht',es:'Rasht',bn:'রাশত',ms:'Rasht'},
        aliases: {ar:['رشت'], fa:['رشت']},
        countryAr:'إيران', countryEn:'Iran', priority: 76 },
    { slug: 'yazd', cc: 'ir', lat: 31.8974, lng: 54.3569, tz: 'Asia/Tehran',
        names: {ar:'يزد',en:'Yazd',fr:'Yazd',de:'Yazd',tr:'Yezd',ur:'یزد',id:'Yazd',es:'Yazd',bn:'ইয়াজদ',ms:'Yazd'},
        aliases: {ar:['يزد'], fa:['یزد']},
        countryAr:'إيران', countryEn:'Iran', priority: 76 },
    { slug: 'kerman', cc: 'ir', lat: 30.2839, lng: 57.0834, tz: 'Asia/Tehran',
        names: {ar:'كرمان',en:'Kerman',fr:'Kerman',de:'Kerman',tr:'Kirman',ur:'کرمان',id:'Kerman',es:'Kermán',bn:'কেরমান',ms:'Kerman'},
        aliases: {ar:['كرمان'], fa:['کرمان']},
        countryAr:'إيران', countryEn:'Iran', priority: 76 },
    { slug: 'urmia', cc: 'ir', lat: 37.5527, lng: 45.0760, tz: 'Asia/Tehran',
        names: {ar:'أرومية',en:'Urmia',fr:'Ourmia',de:'Urmia',tr:'Urmiye',ur:'ارومیہ',id:'Urmia',es:'Urmia',bn:'উরমিয়া',ms:'Urmia'},
        aliases: {ar:['أرومية','ارومية'], fa:['ارومیه']},
        countryAr:'إيران', countryEn:'Iran', priority: 75 },

    // ══════════ Central Asia (3) ══════════
    { slug: 'bukhara', cc: 'uz', lat: 39.7681, lng: 64.4556, tz: 'Asia/Samarkand',
        names: {ar:'بخارى',en:'Bukhara',fr:'Boukhara',de:'Buchara',tr:'Buhara',ur:'بخارا',id:'Bukhara',es:'Bujará',bn:'বুখারা',ms:'Bukhara'},
        aliases: {ar:['بخارى','بخارا'], uz:['Buxoro']},
        countryAr:'أوزبكستان', countryEn:'Uzbekistan', priority: 85 },
    { slug: 'dushanbe', cc: 'tj', lat: 38.5358, lng: 68.7791, tz: 'Asia/Dushanbe',
        names: {ar:'دوشنبه',en:'Dushanbe',fr:'Douchanbé',de:'Duschanbe',tr:'Duşanbe',ur:'دوشنبہ',id:'Dushanbe',es:'Dusambé',bn:'দুশানবে',ms:'Dushanbe'},
        aliases: {ar:['دوشنبه','دوشانبي']},
        countryAr:'طاجيكستان', countryEn:'Tajikistan', priority: 85 },
    { slug: 'ashgabat', cc: 'tm', lat: 37.9601, lng: 58.3261, tz: 'Asia/Ashgabat',
        names: {ar:'عشق آباد',en:'Ashgabat',fr:'Achgabat',de:'Aschgabat',tr:'Aşkabat',ur:'عشق آباد',id:'Asgabat',es:'Asjabad',bn:'আশগাবাত',ms:'Ashgabat'},
        aliases: {ar:['عشق آباد','عشقاباد']},
        countryAr:'تركمانستان', countryEn:'Turkmenistan', priority: 85 },

    // ══════════ South Asia (10) ══════════
    { slug: 'bhopal', cc: 'in', lat: 23.2599, lng: 77.4126, tz: 'Asia/Kolkata',
        names: {ar:'بوبال',en:'Bhopal',fr:'Bhopal',de:'Bhopal',tr:'Bhopal',ur:'بھوپال',id:'Bhopal',es:'Bhopal',bn:'ভোপাল',ms:'Bhopal'},
        aliases: {ar:['بوبال','بھوبال'], hi:['भोपाल']},
        countryAr:'الهند', countryEn:'India', priority: 82 },
    { slug: 'patna', cc: 'in', lat: 25.5941, lng: 85.1376, tz: 'Asia/Kolkata',
        names: {ar:'باتنا',en:'Patna',fr:'Patna',de:'Patna',tr:'Patna',ur:'پٹنہ',id:'Patna',es:'Patna',bn:'পাটনা',ms:'Patna'},
        aliases: {ar:['باتنا'], hi:['पटना']},
        countryAr:'الهند', countryEn:'India', priority: 82 },
    { slug: 'srinagar', cc: 'in', lat: 34.0837, lng: 74.7973, tz: 'Asia/Kolkata',
        names: {ar:'سريناغار',en:'Srinagar',fr:'Srinagar',de:'Srinagar',tr:'Srinagar',ur:'سرینگر',id:'Srinagar',es:'Srinagar',bn:'শ্রীনগর',ms:'Srinagar'},
        aliases: {ar:['سريناغار','سريناجار'], hi:['श्रीनगर']},
        countryAr:'الهند', countryEn:'India', priority: 80 },
    { slug: 'kochi', cc: 'in', lat: 9.9312, lng: 76.2673, tz: 'Asia/Kolkata',
        names: {ar:'كوتشي',en:'Kochi',fr:'Kochi',de:'Kochi',tr:'Kochi',ur:'کوچی',id:'Kochi',es:'Kochi',bn:'কোচি',ms:'Kochi'},
        aliases: {ar:['كوتشي','كوشين'], en:['Cochin'], hi:['कोच्चि']},
        countryAr:'الهند', countryEn:'India', priority: 78 },
    { slug: 'hyderabad-pk', cc: 'pk', lat: 25.3960, lng: 68.3578, tz: 'Asia/Karachi',
        names: {ar:'حيدر آباد',en:'Hyderabad',fr:'Hyderabad',de:'Haidarabad',tr:'Haydarabad',ur:'حیدرآباد',id:'Hyderabad',es:'Hyderabad',bn:'হায়দারাবাদ',ms:'Hyderabad'},
        aliases: {ar:['حيدر آباد باكستان','حيدر آباد السند'], ur:['حیدرآباد سندھ']},
        countryAr:'باكستان', countryEn:'Pakistan', priority: 78 },
    { slug: 'sialkot', cc: 'pk', lat: 32.4945, lng: 74.5229, tz: 'Asia/Karachi',
        names: {ar:'سيالكوت',en:'Sialkot',fr:'Sialkot',de:'Sialkot',tr:'Sialkot',ur:'سیالکوٹ',id:'Sialkot',es:'Sialkot',bn:'শিয়ালকোট',ms:'Sialkot'},
        aliases: {ar:['سيالكوت']},
        countryAr:'باكستان', countryEn:'Pakistan', priority: 76 },
    { slug: 'barisal', cc: 'bd', lat: 22.7010, lng: 90.3535, tz: 'Asia/Dhaka',
        names: {ar:'باريسال',en:'Barisal',fr:'Barisal',de:'Barisal',tr:'Barisal',ur:'باریسال',id:'Barisal',es:'Barisal',bn:'বরিশাল',ms:'Barisal'},
        aliases: {ar:['باريسال','بريشال'], bn:['বরিশাল']},
        countryAr:'بنغلاديش', countryEn:'Bangladesh', priority: 78 },
    { slug: 'kandy', cc: 'lk', lat: 7.2906, lng: 80.6337, tz: 'Asia/Colombo',
        names: {ar:'كاندي',en:'Kandy',fr:'Kandy',de:'Kandy',tr:'Kandy',ur:'کینڈی',id:'Kandy',es:'Kandy',bn:'ক্যান্ডি',ms:'Kandy'},
        aliases: {ar:['كاندي'], si:['මහනුවර']},
        countryAr:'سريلانكا', countryEn:'Sri Lanka', priority: 76 },
    { slug: 'pokhara', cc: 'np', lat: 28.2096, lng: 83.9856, tz: 'Asia/Kathmandu',
        names: {ar:'بوكارا',en:'Pokhara',fr:'Pokhara',de:'Pokhara',tr:'Pokhara',ur:'پوکھرا',id:'Pokhara',es:'Pokhara',bn:'পোখারা',ms:'Pokhara'},
        aliases: {ar:['بوكارا'], ne:['पोखरा']},
        countryAr:'نيبال', countryEn:'Nepal', priority: 76 },
    { slug: 'male', cc: 'mv', lat: 4.1755, lng: 73.5093, tz: 'Indian/Maldives',
        names: {ar:'ماليه',en:'Male',fr:'Malé',de:'Malé',tr:'Male',ur:'مالے',id:'Malé',es:'Malé',bn:'মালে',ms:'Male'},
        aliases: {ar:['ماليه','ماليّه']},
        countryAr:'جزر المالديف', countryEn:'Maldives', priority: 85 },

    // ══════════ Southeast Asia: Indonesia (6) ══════════
    { slug: 'medan', cc: 'id', lat: 3.5952, lng: 98.6722, tz: 'Asia/Jakarta',
        names: {ar:'ميدان',en:'Medan',fr:'Medan',de:'Medan',tr:'Medan',ur:'میدان',id:'Medan',es:'Medan',bn:'মেদান',ms:'Medan'},
        aliases: {ar:['ميدان']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 85 },
    { slug: 'makassar', cc: 'id', lat: -5.1477, lng: 119.4327, tz: 'Asia/Makassar',
        names: {ar:'ماكاسار',en:'Makassar',fr:'Macassar',de:'Makassar',tr:'Makassar',ur:'ماکاسار',id:'Makassar',es:'Macasar',bn:'মাকাসার',ms:'Makassar'},
        aliases: {ar:['ماكاسار','مكاسر']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 82 },
    { slug: 'yogyakarta', cc: 'id', lat: -7.7956, lng: 110.3695, tz: 'Asia/Jakarta',
        names: {ar:'يوغياكارتا',en:'Yogyakarta',fr:'Yogyakarta',de:'Yogyakarta',tr:'Yogyakarta',ur:'یوگیاکارتا',id:'Yogyakarta',es:'Yogyakarta',bn:'যোগ্যকর্তা',ms:'Yogyakarta'},
        aliases: {ar:['يوغياكارتا','جوغياكارتا'], id:['Jogja','Jogjakarta']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 82 },
    { slug: 'semarang', cc: 'id', lat: -6.9667, lng: 110.4167, tz: 'Asia/Jakarta',
        names: {ar:'سيمارانغ',en:'Semarang',fr:'Semarang',de:'Semarang',tr:'Semarang',ur:'سمارنگ',id:'Semarang',es:'Semarang',bn:'সেমারাং',ms:'Semarang'},
        aliases: {ar:['سيمارانغ']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 78 },
    { slug: 'palembang', cc: 'id', lat: -2.9909, lng: 104.7565, tz: 'Asia/Jakarta',
        names: {ar:'باليمبانغ',en:'Palembang',fr:'Palembang',de:'Palembang',tr:'Palembang',ur:'پالمبنگ',id:'Palembang',es:'Palembang',bn:'পালেমবাং',ms:'Palembang'},
        aliases: {ar:['باليمبانغ']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 78 },
    { slug: 'banda-aceh', cc: 'id', lat: 5.5483, lng: 95.3238, tz: 'Asia/Jakarta',
        names: {ar:'باندا آتشيه',en:'Banda Aceh',fr:'Banda Aceh',de:'Banda Aceh',tr:'Banda Açe',ur:'بندا آچے',id:'Banda Aceh',es:'Banda Aceh',bn:'বান্দা আচেহ',ms:'Banda Aceh'},
        aliases: {ar:['باندا آتشيه','بندا أتشيه']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 80 },

    // ══════════ Southeast Asia: Malaysia (7) ══════════
    { slug: 'george-town', cc: 'my', lat: 5.4141, lng: 100.3288, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'جورج تاون',en:'George Town',fr:'George Town',de:'George Town',tr:'George Town',ur:'جارج ٹاؤن',id:'George Town',es:'George Town',bn:'জর্জ টাউন',ms:'George Town'},
        aliases: {ar:['جورج تاون','بينانغ','بنانج'], ms:['Pulau Pinang','Penang']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 82 },
    { slug: 'johor-bahru', cc: 'my', lat: 1.4927, lng: 103.7414, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'جوهور بهرو',en:'Johor Bahru',fr:'Johor Bahru',de:'Johor Bahru',tr:'Johor Bahru',ur:'جوہور بھارو',id:'Johor Bahru',es:'Johor Bahru',bn:'জোহোর বাহরু',ms:'Johor Bahru'},
        aliases: {ar:['جوهور بهرو']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 80 },
    { slug: 'ipoh', cc: 'my', lat: 4.5975, lng: 101.0901, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'إيبوه',en:'Ipoh',fr:'Ipoh',de:'Ipoh',tr:'Ipoh',ur:'ایپوہ',id:'Ipoh',es:'Ipoh',bn:'ইপোহ',ms:'Ipoh'},
        aliases: {ar:['إيبوه','ايبوه']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 76 },
    { slug: 'kota-kinabalu', cc: 'my', lat: 5.9804, lng: 116.0735, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'كوتا كينابالو',en:'Kota Kinabalu',fr:'Kota Kinabalu',de:'Kota Kinabalu',tr:'Kota Kinabalu',ur:'کوٹا کنابالو',id:'Kota Kinabalu',es:'Kota Kinabalu',bn:'কোতা কিনাবালু',ms:'Kota Kinabalu'},
        aliases: {ar:['كوتا كينابالو']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 78 },
    { slug: 'kuching', cc: 'my', lat: 1.5533, lng: 110.3592, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'كوتشينغ',en:'Kuching',fr:'Kuching',de:'Kuching',tr:'Kuching',ur:'کوچنگ',id:'Kuching',es:'Kuching',bn:'কুচিং',ms:'Kuching'},
        aliases: {ar:['كوتشينغ']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 76 },
    { slug: 'shah-alam', cc: 'my', lat: 3.0733, lng: 101.5185, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'شاه عالم',en:'Shah Alam',fr:'Shah Alam',de:'Shah Alam',tr:'Şah Alam',ur:'شاہ عالم',id:'Shah Alam',es:'Shah Alam',bn:'শাহ আলম',ms:'Shah Alam'},
        aliases: {ar:['شاه عالم']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 76 },
    { slug: 'malacca', cc: 'my', lat: 2.1896, lng: 102.2501, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'ملاكا',en:'Malacca',fr:'Malacca',de:'Malakka',tr:'Malakka',ur:'ملاکا',id:'Malaka',es:'Malaca',bn:'মালাক্কা',ms:'Melaka'},
        aliases: {ar:['ملاكا','ملقا'], en:['Melaka']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 80 },

    // ══════════ Southeast Asia: Thailand (3) ══════════
    { slug: 'chiang-mai', cc: 'th', lat: 18.7883, lng: 98.9853, tz: 'Asia/Bangkok',
        names: {ar:'شيانغ ماي',en:'Chiang Mai',fr:'Chiang Mai',de:'Chiang Mai',tr:'Chiang Mai',ur:'چیانگ مائی',id:'Chiang Mai',es:'Chiang Mai',bn:'চিয়াং মাই',ms:'Chiang Mai'},
        aliases: {ar:['شيانغ ماي'], th:['เชียงใหม่']},
        countryAr:'تايلاند', countryEn:'Thailand', priority: 82 },
    { slug: 'phuket', cc: 'th', lat: 7.8804, lng: 98.3923, tz: 'Asia/Bangkok',
        names: {ar:'بوكيت',en:'Phuket',fr:'Phuket',de:'Phuket',tr:'Phuket',ur:'پوکٹ',id:'Phuket',es:'Phuket',bn:'ফুকেট',ms:'Phuket'},
        aliases: {ar:['بوكيت'], th:['ภูเก็ต']},
        countryAr:'تايلاند', countryEn:'Thailand', priority: 80 },
    { slug: 'pattaya', cc: 'th', lat: 12.9236, lng: 100.8825, tz: 'Asia/Bangkok',
        names: {ar:'باتايا',en:'Pattaya',fr:'Pattaya',de:'Pattaya',tr:'Pattaya',ur:'پتایا',id:'Pattaya',es:'Pattaya',bn:'পাতায়া',ms:'Pattaya'},
        aliases: {ar:['باتايا'], th:['พัทยา']},
        countryAr:'تايلاند', countryEn:'Thailand', priority: 76 },

    // ══════════ Southeast Asia: Vietnam / Cambodia / Laos / Myanmar (4) ══════════
    { slug: 'da-nang', cc: 'vn', lat: 16.0544, lng: 108.2022, tz: 'Asia/Ho_Chi_Minh',
        names: {ar:'دا نانغ',en:'Da Nang',fr:'Da Nang',de:'Da Nang',tr:'Da Nang',ur:'دا نانگ',id:'Da Nang',es:'Da Nang',bn:'দা নাং',ms:'Da Nang'},
        aliases: {ar:['دا نانغ','دانانغ'], vi:['Đà Nẵng']},
        countryAr:'فيتنام', countryEn:'Vietnam', priority: 78 },
    { slug: 'siem-reap', cc: 'kh', lat: 13.3672, lng: 103.8448, tz: 'Asia/Phnom_Penh',
        names: {ar:'سيام ريب',en:'Siem Reap',fr:'Siem Reap',de:'Siem Reap',tr:'Siem Reap',ur:'سیم ریپ',id:'Siem Reap',es:'Siem Reap',bn:'সিম রিপ',ms:'Siem Reap'},
        aliases: {ar:['سيام ريب','سيم ريب'], km:['សៀមរាប']},
        countryAr:'كمبوديا', countryEn:'Cambodia', priority: 76 },
    { slug: 'vientiane', cc: 'la', lat: 17.9757, lng: 102.6331, tz: 'Asia/Vientiane',
        names: {ar:'فينتيان',en:'Vientiane',fr:'Vientiane',de:'Vientiane',tr:'Vientiane',ur:'وینتیان',id:'Vientiane',es:'Vientián',bn:'ভিয়েনতিয়েন',ms:'Vientiane'},
        aliases: {ar:['فينتيان','فيينتيان'], lo:['ວຽງຈັນ']},
        countryAr:'لاوس', countryEn:'Laos', priority: 85 },
    { slug: 'mandalay', cc: 'mm', lat: 21.9588, lng: 96.0891, tz: 'Asia/Yangon',
        names: {ar:'ماندالاي',en:'Mandalay',fr:'Mandalay',de:'Mandalay',tr:'Mandalay',ur:'منڈالے',id:'Mandalay',es:'Mandalay',bn:'মান্দালয়',ms:'Mandalay'},
        aliases: {ar:['ماندالاي','مانديلاي'], my:['မန္တလေး']},
        countryAr:'ميانمار', countryEn:'Myanmar', priority: 80 },

    // ══════════ Southeast Asia: Philippines (3) ══════════
    { slug: 'quezon-city', cc: 'ph', lat: 14.6760, lng: 121.0437, tz: 'Asia/Manila',
        names: {ar:'مدينة كيزون',en:'Quezon City',fr:'Quezon City',de:'Quezon City',tr:'Quezon City',ur:'کیزون سٹی',id:'Kota Quezon',es:'Ciudad Quezón',bn:'কেজন সিটি',ms:'Quezon City'},
        aliases: {ar:['مدينة كيزون','كويزون','كيزون']},
        countryAr:'الفلبين', countryEn:'Philippines', priority: 85 },
    { slug: 'cebu', cc: 'ph', lat: 10.3157, lng: 123.8854, tz: 'Asia/Manila',
        names: {ar:'سيبو',en:'Cebu',fr:'Cebu',de:'Cebu',tr:'Cebu',ur:'سیبو',id:'Cebu',es:'Cebú',bn:'সেবু',ms:'Cebu'},
        aliases: {ar:['سيبو']},
        countryAr:'الفلبين', countryEn:'Philippines', priority: 80 },
    { slug: 'davao', cc: 'ph', lat: 7.1907, lng: 125.4553, tz: 'Asia/Manila',
        names: {ar:'دافاو',en:'Davao',fr:'Davao',de:'Davao',tr:'Davao',ur:'داوائو',id:'Davao',es:'Dávao',bn:'দাভাও',ms:'Davao'},
        aliases: {ar:['دافاو']},
        countryAr:'الفلبين', countryEn:'Philippines', priority: 80 },

    // ══════════ Islamic Africa (17) ══════════
    { slug: 'kano', cc: 'ng', lat: 12.0022, lng: 8.5920, tz: 'Africa/Lagos',
        names: {ar:'كانو',en:'Kano',fr:'Kano',de:'Kano',tr:'Kano',ur:'کانو',id:'Kano',es:'Kano',bn:'কানো',ms:'Kano'},
        aliases: {ar:['كانو']},
        countryAr:'نيجيريا', countryEn:'Nigeria', priority: 88 },
    { slug: 'ibadan', cc: 'ng', lat: 7.3775, lng: 3.9470, tz: 'Africa/Lagos',
        names: {ar:'إبادان',en:'Ibadan',fr:'Ibadan',de:'Ibadan',tr:'Ibadan',ur:'ابادان',id:'Ibadan',es:'Ibadán',bn:'ইবাদান',ms:'Ibadan'},
        aliases: {ar:['إبادان','ابادان']},
        countryAr:'نيجيريا', countryEn:'Nigeria', priority: 82 },
    { slug: 'port-harcourt', cc: 'ng', lat: 4.8156, lng: 7.0498, tz: 'Africa/Lagos',
        names: {ar:'بورت هاركورت',en:'Port Harcourt',fr:'Port Harcourt',de:'Port Harcourt',tr:'Port Harcourt',ur:'پورٹ ہارکورٹ',id:'Port Harcourt',es:'Port Harcourt',bn:'পোর্ট হারকোর্ট',ms:'Port Harcourt'},
        aliases: {ar:['بورت هاركورت','بورت هاركورت']},
        countryAr:'نيجيريا', countryEn:'Nigeria', priority: 80 },
    { slug: 'mombasa', cc: 'ke', lat: -4.0435, lng: 39.6682, tz: 'Africa/Nairobi',
        names: {ar:'مومباسا',en:'Mombasa',fr:'Mombasa',de:'Mombasa',tr:'Mombasa',ur:'مومباسا',id:'Mombasa',es:'Mombasa',bn:'মোম্বাসা',ms:'Mombasa'},
        aliases: {ar:['مومباسا'], sw:['Mombasa']},
        countryAr:'كينيا', countryEn:'Kenya', priority: 82 },
    { slug: 'dire-dawa', cc: 'et', lat: 9.5915, lng: 41.8662, tz: 'Africa/Addis_Ababa',
        names: {ar:'ديري داوا',en:'Dire Dawa',fr:'Dire Dawa',de:'Dire Dawa',tr:'Dire Dawa',ur:'ڈائر داوا',id:'Dire Dawa',es:'Dire Dawa',bn:'দিরে দাওয়া',ms:'Dire Dawa'},
        aliases: {ar:['ديري داوا','دري داوا'], am:['ድሬ ዳዋ']},
        countryAr:'إثيوبيا', countryEn:'Ethiopia', priority: 78 },
    { slug: 'hargeisa', cc: 'so', lat: 9.5600, lng: 44.0650, tz: 'Africa/Mogadishu',
        names: {ar:'هرجيسا',en:'Hargeisa',fr:'Hargeisa',de:'Hargeisa',tr:'Hargeisa',ur:'ہرگیسا',id:'Hargeisa',es:'Hargeisa',bn:'হারগেইসা',ms:'Hargeisa'},
        aliases: {ar:['هرجيسا','هرجيسة'], so:['Hargeysa']},
        countryAr:'الصومال', countryEn:'Somalia', priority: 82 },
    { slug: 'djibouti-city', cc: 'dj', lat: 11.5886, lng: 43.1453, tz: 'Africa/Djibouti',
        names: {ar:'جيبوتي',en:'Djibouti',fr:'Djibouti',de:'Dschibuti',tr:'Cibuti',ur:'جیبوتی',id:'Djibouti',es:'Yibuti',bn:'জিবুতি',ms:'Djibouti'},
        aliases: {ar:['جيبوتي','مدينة جيبوتي'], en:['Djibouti City']},
        countryAr:'جيبوتي', countryEn:'Djibouti', priority: 88 },
    { slug: 'kumasi', cc: 'gh', lat: 6.6885, lng: -1.6244, tz: 'Africa/Accra',
        names: {ar:'كوماسي',en:'Kumasi',fr:'Kumasi',de:'Kumasi',tr:'Kumasi',ur:'کماسی',id:'Kumasi',es:'Kumasi',bn:'কুমাসি',ms:'Kumasi'},
        aliases: {ar:['كوماسي']},
        countryAr:'غانا', countryEn:'Ghana', priority: 80 },
    { slug: 'bamako', cc: 'ml', lat: 12.6392, lng: -8.0029, tz: 'Africa/Bamako',
        names: {ar:'باماكو',en:'Bamako',fr:'Bamako',de:'Bamako',tr:'Bamako',ur:'باماکو',id:'Bamako',es:'Bamako',bn:'বামাকো',ms:'Bamako'},
        aliases: {ar:['باماكو']},
        countryAr:'مالي', countryEn:'Mali', priority: 88 },
    { slug: 'conakry', cc: 'gn', lat: 9.6412, lng: -13.5784, tz: 'Africa/Conakry',
        names: {ar:'كوناكري',en:'Conakry',fr:'Conakry',de:'Conakry',tr:'Conakry',ur:'کوناکری',id:'Conakry',es:'Conakri',bn:'কোনাকরি',ms:'Conakry'},
        aliases: {ar:['كوناكري']},
        countryAr:'غينيا', countryEn:'Guinea', priority: 85 },
    { slug: 'freetown', cc: 'sl', lat: 8.4657, lng: -13.2317, tz: 'Africa/Freetown',
        names: {ar:'فريتاون',en:'Freetown',fr:'Freetown',de:'Freetown',tr:'Freetown',ur:'فری ٹاؤن',id:'Freetown',es:'Freetown',bn:'ফ্রিটাউন',ms:'Freetown'},
        aliases: {ar:['فريتاون']},
        countryAr:'سيراليون', countryEn:'Sierra Leone', priority: 85 },
    { slug: 'monrovia', cc: 'lr', lat: 6.3007, lng: -10.7969, tz: 'Africa/Monrovia',
        names: {ar:'مونروفيا',en:'Monrovia',fr:'Monrovia',de:'Monrovia',tr:'Monrovia',ur:'مونروویا',id:'Monrovia',es:'Monrovia',bn:'মনরোভিয়া',ms:'Monrovia'},
        aliases: {ar:['مونروفيا']},
        countryAr:'ليبيريا', countryEn:'Liberia', priority: 85 },
    { slug: 'abidjan', cc: 'ci', lat: 5.3600, lng: -4.0083, tz: 'Africa/Abidjan',
        names: {ar:'أبيدجان',en:'Abidjan',fr:'Abidjan',de:'Abidjan',tr:'Abican',ur:'ابیجان',id:'Abidjan',es:'Abiyán',bn:'আবিদজান',ms:'Abidjan'},
        aliases: {ar:['أبيدجان','ابيدجان']},
        countryAr:'ساحل العاج', countryEn:"Côte d'Ivoire", priority: 88 },
    { slug: 'ouagadougou', cc: 'bf', lat: 12.3714, lng: -1.5197, tz: 'Africa/Ouagadougou',
        names: {ar:'واغادوغو',en:'Ouagadougou',fr:'Ouagadougou',de:'Ouagadougou',tr:'Vagadugu',ur:'واگاڈوگو',id:'Ouagadougou',es:'Uagadugú',bn:'ওয়াগাদোগো',ms:'Ouagadougou'},
        aliases: {ar:['واغادوغو','واغادوغو']},
        countryAr:'بوركينا فاسو', countryEn:'Burkina Faso', priority: 85 },
    { slug: 'niamey', cc: 'ne', lat: 13.5117, lng: 2.1251, tz: 'Africa/Niamey',
        names: {ar:'نيامي',en:'Niamey',fr:'Niamey',de:'Niamey',tr:'Niamey',ur:'نیامے',id:'Niamey',es:'Niamey',bn:'নিয়ামে',ms:'Niamey'},
        aliases: {ar:['نيامي']},
        countryAr:'النيجر', countryEn:'Niger', priority: 85 },
    { slug: 'ndjamena', cc: 'td', lat: 12.1348, lng: 15.0557, tz: 'Africa/Ndjamena',
        names: {ar:'نجامينا',en:"N'Djamena",fr:"N'Djaména",de:"N'Djamena",tr:"N'Djamena",ur:'نجامینا',id:"N'Djamena",es:"Yamena",bn:'নাজামেনা',ms:"N'Djamena"},
        aliases: {ar:['نجامينا','أنجمينا','إنجمينا']},
        countryAr:'تشاد', countryEn:'Chad', priority: 85 },
    { slug: 'yaounde', cc: 'cm', lat: 3.8480, lng: 11.5021, tz: 'Africa/Douala',
        names: {ar:'ياوندي',en:'Yaounde',fr:'Yaoundé',de:'Yaoundé',tr:'Yaoundé',ur:'یاؤنڈے',id:'Yaoundé',es:'Yaundé',bn:'ইয়াউন্দে',ms:'Yaoundé'},
        aliases: {ar:['ياوندي']},
        countryAr:'الكاميرون', countryEn:'Cameroon', priority: 85 },
    { slug: 'zanzibar', cc: 'tz', lat: -6.1659, lng: 39.2026, tz: 'Africa/Dar_es_Salaam',
        names: {ar:'زنجبار',en:'Zanzibar',fr:'Zanzibar',de:'Sansibar',tr:'Zanzibar',ur:'زنجبار',id:'Zanzibar',es:'Zanzíbar',bn:'জাঞ্জিবার',ms:'Zanzibar'},
        aliases: {ar:['زنجبار','زنجبار سيتي'], sw:['Mji wa Zanzibar']},
        countryAr:'تنزانيا', countryEn:'Tanzania', priority: 85 }
];

let added = 0;
for (const c of newCities) {
    if (seen.has(c.slug)) { console.log('  SKIP (exists)', c.slug); continue; }
    places.push({
        slug: c.slug, type: 'city', countryCode: c.cc,
        lat: c.lat, lng: c.lng, timezone: c.tz,
        names: c.names, aliases: c.aliases,
        admin: { countryAr: c.countryAr, countryEn: c.countryEn },
        priority: c.priority, source: 'curated', verified: true
    });
    seen.add(c.slug);
    added++;
}

fs.writeFileSync(PATH, JSON.stringify(places, null, 2) + '\n');
console.log('Added', added, 'cities. Total entries:', places.length);
const counts = places.reduce((a,p) => { a[p.countryCode]=(a[p.countryCode]||0)+1; return a; }, {});
console.log('Per-country counts:', counts);
