// One-shot seeder for GLOBAL-PLACE-SEARCH-CURATED-150-1 — appends 148
// strategic cities to curated-places.json so they hit tier 1 (curated,
// in-process, no external) regardless of language.
//
// Each entry includes:
//   - slug (URL-safe, unique)
//   - type, countryCode, lat, lng, timezone (IANA)
//   - names in all 10 supported langs (ar/en/fr/de/tr/ur/id/es/bn/ms)
//   - aliases (multi-script + common spellings)
//   - admin.countryAr / admin.countryEn
//   - priority (60–100)
//
// Idempotent (skips entries that already exist by slug).
import fs from 'node:fs';

const PATH = './db/places/curated-places.json';
const places = JSON.parse(fs.readFileSync(PATH, 'utf8'));
const seen = new Set(places.map(p => p.slug));

const newCities = [
    // ── USA (10) ──
    { slug: 'los-angeles', cc: 'us', lat: 34.0522, lng: -118.2437, tz: 'America/Los_Angeles',
        names: {ar:'لوس أنجلوس',en:'Los Angeles',fr:'Los Angeles',de:'Los Angeles',tr:'Los Angeles',ur:'لاس اینجلس',id:'Los Angeles',es:'Los Ángeles',bn:'লস অ্যাঞ্জেলেস',ms:'Los Angeles'},
        aliases: {en:['LA','L.A.'], ar:['لوس انجلوس','لوس انجليس']},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 92 },
    { slug: 'chicago', cc: 'us', lat: 41.8781, lng: -87.6298, tz: 'America/Chicago',
        names: {ar:'شيكاغو',en:'Chicago',fr:'Chicago',de:'Chicago',tr:'Şikago',ur:'شکاگو',id:'Chicago',es:'Chicago',bn:'শিকাগো',ms:'Chicago'},
        aliases: {en:[]},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 88 },
    { slug: 'houston', cc: 'us', lat: 29.7604, lng: -95.3698, tz: 'America/Chicago',
        names: {ar:'هيوستن',en:'Houston',fr:'Houston',de:'Houston',tr:'Houston',ur:'ہیوسٹن',id:'Houston',es:'Houston',bn:'হিউস্টন',ms:'Houston'},
        aliases: {en:[]},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 85 },
    { slug: 'phoenix', cc: 'us', lat: 33.4484, lng: -112.0740, tz: 'America/Phoenix',
        names: {ar:'فينيكس',en:'Phoenix',fr:'Phoenix',de:'Phoenix',tr:'Phoenix',ur:'فینکس',id:'Phoenix',es:'Phoenix',bn:'ফিনিক্স',ms:'Phoenix'},
        aliases: {en:[]},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 80 },
    { slug: 'san-francisco', cc: 'us', lat: 37.7749, lng: -122.4194, tz: 'America/Los_Angeles',
        names: {ar:'سان فرانسيسكو',en:'San Francisco',fr:'San Francisco',de:'San Francisco',tr:'San Francisco',ur:'سان فرانسسکو',id:'San Francisco',es:'San Francisco',bn:'সান ফ্রান্সিসকো',ms:'San Francisco'},
        aliases: {en:['SF','San Fran']},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 88 },
    { slug: 'dallas', cc: 'us', lat: 32.7767, lng: -96.7970, tz: 'America/Chicago',
        names: {ar:'دالاس',en:'Dallas',fr:'Dallas',de:'Dallas',tr:'Dallas',ur:'ڈلاس',id:'Dallas',es:'Dallas',bn:'ডালাস',ms:'Dallas'},
        aliases: {en:[]},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 82 },
    { slug: 'washington-dc', cc: 'us', lat: 38.9072, lng: -77.0369, tz: 'America/New_York',
        names: {ar:'واشنطن',en:'Washington',fr:'Washington',de:'Washington',tr:'Washington',ur:'واشنگٹن',id:'Washington',es:'Washington',bn:'ওয়াশিংটন',ms:'Washington'},
        aliases: {en:['Washington DC','Washington, D.C.'], ar:['واشنطن العاصمة','واشنطن دي سي']},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 95 },
    { slug: 'seattle', cc: 'us', lat: 47.6062, lng: -122.3321, tz: 'America/Los_Angeles',
        names: {ar:'سياتل',en:'Seattle',fr:'Seattle',de:'Seattle',tr:'Seattle',ur:'سیئٹل',id:'Seattle',es:'Seattle',bn:'সিয়াটল',ms:'Seattle'},
        aliases: {en:[]},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 82 },
    { slug: 'boston', cc: 'us', lat: 42.3601, lng: -71.0589, tz: 'America/New_York',
        names: {ar:'بوسطن',en:'Boston',fr:'Boston',de:'Boston',tr:'Boston',ur:'بوسٹن',id:'Boston',es:'Boston',bn:'বোস্টন',ms:'Boston'},
        aliases: {en:[]},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 82 },
    { slug: 'miami', cc: 'us', lat: 25.7617, lng: -80.1918, tz: 'America/New_York',
        names: {ar:'ميامي',en:'Miami',fr:'Miami',de:'Miami',tr:'Miami',ur:'میامی',id:'Miami',es:'Miami',bn:'মায়ামি',ms:'Miami'},
        aliases: {en:[]},
        countryAr:'الولايات المتحدة', countryEn:'United States', priority: 85 },

    // ── Canada (4) ──
    { slug: 'toronto', cc: 'ca', lat: 43.6532, lng: -79.3832, tz: 'America/Toronto',
        names: {ar:'تورنتو',en:'Toronto',fr:'Toronto',de:'Toronto',tr:'Toronto',ur:'ٹورنٹو',id:'Toronto',es:'Toronto',bn:'টরন্টো',ms:'Toronto'},
        aliases: {en:[]},
        countryAr:'كندا', countryEn:'Canada', priority: 90 },
    { slug: 'vancouver', cc: 'ca', lat: 49.2827, lng: -123.1207, tz: 'America/Vancouver',
        names: {ar:'فانكوفر',en:'Vancouver',fr:'Vancouver',de:'Vancouver',tr:'Vancouver',ur:'وینکوور',id:'Vancouver',es:'Vancouver',bn:'ভ্যাঙ্কুভার',ms:'Vancouver'},
        aliases: {en:[]},
        countryAr:'كندا', countryEn:'Canada', priority: 88 },
    { slug: 'calgary', cc: 'ca', lat: 51.0447, lng: -114.0719, tz: 'America/Edmonton',
        names: {ar:'كالغاري',en:'Calgary',fr:'Calgary',de:'Calgary',tr:'Calgary',ur:'کیلگری',id:'Calgary',es:'Calgary',bn:'ক্যালগারি',ms:'Calgary'},
        aliases: {en:[]},
        countryAr:'كندا', countryEn:'Canada', priority: 80 },
    { slug: 'ottawa', cc: 'ca', lat: 45.4215, lng: -75.6972, tz: 'America/Toronto',
        names: {ar:'أوتاوا',en:'Ottawa',fr:'Ottawa',de:'Ottawa',tr:'Ottawa',ur:'اوٹاوا',id:'Ottawa',es:'Ottawa',bn:'অটোয়া',ms:'Ottawa'},
        aliases: {en:[]},
        countryAr:'كندا', countryEn:'Canada', priority: 92 },

    // ── UK (4) ──
    { slug: 'manchester', cc: 'gb', lat: 53.4808, lng: -2.2426, tz: 'Europe/London',
        names: {ar:'مانشستر',en:'Manchester',fr:'Manchester',de:'Manchester',tr:'Manchester',ur:'مانچسٹر',id:'Manchester',es:'Mánchester',bn:'ম্যানচেস্টার',ms:'Manchester'},
        aliases: {en:[]},
        countryAr:'المملكة المتحدة', countryEn:'United Kingdom', priority: 85 },
    { slug: 'birmingham', cc: 'gb', lat: 52.4862, lng: -1.8904, tz: 'Europe/London',
        names: {ar:'برمنغهام',en:'Birmingham',fr:'Birmingham',de:'Birmingham',tr:'Birmingham',ur:'برمنگھم',id:'Birmingham',es:'Birmingham',bn:'বার্মিংহাম',ms:'Birmingham'},
        aliases: {en:[]},
        countryAr:'المملكة المتحدة', countryEn:'United Kingdom', priority: 82 },
    { slug: 'edinburgh', cc: 'gb', lat: 55.9533, lng: -3.1883, tz: 'Europe/London',
        names: {ar:'إدنبرة',en:'Edinburgh',fr:'Édimbourg',de:'Edinburgh',tr:'Edinburgh',ur:'ایڈنبرا',id:'Edinburgh',es:'Edimburgo',bn:'এডিনবরা',ms:'Edinburgh'},
        aliases: {en:[]},
        countryAr:'المملكة المتحدة', countryEn:'United Kingdom', priority: 80 },
    { slug: 'glasgow', cc: 'gb', lat: 55.8642, lng: -4.2518, tz: 'Europe/London',
        names: {ar:'غلاسكو',en:'Glasgow',fr:'Glasgow',de:'Glasgow',tr:'Glasgow',ur:'گلاسگو',id:'Glasgow',es:'Glasgow',bn:'গ্লাসগো',ms:'Glasgow'},
        aliases: {en:[]},
        countryAr:'المملكة المتحدة', countryEn:'United Kingdom', priority: 78 },

    // ── France (5) ──
    { slug: 'marseille', cc: 'fr', lat: 43.2965, lng: 5.3698, tz: 'Europe/Paris',
        names: {ar:'مرسيليا',en:'Marseille',fr:'Marseille',de:'Marseille',tr:'Marsilya',ur:'مارسائی',id:'Marseille',es:'Marsella',bn:'মার্সেই',ms:'Marseille'},
        aliases: {en:['Marseilles']},
        countryAr:'فرنسا', countryEn:'France', priority: 85 },
    { slug: 'lyon', cc: 'fr', lat: 45.7640, lng: 4.8357, tz: 'Europe/Paris',
        names: {ar:'ليون',en:'Lyon',fr:'Lyon',de:'Lyon',tr:'Lyon',ur:'لیون',id:'Lyon',es:'Lyon',bn:'লিয়ঁ',ms:'Lyon'},
        aliases: {en:[]},
        countryAr:'فرنسا', countryEn:'France', priority: 82 },
    { slug: 'toulouse', cc: 'fr', lat: 43.6047, lng: 1.4442, tz: 'Europe/Paris',
        names: {ar:'تولوز',en:'Toulouse',fr:'Toulouse',de:'Toulouse',tr:'Toulouse',ur:'تولوز',id:'Toulouse',es:'Tolosa',bn:'তুলুজ',ms:'Toulouse'},
        aliases: {en:[]},
        countryAr:'فرنسا', countryEn:'France', priority: 78 },
    { slug: 'nice-fr', cc: 'fr', lat: 43.7102, lng: 7.2620, tz: 'Europe/Paris',
        names: {ar:'نيس',en:'Nice',fr:'Nice',de:'Nizza',tr:'Nis',ur:'نائس',id:'Nice',es:'Niza',bn:'নিস',ms:'Nice'},
        aliases: {en:[]},
        countryAr:'فرنسا', countryEn:'France', priority: 78 },
    { slug: 'bordeaux', cc: 'fr', lat: 44.8378, lng: -0.5792, tz: 'Europe/Paris',
        names: {ar:'بوردو',en:'Bordeaux',fr:'Bordeaux',de:'Bordeaux',tr:'Bordeaux',ur:'بوردو',id:'Bordeaux',es:'Burdeos',bn:'বর্দো',ms:'Bordeaux'},
        aliases: {en:[]},
        countryAr:'فرنسا', countryEn:'France', priority: 76 },

    // ── Spain (2) ──
    { slug: 'palma-de-mallorca', cc: 'es', lat: 39.5696, lng: 2.6502, tz: 'Europe/Madrid',
        names: {ar:'بالما دي مايوركا',en:'Palma de Mallorca',fr:'Palma de Majorque',de:'Palma de Mallorca',tr:'Palma de Mallorca',ur:'پالما دی میورکا',id:'Palma de Mallorca',es:'Palma de Mallorca',bn:'পালমা দে মায়োরকা',ms:'Palma de Mallorca'},
        aliases: {en:['Palma']},
        countryAr:'إسبانيا', countryEn:'Spain', priority: 76 },
    { slug: 'bilbao', cc: 'es', lat: 43.2630, lng: -2.9350, tz: 'Europe/Madrid',
        names: {ar:'بلباو',en:'Bilbao',fr:'Bilbao',de:'Bilbao',tr:'Bilbao',ur:'بلباؤ',id:'Bilbao',es:'Bilbao',bn:'বিলবাও',ms:'Bilbao'},
        aliases: {en:[]},
        countryAr:'إسبانيا', countryEn:'Spain', priority: 76 },

    // ── Northern Europe (5) ──
    { slug: 'stockholm', cc: 'se', lat: 59.3293, lng: 18.0686, tz: 'Europe/Stockholm',
        names: {ar:'ستوكهولم',en:'Stockholm',fr:'Stockholm',de:'Stockholm',tr:'Stockholm',ur:'سٹاک ہوم',id:'Stockholm',es:'Estocolmo',bn:'স্টকহোম',ms:'Stockholm'},
        aliases: {sv:['Stockholm']},
        countryAr:'السويد', countryEn:'Sweden', priority: 90 },
    { slug: 'oslo', cc: 'no', lat: 59.9139, lng: 10.7522, tz: 'Europe/Oslo',
        names: {ar:'أوسلو',en:'Oslo',fr:'Oslo',de:'Oslo',tr:'Oslo',ur:'اوسلو',id:'Oslo',es:'Oslo',bn:'অসলো',ms:'Oslo'},
        aliases: {no:['Oslo']},
        countryAr:'النرويج', countryEn:'Norway', priority: 90 },
    { slug: 'copenhagen', cc: 'dk', lat: 55.6761, lng: 12.5683, tz: 'Europe/Copenhagen',
        names: {ar:'كوبنهاغن',en:'Copenhagen',fr:'Copenhague',de:'Kopenhagen',tr:'Kopenhag',ur:'کوپن ہیگن',id:'Kopenhagen',es:'Copenhague',bn:'কোপেনহেগেন',ms:'Copenhagen'},
        aliases: {da:['København']},
        countryAr:'الدنمارك', countryEn:'Denmark', priority: 90 },
    { slug: 'helsinki', cc: 'fi', lat: 60.1699, lng: 24.9384, tz: 'Europe/Helsinki',
        names: {ar:'هلسنكي',en:'Helsinki',fr:'Helsinki',de:'Helsinki',tr:'Helsinki',ur:'ہلسنکی',id:'Helsinki',es:'Helsinki',bn:'হেলসিঙ্কি',ms:'Helsinki'},
        aliases: {fi:['Helsinki']},
        countryAr:'فنلندا', countryEn:'Finland', priority: 90 },
    { slug: 'reykjavik', cc: 'is', lat: 64.1466, lng: -21.9426, tz: 'Atlantic/Reykjavik',
        names: {ar:'ريكيافيك',en:'Reykjavik',fr:'Reykjavik',de:'Reykjavík',tr:'Reykjavik',ur:'ریکجاوک',id:'Reykjavik',es:'Reikiavik',bn:'রেইকিয়াভিক',ms:'Reykjavik'},
        aliases: {is:['Reykjavík']},
        countryAr:'آيسلندا', countryEn:'Iceland', priority: 88 },

    // ── Benelux + Ireland (5) ──
    { slug: 'amsterdam', cc: 'nl', lat: 52.3676, lng: 4.9041, tz: 'Europe/Amsterdam',
        names: {ar:'أمستردام',en:'Amsterdam',fr:'Amsterdam',de:'Amsterdam',tr:'Amsterdam',ur:'ایمسٹرڈیم',id:'Amsterdam',es:'Ámsterdam',bn:'আমস্টারডাম',ms:'Amsterdam'},
        aliases: {nl:['Amsterdam']},
        countryAr:'هولندا', countryEn:'Netherlands', priority: 92 },
    { slug: 'brussels', cc: 'be', lat: 50.8503, lng: 4.3517, tz: 'Europe/Brussels',
        names: {ar:'بروكسل',en:'Brussels',fr:'Bruxelles',de:'Brüssel',tr:'Brüksel',ur:'برسلز',id:'Brussel',es:'Bruselas',bn:'ব্রাসেলস',ms:'Brussels'},
        aliases: {nl:['Brussel']},
        countryAr:'بلجيكا', countryEn:'Belgium', priority: 92 },
    { slug: 'luxembourg-city', cc: 'lu', lat: 49.6116, lng: 6.1319, tz: 'Europe/Luxembourg',
        names: {ar:'لوكسمبورغ',en:'Luxembourg',fr:'Luxembourg',de:'Luxemburg',tr:'Lüksemburg',ur:'لکسمبرگ',id:'Luksemburg',es:'Luxemburgo',bn:'লুক্সেমবার্গ',ms:'Luxembourg'},
        aliases: {en:['Luxembourg City'], lb:['Lëtzebuerg']},
        countryAr:'لوكسمبورغ', countryEn:'Luxembourg', priority: 86 },
    { slug: 'the-hague', cc: 'nl', lat: 52.0705, lng: 4.3007, tz: 'Europe/Amsterdam',
        names: {ar:'لاهاي',en:'The Hague',fr:'La Haye',de:'Den Haag',tr:'Lahey',ur:'دی ہیگ',id:'Den Haag',es:'La Haya',bn:'দ্য হেগ',ms:'The Hague'},
        aliases: {nl:['Den Haag',"'s-Gravenhage"]},
        countryAr:'هولندا', countryEn:'Netherlands', priority: 80 },
    { slug: 'dublin', cc: 'ie', lat: 53.3498, lng: -6.2603, tz: 'Europe/Dublin',
        names: {ar:'دبلن',en:'Dublin',fr:'Dublin',de:'Dublin',tr:'Dublin',ur:'ڈبلن',id:'Dublin',es:'Dublín',bn:'ডাবলিন',ms:'Dublin'},
        aliases: {ga:['Baile Átha Cliath']},
        countryAr:'أيرلندا', countryEn:'Ireland', priority: 90 },

    // ── Central/Eastern Europe (13) ──
    { slug: 'warsaw', cc: 'pl', lat: 52.2297, lng: 21.0122, tz: 'Europe/Warsaw',
        names: {ar:'وارسو',en:'Warsaw',fr:'Varsovie',de:'Warschau',tr:'Varşova',ur:'وارسا',id:'Warsawa',es:'Varsovia',bn:'ওয়ারশ',ms:'Warsaw'},
        aliases: {pl:['Warszawa']},
        countryAr:'بولندا', countryEn:'Poland', priority: 90 },
    { slug: 'krakow', cc: 'pl', lat: 50.0647, lng: 19.9450, tz: 'Europe/Warsaw',
        names: {ar:'كراكوف',en:'Krakow',fr:'Cracovie',de:'Krakau',tr:'Krakov',ur:'کراکوف',id:'Krakow',es:'Cracovia',bn:'ক্রাকো',ms:'Krakow'},
        aliases: {en:['Cracow'], pl:['Kraków']},
        countryAr:'بولندا', countryEn:'Poland', priority: 80 },
    { slug: 'prague', cc: 'cz', lat: 50.0755, lng: 14.4378, tz: 'Europe/Prague',
        names: {ar:'براغ',en:'Prague',fr:'Prague',de:'Prag',tr:'Prag',ur:'پراگ',id:'Praha',es:'Praga',bn:'প্রাগ',ms:'Prague'},
        aliases: {cs:['Praha']},
        countryAr:'التشيك', countryEn:'Czech Republic', priority: 90 },
    { slug: 'budapest', cc: 'hu', lat: 47.4979, lng: 19.0402, tz: 'Europe/Budapest',
        names: {ar:'بودابست',en:'Budapest',fr:'Budapest',de:'Budapest',tr:'Budapeşte',ur:'بوڈاپسٹ',id:'Budapest',es:'Budapest',bn:'বুদাপেস্ট',ms:'Budapest'},
        aliases: {hu:['Budapest']},
        countryAr:'المجر', countryEn:'Hungary', priority: 90 },
    { slug: 'bratislava', cc: 'sk', lat: 48.1486, lng: 17.1077, tz: 'Europe/Bratislava',
        names: {ar:'براتيسلافا',en:'Bratislava',fr:'Bratislava',de:'Pressburg',tr:'Bratislava',ur:'براتسلاوا',id:'Bratislava',es:'Bratislava',bn:'ব্রাতিস্লাভা',ms:'Bratislava'},
        aliases: {sk:['Bratislava']},
        countryAr:'سلوفاكيا', countryEn:'Slovakia', priority: 85 },
    { slug: 'ljubljana', cc: 'si', lat: 46.0569, lng: 14.5058, tz: 'Europe/Ljubljana',
        names: {ar:'ليوبليانا',en:'Ljubljana',fr:'Ljubljana',de:'Laibach',tr:'Lyublyana',ur:'لیوبلیانا',id:'Ljubljana',es:'Liubliana',bn:'লিউব্লিয়ানা',ms:'Ljubljana'},
        aliases: {sl:['Ljubljana']},
        countryAr:'سلوفينيا', countryEn:'Slovenia', priority: 82 },
    { slug: 'zagreb', cc: 'hr', lat: 45.8150, lng: 15.9819, tz: 'Europe/Zagreb',
        names: {ar:'زغرب',en:'Zagreb',fr:'Zagreb',de:'Zagreb',tr:'Zagreb',ur:'زغرب',id:'Zagreb',es:'Zagreb',bn:'জাগরেব',ms:'Zagreb'},
        aliases: {hr:['Zagreb']},
        countryAr:'كرواتيا', countryEn:'Croatia', priority: 85 },
    { slug: 'belgrade', cc: 'rs', lat: 44.7866, lng: 20.4489, tz: 'Europe/Belgrade',
        names: {ar:'بلغراد',en:'Belgrade',fr:'Belgrade',de:'Belgrad',tr:'Belgrad',ur:'بلغراد',id:'Beograd',es:'Belgrado',bn:'বেলগ্রেড',ms:'Belgrade'},
        aliases: {sr:['Београд','Beograd']},
        countryAr:'صربيا', countryEn:'Serbia', priority: 88 },
    { slug: 'bucharest', cc: 'ro', lat: 44.4268, lng: 26.1025, tz: 'Europe/Bucharest',
        names: {ar:'بوخارست',en:'Bucharest',fr:'Bucarest',de:'Bukarest',tr:'Bükreş',ur:'بخارسٹ',id:'Bucharest',es:'Bucarest',bn:'বুখারেস্ট',ms:'Bucharest'},
        aliases: {ro:['București']},
        countryAr:'رومانيا', countryEn:'Romania', priority: 88 },
    { slug: 'sofia', cc: 'bg', lat: 42.6977, lng: 23.3219, tz: 'Europe/Sofia',
        names: {ar:'صوفيا',en:'Sofia',fr:'Sofia',de:'Sofia',tr:'Sofya',ur:'صوفیہ',id:'Sofia',es:'Sofía',bn:'সোফিয়া',ms:'Sofia'},
        aliases: {bg:['София']},
        countryAr:'بلغاريا', countryEn:'Bulgaria', priority: 88 },
    { slug: 'athens', cc: 'gr', lat: 37.9838, lng: 23.7275, tz: 'Europe/Athens',
        names: {ar:'أثينا',en:'Athens',fr:'Athènes',de:'Athen',tr:'Atina',ur:'ایتھنز',id:'Athena',es:'Atenas',bn:'এথেন্স',ms:'Athens'},
        aliases: {el:['Αθήνα','Athína']},
        countryAr:'اليونان', countryEn:'Greece', priority: 92 },
    { slug: 'vilnius', cc: 'lt', lat: 54.6872, lng: 25.2797, tz: 'Europe/Vilnius',
        names: {ar:'فيلنيوس',en:'Vilnius',fr:'Vilnius',de:'Wilna',tr:'Vilnius',ur:'ولنیئس',id:'Vilnius',es:'Vilna',bn:'ভিলনিয়াস',ms:'Vilnius'},
        aliases: {lt:['Vilnius']},
        countryAr:'ليتوانيا', countryEn:'Lithuania', priority: 82 },
    { slug: 'tallinn', cc: 'ee', lat: 59.4370, lng: 24.7536, tz: 'Europe/Tallinn',
        names: {ar:'تالين',en:'Tallinn',fr:'Tallinn',de:'Tallinn',tr:'Tallinn',ur:'ٹالن',id:'Tallinn',es:'Tallin',bn:'তাল্লিন',ms:'Tallinn'},
        aliases: {et:['Tallinn']},
        countryAr:'إستونيا', countryEn:'Estonia', priority: 82 },

    // ── Turkey (6) ──
    { slug: 'ankara', cc: 'tr', lat: 39.9334, lng: 32.8597, tz: 'Europe/Istanbul',
        names: {ar:'أنقرة',en:'Ankara',fr:'Ankara',de:'Ankara',tr:'Ankara',ur:'انقرہ',id:'Ankara',es:'Ankara',bn:'আঙ্কারা',ms:'Ankara'},
        aliases: {tr:['Ankara']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 95 },
    { slug: 'izmir', cc: 'tr', lat: 38.4192, lng: 27.1287, tz: 'Europe/Istanbul',
        names: {ar:'إزمير',en:'Izmir',fr:'Izmir',de:'Izmir',tr:'İzmir',ur:'ازمیر',id:'Izmir',es:'Esmirna',bn:'ইজমির',ms:'Izmir'},
        aliases: {tr:['İzmir']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 88 },
    { slug: 'bursa', cc: 'tr', lat: 40.1885, lng: 29.0610, tz: 'Europe/Istanbul',
        names: {ar:'بورصة',en:'Bursa',fr:'Bursa',de:'Bursa',tr:'Bursa',ur:'بورصہ',id:'Bursa',es:'Bursa',bn:'বুরসা',ms:'Bursa'},
        aliases: {tr:['Bursa']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 82 },
    { slug: 'antalya', cc: 'tr', lat: 36.8969, lng: 30.7133, tz: 'Europe/Istanbul',
        names: {ar:'أنطاليا',en:'Antalya',fr:'Antalya',de:'Antalya',tr:'Antalya',ur:'انطالیہ',id:'Antalya',es:'Antalia',bn:'আন্তালিয়া',ms:'Antalya'},
        aliases: {tr:['Antalya']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 85 },
    { slug: 'konya', cc: 'tr', lat: 37.8714, lng: 32.4847, tz: 'Europe/Istanbul',
        names: {ar:'قونية',en:'Konya',fr:'Konya',de:'Konya',tr:'Konya',ur:'قونیہ',id:'Konya',es:'Konya',bn:'কোনিয়া',ms:'Konya'},
        aliases: {tr:['Konya']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 80 },
    { slug: 'adana', cc: 'tr', lat: 37.0000, lng: 35.3213, tz: 'Europe/Istanbul',
        names: {ar:'أضنة',en:'Adana',fr:'Adana',de:'Adana',tr:'Adana',ur:'اڈانا',id:'Adana',es:'Adana',bn:'আদানা',ms:'Adana'},
        aliases: {tr:['Adana']},
        countryAr:'تركيا', countryEn:'Turkey', priority: 78 },

    // ── Iran (6) ──
    { slug: 'tehran', cc: 'ir', lat: 35.6892, lng: 51.3890, tz: 'Asia/Tehran',
        names: {ar:'طهران',en:'Tehran',fr:'Téhéran',de:'Teheran',tr:'Tahran',ur:'تہران',id:'Teheran',es:'Teherán',bn:'তেহরান',ms:'Tehran'},
        aliases: {fa:['تهران']},
        countryAr:'إيران', countryEn:'Iran', priority: 95 },
    { slug: 'mashhad', cc: 'ir', lat: 36.2605, lng: 59.6168, tz: 'Asia/Tehran',
        names: {ar:'مشهد',en:'Mashhad',fr:'Mashhad',de:'Maschhad',tr:'Meşhed',ur:'مشہد',id:'Masyhad',es:'Mashhad',bn:'মাশহাদ',ms:'Mashhad'},
        aliases: {fa:['مشهد']},
        countryAr:'إيران', countryEn:'Iran', priority: 88 },
    { slug: 'isfahan', cc: 'ir', lat: 32.6539, lng: 51.6660, tz: 'Asia/Tehran',
        names: {ar:'أصفهان',en:'Isfahan',fr:'Ispahan',de:'Isfahan',tr:'İsfahan',ur:'اصفہان',id:'Isfahan',es:'Isfahán',bn:'ইসফাহান',ms:'Isfahan'},
        aliases: {fa:['اصفهان'], en:['Esfahan']},
        countryAr:'إيران', countryEn:'Iran', priority: 85 },
    { slug: 'shiraz', cc: 'ir', lat: 29.5916, lng: 52.5836, tz: 'Asia/Tehran',
        names: {ar:'شيراز',en:'Shiraz',fr:'Chiraz',de:'Schiras',tr:'Şiraz',ur:'شیراز',id:'Syiraz',es:'Shiraz',bn:'শিরাজ',ms:'Shiraz'},
        aliases: {fa:['شیراز']},
        countryAr:'إيران', countryEn:'Iran', priority: 82 },
    { slug: 'tabriz', cc: 'ir', lat: 38.0962, lng: 46.2738, tz: 'Asia/Tehran',
        names: {ar:'تبريز',en:'Tabriz',fr:'Tabriz',de:'Täbris',tr:'Tebriz',ur:'تبریز',id:'Tabriz',es:'Tabriz',bn:'তাবরিজ',ms:'Tabriz'},
        aliases: {fa:['تبریز']},
        countryAr:'إيران', countryEn:'Iran', priority: 80 },
    { slug: 'qom', cc: 'ir', lat: 34.6416, lng: 50.8746, tz: 'Asia/Tehran',
        names: {ar:'قم',en:'Qom',fr:'Qom',de:'Ghom',tr:'Kum',ur:'قم',id:'Qom',es:'Qom',bn:'কোম',ms:'Qom'},
        aliases: {fa:['قم'], en:['Qum']},
        countryAr:'إيران', countryEn:'Iran', priority: 82 },

    // ── Caucasus + Central Asia (8) ──
    { slug: 'baku', cc: 'az', lat: 40.4093, lng: 49.8671, tz: 'Asia/Baku',
        names: {ar:'باكو',en:'Baku',fr:'Bakou',de:'Baku',tr:'Bakü',ur:'باکو',id:'Baku',es:'Bakú',bn:'বাকু',ms:'Baku'},
        aliases: {az:['Bakı']},
        countryAr:'أذربيجان', countryEn:'Azerbaijan', priority: 90 },
    { slug: 'yerevan', cc: 'am', lat: 40.1872, lng: 44.5152, tz: 'Asia/Yerevan',
        names: {ar:'يريفان',en:'Yerevan',fr:'Erevan',de:'Eriwan',tr:'Erivan',ur:'یریوان',id:'Yerevan',es:'Ereván',bn:'ইয়েরেভান',ms:'Yerevan'},
        aliases: {hy:['Երևան']},
        countryAr:'أرمينيا', countryEn:'Armenia', priority: 88 },
    { slug: 'tbilisi', cc: 'ge', lat: 41.7151, lng: 44.8271, tz: 'Asia/Tbilisi',
        names: {ar:'تبليسي',en:'Tbilisi',fr:'Tbilissi',de:'Tiflis',tr:'Tiflis',ur:'تبلیسی',id:'Tbilisi',es:'Tiflis',bn:'তিবিলিসি',ms:'Tbilisi'},
        aliases: {ka:['თბილისი']},
        countryAr:'جورجيا', countryEn:'Georgia', priority: 88 },
    { slug: 'tashkent', cc: 'uz', lat: 41.2995, lng: 69.2401, tz: 'Asia/Tashkent',
        names: {ar:'طشقند',en:'Tashkent',fr:'Tachkent',de:'Taschkent',tr:'Taşkent',ur:'تاشقند',id:'Tashkent',es:'Tashkent',bn:'তাশখন্দ',ms:'Tashkent'},
        aliases: {uz:['Toshkent']},
        countryAr:'أوزبكستان', countryEn:'Uzbekistan', priority: 90 },
    { slug: 'samarkand', cc: 'uz', lat: 39.6270, lng: 66.9750, tz: 'Asia/Tashkent',
        names: {ar:'سمرقند',en:'Samarkand',fr:'Samarcande',de:'Samarkand',tr:'Semerkant',ur:'سمرقند',id:'Samarkand',es:'Samarcanda',bn:'সমরকন্দ',ms:'Samarkand'},
        aliases: {uz:['Samarqand']},
        countryAr:'أوزبكستان', countryEn:'Uzbekistan', priority: 82 },
    { slug: 'almaty', cc: 'kz', lat: 43.2220, lng: 76.8512, tz: 'Asia/Almaty',
        names: {ar:'ألما آتا',en:'Almaty',fr:'Almaty',de:'Almaty',tr:'Almatı',ur:'الماتی',id:'Almaty',es:'Almaty',bn:'আলমাটি',ms:'Almaty'},
        aliases: {ru:['Алматы'], en:['Alma-Ata']},
        countryAr:'كازاخستان', countryEn:'Kazakhstan', priority: 88 },
    { slug: 'astana', cc: 'kz', lat: 51.1694, lng: 71.4491, tz: 'Asia/Almaty',
        names: {ar:'أستانا',en:'Astana',fr:'Astana',de:'Astana',tr:'Astana',ur:'استانا',id:'Astana',es:'Astaná',bn:'আস্তানা',ms:'Astana'},
        aliases: {kk:['Астана'], en:['Nur-Sultan']},
        countryAr:'كازاخستان', countryEn:'Kazakhstan', priority: 90 },
    { slug: 'bishkek', cc: 'kg', lat: 42.8746, lng: 74.5698, tz: 'Asia/Bishkek',
        names: {ar:'بيشكيك',en:'Bishkek',fr:'Bichkek',de:'Bischkek',tr:'Bişkek',ur:'بشکیک',id:'Bishkek',es:'Biskek',bn:'বিশকেক',ms:'Bishkek'},
        aliases: {ky:['Бишкек']},
        countryAr:'قيرغيزستان', countryEn:'Kyrgyzstan', priority: 82 },

    // ── India expansion (6) ──
    { slug: 'pune', cc: 'in', lat: 18.5204, lng: 73.8567, tz: 'Asia/Kolkata',
        names: {ar:'بونه',en:'Pune',fr:'Pune',de:'Pune',tr:'Pune',ur:'پونے',id:'Pune',es:'Pune',bn:'পুনে',ms:'Pune'},
        aliases: {mr:['पुणे'], hi:['पुणे']},
        countryAr:'الهند', countryEn:'India', priority: 82 },
    { slug: 'jaipur', cc: 'in', lat: 26.9124, lng: 75.7873, tz: 'Asia/Kolkata',
        names: {ar:'جايبور',en:'Jaipur',fr:'Jaipur',de:'Jaipur',tr:'Jaipur',ur:'جے پور',id:'Jaipur',es:'Jaipur',bn:'জয়পুর',ms:'Jaipur'},
        aliases: {hi:['जयपुर']},
        countryAr:'الهند', countryEn:'India', priority: 80 },
    { slug: 'surat', cc: 'in', lat: 21.1702, lng: 72.8311, tz: 'Asia/Kolkata',
        names: {ar:'سورت',en:'Surat',fr:'Surat',de:'Surat',tr:'Surat',ur:'سورت',id:'Surat',es:'Surat',bn:'সুরাট',ms:'Surat'},
        aliases: {hi:['सूरत'], gu:['સુરત']},
        countryAr:'الهند', countryEn:'India', priority: 78 },
    { slug: 'kanpur', cc: 'in', lat: 26.4499, lng: 80.3319, tz: 'Asia/Kolkata',
        names: {ar:'كانبور',en:'Kanpur',fr:'Kanpur',de:'Kanpur',tr:'Kanpur',ur:'کانپور',id:'Kanpur',es:'Kanpur',bn:'কানপুর',ms:'Kanpur'},
        aliases: {hi:['कानपुर']},
        countryAr:'الهند', countryEn:'India', priority: 76 },
    { slug: 'indore', cc: 'in', lat: 22.7196, lng: 75.8577, tz: 'Asia/Kolkata',
        names: {ar:'إندور',en:'Indore',fr:'Indore',de:'Indore',tr:'Indore',ur:'اندور',id:'Indore',es:'Indore',bn:'ইন্দোর',ms:'Indore'},
        aliases: {hi:['इंदौर']},
        countryAr:'الهند', countryEn:'India', priority: 76 },
    { slug: 'nagpur', cc: 'in', lat: 21.1458, lng: 79.0882, tz: 'Asia/Kolkata',
        names: {ar:'ناغبور',en:'Nagpur',fr:'Nagpur',de:'Nagpur',tr:'Nagpur',ur:'ناگپور',id:'Nagpur',es:'Nagpur',bn:'নাগপুর',ms:'Nagpur'},
        aliases: {hi:['नागपुर'], mr:['नागपूर']},
        countryAr:'الهند', countryEn:'India', priority: 76 },

    // ── South Asia (other) (5) ──
    { slug: 'faisalabad', cc: 'pk', lat: 31.4504, lng: 73.1350, tz: 'Asia/Karachi',
        names: {ar:'فيصل آباد',en:'Faisalabad',fr:'Faisalabad',de:'Faisalabad',tr:'Faisalabad',ur:'فیصل آباد',id:'Faisalabad',es:'Faisalabad',bn:'ফয়সালাবাদ',ms:'Faisalabad'},
        aliases: {ur:['فیصل آباد']},
        countryAr:'باكستان', countryEn:'Pakistan', priority: 80 },
    { slug: 'quetta', cc: 'pk', lat: 30.1798, lng: 66.9750, tz: 'Asia/Karachi',
        names: {ar:'كويتا',en:'Quetta',fr:'Quetta',de:'Quetta',tr:'Quetta',ur:'کوئٹہ',id:'Quetta',es:'Quetta',bn:'কোয়েটা',ms:'Quetta'},
        aliases: {ur:['کوئٹہ']},
        countryAr:'باكستان', countryEn:'Pakistan', priority: 76 },
    { slug: 'colombo', cc: 'lk', lat: 6.9271, lng: 79.8612, tz: 'Asia/Colombo',
        names: {ar:'كولومبو',en:'Colombo',fr:'Colombo',de:'Colombo',tr:'Kolombo',ur:'کولمبو',id:'Kolombo',es:'Colombo',bn:'কলম্বো',ms:'Colombo'},
        aliases: {si:['කොළඹ'], ta:['கொழும்பு']},
        countryAr:'سريلانكا', countryEn:'Sri Lanka', priority: 88 },
    { slug: 'kathmandu', cc: 'np', lat: 27.7172, lng: 85.3240, tz: 'Asia/Kathmandu',
        names: {ar:'كاتماندو',en:'Kathmandu',fr:'Katmandou',de:'Kathmandu',tr:'Katmandu',ur:'کھٹمنڈو',id:'Kathmandu',es:'Katmandú',bn:'কাঠমান্ডু',ms:'Kathmandu'},
        aliases: {ne:['काठमाडौँ']},
        countryAr:'نيبال', countryEn:'Nepal', priority: 88 },
    { slug: 'yangon', cc: 'mm', lat: 16.8409, lng: 96.1735, tz: 'Asia/Yangon',
        names: {ar:'يانغون',en:'Yangon',fr:'Rangoun',de:'Rangun',tr:'Yangon',ur:'یانگون',id:'Yangon',es:'Rangún',bn:'ইয়াঙ্গুন',ms:'Yangon'},
        aliases: {my:['ရန်ကုန်'], en:['Rangoon']},
        countryAr:'ميانمار', countryEn:'Myanmar', priority: 85 },

    // ── Southeast Asia (10) ──
    { slug: 'kuala-lumpur', cc: 'my', lat: 3.1390, lng: 101.6869, tz: 'Asia/Kuala_Lumpur',
        names: {ar:'كوالالمبور',en:'Kuala Lumpur',fr:'Kuala Lumpur',de:'Kuala Lumpur',tr:'Kuala Lumpur',ur:'کوالالمپور',id:'Kuala Lumpur',es:'Kuala Lumpur',bn:'কুয়ালালামপুর',ms:'Kuala Lumpur'},
        aliases: {en:['KL']},
        countryAr:'ماليزيا', countryEn:'Malaysia', priority: 95 },
    { slug: 'singapore', cc: 'sg', lat: 1.3521, lng: 103.8198, tz: 'Asia/Singapore',
        names: {ar:'سنغافورة',en:'Singapore',fr:'Singapour',de:'Singapur',tr:'Singapur',ur:'سنگاپور',id:'Singapura',es:'Singapur',bn:'সিঙ্গাপুর',ms:'Singapura'},
        aliases: {zh:['新加坡']},
        countryAr:'سنغافورة', countryEn:'Singapore', priority: 95 },
    { slug: 'bangkok', cc: 'th', lat: 13.7563, lng: 100.5018, tz: 'Asia/Bangkok',
        names: {ar:'بانكوك',en:'Bangkok',fr:'Bangkok',de:'Bangkok',tr:'Bangkok',ur:'بنکاک',id:'Bangkok',es:'Bangkok',bn:'ব্যাংকক',ms:'Bangkok'},
        aliases: {th:['กรุงเทพ','กรุงเทพมหานคร']},
        countryAr:'تايلاند', countryEn:'Thailand', priority: 95 },
    { slug: 'jakarta', cc: 'id', lat: -6.2088, lng: 106.8456, tz: 'Asia/Jakarta',
        names: {ar:'جاكرتا',en:'Jakarta',fr:'Jakarta',de:'Jakarta',tr:'Cakarta',ur:'جکارتا',id:'Jakarta',es:'Yakarta',bn:'জাকার্তা',ms:'Jakarta'},
        aliases: {id:['Jakarta','DKI Jakarta']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 95 },
    { slug: 'surabaya', cc: 'id', lat: -7.2575, lng: 112.7521, tz: 'Asia/Jakarta',
        names: {ar:'سورابايا',en:'Surabaya',fr:'Surabaya',de:'Surabaya',tr:'Surabaya',ur:'سورابایا',id:'Surabaya',es:'Surabaya',bn:'সুরাবায়া',ms:'Surabaya'},
        aliases: {id:['Surabaya']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 82 },
    { slug: 'manila', cc: 'ph', lat: 14.5995, lng: 120.9842, tz: 'Asia/Manila',
        names: {ar:'مانيلا',en:'Manila',fr:'Manille',de:'Manila',tr:'Manila',ur:'منیلا',id:'Manila',es:'Manila',bn:'ম্যানিলা',ms:'Manila'},
        aliases: {tl:['Maynila']},
        countryAr:'الفلبين', countryEn:'Philippines', priority: 92 },
    { slug: 'hanoi', cc: 'vn', lat: 21.0285, lng: 105.8542, tz: 'Asia/Ho_Chi_Minh',
        names: {ar:'هانوي',en:'Hanoi',fr:'Hanoï',de:'Hanoi',tr:'Hanoi',ur:'ہنوئی',id:'Hanoi',es:'Hanói',bn:'হ্যানয়',ms:'Hanoi'},
        aliases: {vi:['Hà Nội']},
        countryAr:'فيتنام', countryEn:'Vietnam', priority: 92 },
    { slug: 'ho-chi-minh', cc: 'vn', lat: 10.8231, lng: 106.6297, tz: 'Asia/Ho_Chi_Minh',
        names: {ar:'هو تشي مينه',en:'Ho Chi Minh City',fr:'Hô-Chi-Minh-Ville',de:'Ho-Chi-Minh-Stadt',tr:'Ho Chi Minh',ur:'ہو چی منہ',id:'Kota Ho Chi Minh',es:'Ciudad Ho Chi Minh',bn:'হো চি মিন সিটি',ms:'Ho Chi Minh'},
        aliases: {vi:['Thành phố Hồ Chí Minh','Sài Gòn'], en:['Saigon','Ho Chi Minh'], ar:['سايغون']},
        countryAr:'فيتنام', countryEn:'Vietnam', priority: 90 },
    { slug: 'phnom-penh', cc: 'kh', lat: 11.5564, lng: 104.9282, tz: 'Asia/Phnom_Penh',
        names: {ar:'بنوم بنه',en:'Phnom Penh',fr:'Phnom Penh',de:'Phnom Penh',tr:'Phnom Penh',ur:'نوم پن',id:'Phnom Penh',es:'Nom Pen',bn:'নম পেন',ms:'Phnom Penh'},
        aliases: {km:['ភ្នំពេញ']},
        countryAr:'كمبوديا', countryEn:'Cambodia', priority: 85 },
    { slug: 'bandung', cc: 'id', lat: -6.9175, lng: 107.6191, tz: 'Asia/Jakarta',
        names: {ar:'باندونغ',en:'Bandung',fr:'Bandung',de:'Bandung',tr:'Bandung',ur:'بانڈنگ',id:'Bandung',es:'Bandung',bn:'বান্দুং',ms:'Bandung'},
        aliases: {id:['Bandung']},
        countryAr:'إندونيسيا', countryEn:'Indonesia', priority: 80 },

    // ── Korea (4) ──
    { slug: 'seoul', cc: 'kr', lat: 37.5665, lng: 126.9780, tz: 'Asia/Seoul',
        names: {ar:'سيول',en:'Seoul',fr:'Séoul',de:'Seoul',tr:'Seul',ur:'سیول',id:'Seoul',es:'Seúl',bn:'সিউল',ms:'Seoul'},
        aliases: {ko:['서울','서울특별시']},
        countryAr:'كوريا الجنوبية', countryEn:'South Korea', priority: 95 },
    { slug: 'busan', cc: 'kr', lat: 35.1796, lng: 129.0756, tz: 'Asia/Seoul',
        names: {ar:'بوسان',en:'Busan',fr:'Busan',de:'Busan',tr:'Busan',ur:'بوسان',id:'Busan',es:'Busán',bn:'বুসান',ms:'Busan'},
        aliases: {ko:['부산'], en:['Pusan']},
        countryAr:'كوريا الجنوبية', countryEn:'South Korea', priority: 85 },
    { slug: 'incheon', cc: 'kr', lat: 37.4563, lng: 126.7052, tz: 'Asia/Seoul',
        names: {ar:'إنتشون',en:'Incheon',fr:'Incheon',de:'Incheon',tr:'Incheon',ur:'انچیون',id:'Incheon',es:'Incheon',bn:'ইনচন',ms:'Incheon'},
        aliases: {ko:['인천']},
        countryAr:'كوريا الجنوبية', countryEn:'South Korea', priority: 80 },
    { slug: 'pyongyang', cc: 'kp', lat: 39.0392, lng: 125.7625, tz: 'Asia/Pyongyang',
        names: {ar:'بيونغ يانغ',en:'Pyongyang',fr:'Pyongyang',de:'Pjöngjang',tr:'Pyongyang',ur:'پیانگ یانگ',id:'Pyongyang',es:'Pionyang',bn:'পিয়ংইয়ং',ms:'Pyongyang'},
        aliases: {ko:['평양']},
        countryAr:'كوريا الشمالية', countryEn:'North Korea', priority: 90 },

    // ── Oceania (5) ──
    { slug: 'sydney', cc: 'au', lat: -33.8688, lng: 151.2093, tz: 'Australia/Sydney',
        names: {ar:'سيدني',en:'Sydney',fr:'Sydney',de:'Sydney',tr:'Sidney',ur:'سڈنی',id:'Sydney',es:'Sídney',bn:'সিডনি',ms:'Sydney'},
        aliases: {en:['Sidney']},
        countryAr:'أستراليا', countryEn:'Australia', priority: 92 },
    { slug: 'melbourne', cc: 'au', lat: -37.8136, lng: 144.9631, tz: 'Australia/Melbourne',
        names: {ar:'ملبورن',en:'Melbourne',fr:'Melbourne',de:'Melbourne',tr:'Melbourne',ur:'میلبورن',id:'Melbourne',es:'Melbourne',bn:'মেলবোর্ন',ms:'Melbourne'},
        aliases: {en:[]},
        countryAr:'أستراليا', countryEn:'Australia', priority: 90 },
    { slug: 'brisbane', cc: 'au', lat: -27.4698, lng: 153.0251, tz: 'Australia/Brisbane',
        names: {ar:'بريزبن',en:'Brisbane',fr:'Brisbane',de:'Brisbane',tr:'Brisbane',ur:'برسبین',id:'Brisbane',es:'Brisbane',bn:'ব্রিসবেন',ms:'Brisbane'},
        aliases: {en:[]},
        countryAr:'أستراليا', countryEn:'Australia', priority: 82 },
    { slug: 'perth', cc: 'au', lat: -31.9505, lng: 115.8605, tz: 'Australia/Perth',
        names: {ar:'بيرث',en:'Perth',fr:'Perth',de:'Perth',tr:'Perth',ur:'پرتھ',id:'Perth',es:'Perth',bn:'পার্থ',ms:'Perth'},
        aliases: {en:[]},
        countryAr:'أستراليا', countryEn:'Australia', priority: 80 },
    { slug: 'auckland', cc: 'nz', lat: -36.8485, lng: 174.7633, tz: 'Pacific/Auckland',
        names: {ar:'أوكلاند',en:'Auckland',fr:'Auckland',de:'Auckland',tr:'Auckland',ur:'آک لینڈ',id:'Auckland',es:'Auckland',bn:'অকল্যান্ড',ms:'Auckland'},
        aliases: {mi:['Tāmaki Makaurau']},
        countryAr:'نيوزيلندا', countryEn:'New Zealand', priority: 90 },

    // ── Sub-Saharan Africa (12) ──
    { slug: 'lagos', cc: 'ng', lat: 6.5244, lng: 3.3792, tz: 'Africa/Lagos',
        names: {ar:'لاغوس',en:'Lagos',fr:'Lagos',de:'Lagos',tr:'Lagos',ur:'لاگوس',id:'Lagos',es:'Lagos',bn:'লাগোস',ms:'Lagos'},
        aliases: {en:[]},
        countryAr:'نيجيريا', countryEn:'Nigeria', priority: 92 },
    { slug: 'abuja', cc: 'ng', lat: 9.0765, lng: 7.3986, tz: 'Africa/Lagos',
        names: {ar:'أبوجا',en:'Abuja',fr:'Abuja',de:'Abuja',tr:'Abuja',ur:'ابوجا',id:'Abuja',es:'Abuya',bn:'আবুজা',ms:'Abuja'},
        aliases: {en:[]},
        countryAr:'نيجيريا', countryEn:'Nigeria', priority: 88 },
    { slug: 'nairobi', cc: 'ke', lat: -1.2921, lng: 36.8219, tz: 'Africa/Nairobi',
        names: {ar:'نيروبي',en:'Nairobi',fr:'Nairobi',de:'Nairobi',tr:'Nairobi',ur:'نیروبی',id:'Nairobi',es:'Nairobi',bn:'নাইরোবি',ms:'Nairobi'},
        aliases: {sw:['Nairobi']},
        countryAr:'كينيا', countryEn:'Kenya', priority: 92 },
    { slug: 'addis-ababa', cc: 'et', lat: 9.0320, lng: 38.7469, tz: 'Africa/Addis_Ababa',
        names: {ar:'أديس أبابا',en:'Addis Ababa',fr:'Addis-Abeba',de:'Addis Abeba',tr:'Addis Ababa',ur:'ادیس ابابا',id:'Addis Ababa',es:'Adís Abeba',bn:'আদ্দিস আবাবা',ms:'Addis Ababa'},
        aliases: {am:['አዲስ አበባ']},
        countryAr:'إثيوبيا', countryEn:'Ethiopia', priority: 92 },
    { slug: 'accra', cc: 'gh', lat: 5.6037, lng: -0.1870, tz: 'Africa/Accra',
        names: {ar:'أكرا',en:'Accra',fr:'Accra',de:'Accra',tr:'Akra',ur:'اکرا',id:'Accra',es:'Acra',bn:'আক্রা',ms:'Accra'},
        aliases: {en:[]},
        countryAr:'غانا', countryEn:'Ghana', priority: 88 },
    { slug: 'dakar', cc: 'sn', lat: 14.7167, lng: -17.4677, tz: 'Africa/Dakar',
        names: {ar:'داكار',en:'Dakar',fr:'Dakar',de:'Dakar',tr:'Dakar',ur:'ڈاکار',id:'Dakar',es:'Dakar',bn:'ডাকার',ms:'Dakar'},
        aliases: {fr:['Dakar']},
        countryAr:'السنغال', countryEn:'Senegal', priority: 88 },
    { slug: 'johannesburg', cc: 'za', lat: -26.2041, lng: 28.0473, tz: 'Africa/Johannesburg',
        names: {ar:'جوهانسبرغ',en:'Johannesburg',fr:'Johannesbourg',de:'Johannesburg',tr:'Johannesburg',ur:'جوہانسبرگ',id:'Johannesburg',es:'Johannesburgo',bn:'জোহানেসবার্গ',ms:'Johannesburg'},
        aliases: {en:['Joburg','Jozi']},
        countryAr:'جنوب أفريقيا', countryEn:'South Africa', priority: 90 },
    { slug: 'cape-town', cc: 'za', lat: -33.9249, lng: 18.4241, tz: 'Africa/Johannesburg',
        names: {ar:'كيب تاون',en:'Cape Town',fr:'Le Cap',de:'Kapstadt',tr:'Cape Town',ur:'کیپ ٹاؤن',id:'Cape Town',es:'Ciudad del Cabo',bn:'কেপ টাউন',ms:'Cape Town'},
        aliases: {af:['Kaapstad']},
        countryAr:'جنوب أفريقيا', countryEn:'South Africa', priority: 88 },
    { slug: 'kinshasa', cc: 'cd', lat: -4.4419, lng: 15.2663, tz: 'Africa/Kinshasa',
        names: {ar:'كينشاسا',en:'Kinshasa',fr:'Kinshasa',de:'Kinshasa',tr:'Kinşasa',ur:'کنشاسا',id:'Kinshasa',es:'Kinsasa',bn:'কিনশাসা',ms:'Kinshasa'},
        aliases: {fr:['Kinshasa']},
        countryAr:'جمهورية الكونغو الديمقراطية', countryEn:'DR Congo', priority: 88 },
    { slug: 'luanda', cc: 'ao', lat: -8.8390, lng: 13.2894, tz: 'Africa/Luanda',
        names: {ar:'لواندا',en:'Luanda',fr:'Luanda',de:'Luanda',tr:'Luanda',ur:'لوآنڈا',id:'Luanda',es:'Luanda',bn:'লুয়ান্ডা',ms:'Luanda'},
        aliases: {pt:['Luanda']},
        countryAr:'أنغولا', countryEn:'Angola', priority: 85 },
    { slug: 'kampala', cc: 'ug', lat: 0.3476, lng: 32.5825, tz: 'Africa/Kampala',
        names: {ar:'كمبالا',en:'Kampala',fr:'Kampala',de:'Kampala',tr:'Kampala',ur:'کمپالا',id:'Kampala',es:'Kampala',bn:'কাম্পালা',ms:'Kampala'},
        aliases: {sw:['Kampala']},
        countryAr:'أوغندا', countryEn:'Uganda', priority: 85 },
    { slug: 'dar-es-salaam', cc: 'tz', lat: -6.7924, lng: 39.2083, tz: 'Africa/Dar_es_Salaam',
        names: {ar:'دار السلام',en:'Dar es Salaam',fr:'Dar es Salaam',de:'Daressalam',tr:'Dar es Salaam',ur:'دار السلام',id:'Dar es Salaam',es:'Dar es Salam',bn:'দার এস সালাম',ms:'Dar es Salaam'},
        aliases: {sw:['Dar es Salaam']},
        countryAr:'تنزانيا', countryEn:'Tanzania', priority: 85 },

    // ── Latin America (10) ──
    { slug: 'mexico-city', cc: 'mx', lat: 19.4326, lng: -99.1332, tz: 'America/Mexico_City',
        names: {ar:'مكسيكو سيتي',en:'Mexico City',fr:'Mexico',de:'Mexiko-Stadt',tr:'Meksika',ur:'میکسیکو سٹی',id:'Kota Meksiko',es:'Ciudad de México',bn:'মেক্সিকো সিটি',ms:'Mexico City'},
        aliases: {es:['CDMX','México DF']},
        countryAr:'المكسيك', countryEn:'Mexico', priority: 92 },
    { slug: 'buenos-aires', cc: 'ar', lat: -34.6037, lng: -58.3816, tz: 'America/Argentina/Buenos_Aires',
        names: {ar:'بوينس آيرس',en:'Buenos Aires',fr:'Buenos Aires',de:'Buenos Aires',tr:'Buenos Aires',ur:'بیونس آئرس',id:'Buenos Aires',es:'Buenos Aires',bn:'বুয়েনস আইরেস',ms:'Buenos Aires'},
        aliases: {es:['BA','CABA']},
        countryAr:'الأرجنتين', countryEn:'Argentina', priority: 92 },
    { slug: 'santiago-cl', cc: 'cl', lat: -33.4489, lng: -70.6693, tz: 'America/Santiago',
        names: {ar:'سانتياغو',en:'Santiago',fr:'Santiago',de:'Santiago',tr:'Santiago',ur:'سانتیاگو',id:'Santiago',es:'Santiago',bn:'সান্তিয়াগো',ms:'Santiago'},
        aliases: {es:['Santiago de Chile']},
        countryAr:'تشيلي', countryEn:'Chile', priority: 90 },
    { slug: 'bogota', cc: 'co', lat: 4.7110, lng: -74.0721, tz: 'America/Bogota',
        names: {ar:'بوغوتا',en:'Bogota',fr:'Bogota',de:'Bogotá',tr:'Bogota',ur:'بوگوٹا',id:'Bogota',es:'Bogotá',bn:'বোগোতা',ms:'Bogota'},
        aliases: {es:['Bogotá']},
        countryAr:'كولومبيا', countryEn:'Colombia', priority: 90 },
    { slug: 'lima', cc: 'pe', lat: -12.0464, lng: -77.0428, tz: 'America/Lima',
        names: {ar:'ليما',en:'Lima',fr:'Lima',de:'Lima',tr:'Lima',ur:'لیما',id:'Lima',es:'Lima',bn:'লিমা',ms:'Lima'},
        aliases: {es:['Lima']},
        countryAr:'بيرو', countryEn:'Peru', priority: 90 },
    { slug: 'caracas', cc: 've', lat: 10.4806, lng: -66.9036, tz: 'America/Caracas',
        names: {ar:'كاراكاس',en:'Caracas',fr:'Caracas',de:'Caracas',tr:'Karakas',ur:'کاراکس',id:'Caracas',es:'Caracas',bn:'কারাকাস',ms:'Caracas'},
        aliases: {es:['Caracas']},
        countryAr:'فنزويلا', countryEn:'Venezuela', priority: 88 },
    { slug: 'brasilia', cc: 'br', lat: -15.8267, lng: -47.9218, tz: 'America/Sao_Paulo',
        names: {ar:'برازيليا',en:'Brasilia',fr:'Brasilia',de:'Brasília',tr:'Brasilia',ur:'برازیلیا',id:'Brasilia',es:'Brasilia',bn:'ব্রাসিলিয়া',ms:'Brasilia'},
        aliases: {pt:['Brasília']},
        countryAr:'البرازيل', countryEn:'Brazil', priority: 92 },
    { slug: 'montevideo', cc: 'uy', lat: -34.9011, lng: -56.1645, tz: 'America/Montevideo',
        names: {ar:'مونتيفيديو',en:'Montevideo',fr:'Montevideo',de:'Montevideo',tr:'Montevideo',ur:'مونٹیویڈیو',id:'Montevideo',es:'Montevideo',bn:'মন্টিভিডিও',ms:'Montevideo'},
        aliases: {es:['Montevideo']},
        countryAr:'أوروغواي', countryEn:'Uruguay', priority: 85 },
    { slug: 'quito', cc: 'ec', lat: -0.1807, lng: -78.4678, tz: 'America/Guayaquil',
        names: {ar:'كيتو',en:'Quito',fr:'Quito',de:'Quito',tr:'Quito',ur:'کیٹو',id:'Quito',es:'Quito',bn:'কিটো',ms:'Quito'},
        aliases: {es:['Quito']},
        countryAr:'الإكوادور', countryEn:'Ecuador', priority: 88 },
    { slug: 'la-paz', cc: 'bo', lat: -16.4897, lng: -68.1193, tz: 'America/La_Paz',
        names: {ar:'لا باز',en:'La Paz',fr:'La Paz',de:'La Paz',tr:'La Paz',ur:'لا پاز',id:'La Paz',es:'La Paz',bn:'লা পাজ',ms:'La Paz'},
        aliases: {es:['La Paz']},
        countryAr:'بوليفيا', countryEn:'Bolivia', priority: 85 },

    // ── Saudi Arabia expansion (8) ──
    { slug: 'tabuk', cc: 'sa', lat: 28.3835, lng: 36.5662, tz: 'Asia/Riyadh',
        names: {ar:'تبوك',en:'Tabuk',fr:'Tabouk',de:'Tabuk',tr:'Tebük',ur:'تبوک',id:'Tabuk',es:'Tabuk',bn:'তাবুক',ms:'Tabuk'},
        aliases: {ar:['تبوك']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 82 },
    { slug: 'hail', cc: 'sa', lat: 27.5219, lng: 41.6907, tz: 'Asia/Riyadh',
        names: {ar:'حائل',en:'Hail',fr:'Haïl',de:'Hail',tr:'Hail',ur:'حائل',id:'Hail',es:'Hail',bn:'হাইল',ms:'Hail'},
        aliases: {ar:['حائل']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 80 },
    { slug: 'buraidah', cc: 'sa', lat: 26.3260, lng: 43.9750, tz: 'Asia/Riyadh',
        names: {ar:'بريدة',en:'Buraidah',fr:'Buraydah',de:'Buraida',tr:'Bureyde',ur:'بریدہ',id:'Buraidah',es:'Buraida',bn:'বুরাইদা',ms:'Buraidah'},
        aliases: {ar:['بريدة','البريدة']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 82 },
    { slug: 'jubail', cc: 'sa', lat: 27.0046, lng: 49.6458, tz: 'Asia/Riyadh',
        names: {ar:'الجبيل',en:'Jubail',fr:'Jubail',de:'Dschubail',tr:'Cübeyl',ur:'جبیل',id:'Jubail',es:'Jubail',bn:'জুবাইল',ms:'Jubail'},
        aliases: {ar:['جبيل','الجبيل الصناعية']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 80 },
    { slug: 'yanbu', cc: 'sa', lat: 24.0890, lng: 38.0617, tz: 'Asia/Riyadh',
        names: {ar:'ينبع',en:'Yanbu',fr:'Yanbu',de:'Yanbu',tr:'Yenbu',ur:'ینبع',id:'Yanbu',es:'Yanbu',bn:'ইয়ানবু',ms:'Yanbu'},
        aliases: {ar:['ينبع','ينبع البحر']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 80 },
    { slug: 'abha', cc: 'sa', lat: 18.2164, lng: 42.5053, tz: 'Asia/Riyadh',
        names: {ar:'أبها',en:'Abha',fr:'Abha',de:'Abha',tr:'Ebha',ur:'ابہا',id:'Abha',es:'Abha',bn:'আভা',ms:'Abha'},
        aliases: {ar:['أبها']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 80 },
    { slug: 'taif', cc: 'sa', lat: 21.2854, lng: 40.4183, tz: 'Asia/Riyadh',
        names: {ar:'الطائف',en:'Taif',fr:'Taïf',de:'at-Taif',tr:'Taif',ur:'الطائف',id:'Taif',es:'Taif',bn:'তাইফ',ms:'Taif'},
        aliases: {ar:['الطائف','طائف']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 85 },
    { slug: 'khamis-mushait', cc: 'sa', lat: 18.3060, lng: 42.7290, tz: 'Asia/Riyadh',
        names: {ar:'خميس مشيط',en:'Khamis Mushait',fr:'Khamis Mushait',de:'Chamis Muschait',tr:'Khamis Mushayt',ur:'خمیس مشیط',id:'Khamis Mushait',es:'Jamis Mushait',bn:'খামিস মুশাইত',ms:'Khamis Mushait'},
        aliases: {ar:['خميس مشيط']},
        countryAr:'المملكة العربية السعودية', countryEn:'Saudi Arabia', priority: 78 },

    // ── GCC / Middle East expansion (5) ──
    { slug: 'salalah', cc: 'om', lat: 17.0151, lng: 54.0924, tz: 'Asia/Muscat',
        names: {ar:'صلالة',en:'Salalah',fr:'Salalah',de:'Salala',tr:'Selale',ur:'صلالہ',id:'Salalah',es:'Salalah',bn:'সালালাহ',ms:'Salalah'},
        aliases: {ar:['صلالة']},
        countryAr:'سلطنة عمان', countryEn:'Oman', priority: 80 },
    { slug: 'al-ain', cc: 'ae', lat: 24.2075, lng: 55.7447, tz: 'Asia/Dubai',
        names: {ar:'العين',en:'Al Ain',fr:'Al Aïn',de:'al-Ain',tr:'El Ayn',ur:'العین',id:'Al Ain',es:'Al Ain',bn:'আল আইন',ms:'Al Ain'},
        aliases: {ar:['العين','عين']},
        countryAr:'الإمارات العربية المتحدة', countryEn:'United Arab Emirates', priority: 82 },
    { slug: 'ras-al-khaimah', cc: 'ae', lat: 25.7889, lng: 55.9758, tz: 'Asia/Dubai',
        names: {ar:'رأس الخيمة',en:'Ras Al Khaimah',fr:'Ras el Khaïmah',de:"Ra's al-Chaima",tr:'Resülhayme',ur:'راس الخیمہ',id:'Ras Al Khaimah',es:'Ras al-Jaima',bn:'রাস আল খাইমাহ',ms:'Ras Al Khaimah'},
        aliases: {ar:['رأس الخيمة','راس الخيمة'], en:['RAK']},
        countryAr:'الإمارات العربية المتحدة', countryEn:'United Arab Emirates', priority: 78 },
    { slug: 'najaf', cc: 'iq', lat: 32.0009, lng: 44.3389, tz: 'Asia/Baghdad',
        names: {ar:'النجف',en:'Najaf',fr:'Nadjaf',de:'Nadschaf',tr:'Necef',ur:'نجف',id:'Najaf',es:'Náyaf',bn:'নাজাফ',ms:'Najaf'},
        aliases: {ar:['النجف','نجف']},
        countryAr:'العراق', countryEn:'Iraq', priority: 85 },
    { slug: 'erbil', cc: 'iq', lat: 36.1911, lng: 44.0094, tz: 'Asia/Baghdad',
        names: {ar:'أربيل',en:'Erbil',fr:'Erbil',de:'Erbil',tr:'Erbil',ur:'اربیل',id:'Erbil',es:'Erbil',bn:'এরবিল',ms:'Erbil'},
        aliases: {ar:['أربيل','اربيل'], en:['Arbil','Hawler'], ku:['هەولێر']},
        countryAr:'العراق', countryEn:'Iraq', priority: 82 },

    // ── Egypt expansion (3) ──
    { slug: 'giza', cc: 'eg', lat: 30.0131, lng: 31.2089, tz: 'Africa/Cairo',
        names: {ar:'الجيزة',en:'Giza',fr:'Gizeh',de:'Gizeh',tr:'Giza',ur:'الجیزہ',id:'Giza',es:'Guiza',bn:'গিজা',ms:'Giza'},
        aliases: {ar:['الجيزة','جيزة']},
        countryAr:'مصر', countryEn:'Egypt', priority: 88 },
    { slug: 'port-said', cc: 'eg', lat: 31.2653, lng: 32.3019, tz: 'Africa/Cairo',
        names: {ar:'بورسعيد',en:'Port Said',fr:'Port-Saïd',de:'Port Said',tr:'Port Said',ur:'پورٹ سعید',id:'Port Said',es:'Puerto Saíd',bn:'পোর্ট সাইদ',ms:'Port Said'},
        aliases: {ar:['بورسعيد','بور سعيد']},
        countryAr:'مصر', countryEn:'Egypt', priority: 80 },
    { slug: 'suez', cc: 'eg', lat: 29.9668, lng: 32.5498, tz: 'Africa/Cairo',
        names: {ar:'السويس',en:'Suez',fr:'Suez',de:'Sues',tr:'Süveyş',ur:'سویز',id:'Suez',es:'Suez',bn:'সুয়েজ',ms:'Suez'},
        aliases: {ar:['السويس','سويس']},
        countryAr:'مصر', countryEn:'Egypt', priority: 80 },

    // ── North Africa expansion (5) ──
    { slug: 'fes', cc: 'ma', lat: 34.0181, lng: -5.0078, tz: 'Africa/Casablanca',
        names: {ar:'فاس',en:'Fes',fr:'Fès',de:'Fès',tr:'Fas',ur:'فاس',id:'Fes',es:'Fez',bn:'ফেস',ms:'Fes'},
        aliases: {ar:['فاس'], en:['Fez']},
        countryAr:'المغرب', countryEn:'Morocco', priority: 85 },
    { slug: 'oran', cc: 'dz', lat: 35.6976, lng: -0.6337, tz: 'Africa/Algiers',
        names: {ar:'وهران',en:'Oran',fr:'Oran',de:'Oran',tr:'Oran',ur:'وہران',id:'Oran',es:'Orán',bn:'ওরান',ms:'Oran'},
        aliases: {ar:['وهران']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 85 },
    { slug: 'constantine', cc: 'dz', lat: 36.3650, lng: 6.6147, tz: 'Africa/Algiers',
        names: {ar:'قسنطينة',en:'Constantine',fr:'Constantine',de:'Constantine',tr:'Konstantin',ur:'قسنطینہ',id:'Constantine',es:'Constantina',bn:'কনস্টানটিন',ms:'Constantine'},
        aliases: {ar:['قسنطينة']},
        countryAr:'الجزائر', countryEn:'Algeria', priority: 80 },
    { slug: 'sfax', cc: 'tn', lat: 34.7406, lng: 10.7603, tz: 'Africa/Tunis',
        names: {ar:'صفاقس',en:'Sfax',fr:'Sfax',de:'Sfax',tr:'Sfaks',ur:'صفاقس',id:'Sfax',es:'Sfax',bn:'স্ফ্যাক্স',ms:'Sfax'},
        aliases: {ar:['صفاقس']},
        countryAr:'تونس', countryEn:'Tunisia', priority: 80 },
    { slug: 'benghazi', cc: 'ly', lat: 32.1188, lng: 20.0867, tz: 'Africa/Tripoli',
        names: {ar:'بنغازي',en:'Benghazi',fr:'Benghazi',de:'Bengasi',tr:'Bingazi',ur:'بنغازی',id:'Benghazi',es:'Bengasi',bn:'বেনগাজি',ms:'Benghazi'},
        aliases: {ar:['بنغازي']},
        countryAr:'ليبيا', countryEn:'Libya', priority: 85 },

    // ── Mexico extras (2) ──
    { slug: 'guadalajara', cc: 'mx', lat: 20.6597, lng: -103.3496, tz: 'America/Mexico_City',
        names: {ar:'غوادالاخارا',en:'Guadalajara',fr:'Guadalajara',de:'Guadalajara',tr:'Guadalajara',ur:'گواڈالاجارا',id:'Guadalajara',es:'Guadalajara',bn:'গুয়াদালাজারা',ms:'Guadalajara'},
        aliases: {es:['Guadalajara']},
        countryAr:'المكسيك', countryEn:'Mexico', priority: 82 },
    { slug: 'monterrey', cc: 'mx', lat: 25.6866, lng: -100.3161, tz: 'America/Monterrey',
        names: {ar:'مونتيري',en:'Monterrey',fr:'Monterrey',de:'Monterrey',tr:'Monterrey',ur:'مونٹیری',id:'Monterrey',es:'Monterrey',bn:'মন্টেরে',ms:'Monterrey'},
        aliases: {es:['Monterrey']},
        countryAr:'المكسيك', countryEn:'Mexico', priority: 82 },

    // ── Extra strategic 5 to reach 148 ──
    { slug: 'hong-kong', cc: 'hk', lat: 22.3193, lng: 114.1694, tz: 'Asia/Hong_Kong',
        names: {ar:'هونغ كونغ',en:'Hong Kong',fr:'Hong Kong',de:'Hongkong',tr:'Hong Kong',ur:'ہانگ کانگ',id:'Hong Kong',es:'Hong Kong',bn:'হংকং',ms:'Hong Kong'},
        aliases: {zh:['香港','香港特別行政區']},
        countryAr:'هونغ كونغ', countryEn:'Hong Kong', priority: 92 },
    { slug: 'taipei', cc: 'tw', lat: 25.0330, lng: 121.5654, tz: 'Asia/Taipei',
        names: {ar:'تايبيه',en:'Taipei',fr:'Taipei',de:'Taipeh',tr:'Tayvan',ur:'تائی پے',id:'Taipei',es:'Taipéi',bn:'তাইপে',ms:'Taipei'},
        aliases: {zh:['臺北','台北','臺北市']},
        countryAr:'تايوان', countryEn:'Taiwan', priority: 92 },
    { slug: 'tripoli-lb', cc: 'lb', lat: 34.4367, lng: 35.8497, tz: 'Asia/Beirut',
        names: {ar:'طرابلس',en:'Tripoli',fr:'Tripoli',de:'Tripoli',tr:'Trablusşam',ur:'طرابلس',id:'Tripoli',es:'Trípoli',bn:'ত্রিপলি',ms:'Tripoli'},
        aliases: {ar:['طرابلس لبنان','طرابلس الشام']},
        countryAr:'لبنان', countryEn:'Lebanon', priority: 80 },
    { slug: 'nicosia', cc: 'cy', lat: 35.1856, lng: 33.3823, tz: 'Asia/Nicosia',
        names: {ar:'نيقوسيا',en:'Nicosia',fr:'Nicosie',de:'Nikosia',tr:'Lefkoşa',ur:'نیکوشیا',id:'Nikosia',es:'Nicosia',bn:'নিকোসিয়া',ms:'Nicosia'},
        aliases: {el:['Λευκωσία'], tr:['Lefkoşa']},
        countryAr:'قبرص', countryEn:'Cyprus', priority: 85 },
    { slug: 'valletta', cc: 'mt', lat: 35.8989, lng: 14.5146, tz: 'Europe/Malta',
        names: {ar:'فاليتا',en:'Valletta',fr:'La Valette',de:'Valletta',tr:'Valletta',ur:'ویلیٹا',id:'Valletta',es:'La Valeta',bn:'ভ্যালেটা',ms:'Valletta'},
        aliases: {mt:['Il-Belt Valletta']},
        countryAr:'مالطا', countryEn:'Malta', priority: 82 }
];

let added = 0;
for (const c of newCities) {
    if (seen.has(c.slug)) { console.log('  SKIP (exists)', c.slug); continue; }
    places.push({
        slug: c.slug, type: 'city', countryCode: c.cc,
        lat: c.lat, lng: c.lng, timezone: c.tz,
        names: c.names, aliases: c.aliases,
        admin: { countryAr: c.countryAr, countryEn: c.countryEn },
        priority: c.priority, source: 'curated', verified: true
    });
    seen.add(c.slug);
    added++;
}

fs.writeFileSync(PATH, JSON.stringify(places, null, 2) + '\n');
console.log('Added', added, 'cities. Total entries:', places.length);
const counts = places.reduce((a,p) => { a[p.countryCode]=(a[p.countryCode]||0)+1; return a; }, {});
console.log('Per-country counts:', counts);
